// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package code.bankconnectors.grpc.connector

object ConnectorProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      code.bankconnectors.grpc.connector.ObpConnectorRequest,
      code.bankconnectors.grpc.connector.ObpConnectorResponse
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Cg9jb25uZWN0b3IucHJvdG8SGGNvZGUuYmFua2Nvbm5lY3RvcnMuZ3JwYyJ8ChNPYnBDb25uZWN0b3JSZXF1ZXN0EjAKC21ld
  GhvZF9uYW1lGAEgASgJQg/iPwwSCm1ldGhvZE5hbWVSCm1ldGhvZE5hbWUSMwoManNvbl9wYXlsb2FkGAIgASgJQhDiPw0SC2pzb
  25QYXlsb2FkUgtqc29uUGF5bG9hZCJLChRPYnBDb25uZWN0b3JSZXNwb25zZRIzCgxqc29uX3BheWxvYWQYASABKAlCEOI/DRILa
  nNvblBheWxvYWRSC2pzb25QYXlsb2FkMosBChNPYnBDb25uZWN0b3JTZXJ2aWNlEnQKEVByb2Nlc3NPYnBSZXF1ZXN0Ei0uY29kZ
  S5iYW5rY29ubmVjdG9ycy5ncnBjLk9icENvbm5lY3RvclJlcXVlc3QaLi5jb2RlLmJhbmtjb25uZWN0b3JzLmdycGMuT2JwQ29ub
  mVjdG9yUmVzcG9uc2UiAGIGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}