package bootstrap.http4s

import java.io.File
import java.net.URL
import java.security.KeyStore
import java.security.cert.X509Certificate
import javax.net.ssl.{HttpsURLConnection, KeyManagerFactory, SSLContext, TrustManagerFactory}

import cats.effect.IO
import cats.effect.unsafe.implicits.global
import code.api.util.{CertificateUtil, PeerTrust}
import code.api.util.http4s.CallerCertificate
import com.comcast.ip4s.{Host, Port}
import fs2.io.net.tls.{TLSContext, TLSParameters}
import org.http4s.{HttpApp, Response, Status}
import org.http4s.ember.server.EmberServerBuilder
import org.scalatest.BeforeAndAfterAll
import org.typelevel.ci.CIString
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers

/**
 * Guards the development certificate set in `obp-api/src/test/resources/cert`, regenerated by
 * `scripts/generate_dev_certs.sh`.
 *
 * Certificates checked into a repository rot silently: of the seven entries in the older
 * `server.trust.jks`, five had expired and two were public web CAs, and nothing failed to tell
 * anyone. So this asserts the properties the set is supposed to have — that each identity is
 * usable in the role it is named for, and that the names themselves match what the documentation
 * and `mtls.trusted_proxy.*` examples say.
 */
class DevCertificateSetTest extends AnyFlatSpec with Matchers with BeforeAndAfterAll {

  private val password = "123456"

  // The role-named stores generate_dev_certs.sh writes; see docs/MTLS.md.
  private val ObpServer = "obp-server.p12"
  private val TppClient = "tpp-client.p12"
  private val ProxyClient = "proxy-client.p12"
  private val DevTruststore = "dev-truststore.p12"
  private val ExpiredTpp = "expired-tpp.p12"
  private val certDir = new File(getClass.getResource("/cert/dev-ca.crt").toURI).getParentFile
  private def path(name: String) = new File(certDir, name).getAbsolutePath

  private def loadP12(name: String): KeyStore = {
    val store = KeyStore.getInstance("PKCS12")
    val in = new java.io.FileInputStream(path(name))
    try store.load(in, password.toCharArray) finally in.close()
    store
  }

  private def certOf(name: String): X509Certificate = {
    val store = loadP12(name)
    store.getCertificate(store.aliases().nextElement()).asInstanceOf[X509Certificate]
  }

  private val echoApp: HttpApp[IO] = HttpApp[IO] { req =>
    val value = req.headers.get(CIString("PSD2-CERT")).map(_.head.value).getOrElse("NONE")
    IO.pure(Response[IO](Status.Ok).withEntity(value))
  }

  // The proxy identity exists so a deployment where OBP sits behind nginx can be described at all.
  private lazy val behindProxy = {
    val proxy = certOf(ProxyClient)
    // Issuer is the CA, NOT the proxy's own subject. Obvious written down, easy to get wrong: it
    // holds for self-signed certificates, so a config that works against a throwaway pair silently
    // matches nothing once the proxy is properly CA-signed.
    val issuer = PeerTrust.canonicalDn(proxy.getIssuerX500Principal.getName).get
    val subject = PeerTrust.canonicalDn(proxy.getSubjectX500Principal.getName).get
    PeerTrust.TrustConfig(List(PeerTrust.TrustedProxy(issuer, Some(subject))),
      trustForwardedHeaderWithoutTls = false)
  }
  private val asEdge = PeerTrust.TrustConfig(Nil, trustForwardedHeaderWithoutTls = false)

  private val resolvingApp: HttpApp[IO] = HttpApp[IO] { req =>
    val config = if (req.uri.path.renderString.startsWith("/behind-proxy")) behindProxy else asEdge
    echoApp(CallerCertificate.resolveCaller(req, config))
  }

  private var shutdown: IO[Unit] = IO.unit
  private var serverPort: Int = 0

  override def beforeAll(): Unit = {
    // Exactly how Http4sServer builds it, but pointed at the new set.
    val sslContext = Http4sMtls.buildSslContext(Http4sMtls.MtlsConfig(
      keystorePath = path(ObpServer),
      keystorePassword = password,
      truststorePath = path(DevTruststore),
      truststorePassword = password,
      needClientAuth = true
    ))
    val (server, release) = EmberServerBuilder
      .default[IO]
      .withHost(Host.fromString("127.0.0.1").get)
      .withPort(Port.fromInt(0).get)
      .withTLS(TLSContext.Builder.forAsync[IO].fromSSLContext(sslContext), TLSParameters(needClientAuth = true))
      .withHttpApp(resolvingApp)
      .build
      .allocated
      .unsafeRunSync()
    serverPort = server.address.getPort
    shutdown = release
  }

  override def afterAll(): Unit = shutdown.unsafeRunSync()

  private def clientContext(identity: Option[String]): SSLContext = {
    val trustManagerFactory = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm)
    trustManagerFactory.init(loadP12(DevTruststore))
    val keyManagers = identity.map { name =>
      val keyManagerFactory = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm)
      keyManagerFactory.init(loadP12(name), password.toCharArray)
      keyManagerFactory.getKeyManagers
    }.orNull
    val context = SSLContext.getInstance("TLS")
    context.init(keyManagers, trustManagerFactory.getTrustManagers, null)
    context
  }

  private def get(identity: Option[String], path: String = "/as-edge", forwarded: Option[String] = None): String = {
    val connection = new URL(s"https://localhost:$serverPort$path").openConnection().asInstanceOf[HttpsURLConnection]
    connection.setSSLSocketFactory(clientContext(identity).getSocketFactory)
    forwarded.foreach(connection.setRequestProperty("PSD2-CERT", _))
    try scala.io.Source.fromInputStream(connection.getInputStream).mkString
    finally connection.disconnect()
  }

  "the dev server certificate" should "be verifiable by hostname, with no need to disable checking" in {
    // The old server.jks leaf has no SAN, so every documented curl needed -k or a CN fallback.
    // Reaching it as "localhost" without a custom HostnameVerifier is the assertion.
    get(Some(TppClient)) shouldEqual CertificateUtil.toPem(certOf(TppClient))
  }

  "the TPP client identity" should "be trusted through the CA alone" in {
    // Nothing is pinned in the truststore: only dev-ca is there, so this passing means the chain
    // was built and validated rather than the leaf being listed.
    val store = loadP12(DevTruststore)
    java.util.Collections.list(store.aliases()).size shouldEqual 1
    store.isCertificateEntry("dev-ca") shouldBe true
  }

  "the expired client identity" should "be rejected by the handshake" in {
    // Certificate expiry had no coverage before this fixture existed.
    an[Exception] should be thrownBy get(Some(ExpiredTpp))
  }

  "a certless handshake" should "be rejected under client_auth=need" in {
    an[Exception] should be thrownBy get(None)
  }

  "the proxy identity" should "be usable as a forwarder, keeping the App's certificate" in {
    val appPem = CertificateUtil.toPem(certOf(TppClient))
    get(Some(ProxyClient), "/behind-proxy", Some(
      CertificateUtil.normalizePemX509Certificate(appPem))) shouldEqual
      CertificateUtil.normalizePemX509Certificate(appPem)
  }

  // The DNs are configuration values now — docs/MTLS_TOPOLOGIES.md §5.1 shows operators typing them
  // into mtls.trusted_proxy.N.subject. If a regenerated set changes them, the examples go stale
  // silently, so pin the names here.
  "the identities" should "carry the documented role-named subjects" in {
    certOf(ObpServer).getSubjectX500Principal.getName should include("CN=localhost")
    certOf(TppClient).getSubjectX500Principal.getName should include("CN=test-tpp")
    certOf(ProxyClient).getSubjectX500Principal.getName should include("CN=nginx-dev-1")
    // The App is a different organisation from the bank: a TPP sharing TESOBE's O would make the
    // Consumer and regulated-entity lookups look better tested than they are.
    certOf(TppClient).getSubjectX500Principal.getName should include("O=Example TPP Ltd")
    certOf(ObpServer).getSubjectX500Principal.getName should include("O=TESOBE GmbH")
  }

  it should "separate client and server extended key usage" in {
    // serverAuth on a client certificate would let a mix-up work anyway, and hide it.
    certOf(ObpServer).getExtendedKeyUsage should contain("1.3.6.1.5.5.7.3.1")   // serverAuth
    certOf(ObpServer).getExtendedKeyUsage should not contain "1.3.6.1.5.5.7.3.2"
    certOf(TppClient).getExtendedKeyUsage should contain("1.3.6.1.5.5.7.3.2")   // clientAuth
    certOf(TppClient).getExtendedKeyUsage should not contain "1.3.6.1.5.5.7.3.1"
  }

  "every identity except the expired fixture" should "be valid for years to come" in {
    // Five of the seven entries in the old truststore had expired unnoticed.
    val fiveYears = new java.util.Date(System.currentTimeMillis() + 5L * 365 * 24 * 60 * 60 * 1000)
    List(ObpServer, TppClient, ProxyClient).foreach { name =>
      withClue(s"$name: ") { noException should be thrownBy certOf(name).checkValidity(fiveYears) }
    }
  }
}
