// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package code.obp.grpc.api

@SerialVersionUID(0L)
final case class ViewsJSONV121Grpc(
    views: _root_.scala.collection.Seq[code.obp.grpc.api.ViewJSONV121Grpc] = _root_.scala.collection.Seq.empty
    ) extends scalapb.GeneratedMessage with scalapb.Message[ViewsJSONV121Grpc] with scalapb.lenses.Updatable[ViewsJSONV121Grpc] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      views.foreach(views => __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(views.serializedSize) + views.serializedSize)
      __size
    }
    final override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      views.foreach { __v =>
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__v.serializedSize)
        __v.writeTo(_output__)
      };
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): code.obp.grpc.api.ViewsJSONV121Grpc = {
      val __views = (_root_.scala.collection.immutable.Vector.newBuilder[code.obp.grpc.api.ViewJSONV121Grpc] ++= this.views)
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __views += _root_.scalapb.LiteParser.readMessage(_input__, code.obp.grpc.api.ViewJSONV121Grpc.defaultInstance)
          case tag => _input__.skipField(tag)
        }
      }
      code.obp.grpc.api.ViewsJSONV121Grpc(
          views = __views.result()
      )
    }
    def clearViews = copy(views = _root_.scala.collection.Seq.empty)
    def addViews(__vs: code.obp.grpc.api.ViewJSONV121Grpc*): ViewsJSONV121Grpc = addAllViews(__vs)
    def addAllViews(__vs: TraversableOnce[code.obp.grpc.api.ViewJSONV121Grpc]): ViewsJSONV121Grpc = copy(views = views ++ __vs)
    def withViews(__v: _root_.scala.collection.Seq[code.obp.grpc.api.ViewJSONV121Grpc]): ViewsJSONV121Grpc = copy(views = __v)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => views
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PRepeated(views.map(_.toPMessage)(_root_.scala.collection.breakOut))
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = code.obp.grpc.api.ViewsJSONV121Grpc
}

object ViewsJSONV121Grpc extends scalapb.GeneratedMessageCompanion[code.obp.grpc.api.ViewsJSONV121Grpc] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[code.obp.grpc.api.ViewsJSONV121Grpc] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): code.obp.grpc.api.ViewsJSONV121Grpc = {
    require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
    val __fields = javaDescriptor.getFields
    code.obp.grpc.api.ViewsJSONV121Grpc(
      __fieldsMap.getOrElse(__fields.get(0), Nil).asInstanceOf[_root_.scala.collection.Seq[code.obp.grpc.api.ViewJSONV121Grpc]]
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[code.obp.grpc.api.ViewsJSONV121Grpc] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      code.obp.grpc.api.ViewsJSONV121Grpc(
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.collection.Seq[code.obp.grpc.api.ViewJSONV121Grpc]]).getOrElse(_root_.scala.collection.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = ApiProto.javaDescriptor.getMessageTypes.get(3)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ApiProto.scalaDescriptor.messages(3)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = code.obp.grpc.api.ViewJSONV121Grpc
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = code.obp.grpc.api.ViewsJSONV121Grpc(
  )
  implicit class ViewsJSONV121GrpcLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, code.obp.grpc.api.ViewsJSONV121Grpc]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, code.obp.grpc.api.ViewsJSONV121Grpc](_l) {
    def views: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.collection.Seq[code.obp.grpc.api.ViewJSONV121Grpc]] = field(_.views)((c_, f_) => c_.copy(views = f_))
  }
  final val VIEWS_FIELD_NUMBER = 1
}
