-- ATM table, the first table taken off Lift Mapper.
--
-- Flyway owns this table because its Lift entity (MappedAtm) has been deleted and
-- Schemifier therefore no longer creates it. The DDL below is not hand-written: it is
-- exactly what Schemifier emitted for the entity as it stood when it was removed,
-- captured with FlywayBaselineExport and narrowed to this one table.
--
-- Deliberately NOT the reference branch's V001__initial_schema.sql, which is a snapshot
-- of all ~148 Schemifier-owned tables: enabling that would pre-create every table with
-- stale columns that Schemifier then does not patch.

CREATE TABLE mappedatm(
    createdat TIMESTAMP,
    mbankid CHARACTER VARYING(44),
    mline1 CHARACTER VARYING(255),
    mline2 CHARACTER VARYING(255),
    mline3 CHARACTER VARYING(255),
    mcity CHARACTER VARYING(255),
    mcounty CHARACTER VARYING(255),
    mstate CHARACTER VARYING(255),
    mcountrycode CHARACTER VARYING(2),
    mpostcode CHARACTER VARYING(20),
    mlocationlatitude DOUBLE PRECISION,
    mlocationlongitude DOUBLE PRECISION,
    mlicenseid CHARACTER VARYING(44),
    mlicensename CHARACTER VARYING(255),
    misaccessible CHARACTER VARYING(1),
    mmoreinfo CHARACTER VARYING(128),
    matmid CHARACTER VARYING(44),
    mlocatedat CHARACTER VARYING(32),
    mservices CHARACTER VARYING,
    mnotes CHARACTER VARYING,
    mminimumwithdrawal CHARACTER VARYING(255),
    msitename CHARACTER VARYING(255),
    mbalanceinquiryfee CHARACTER VARYING(255),
    matmtype CHARACTER VARYING(255),
    mphone CHARACTER VARYING(255),
    updatedat TIMESTAMP,
    mname CHARACTER VARYING(255),
    mopeningtimeonmonday CHARACTER VARYING(5),
    mclosingtimeonmonday CHARACTER VARYING(5),
    mopeningtimeontuesday CHARACTER VARYING(5),
    mclosingtimeontuesday CHARACTER VARYING(5),
    mopeningtimeonwednesday CHARACTER VARYING(5),
    mclosingtimeonwednesday CHARACTER VARYING(5),
    mopeningtimeonthursday CHARACTER VARYING(5),
    mclosingtimeonthursday CHARACTER VARYING(5),
    mopeningtimeonfriday CHARACTER VARYING(5),
    mclosingtimeonfriday CHARACTER VARYING(5),
    mopeningtimeonsaturday CHARACTER VARYING(5),
    mclosingtimeonsaturday CHARACTER VARYING(5),
    mopeningtimeonsunday CHARACTER VARYING(5),
    mclosingtimeonsunday CHARACTER VARYING(5),
    mhasdepositcapability CHARACTER VARYING(1),
    msupportedlanguages CHARACTER VARYING,
    maccessibilityfeatures CHARACTER VARYING,
    msupportedcurrencies CHARACTER VARYING,
    mlocationcategories CHARACTER VARYING,
    mbranchidentification CHARACTER VARYING(255),
    msiteidentification CHARACTER VARYING(255),
    mcashwithdrawalnationalfee CHARACTER VARYING(255),
    mcashwithdrawalinternationalfee CHARACTER VARYING(255),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedatm ADD CONSTRAINT mappedatm_pk PRIMARY KEY(id);
CREATE INDEX mappedatm_mbankid ON mappedatm(mbankid NULLS FIRST);
