-- Narrative table, second table off Lift Mapper.
-- DDL captured from FlywayBaselineExport (Schemifier's own output for the entity as it
-- stood when it was deleted), narrowed to this table. Note TRANSACTION_C: Lift escapes
-- the SQL reserved word TRANSACTION with a _c suffix.

CREATE TABLE mappednarrative(
    createdat TIMESTAMP,
    transaction_c CHARACTER VARYING(44),
    bank CHARACTER VARYING(44),
    updatedat TIMESTAMP,
    narrative CHARACTER VARYING(2000),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    account CHARACTER VARYING(64)
);
ALTER TABLE mappednarrative ADD CONSTRAINT mappednarrative_pk PRIMARY KEY(id);
