-- Comment table, third table off Lift Mapper.
-- DDL from FlywayBaselineExport (Schemifier's own output), narrowed to this table.

CREATE TABLE mappedcomment(
    createdat TIMESTAMP,
    apiid CHARACTER VARYING(36),
    text_ CHARACTER VARYING(2000),
    poster BIGINT,
    replyto CHARACTER VARYING(36),
    bank CHARACTER VARYING(44),
    updatedat TIMESTAMP,
    transaction_c CHARACTER VARYING(44),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    view_c CHARACTER VARYING(44),
    date_c TIMESTAMP,
    account CHARACTER VARYING(64)
);
ALTER TABLE mappedcomment ADD CONSTRAINT mappedcomment_pk PRIMARY KEY(id);
