-- Tag table, fourth table off Lift Mapper.
-- DDL from FlywayBaselineExport (Schemifier's own output), narrowed to this table.

CREATE TABLE mappedtag(
    createdat TIMESTAMP,
    tagid CHARACTER VARYING(36),
    transaction_c CHARACTER VARYING(44),
    updatedat TIMESTAMP,
    bank CHARACTER VARYING(44),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    user_c BIGINT,
    tag CHARACTER VARYING(64),
    view_c CHARACTER VARYING(20),
    date_c TIMESTAMP,
    account CHARACTER VARYING(64)
);
ALTER TABLE mappedtag ADD CONSTRAINT mappedtag_pk PRIMARY KEY(id);
