-- Where-tag (geo tag) table, fifth table off Lift Mapper.
-- DDL from FlywayBaselineExport (Schemifier's own output), narrowed to this table.

CREATE TABLE mappedwheretag(
    transaction_c CHARACTER VARYING(44),
    updatedat TIMESTAMP,
    bank CHARACTER VARYING(44),
    createdat TIMESTAMP,
    geolongitude DOUBLE PRECISION,
    geolatitude DOUBLE PRECISION,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    user_c BIGINT,
    view_c CHARACTER VARYING(44),
    date_c TIMESTAMP,
    account CHARACTER VARYING(64)
);
ALTER TABLE mappedwheretag ADD CONSTRAINT mappedwheretag_pk PRIMARY KEY(id);
