-- Transaction image table, sixth table off Lift Mapper.
-- DDL from FlywayBaselineExport (Schemifier's own output), narrowed to this table.

CREATE TABLE mappedtransactionimage(
    createdat TIMESTAMP,
    transaction_c CHARACTER VARYING(44),
    updatedat TIMESTAMP,
    bank CHARACTER VARYING(44),
    imageid CHARACTER VARYING(36),
    imagedescription CHARACTER VARYING(2000),
    url CHARACTER VARYING(2000),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    user_c BIGINT,
    view_c CHARACTER VARYING(44),
    date_c TIMESTAMP,
    account CHARACTER VARYING(64)
);
ALTER TABLE mappedtransactionimage ADD CONSTRAINT mappedtransactionimage_pk PRIMARY KEY(id);
