-- Product tag table, seventh table off Lift Mapper.
-- Table and plain index are Schemifier's own output (FlywayBaselineExport), narrowed here.
--
-- The UNIQUE index is added by hand because the export does not carry it: the entity
-- declared UniqueIndex(BankId, ProductCode, Tag) via dbIndexes, and only the plain
-- Index(BankId, ProductCode) survived the dump. It is not decoration - ProductTagsProvider
-- diffs desired against stored tags instead of truncating, and that is only race-free at
-- row level if the database refuses a duplicate (bank, product, tag).

CREATE TABLE producttag(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    tag CHARACTER VARYING(100),
    productcode CHARACTER VARYING(50),
    bankid CHARACTER VARYING(44)
);
ALTER TABLE producttag ADD CONSTRAINT producttag_pk PRIMARY KEY(id);
CREATE INDEX producttag_bankid_productcode ON producttag(bankid NULLS FIRST, productcode NULLS FIRST);
CREATE UNIQUE INDEX producttag_bankid_productcode_tag ON producttag(bankid NULLS FIRST, productcode NULLS FIRST, tag NULLS FIRST);
