-- Connector trace table, eighth table off Lift Mapper.
-- Table name is connector_trace, not connectortrace: the entity overrode dbTableName.
-- DDL from FlywayBaselineExport (Schemifier's own output), narrowed to this table.

CREATE TABLE connector_trace(
    issuccessful BOOLEAN,
    bankid CHARACTER VARYING(256),
    httpverb CHARACTER VARYING(16),
    userid CHARACTER VARYING(256),
    correlationid CHARACTER VARYING(256),
    functionname CHARACTER VARYING(128),
    connectorname CHARACTER VARYING(64),
    inboundmessage CHARACTER VARYING,
    outboundmessage CHARACTER VARYING,
    url CHARACTER VARYING(2000),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    duration BIGINT,
    date_c TIMESTAMP
);
ALTER TABLE connector_trace ADD CONSTRAINT connector_trace_pk PRIMARY KEY(id);
