-- Consent item table, ninth table off Lift Mapper.
-- The entity had no provider and no call sites at all: every access to this table is raw
-- SQL (DoobieConsentQueries, MappedConsent, the v5.1.0 endpoints, the reference-id
-- migration). It existed only so Schemifier would create the table, which is now Flyway's
-- job. Table and column names are snake_case via dbTableName/dbColumnName overrides.

CREATE TABLE consent_item(
    consent_item_id CHARACTER VARYING(36),
    account_id CHARACTER VARYING(255),
    bank_id CHARACTER VARYING(255),
    consent_reference_id CHARACTER VARYING(36),
    role_name CHARACTER VARYING(255),
    view_id CHARACTER VARYING(255),
    item_type CHARACTER VARYING(64),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE consent_item ADD CONSTRAINT consent_item_pk PRIMARY KEY(id);
