-- JSON schema validation table, tenth table off Lift Mapper.
-- DDL from FlywayBaselineExport (Schemifier's own output), narrowed to this table.
--
-- The UNIQUE index is added by hand: the entity declared UniqueIndex(OperationId) through
-- dbIndexes and the export does not carry dbIndexes-declared unique indexes (same gap as
-- producttag). It is load-bearing - getByOperationId and update both assume one row per
-- operation id, and update's find-then-write would otherwise race into duplicates.

CREATE TABLE jsonschemavalidation(
    jsonschema CHARACTER VARYING,
    operationid CHARACTER VARYING(200),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE jsonschemavalidation ADD CONSTRAINT jsonschemavalidation_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX jsonschemavalidation_operationid ON jsonschemavalidation(operationid NULLS FIRST);
