-- Transaction type table, eleventh table off Lift Mapper.
-- DDL from FlywayBaselineExport (Schemifier's own output), narrowed to this table.
--
-- Both UNIQUE indexes are added by hand: the entity declared
-- UniqueIndex(mTransactionTypeId) and UniqueIndex(mBankId, mShortCode) through dbIndexes,
-- and the export drops dbIndexes-declared unique indexes. createOrUpdate looks the id up
-- and inserts only when absent, which is only safe against concurrent callers if the
-- database refuses the duplicate.

CREATE TABLE mappedtransactiontype(
    createdat TIMESTAMP,
    mbankid CHARACTER VARYING(44),
    mdescription CHARACTER VARYING(2000),
    mtransactiontypeid CHARACTER VARYING(44),
    mshortcode CHARACTER VARYING(20),
    msummary CHARACTER VARYING(64),
    updatedat TIMESTAMP,
    mcustomerfee_currency CHARACTER VARYING(3),
    mcustomerfee_amount BIGINT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedtransactiontype ADD CONSTRAINT mappedtransactiontype_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX mappedtransactiontype_mtransactiontypeid ON mappedtransactiontype(mtransactiontypeid NULLS FIRST);
CREATE UNIQUE INDEX mappedtransactiontype_mbankid_mshortcode ON mappedtransactiontype(mbankid NULLS FIRST, mshortcode NULLS FIRST);
