-- ETag table, thirteenth table off Lift Mapper.
-- Table name is ETag, not MappedETag: the entity overrode dbTableName.
-- Columns from FlywayBaselineExport (Schemifier's own output), narrowed to this table.
--
-- The unique index is added by hand and is not optional. FlywayBaselineExport does not emit
-- dbIndexes-declared unique indexes; the database has this one, confirmed by reading
-- information_schema.indexes on a normally booted instance:
--   ETAG / ETAG_ETAGRESOURCE / UNIQUE INDEX
-- Dropping it would let checkIfModifiedSinceHeader accumulate several rows per cache key,
-- since it looks the key up and inserts when absent, with no other guard.

CREATE TABLE etag(
    etagresource CHARACTER VARYING(1000),
    etagvalue CHARACTER VARYING(256),
    lastupdatedmssinceepoch BIGINT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE etag ADD CONSTRAINT etag_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX etag_etagresource ON etag(etagresource NULLS FIRST);
