-- Authentication type validation table, fourteenth table off Lift Mapper.
-- Columns from FlywayBaselineExport (Schemifier's own output), narrowed to this table.
--
-- The unique index is added by hand and is required. FlywayBaselineExport does not emit
-- dbIndexes-declared unique indexes even though Schemifier creates them; read from a booted
-- instance, information_schema.indexes reports:
--   AUTHENTICATIONTYPEVALIDATION / AUTHENTICATIONTYPEVALIDATION_OPERATIONID / UNIQUE INDEX
-- getByOperationId and update both assume one row per operation id.

CREATE TABLE authenticationtypevalidation(
    operationid CHARACTER VARYING(200),
    allowedauthtypes CHARACTER VARYING(300),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE authenticationtypevalidation ADD CONSTRAINT authenticationtypevalidation_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX authenticationtypevalidation_operationid ON authenticationtypevalidation(operationid NULLS FIRST);
