-- Connector method table, sixteenth table off Lift Mapper.
-- MethodBody is a MappedText, so CHARACTER VARYING with no bound - connector bodies are
-- whole method sources and a bounded column would truncate them.
--
-- Both unique indexes are added by hand and are required. FlywayBaselineExport does not emit
-- dbIndexes-declared unique indexes even though Schemifier creates them; read from a booted
-- instance, information_schema.indexes reports:
--   CONNECTORMETHOD / CONNECTORMETHOD_CONNECTORMETHODID / UNIQUE INDEX
--   CONNECTORMETHOD / CONNECTORMETHOD_METHODNAME       / UNIQUE INDEX
-- The one on the method name is what makes getByMethodName a single-row lookup, which the
-- connector dispatch relies on.

CREATE TABLE connectormethod(
    connectormethodid CHARACTER VARYING(44),
    methodname CHARACTER VARYING(255),
    methodbody CHARACTER VARYING,
    lang CHARACTER VARYING(50),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE connectormethod ADD CONSTRAINT connectormethod_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX connectormethod_connectormethodid ON connectormethod(connectormethodid NULLS FIRST);
CREATE UNIQUE INDEX connectormethod_methodname ON connectormethod(methodname NULLS FIRST);
