-- Api collection endpoint table, seventeenth table off Lift Mapper.
-- ApiCollectionEndpointId is a MappedUUID, hence VARCHAR(36).
--
-- Both unique indexes are added by hand and are required. FlywayBaselineExport does not emit
-- dbIndexes-declared unique indexes even though Schemifier creates them; read from a booted
-- instance, information_schema.indexes reports:
--   APICOLLECTIONENDPOINT / APICOLLECTIONENDPOINT_APICOLLECTIONENDPOINTID / UNIQUE INDEX
--   APICOLLECTIONENDPOINT / APICOLLECTIONENDPOINT_APICOLLECTIONID_OPERATIONID / UNIQUE INDEX
-- The second is what keeps one endpoint from being added twice to the same collection.

CREATE TABLE apicollectionendpoint(
    apicollectionid CHARACTER VARYING(100),
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    operationid CHARACTER VARYING(100),
    apicollectionendpointid CHARACTER VARYING(36),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE apicollectionendpoint ADD CONSTRAINT apicollectionendpoint_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX apicollectionendpoint_apicollectionendpointid ON apicollectionendpoint(apicollectionendpointid NULLS FIRST);
CREATE UNIQUE INDEX apicollectionendpoint_apicollectionid_operationid ON apicollectionendpoint(apicollectionid NULLS FIRST, operationid NULLS FIRST);
