-- Featured api collection table, eighteenth table off Lift Mapper.
-- FeaturedApiCollectionId is a MappedUUID, hence VARCHAR(36).
--
-- Both unique indexes are added by hand and are required. FlywayBaselineExport does not emit
-- dbIndexes-declared unique indexes even though Schemifier creates them; read from a booted
-- instance, information_schema.indexes reports:
--   FEATUREDAPICOLLECTION / FEATUREDAPICOLLECTION_FEATUREDAPICOLLECTIONID / UNIQUE INDEX
--   FEATUREDAPICOLLECTION / FEATUREDAPICOLLECTION_APICOLLECTIONID        / UNIQUE INDEX
-- The second is what checkFeaturedApiCollectionDoesNotExist relies on: at most one featured row
-- per api collection.

CREATE TABLE featuredapicollection(
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    apicollectionid CHARACTER VARYING(100),
    sortorder INTEGER,
    featuredapicollectionid CHARACTER VARYING(36),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE featuredapicollection ADD CONSTRAINT featuredapicollection_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX featuredapicollection_featuredapicollectionid ON featuredapicollection(featuredapicollectionid NULLS FIRST);
CREATE UNIQUE INDEX featuredapicollection_apicollectionid ON featuredapicollection(apicollectionid NULLS FIRST);
