-- Consent auth context table, nineteenth table off Lift Mapper.
-- Table name is ConsentAuthContext, not MappedConsentAuthContext: the entity overrode
-- dbTableName. Key is a reserved word in H2, hence the KEY_C column; VALUE is not reserved
-- here because the runtime H2 URL carries NON_KEYWORDS=VALUE.
--
-- The unique index is added by hand and does exist. FlywayBaselineExport does not emit
-- dbIndexes-declared unique indexes even though Schemifier creates them; read from a booted
-- instance, information_schema.indexes reports:
--   CONSENTAUTHCONTEXT / CONSENTAUTHCONTEXT_CONSENTID_KEY_C_CREATEDAT / UNIQUE INDEX
-- This is not the index MigrationOfConsentAuthContextDropIndex removes - that one-time
-- runtime migration (still tracked in migration_script_log, not Flyway) drops a differently
-- named legacy index, consentauthcontext_consentid_key_c, which had no createdAt column and
-- really did block legitimate duplicate (consentId, key) rows. The index kept here includes
-- createdAt at millisecond precision, so in practice it almost never rejects an insert -
-- createConsentAuthContextAkka relies on exactly that: it always inserts, with no existence
-- check, and duplicate (consentId, key) pairs are the documented, intended behaviour.

CREATE TABLE consentauthcontext(
    value CHARACTER VARYING(255),
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    consentid CHARACTER VARYING(44),
    consentauthcontextid CHARACTER VARYING(36),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    key_c CHARACTER VARYING(255)
);
ALTER TABLE consentauthcontext ADD CONSTRAINT consentauthcontext_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX consentauthcontext_consentid_key_c_createdat ON consentauthcontext(consentid NULLS FIRST, key_c NULLS FIRST, createdat NULLS FIRST);
