-- User auth context table, twentieth table off Lift Mapper. Table name stays
-- mappeduserauthcontext (the entity did not override dbTableName).
--
-- mKey/mValue are 4000 chars: that width itself was a historical migration
-- (MigrationOfUserAuthContextFieldLength), already applied everywhere; Flyway creates it at
-- that width directly, so there is nothing left for that migration to widen on a fresh instance.
--
-- The unique index is added by hand and does exist. FlywayBaselineExport does not emit
-- dbIndexes-declared unique indexes even though Schemifier creates them; read from a booted
-- instance, information_schema.indexes reports:
--   MAPPEDUSERAUTHCONTEXT / MAPPEDUSERAUTHCONTEXT_MUSERID_MKEY_CREATEDAT / UNIQUE INDEX
-- Same shape as consent_auth_context: createdAt is part of the key, so two writes for the same
-- (userId, key) inside one millisecond collide, and everything else about "duplicates" is
-- intentional - see createUserAuthContext's callers.

CREATE TABLE mappeduserauthcontext(
    muserid CHARACTER VARYING(44),
    mconsumerid CHARACTER VARYING(255),
    mvalue CHARACTER VARYING(4000),
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    muserauthcontextid CHARACTER VARYING(36),
    mkey CHARACTER VARYING(4000),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappeduserauthcontext ADD CONSTRAINT mappeduserauthcontext_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX mappeduserauthcontext_muserid_mkey_createdat ON mappeduserauthcontext(muserid NULLS FIRST, mkey NULLS FIRST, createdat NULLS FIRST);
