-- User init action table, twenty-first table off Lift Mapper.
-- UserId is a MappedUUID, hence VARCHAR(36).
--
-- The unique index is added by hand and is required. FlywayBaselineExport does not emit
-- dbIndexes-declared unique indexes even though Schemifier creates them; read from a booted
-- instance, information_schema.indexes reports:
--   USERINITACTION / USERINITACTION_USERID_ACTIONNAME_ACTIONVALUE / UNIQUE INDEX
-- createOrUpdateInitAction relies on it: it finds by the full (userId, actionName, actionValue)
-- triple and updates in place, so a second write for the same triple must not add a row.

CREATE TABLE userinitaction(
    actionname CHARACTER VARYING(100),
    actionvalue CHARACTER VARYING(100),
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    userid CHARACTER VARYING(36),
    success BOOLEAN,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE userinitaction ADD CONSTRAINT userinitaction_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX userinitaction_userid_actionname_actionvalue ON userinitaction(userid NULLS FIRST, actionname NULLS FIRST, actionvalue NULLS FIRST);
