-- Account id mapping table, twenty-second table off Lift Mapper.
-- mAccountId is a MappedUUID, hence VARCHAR(36).
--
-- Both unique indexes are added by hand and are required. FlywayBaselineExport does not emit
-- dbIndexes-declared unique indexes even though Schemifier creates them; read from a booted
-- instance, information_schema.indexes reports:
--   ACCOUNTIDMAPPING / ACCOUNTIDMAPPING_MACCOUNTID / UNIQUE INDEX
--   ACCOUNTIDMAPPING / ACCOUNTIDMAPPING_MACCOUNTID_MACCOUNTPLAINTEXTREFERENCE / UNIQUE INDEX
-- getOrCreateAccountId's comment describes a concurrent-insert retry for a duplicate
-- accountPlainTextReference, but neither index actually constrains that column alone -
-- mAccountId is what is unique here, and every fresh insert gets a new random UUID for it, so
-- two concurrent creates for the SAME accountPlainTextReference do not collide at the database
-- level and both succeed. That gap is reproduced as-is: it is a genuine schema question (should
-- accountPlainTextReference be unique on its own?) rather than something a table migration
-- should decide unilaterally, and this table's rows already exist under today's schema. The
-- retry branch is kept in the provider as dead-but-harmless code, matching what it actually is
-- today.

CREATE TABLE accountidmapping(
    maccountid CHARACTER VARYING(36),
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    maccountplaintextreference CHARACTER VARYING(255),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE accountidmapping ADD CONSTRAINT accountidmapping_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX accountidmapping_maccountid ON accountidmapping(maccountid NULLS FIRST);
CREATE UNIQUE INDEX accountidmapping_maccountid_maccountplaintextreference ON accountidmapping(maccountid NULLS FIRST, maccountplaintextreference NULLS FIRST);
