-- Bank account data table, twenty-fifth table off Lift Mapper.
-- Nothing creates or reads this table anywhere in the current codebase - only
-- DeleteAccountCascade deletes from it, to clear out any rows an account may have picked up
-- while this entity was in active use. Kept so that cascade delete still has a real table to
-- target; not a candidate for dropping outright without checking production data first.
--
-- The unique index is added by hand and does exist. FlywayBaselineExport does not emit
-- dbIndexes-declared unique indexes even though Schemifier creates them; read from a booted
-- instance, information_schema.indexes reports:
--   MAPPEDBANKACCOUNTDATA / MAPPEDBANKACCOUNTDATA_BANKID_ACCOUNTID / UNIQUE INDEX

CREATE TABLE mappedbankaccountdata(
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    accountlabel CHARACTER VARYING(255),
    bankid CHARACTER VARYING(255),
    accountid CHARACTER VARYING(255),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedbankaccountdata ADD CONSTRAINT mappedbankaccountdata_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX mappedbankaccountdata_bankid_accountid ON mappedbankaccountdata(bankid NULLS FIRST, accountid NULLS FIRST);
