-- Api collection table, twenty-sixth table off Lift Mapper.
-- ApiCollectionId is a MappedUUID, hence VARCHAR(36).
--
-- Both unique indexes are added by hand and are required. FlywayBaselineExport does not emit
-- dbIndexes-declared unique indexes even though Schemifier creates them; read from a booted
-- instance, information_schema.indexes reports:
--   APICOLLECTION / APICOLLECTION_APICOLLECTIONID / UNIQUE INDEX
--   APICOLLECTION / APICOLLECTION_USERID_APICOLLECTIONNAME / UNIQUE INDEX
-- The second is what keeps one user from creating two collections with the same name.

CREATE TABLE apicollection(
    apicollectionid CHARACTER VARYING(36),
    apicollectionname CHARACTER VARYING(100),
    issharable BOOLEAN,
    userid CHARACTER VARYING(100),
    description CHARACTER VARYING(2000),
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE apicollection ADD CONSTRAINT apicollection_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX apicollection_apicollectionid ON apicollection(apicollectionid NULLS FIRST);
CREATE UNIQUE INDEX apicollection_userid_apicollectionname ON apicollection(userid NULLS FIRST, apicollectionname NULLS FIRST);
