-- Bank account routing table, twenty-eighth table off Lift Mapper. Stores IBAN and other
-- account-routing addresses (schemes: IBAN, OBP, sort-code-account-number, ...). BankId is a
-- UUIDString (44 chars); AccountId is the wider AccountIdString (64 chars) - not the usual
-- MappedUUID shape seen on most other tables.
--
-- Both unique indexes are added by hand and are required. FlywayBaselineExport does not emit
-- dbIndexes-declared unique indexes even though Schemifier creates them; read from a booted
-- instance, information_schema.indexes reports:
--   BANKACCOUNTROUTING / BANKACCOUNTROUTING_BANKID_ACCOUNTID_ACCOUNTROUTINGSCHEME / UNIQUE INDEX
--   BANKACCOUNTROUTING / BANKACCOUNTROUTING_BANKID_ACCOUNTROUTINGSCHEME_ACCOUNTROUTINGADDRESS / UNIQUE INDEX
-- The first is "one address per (account, scheme)"; the second is "one account per
-- (bank, scheme, address)" - an address like an IBAN can't be claimed by two different accounts
-- at the same bank under the same scheme. Both are read directly by
-- LocalMappedConnector.getBankAccountByRoutingLegacy and getAccountRouting, which rely on the
-- database, not application code, to keep either from being violated.

CREATE TABLE bankaccountrouting(
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    bankid CHARACTER VARYING(44),
    accountid CHARACTER VARYING(64),
    accountroutingscheme CHARACTER VARYING(32),
    accountroutingaddress CHARACTER VARYING(128),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE bankaccountrouting ADD CONSTRAINT bankaccountrouting_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX bankaccountrouting_bankid_accountid_accountroutingscheme ON bankaccountrouting(bankid NULLS FIRST, accountid NULLS FIRST, accountroutingscheme NULLS FIRST);
CREATE UNIQUE INDEX bankaccountrouting_bankid_accountroutingscheme_accountroutingaddress ON bankaccountrouting(bankid NULLS FIRST, accountroutingscheme NULLS FIRST, accountroutingaddress NULLS FIRST);
