-- FX rate table, twenty-ninth table off Lift Mapper. BankId is a UUIDString (44 chars);
-- currency codes are ISO 3-letter.
--
-- No unique index: only plain indexes on the two currency-code columns, matching Schemifier's
-- actual output. The entity declared a foreign key on both currency columns pointing at
-- MappedCurrency, but that table has always had zero rows and the FK was never enforced in
-- practice - confirmed by inserting a row for a currency pair with nothing in MappedCurrency,
-- which succeeded. MappedCurrency is deleted as dead code in the same change (see
-- MappedCurrency.scala's removal), so there is no FK target to declare here even if one were
-- wanted.
--
-- createOrUpdateFXRate is find-then-write on (bankId, fromCurrencyCode, toCurrencyCode); with no
-- unique index, a genuinely concurrent pair of calls for the same triple can both miss the find
-- and both insert, same as the id-mapping tables' documented gap.

CREATE TABLE mappedfxrate(
    mbankid CHARACTER VARYING(44),
    mfromcurrencycode CHARACTER VARYING(3),
    mtocurrencycode CHARACTER VARYING(3),
    mconversionvalue DOUBLE PRECISION,
    meffectivedate TIMESTAMP,
    minverseconversionvalue DOUBLE PRECISION,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedfxrate ADD CONSTRAINT mappedfxrate_pk PRIMARY KEY(id);
CREATE INDEX mappedfxrate_mfromcurrencycode ON mappedfxrate(mfromcurrencycode NULLS FIRST);
CREATE INDEX mappedfxrate_mtocurrencycode ON mappedfxrate(mtocurrencycode NULLS FIRST);
