-- Migration script log table, thirty-first table off Lift Mapper. This is migration bookkeeping
-- itself - the table every historical migration script writes to via Migration.saveLog, and the
-- one resetDatabaseForTestClass (ServerSetup.scala) deliberately excludes from its per-test-class
-- wipe: clearing it makes isExecuted always false, so a fresh test JVM would re-run every
-- historical migration against a database that already has their effects (e.g. migration-created
-- views), and a migration that retypes a view-projected column then fails outright. That
-- exclusion continues to apply after this table moves to Flyway - it is simply never in the
-- automatic per-table reset list any migrated table gets added to.
--
-- The unique index is added by hand and does exist. FlywayBaselineExport does not emit
-- dbIndexes-declared unique indexes even though Schemifier creates them; read from a booted
-- instance, information_schema.indexes reports:
--   MIGRATIONSCRIPTLOG / MIGRATIONSCRIPTLOG_NAME_ISSUCCESSFUL / UNIQUE INDEX
-- saveLog's find-then-update-or-create keys on exactly (name, isSuccessful).

CREATE TABLE migrationscriptlog(
    issuccessful BOOLEAN,
    commitid CHARACTER VARYING(100),
    startdate BIGINT,
    enddate BIGINT,
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    remark CHARACTER VARYING(1024),
    migrationscriptlogid CHARACTER VARYING(36),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    name CHARACTER VARYING(100)
);
ALTER TABLE migrationscriptlog ADD CONSTRAINT migrationscriptlog_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX migrationscriptlog_name_issuccessful ON migrationscriptlog(name NULLS FIRST, issuccessful NULLS FIRST);
