-- Transaction request reasons table, thirty-second table off Lift Mapper. A write-only audit
-- record: nothing in the codebase reads it back - it is populated alongside a transaction
-- request's creation and never queried again here. TransactionRequestReasonId defaults via
-- APIUtil.generateUUID(), hence VARCHAR(44) like other UUID-valued columns.
--
-- No unique index - only the primary key. Schemifier's own output for this table, confirmed by
-- reading information_schema.indexes on a booted instance; multiple reasons naturally attach to
-- one transactionrequestid, so nothing here was ever expected to be unique.

CREATE TABLE transactionrequestreasons(
    amount CHARACTER VARYING(32),
    currency CHARACTER VARYING(3),
    documentnumber CHARACTER VARYING(100),
    description CHARACTER VARYING(2048),
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    transactionrequestid CHARACTER VARYING(44),
    transactionrequestreasonid CHARACTER VARYING(44),
    code CHARACTER VARYING(8),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE transactionrequestreasons ADD CONSTRAINT transactionrequestreasons_pk PRIMARY KEY(id);
