-- Api product attribute table, thirty-third table off Lift Mapper. ApiProductAttributeId is a
-- MappedUUID (36 chars); BankId is a UUIDString (44 chars). Type is a reserved word in H2, hence
-- the TYPE_C column.
--
-- The unique index is added by hand and is required. FlywayBaselineExport does not emit
-- dbIndexes-declared unique indexes even though Schemifier creates them; read from a booted
-- instance, information_schema.indexes reports:
--   APIPRODUCTATTRIBUTE / APIPRODUCTATTRIBUTE_APIPRODUCTATTRIBUTEID / UNIQUE INDEX
-- createOrUpdateApiProductAttribute looks up by this id, not by (bankId, apiProductCode), so a
-- bank/product pair can carry more than one attribute with the same name at once - lookup by id
-- is the only thing that has to be unique.

CREATE TABLE apiproductattribute(
    isactive BOOLEAN,
    apiproductcode CHARACTER VARYING(50),
    value CHARACTER VARYING(2000),
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    bankid CHARACTER VARYING(44),
    apiproductattributeid CHARACTER VARYING(36),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    name CHARACTER VARYING(256),
    type_c CHARACTER VARYING(50)
);
ALTER TABLE apiproductattribute ADD CONSTRAINT apiproductattribute_pk PRIMARY KEY(id);
CREATE INDEX apiproductattribute_bankid ON apiproductattribute(bankid NULLS FIRST);
CREATE UNIQUE INDEX apiproductattribute_apiproductattributeid ON apiproductattribute(apiproductattributeid NULLS FIRST);
