-- User auth context update table, thirty-fourth table off Lift Mapper. The SCA-style
-- challenge/answer flow for updating a user auth context. mUserAuthContextUpdateId is a
-- MappedUUID (36 chars); mUserId is a UUIDString (44 chars).
--
-- No unique index - only the primary key, matching Schemifier's real output (the entity's own
-- dbIndexes is `super.dbIndexes`, adding nothing). MigrationOfMappedUserAuthContextUpdate drops
-- a legacy index (mappeduserauthcontextupdate_muserid_mkey) that predates this; a fresh instance
-- never had it.
--
-- Concurrent challenge answers are guarded by an atomic conditional UPDATE
-- (DoobieUserAuthContextUpdateQueries.conditionalStatusTransition), not by anything declared
-- here - that is what stops two correct concurrent answers both being accepted
-- (CONCURRENCY_HAZARDS.md hazard H2).

CREATE TABLE mappeduserauthcontextupdate(
    muserid CHARACTER VARYING(44),
    mstatus CHARACTER VARYING(20),
    mconsumerid CHARACTER VARYING(255),
    mchallenge CHARACTER VARYING(10),
    mvalue CHARACTER VARYING(50),
    mkey CHARACTER VARYING(50),
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    muserauthcontextupdateid CHARACTER VARYING(36),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappeduserauthcontextupdate ADD CONSTRAINT mappeduserauthcontextupdate_pk PRIMARY KEY(id);
