-- Card attribute table, thirty-fifth table off Lift Mapper. mCardAttributeId is a MappedUUID
-- (36 chars); mBankId/mCardId are UUIDString (44 chars).
--
-- No unique index - only two plain indexes on mCardId and mCardAttributeId, matching
-- Schemifier's real output (the entity's own dbIndexes declares only Index, never UniqueIndex).
-- createOrUpdateCardAttribute finds by mCardAttributeId to decide update vs create, but nothing
-- in the schema enforces that lookup key being unique.

CREATE TABLE mappedcardattribute(
    mcardid CHARACTER VARYING(44),
    mcardattributeid CHARACTER VARYING(36),
    mbankid CHARACTER VARYING(44),
    mname CHARACTER VARYING(50),
    mtype CHARACTER VARYING(50),
    mvalue CHARACTER VARYING(255),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedcardattribute ADD CONSTRAINT mappedcardattribute_pk PRIMARY KEY(id);
CREATE INDEX mappedcardattribute_mcardid ON mappedcardattribute(mcardid NULLS FIRST);
CREATE INDEX mappedcardattribute_mcardattributeid ON mappedcardattribute(mcardattributeid NULLS FIRST);
