-- Counterparty attribute table, thirty-eighth table off Lift Mapper. CounterpartyAttributeId is
-- a MappedUUID (36 chars); CounterpartyId_ is a UUIDString (44 chars) with an explicit
-- dbColumnName override ("CounterpartyId"), so the column is clean - no trailing underscore.
-- The Type column is stored as TYPE_C for the same reserved-word reason as AtmAttribute/
-- BankAttribute.
--
-- No unique index - only a plain index on counterpartyid, matching the entity's own dbIndexes
-- (Index(CounterpartyId_)), confirmed against a booted instance's information_schema.indexes.
--
-- IsActive defaults to true at the application layer (isActive.getOrElse(true) on create), not
-- via a column DEFAULT - matching the Mapper field's defaultValue, which only fired through the
-- Mapper API.

CREATE TABLE counterpartyattribute(
    isactive BOOLEAN,
    counterpartyid CHARACTER VARYING(44),
    value CHARACTER VARYING(255),
    counterpartyattributeid CHARACTER VARYING(36),
    name CHARACTER VARYING(50),
    type_c CHARACTER VARYING(50),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE counterpartyattribute ADD CONSTRAINT counterpartyattribute_pk PRIMARY KEY(id);
CREATE INDEX counterpartyattribute_counterpartyid ON counterpartyattribute(counterpartyid NULLS FIRST);
