-- Product attribute table, fortieth table off Lift Mapper. mProductAttributeId is a MappedUUID
-- (36 chars); mBankId is a UUIDString (44 chars). No reserved-word column renames here - mType
-- (unlike the bare Type column on AtmAttribute/BankAttribute/CounterpartyAttribute/
-- RegulatedEntityAttribute) does not collide with H2's reserved TYPE keyword.
--
-- No unique index - only plain indexes on mBankId and mProductAttributeId, matching the entity's
-- own dbIndexes (Index(mBankId) :: Index(mProductAttributeId)), confirmed against a booted
-- instance's information_schema.indexes.
--
-- IsActive defaults to true at the application layer (isActive.getOrElse(true) on create), not
-- via a column DEFAULT - matching the Mapper field's defaultValue, which only fired through the
-- Mapper API.

CREATE TABLE mappedproductattribute(
    mbankid CHARACTER VARYING(44),
    mcode CHARACTER VARYING(50),
    mname CHARACTER VARYING(50),
    mtype CHARACTER VARYING(50),
    isactive BOOLEAN,
    mvalue CHARACTER VARYING(255),
    mproductattributeid CHARACTER VARYING(36),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedproductattribute ADD CONSTRAINT mappedproductattribute_pk PRIMARY KEY(id);
CREATE INDEX mappedproductattribute_mbankid ON mappedproductattribute(mbankid NULLS FIRST);
CREATE INDEX mappedproductattribute_mproductattributeid ON mappedproductattribute(mproductattributeid NULLS FIRST);
