-- Customer attribute table, forty-first table off Lift Mapper. mCustomerAttributeId is a
-- MappedUUID (36 chars); mBankId/mCustomerId are UUIDString (44 chars). mBankId has an explicit
-- dbColumnName override ("mbankidid") - a historical typo baked into the schema, preserved
-- verbatim (see the entity's own comment: "the column name is typo that left over from history").
-- mValue is 2000 chars, wider than the 255 used by the other *Attribute tables.
--
-- No unique index - only plain indexes on mCustomerId and mCustomerAttributeId, matching the
-- entity's own dbIndexes (Index(mCustomerId) :: Index(mCustomerAttributeId)), confirmed against a
-- booted instance's information_schema.indexes.

CREATE TABLE mappedcustomerattribute(
    mvalue CHARACTER VARYING(2000),
    mbankidid CHARACTER VARYING(44),
    mname CHARACTER VARYING(50),
    mcustomerid CHARACTER VARYING(44),
    mtype CHARACTER VARYING(50),
    mcustomerattributeid CHARACTER VARYING(36),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedcustomerattribute ADD CONSTRAINT mappedcustomerattribute_pk PRIMARY KEY(id);
CREATE INDEX mappedcustomerattribute_mcustomerid ON mappedcustomerattribute(mcustomerid NULLS FIRST);
CREATE INDEX mappedcustomerattribute_mcustomerattributeid ON mappedcustomerattribute(mcustomerattributeid NULLS FIRST);
