-- Account attribute table, forty-second table off Lift Mapper. mAccountAttributeId is a
-- MappedUUID (36 chars); mBankIdId/mAccountId are UUIDString (44 chars).
--
-- No unique index - only plain indexes on mAccountId and mAccountAttributeId, matching the
-- entity's own dbIndexes (Index(mAccountId) :: Index(mAccountAttributeId)), confirmed against a
-- booted instance's information_schema.indexes.

CREATE TABLE mappedaccountattribute(
    mvalue CHARACTER VARYING(255),
    mbankidid CHARACTER VARYING(44),
    maccountid CHARACTER VARYING(44),
    mcode CHARACTER VARYING(50),
    mname CHARACTER VARYING(50),
    mtype CHARACTER VARYING(50),
    maccountattributeid CHARACTER VARYING(36),
    mproductinstancecode CHARACTER VARYING(255),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedaccountattribute ADD CONSTRAINT mappedaccountattribute_pk PRIMARY KEY(id);
CREATE INDEX mappedaccountattribute_maccountid ON mappedaccountattribute(maccountid NULLS FIRST);
CREATE INDEX mappedaccountattribute_maccountattributeid ON mappedaccountattribute(maccountattributeid NULLS FIRST);
