-- Transaction attribute table, forty-third table off Lift Mapper. mTransactionAttributeId is a
-- MappedUUID (36 chars); mBankId/mTransactionId are UUIDString (44 chars).
--
-- No unique index - only plain indexes on mTransactionId and mTransactionAttributeId, matching
-- the entity's own dbIndexes (Index(mTransactionId) :: Index(mTransactionAttributeId)),
-- confirmed against a booted instance's information_schema.indexes.

CREATE TABLE mappedtransactionattribute(
    mtransactionid CHARACTER VARYING(44),
    mvalue CHARACTER VARYING(255),
    mbankid CHARACTER VARYING(44),
    mname CHARACTER VARYING(50),
    mtype CHARACTER VARYING(50),
    mtransactionattributeid CHARACTER VARYING(36),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedtransactionattribute ADD CONSTRAINT mappedtransactionattribute_pk PRIMARY KEY(id);
CREATE INDEX mappedtransactionattribute_mtransactionid ON mappedtransactionattribute(mtransactionid NULLS FIRST);
CREATE INDEX mappedtransactionattribute_mtransactionattributeid ON mappedtransactionattribute(mtransactionattributeid NULLS FIRST);
