-- Transaction-request attribute table, forty-fourth table off Lift Mapper.
-- TransactionRequestAttributeId is a MappedUUID (36 chars); BankId/TransactionRequestId are
-- UUIDString (44 chars). The Type column is stored as TYPE_C for the same reserved-word reason
-- as AtmAttribute/BankAttribute/CounterpartyAttribute/RegulatedEntityAttribute. Value is a
-- MappedText, so CHARACTER VARYING with no bound (same pattern as V015's MethodBody) - Open
-- Corridor promise evidence stores the full A1.1 preimage JSON here, which exceeds any fixed
-- varchar bound.
--
-- No unique index - only plain indexes on transactionrequestid and
-- transactionrequestattributeid, matching the entity's own dbIndexes
-- (Index(TransactionRequestId) :: Index(TransactionRequestAttributeId)), confirmed against a
-- booted instance's information_schema.indexes.

CREATE TABLE transactionrequestattribute(
    value CHARACTER VARYING,
    bankid CHARACTER VARYING(44),
    ispersonal BOOLEAN,
    transactionrequestid CHARACTER VARYING(44),
    transactionrequestattributeid CHARACTER VARYING(36),
    name CHARACTER VARYING(50),
    type_c CHARACTER VARYING(50),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE transactionrequestattribute ADD CONSTRAINT transactionrequestattribute_pk PRIMARY KEY(id);
CREATE INDEX transactionrequestattribute_transactionrequestid ON transactionrequestattribute(transactionrequestid NULLS FIRST);
CREATE INDEX transactionrequestattribute_transactionrequestattributeid ON transactionrequestattribute(transactionrequestattributeid NULLS FIRST);
