-- Tax residence table, forty-fifth table off Lift Mapper. mCustomerId is a
-- MappedLongForeignKey(this, MappedCustomer) - it stores the customer's internal BIGINT primary
-- key (mappedcustomer.id), not the customer's UUID customerId. mTaxResidenceId is a MappedUUID
-- (36 chars); mDomain/mTaxNumber are MediumString (20 chars each). createdat/updatedat come from
-- the CreatedUpdated mixin.
--
-- Two indexes: a plain index on mcustomerid (auto-generated by the foreign-key field) and a
-- UNIQUE INDEX on (mcustomerid, mdomain, mtaxnumber), matching the entity's own dbIndexes
-- (UniqueIndex(mCustomerId, mDomain, mTaxNumber)), confirmed against a booted instance's
-- information_schema.indexes - a customer cannot have the same domain+number pair twice.

CREATE TABLE mappedtaxresidence(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    mcustomerid BIGINT,
    mtaxresidenceid CHARACTER VARYING(36),
    mdomain CHARACTER VARYING(20),
    mtaxnumber CHARACTER VARYING(20)
);
ALTER TABLE mappedtaxresidence ADD CONSTRAINT mappedtaxresidence_pk PRIMARY KEY(id);
CREATE INDEX mappedtaxresidence_mcustomerid ON mappedtaxresidence(mcustomerid NULLS FIRST);
CREATE UNIQUE INDEX mappedtaxresidence_mcustomerid_mdomain_mtaxnumber ON mappedtaxresidence(mcustomerid NULLS FIRST, mdomain NULLS FIRST, mtaxnumber NULLS FIRST);
