-- Customer link table (bank-to-bank customer relationships, e.g. spouse/parent at another
-- bank), forty-sixth table off Lift Mapper. CustomerLinkId is a MappedUUID (36 chars);
-- CustomerId/OtherCustomerId are UUIDString (44 chars); BankId/OtherBankId/RelationshipTo are
-- plain MappedString(255). createdat/updatedat come from the CreatedUpdated mixin. dbTableName is
-- explicitly overridden to "CustomerLink" (mixed case in the entity source; H2 stores/reports it
-- lowercase either way).
--
-- Unique index on customerlinkid, matching UniqueIndex(CustomerLinkId); plain indexes on
-- customerid and othercustomerid, matching Index(CustomerId)/Index(OtherCustomerId) - confirmed
-- against a booted instance's information_schema.indexes.

CREATE TABLE customerlink(
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    bankid CHARACTER VARYING(255),
    customerlinkid CHARACTER VARYING(36),
    relationshipto CHARACTER VARYING(255),
    customerid CHARACTER VARYING(44),
    otherbankid CHARACTER VARYING(255),
    othercustomerid CHARACTER VARYING(44),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE customerlink ADD CONSTRAINT customerlink_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX customerlink_customerlinkid ON customerlink(customerlinkid NULLS FIRST);
CREATE INDEX customerlink_customerid ON customerlink(customerid NULLS FIRST);
CREATE INDEX customerlink_othercustomerid ON customerlink(othercustomerid NULLS FIRST);
