-- Counterparty limit table, forty-seventh table off Lift Mapper. CounterpartyLimitId is a
-- MappedUUID (36 chars); BankId/AccountId/ViewId/CounterpartyId/Currency are MappedString(255),
-- with BankId/AccountId/ViewId/CounterpartyId declared dbNotNull_?=true. The four amount fields
-- are MappedDecimal(MathContext.DECIMAL64, 10) -> NUMERIC(16,10); the three transaction-count
-- fields are MappedInt -> INTEGER. createdat/updatedat come from the CreatedUpdated mixin.
--
-- Two unique indexes: one on counterpartylimitid, one on the composite
-- (bankid, accountid, viewid, counterpartyid) - at most one limit per (bank, account, view,
-- counterparty) tuple. Matches the entity's own dbIndexes
-- (UniqueIndex(CounterpartyLimitId) :: UniqueIndex(BankId, AccountId, ViewId, CounterpartyId)),
-- confirmed against a booted instance's information_schema.indexes.

CREATE TABLE counterpartylimit(
    maxsingleamount NUMERIC(16, 10),
    maxmonthlyamount NUMERIC(16, 10),
    maxyearlyamount NUMERIC(16, 10),
    maxtotalamount NUMERIC(16, 10),
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    bankid CHARACTER VARYING(255) NOT NULL,
    accountid CHARACTER VARYING(255) NOT NULL,
    currency CHARACTER VARYING(255),
    viewid CHARACTER VARYING(255) NOT NULL,
    counterpartyid CHARACTER VARYING(255) NOT NULL,
    counterpartylimitid CHARACTER VARYING(36),
    maxnumberofmonthlytransactions INTEGER,
    maxnumberofyearlytransactions INTEGER,
    maxnumberoftransactions INTEGER,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE counterpartylimit ADD CONSTRAINT counterpartylimit_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX counterpartylimit_counterpartylimitid ON counterpartylimit(counterpartylimitid NULLS FIRST);
CREATE UNIQUE INDEX counterpartylimit_bankid_accountid_viewid_counterpartyid ON counterpartylimit(bankid NULLS FIRST, accountid NULLS FIRST, viewid NULLS FIRST, counterpartyid NULLS FIRST);
