-- Customer account link table (which customer(s) can act as agent/owner on which account),
-- forty-eighth table off Lift Mapper. CustomerAccountLinkId is a MappedUUID (36 chars);
-- CustomerId/AccountId are UUIDString (44 chars); BankId/RelationshipType are
-- MappedString(255). createdat/updatedat come from the CreatedUpdated mixin.
--
-- Two unique indexes: one on customeraccountlinkid, one on the composite (accountid, customerid)
-- - a customer has at most one link per account. Matches the entity's own dbIndexes
-- (UniqueIndex(CustomerAccountLinkId) :: UniqueIndex(AccountId, CustomerId)), confirmed against a
-- booted instance's information_schema.indexes.

CREATE TABLE customeraccountlink(
    customerid CHARACTER VARYING(44),
    relationshiptype CHARACTER VARYING(255),
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    bankid CHARACTER VARYING(255),
    accountid CHARACTER VARYING(44),
    customeraccountlinkid CHARACTER VARYING(36),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE customeraccountlink ADD CONSTRAINT customeraccountlink_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX customeraccountlink_customeraccountlinkid ON customeraccountlink(customeraccountlinkid NULLS FIRST);
CREATE UNIQUE INDEX customeraccountlink_accountid_customerid ON customeraccountlink(accountid NULLS FIRST, customerid NULLS FIRST);
