-- User-customer link table, forty-ninth table off Lift Mapper. mUserCustomerLinkId is a
-- MappedUUID (36 chars); mUserId/mCustomerId are UUIDString (44 chars); mDateInserted is a
-- separate MappedDateTime column distinct from the createdat/updatedat pair the CreatedUpdated
-- mixin also adds (the trait's dateInserted getter reads mdateinserted, not createdat).
--
-- Two unique indexes: one on musercustomerlinkid, one on the composite (muserid, mcustomerid) -
-- a user has at most one link per customer. Matches the entity's own dbIndexes
-- (UniqueIndex(mUserCustomerLinkId) :: UniqueIndex(mUserId, mCustomerId)), confirmed against a
-- booted instance's information_schema.indexes.
--
-- ConcurrentDuplicateCreationTest scenario L relies on this unique index: getOCreateUserCustomerLink
-- does find-then-insert with no surrounding transaction, and depends on the second concurrent
-- insert failing the constraint so it can retry the find - dropping this index would let two
-- threads both insert a row for the same (userId, customerId) pair.

CREATE TABLE mappedusercustomerlink(
    misactive BOOLEAN,
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    muserid CHARACTER VARYING(44),
    mcustomerid CHARACTER VARYING(44),
    mdateinserted TIMESTAMP,
    musercustomerlinkid CHARACTER VARYING(36),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedusercustomerlink ADD CONSTRAINT mappedusercustomerlink_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX mappedusercustomerlink_musercustomerlinkid ON mappedusercustomerlink(musercustomerlinkid NULLS FIRST);
CREATE UNIQUE INDEX mappedusercustomerlink_muserid_mcustomerid ON mappedusercustomerlink(muserid NULLS FIRST, mcustomerid NULLS FIRST);
