-- CRM event table, fiftieth table off Lift Mapper. mCrmEventId is a MappedUUID (36 chars);
-- mBankId is a UUIDString (44 chars); mUserId is a MappedLongForeignKey(this, ResourceUser) -
-- it stores ResourceUser's internal BIGINT primary key, not the user's UUID userId.
-- createdat/updatedat come from the CreatedUpdated mixin (unused by the entity's own fields,
-- which use separate mScheduledDate/mActualDate columns).
--
-- Three indexes: a UNIQUE INDEX on mcrmeventid and a plain index on mbankid, both matching the
-- entity's own dbIndexes (UniqueIndex(mCrmEventId) :: Index(mBankId)); plus a plain index on
-- muserid that the entity does NOT declare explicitly - Lift Mapper auto-indexes
-- MappedLongForeignKey columns, confirmed against a booted instance's information_schema.indexes.

CREATE TABLE mappedcrmevent(
    mcrmeventid CHARACTER VARYING(36),
    mdetail CHARACTER VARYING(1024),
    mchannel CHARACTER VARYING(32),
    mscheduleddate TIMESTAMP,
    mactualdate TIMESTAMP,
    mresult CHARACTER VARYING(32),
    mcustomername CHARACTER VARYING(64),
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    mbankid CHARACTER VARYING(44),
    mcategory CHARACTER VARYING(32),
    muserid BIGINT,
    mcustomernumber CHARACTER VARYING(64),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedcrmevent ADD CONSTRAINT mappedcrmevent_pk PRIMARY KEY(id);
CREATE INDEX mappedcrmevent_muserid ON mappedcrmevent(muserid NULLS FIRST);
CREATE UNIQUE INDEX mappedcrmevent_mcrmeventid ON mappedcrmevent(mcrmeventid NULLS FIRST);
CREATE INDEX mappedcrmevent_mbankid ON mappedcrmevent(mbankid NULLS FIRST);
