-- Payee lookup cache table (fifty-second table off Lift Mapper). Backs the mobile-wallet
-- payee-lookup flow: createPayeeLookup writes a short-lived row keyed by a random lookupId,
-- getActivePayeeLookup reads it back by lookupId and filters expired rows in Scala (expired
-- rows are not auto-deleted). One unique index on lookupid (Schemifier's UniqueIndex(LookupId))
-- and one plain index on expiresat (Index(ExpiresAt)), confirmed against a booted instance's
-- information_schema.indexes.

CREATE TABLE payeelookup(
    lookupid CHARACTER VARYING(64),
    identifiertype CHARACTER VARYING(64),
    identifier CHARACTER VARYING(255),
    fspid CHARACTER VARYING(32),
    networkprovider CHARACTER VARYING(64),
    fullname CHARACTER VARYING(255),
    accountcategory CHARACTER VARYING(32),
    accounttype CHARACTER VARYING(32),
    identitytype CHARACTER VARYING(32),
    identityvalue CHARACTER VARYING(64),
    frombankid CHARACTER VARYING(255),
    fromaccountid CHARACTER VARYING(255),
    createdbyuserid CHARACTER VARYING(255),
    creationdate TIMESTAMP,
    expiresat TIMESTAMP,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE payeelookup ADD CONSTRAINT payeelookup_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX payeelookup_lookupid ON payeelookup(lookupid NULLS FIRST);
CREATE INDEX payeelookup_expiresat ON payeelookup(expiresat NULLS FIRST);
