-- Append-only audit log of MetricsArchiveScheduler runs (fifty-fourth table off Lift Mapper).
-- One row per completed run: how many rows were moved metric -> metricarchive, how many
-- outdated archive rows were deleted, wall-clock duration, and whether the run succeeded.
-- Self-capped by MetricsArchiveRun.recordRun via pruneToMostRecent - the table stays small.
--
-- One unique index on runid (Schemifier's UniqueIndex(RunId)) and one plain index on
-- startedat (Index(StartedAt)), confirmed against a booted instance's information_schema.

CREATE TABLE metricsarchiverun(
    success BOOLEAN,
    runid CHARACTER VARYING(36),
    startedat TIMESTAMP,
    apiinstanceid CHARACTER VARYING(100),
    endedat TIMESTAMP,
    durationms BIGINT,
    rowsmovedtoarchive INTEGER,
    remark TEXT,
    rowsdeletedfromarchive INTEGER,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE metricsarchiverun ADD CONSTRAINT metricsarchiverun_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX metricsarchiverun_runid ON metricsarchiverun(runid NULLS FIRST);
CREATE INDEX metricsarchiverun_startedat ON metricsarchiverun(startedat NULLS FIRST);
