-- Open Corridor platform fee accrual ledger (fifty-fifth table off Lift Mapper).
-- One row per covered promise: OpenCorridorSettlement.accrue writes it in the settle
-- transaction, OpenCorridorFees.sweep sums a bank's unswept rows per currency and stamps
-- them with a fee_settlement_id once swept. NULL/empty fee_settlement_id means still open.
--
-- Unique index on transaction_request_id (accrual is idempotent per covered promise),
-- plain indexes on debtor_bank_id and fee_settlement_id, confirmed against a booted
-- instance's information_schema.

CREATE TABLE open_corridor_fee_accrual(
    currency CHARACTER VARYING(8),
    amount CHARACTER VARYING(32),
    debtor_bank_id CHARACTER VARYING(255),
    fee_settlement_id CHARACTER VARYING(64),
    accrued_at TIMESTAMP,
    transaction_request_id CHARACTER VARYING(64),
    covered_by_settlement_id CHARACTER VARYING(64),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE open_corridor_fee_accrual ADD CONSTRAINT open_corridor_fee_accrual_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX open_corridor_fee_accrual_transaction_request_id ON open_corridor_fee_accrual(transaction_request_id NULLS FIRST);
CREATE INDEX open_corridor_fee_accrual_debtor_bank_id ON open_corridor_fee_accrual(debtor_bank_id NULLS FIRST);
CREATE INDEX open_corridor_fee_accrual_fee_settlement_id ON open_corridor_fee_accrual(fee_settlement_id NULLS FIRST);
