-- Per-request callback registry for UTILITY transaction-requests (fifty-sixth table off
-- Lift Mapper). When a caller supplies a callback_url on a UTILITY payment, OBP persists
-- a row here and fires a fire-and-forget POST of the final result via
-- UtilityCallbackDispatcher. Distinct from the account-event webhook system: this is a
-- one-shot callback bound to a single transaction request.
--
-- One unique index on callbackid, one plain index on transactionrequestid, confirmed
-- against a booted instance's information_schema.

CREATE TABLE utilitypaymentcallback(
    createdbyuserid CHARACTER VARYING(255),
    callbackid CHARACTER VARYING(64),
    callbackurl CHARACTER VARYING(2048),
    identifiertype CHARACTER VARYING(64),
    identifier CHARACTER VARYING(255),
    frombankid CHARACTER VARYING(255),
    fromaccountid CHARACTER VARYING(255),
    status CHARACTER VARYING(32),
    attempts INTEGER,
    responsecode CHARACTER VARYING(32),
    creationdate TIMESTAMP,
    lastattemptdate TIMESTAMP,
    transactionrequestid CHARACTER VARYING(64),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE utilitypaymentcallback ADD CONSTRAINT utilitypaymentcallback_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX utilitypaymentcallback_callbackid ON utilitypaymentcallback(callbackid NULLS FIRST);
CREATE INDEX utilitypaymentcallback_transactionrequestid ON utilitypaymentcallback(transactionrequestid NULLS FIRST);
