-- Web UI properties table (fifty-seventh table off Lift Mapper). Props whose name starts
-- with "webui_" can be overridden here at runtime via CRUD endpoints instead of the static
-- props file; MappedWebUiPropsProvider.getWebUiPropsValue layers brand/language variants
-- over the requested name before falling back to APIUtil.getPropsValue.
--
-- Two unique indexes (webuipropsid, name), confirmed against a booted instance's
-- information_schema.

CREATE TABLE webuiprops(
    value TEXT,
    webuipropsid CHARACTER VARYING(36),
    name CHARACTER VARYING(255),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE webuiprops ADD CONSTRAINT webuiprops_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX webuiprops_webuipropsid ON webuiprops(webuipropsid NULLS FIRST);
CREATE UNIQUE INDEX webuiprops_name ON webuiprops(name NULLS FIRST);
