-- Groups-of-roles table (fifty-ninth table off Lift Mapper, dbTableName override
-- "GroupOfRoles"). Backs the v6.0.0 management/groups CRUD endpoints - a named bundle
-- of roles (list_of_roles, comma-separated) that can be granted to a user's entitlement
-- in one shot, scoped to a bank or system-wide (empty bank_id).
--
-- Two plain indexes (groupid, bankid) - the entity declares Index, not UniqueIndex, for
-- both - confirmed against a booted instance's information_schema.

CREATE TABLE groupofroles(
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    bankid CHARACTER VARYING(255),
    groupid CHARACTER VARYING(36),
    groupname CHARACTER VARYING(255),
    groupdescription TEXT,
    listofroles TEXT,
    isenabled BOOLEAN,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE groupofroles ADD CONSTRAINT groupofroles_pk PRIMARY KEY(id);
CREATE INDEX groupofroles_groupid ON groupofroles(groupid NULLS FIRST);
CREATE INDEX groupofroles_bankid ON groupofroles(bankid NULLS FIRST);
