-- Organisation directory table (sixtieth table off Lift Mapper, dbTableName override
-- "Organisation"). Backs the v7.0.0 management/organisations CRUD endpoints.
--
-- One unique index on organisationid, confirmed against a booted instance's
-- information_schema.

CREATE TABLE organisation(
    organisationid CHARACTER VARYING(64),
    website CHARACTER VARYING(1024),
    logourl CHARACTER VARYING(1024),
    visibility CHARACTER VARYING(32),
    createdbyuserid CHARACTER VARYING(255),
    status CHARACTER VARYING(32),
    creationdate TIMESTAMP,
    lastupdate TIMESTAMP,
    name CHARACTER VARYING(255),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE organisation ADD CONSTRAINT organisation_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX organisation_organisationid ON organisation(organisationid NULLS FIRST);
