-- Attribute definitions (sixty-first table off Lift Mapper). Declares the attributes that may
-- be attached to each entity category (Account / Transaction / Customer / Product / Card /
-- TransactionRequest ...): name, value type, description, alias, which views the attribute may
-- be seen on, and whether it is active. The per-entity attribute tables carry the values; this
-- table is the schema for them.
--
-- One unique index on (bankid, name, category), confirmed against a booted instance's
-- information_schema - the natural key the provider's find-then-update keys off.

CREATE TABLE attributedefinition(
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    bankid CHARACTER VARYING(50),
    isactive BOOLEAN,
    description CHARACTER VARYING(256),
    typeofvalue CHARACTER VARYING(50),
    alias CHARACTER VARYING(50),
    canbeseenonviews CHARACTER VARYING(256),
    attributedefinitionid CHARACTER VARYING(36),
    name CHARACTER VARYING(50),
    category CHARACTER VARYING(50),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE attributedefinition ADD CONSTRAINT attributedefinition_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX attributedefinition_bankid_name_category
    ON attributedefinition(bankid NULLS FIRST, name NULLS FIRST, category NULLS FIRST);
