-- Scheduler lock table (sixty-second table off Lift Mapper).
--
-- This is a LOCK table, not a job-history log: a row exists only while a job holds the lock and
-- is deleted when the job finishes. In healthy operation it is empty; rows present are either
-- currently-running jobs or stale locks left by a JVM that died before its finally block ran.
-- Contrast metricsarchiverun, which is the durable audit log of completed runs.
--
-- One unique index on jobid, confirmed against a booted instance's information_schema.

CREATE TABLE jobscheduler(
    jobid CHARACTER VARYING(36),
    apiinstanceid CHARACTER VARYING(100),
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    name CHARACTER VARYING(100),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE jobscheduler ADD CONSTRAINT jobscheduler_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX jobscheduler_jobid ON jobscheduler(jobid NULLS FIRST);
