-- Endpoint tags (sixty-fourth table off Lift Mapper). User-defined tags attached to an endpoint
-- by operationId, either system-level (bankid null/empty) or scoped to one bank. Surfaced on
-- resource docs alongside the built-in tags.
--
-- One unique index on endpointtagid, confirmed against a booted instance's information_schema.
-- Note there is NO uniqueness on (operationid, tagname) or (bankid, operationid, tagname), so the
-- same tag can be created repeatedly for one endpoint.

CREATE TABLE endpointtag(
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    bankid CHARACTER VARYING(255),
    operationid CHARACTER VARYING(255),
    tagname CHARACTER VARYING(255),
    endpointtagid CHARACTER VARYING(36),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE endpointtag ADD CONSTRAINT endpointtag_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX endpointtag_endpointtagid ON endpointtag(endpointtagid NULLS FIRST);
