-- API products (sixty-fifth table off Lift Mapper). A bank's catalogue of API products: naming,
-- pricing, call limits, and a tag list.
--
-- tags is stored pipe-delimited with leading and trailing pipes ("|featured|beta|") so that a
-- LIKE '%|tag|%' filter matches a whole tag rather than a substring of one. Empty list is "".
--
-- One unique index on (bankid, apiproductcode) - the natural key the provider's find-then-update
-- keys off - plus a plain index on bankid. Confirmed against a booted instance.

CREATE TABLE apiproduct(
    tags CHARACTER VARYING(2000),
    description CHARACTER VARYING(2000),
    persecondcalllimit BIGINT,
    perminutecalllimit BIGINT,
    perhourcalllimit BIGINT,
    perdaycalllimit BIGINT,
    perweekcalllimit BIGINT,
    permonthcalllimit BIGINT,
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    bankid CHARACTER VARYING(44),
    apiproductid CHARACTER VARYING(36),
    moreinfourl CHARACTER VARYING(2000),
    collectionid CHARACTER VARYING(50),
    apiproductcode CHARACTER VARYING(50),
    parentapiproductcode CHARACTER VARYING(50),
    termsandconditionsurl CHARACTER VARYING(2000),
    monthlysubscriptioncurrency CHARACTER VARYING(3),
    monthlysubscriptionamount CHARACTER VARYING(50),
    name CHARACTER VARYING(256),
    category CHARACTER VARYING(256),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE apiproduct ADD CONSTRAINT apiproduct_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX apiproduct_bankid_apiproductcode ON apiproduct(bankid NULLS FIRST, apiproductcode NULLS FIRST);
CREATE INDEX apiproduct_bankid ON apiproduct(bankid NULLS FIRST);
