-- Per-bank AMQP broker coordinates (sixty-sixth table off Lift Mapper). Where OBP-API publishes
-- messages destined for a bank's own infrastructure: each onboarded bank's Bank Node consumes on
-- its OWN vhost with its own credentials, so permission isolation is enforced at the broker level
-- and publishing is keyed by bank_id through this registry.
--
-- password is write-only by contract: accepted on registration, never echoed by any endpoint
-- (AmqpBankBrokerJsonV700 deliberately has no password field).
--
-- One unique index on bank_id - one broker per bank, which is what makes upsert well-defined.
-- Confirmed against a booted instance.

CREATE TABLE amqp_bank_broker(
    bank_id CHARACTER VARYING(255),
    host CHARACTER VARYING(255),
    port INTEGER,
    virtual_host CHARACTER VARYING(255),
    username CHARACTER VARYING(255),
    password CHARACTER VARYING(255),
    use_ssl BOOLEAN,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE amqp_bank_broker ADD CONSTRAINT amqp_bank_broker_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX amqp_bank_broker_bank_id ON amqp_bank_broker(bank_id NULLS FIRST);
