-- Product fees (sixty-seventh table off Lift Mapper). Fees attached to a bank's product:
-- name, amount+currency, frequency and type, with an active flag.
--
-- The `type` field is stored as TYPE_C, not TYPE: Lift's Schemifier appends "_c" to column names
-- that collide with SQL reserved words. Reproduced exactly - naming it TYPE here would create a
-- column the code never reads.
--
-- amount is DECIMAL(34,2) - MappedDecimal with MathContext.DECIMAL128 and scale 2.
--
-- Two PLAIN indexes (bankid, productfeeid) - the entity declares Index, not UniqueIndex, for
-- both, so productfeeid is NOT unique at the database level even though the provider treats it
-- as an identifier. Confirmed against a booted instance; reproduced as-is.

CREATE TABLE productfee(
    moreinfo CHARACTER VARYING(255),
    bankid CHARACTER VARYING(44),
    currency CHARACTER VARYING(50),
    amount NUMERIC(34, 2),
    productcode CHARACTER VARYING(50),
    productfeeid CHARACTER VARYING(44),
    isactive BOOLEAN,
    frequency CHARACTER VARYING(255),
    name CHARACTER VARYING(100),
    type_c CHARACTER VARYING(255),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE productfee ADD CONSTRAINT productfee_pk PRIMARY KEY(id);
CREATE INDEX productfee_bankid ON productfee(bankid NULLS FIRST);
CREATE INDEX productfee_productfeeid ON productfee(productfeeid NULLS FIRST);
