-- Transactional outbox (sixty-eighth table off Lift Mapper).
--
-- The business event (e.g. an Open Corridor settle) commits in one DB transaction; its outbound
-- messages must survive a crash between that commit and the publish. So they are written here in
-- the SAME transaction and a relay publishes them afterwards with at-least-once redelivery.
-- Publishing to a broker cannot join the DB transaction - this table is what closes that gap.
--
-- Row lifecycle: PENDING (relay keeps publishing with backoff) -> DELIVERED (receiver replied
-- success) or STICKY (receiver replied with an error retrying cannot fix; needs operator
-- reconciliation via GET /management/message-outbox and its /retry).
--
-- updated_at is not decoration: the relay's exponential backoff is computed from it, so every
-- write must stamp it. Three plain indexes (status, subject_id, outbox_type) - none unique -
-- confirmed against a booted instance.

CREATE TABLE message_outbox(
    attempts INTEGER,
    last_error CHARACTER VARYING(2000),
    last_reply_json TEXT,
    subject_id CHARACTER VARYING(64),
    outbox_type CHARACTER VARYING(32),
    subject_id_type CHARACTER VARYING(32),
    operation_name CHARACTER VARYING(64),
    target_id CHARACTER VARYING(255),
    payload_json TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    metadata_json TEXT,
    status CHARACTER VARYING(16),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE message_outbox ADD CONSTRAINT message_outbox_pk PRIMARY KEY(id);
CREATE INDEX message_outbox_status ON message_outbox(status NULLS FIRST);
CREATE INDEX message_outbox_subject_id ON message_outbox(subject_id NULLS FIRST);
CREATE INDEX message_outbox_outbox_type ON message_outbox(outbox_type NULLS FIRST);
