-- User invitations (seventy-first table off Lift Mapper). An invitation a bank issues to a
-- prospective user; the invitee follows a link carrying `secretkey` to claim it.
--
-- secretkey is a CSPRNG-generated Long (SecureRandomUtil), and it is the ONLY credential on the
-- invitation link - getUserInvitationBySecretLink looks up by it alone, with no bank scoping. It
-- is therefore security-relevant rather than an ordinary column, which is why the Doobie insert
-- generates it the same way rather than letting a caller pass one in.
--
-- Note there is NO index on secretkey despite every claim lookup filtering on it, and no
-- uniqueness constraint on it either. Confirmed against a booted instance; reproduced as-is,
-- since adding either is a schema decision beyond a storage swap.
--
-- One unique index on userinvitationid.

CREATE TABLE userinvitation(
    userinvitationid CHARACTER VARYING(44),
    firstname CHARACTER VARYING(50),
    lastname CHARACTER VARYING(50),
    purpose CHARACTER VARYING(50),
    secretkey BIGINT,
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    bankid CHARACTER VARYING(255),
    company CHARACTER VARYING(50),
    status CHARACTER VARYING(50),
    country CHARACTER VARYING(50),
    email CHARACTER VARYING(50),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE userinvitation ADD CONSTRAINT userinvitation_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX userinvitation_userinvitationid ON userinvitation(userinvitationid NULLS FIRST);
