-- Connector method routing (seventy-second table off Lift Mapper).
--
-- This is what StarConnector consults on EVERY connector call to decide which connector
-- implementation handles a given method for a given bank. The resolution order in
-- code.bankconnectors.package is: exact method+bankId match, then regex bankIdPattern match, then
-- method-only, then fall back to `mapped`. So this table is on the hottest path in the codebase
-- and its read semantics are load-bearing.
--
-- bankidpattern defaults to ".*" (match any) rather than NULL - MethodRouting.bankIdPatternMatchAny.
-- The provider treats a blank pattern as "not supplied" and, in that case, forces
-- isbankidexactmatch false: an exact match against no pattern is meaningless.
--
-- parameters holds the whole key/value list as one JSON array string rather than a child table.
--
-- One unique index on methodroutingid. Note there is NO uniqueness on
-- (methodname, bankidpattern), so several routings can compete for one method - resolution order,
-- not the schema, is what picks a winner. Confirmed against a booted instance.

CREATE TABLE methodrouting(
    methodroutingid CHARACTER VARYING(36),
    methodname CHARACTER VARYING(255),
    isbankidexactmatch BOOLEAN,
    bankidpattern CHARACTER VARYING(255),
    connectorname CHARACTER VARYING(255),
    parameters TEXT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE methodrouting ADD CONSTRAINT methodrouting_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX methodrouting_methodroutingid ON methodrouting(methodroutingid NULLS FIRST);
