-- Account access requests (seventy-third table off Lift Mapper). A maker/checker workflow: a
-- requestor asks for a user to be granted a view on an account, and a checker approves or
-- declines it exactly once.
--
-- "Exactly once" is enforced in SQL, not in Scala: updateStatus goes through
-- DoobieBusinessStatusQueries.conditionalAccountAccessRequestStatus, an
-- UPDATE ... WHERE id = ? AND status = 'INITIATED'. The loser of a concurrent approve/decline
-- gets 0 rows back and a Failure, rather than silently overwriting the other decision. That
-- guard predates this migration (see ConcurrentBusinessStatusRaceTest scenario M2) and the
-- migration leaves it exactly as it is - it is the whole reason the table is safe.
--
-- Four PLAIN indexes, none unique - including on accountaccessrequestid, which the provider
-- treats as an identifier. Confirmed against a booted instance; reproduced as-is.

CREATE TABLE accountaccessrequest(
    viewid CHARACTER VARYING(255),
    issystemview BOOLEAN,
    requestoruserid CHARACTER VARYING(44),
    targetuserid CHARACTER VARYING(44),
    checkeruserid CHARACTER VARYING(255),
    checkercomment TEXT,
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    bankid CHARACTER VARYING(44),
    accountid CHARACTER VARYING(44),
    status CHARACTER VARYING(64),
    accountaccessrequestid CHARACTER VARYING(36),
    businessjustification TEXT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE accountaccessrequest ADD CONSTRAINT accountaccessrequest_pk PRIMARY KEY(id);
CREATE INDEX accountaccessrequest_accountaccessrequestid ON accountaccessrequest(accountaccessrequestid NULLS FIRST);
CREATE INDEX accountaccessrequest_bankid_accountid ON accountaccessrequest(bankid NULLS FIRST, accountid NULLS FIRST);
CREATE INDEX accountaccessrequest_requestoruserid ON accountaccessrequest(requestoruserid NULLS FIRST);
CREATE INDEX accountaccessrequest_status ON accountaccessrequest(status NULLS FIRST);
