-- Bulk payments (seventy-fourth and seventy-fifth tables off Lift Mapper — two tables, one
-- entity file).
--
-- BULKPAYMENT: one row per item in a bulk transaction request. The unique index on
-- (transactionrequestid, itemindex) is what stops the same item being recorded twice for a
-- request.
--
-- BULKBATCHREFERENCE: one row per claimed batch_reference, scoped to a source account. Its unique
-- index on (frombankid, fromaccountid, batchreference) is the IDEMPOTENCY GUARD for bulk
-- submission: claimBatchReference relies on the database rejecting a duplicate claim, with tryo
-- turning that rejection into a Failure. Without the constraint, two concurrent submissions of
-- the same batch reference would both be accepted and the batch would execute twice. Not
-- decoration.
--
-- Every column is nullable, including those the code treats as required — Schemifier only marks
-- NOT NULL where dbNotNull_? says so, and this entity does not. failurereason and transactionid
-- are explicitly nullable and genuinely carry NULL (written from Option via orNull, read back
-- through Option), so their bindings must be Option-typed on the Doobie side.

CREATE TABLE bulkpayment(
    routingscheme CHARACTER VARYING(64),
    itemindex INTEGER,
    endtoendid CHARACTER VARYING(64),
    failurereason CHARACTER VARYING(1000),
    currency CHARACTER VARYING(8),
    address CHARACTER VARYING(128),
    description CHARACTER VARYING(2000),
    transactionid CHARACTER VARYING(64),
    status CHARACTER VARYING(16),
    amount CHARACTER VARYING(32),
    transactionrequestid CHARACTER VARYING(64),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE bulkpayment ADD CONSTRAINT bulkpayment_pk PRIMARY KEY(id);
CREATE INDEX bulkpayment_transactionrequestid ON bulkpayment(transactionrequestid NULLS FIRST);
CREATE UNIQUE INDEX bulkpayment_transactionrequestid_itemindex ON bulkpayment(transactionrequestid NULLS FIRST, itemindex NULLS FIRST);

CREATE TABLE bulkbatchreference(
    frombankid CHARACTER VARYING(255),
    fromaccountid CHARACTER VARYING(255),
    batchreference CHARACTER VARYING(64),
    transactionrequestid CHARACTER VARYING(64),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE bulkbatchreference ADD CONSTRAINT bulkbatchreference_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX bulkbatchreference_frombankid_fromaccountid_batchreference ON bulkbatchreference(frombankid NULLS FIRST, fromaccountid NULLS FIRST, batchreference NULLS FIRST);
