-- The KYC family (status / media / check / document) plus social-media handles: five tables that
-- share one shape — a customer-scoped history read newest-first by updatedat.
--
-- Notes that are easy to get wrong when reading these tables cold:
--
--   * updatedat is NOT bookkeeping here. Every getKyc*/getSocialMedias orders by it descending, so
--     a write path that forgets to stamp it silently reorders the caller's results. The Doobie
--     update paths stamp it explicitly for that reason.
--
--   * mid carries a UNIQUE index on kycmedia/kyccheck/kycdocument — it is the caller-supplied id
--     the add* methods use to decide update-vs-insert, so the constraint is what keeps that
--     decision single-valued.
--
--   * MAPPEDKYCSTATUS deliberately has NO unique index. addKycStatus looks a row up by
--     (mbankid, mcustomerid) and updates it, or inserts if absent — a check-then-act with nothing
--     underneath it, so two concurrent first-time writes for the same customer can both insert.
--     That is pre-existing and is reproduced as-is rather than corrected under a storage swap.
--
--   * user_c (the never-populated ResourceUser foreign key) and MAPPEDSOCIALMEDIA.bank are dead
--     columns: no code path writes or reads them. They are kept so the schema this migration
--     builds matches the one Schemifier built, rather than quietly diverging from deployed
--     databases.

CREATE TABLE mappedkycstatus(
    mcustomerid CHARACTER VARYING(44),
    mcustomernumber CHARACTER VARYING(64),
    mdate TIMESTAMP,
    mok BOOLEAN,
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    mbankid CHARACTER VARYING(44),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    user_c BIGINT
);
ALTER TABLE mappedkycstatus ADD CONSTRAINT mappedkycstatus_pk PRIMARY KEY(id);
CREATE INDEX mappedkycstatus_user_c ON mappedkycstatus(user_c NULLS FIRST);

CREATE TABLE mappedkycmedia(
    mcustomerid CHARACTER VARYING(44),
    mid CHARACTER VARYING(44),
    mcustomernumber CHARACTER VARYING(44),
    mtype CHARACTER VARYING(50),
    murl CHARACTER VARYING(255),
    mdate TIMESTAMP,
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    mbankid CHARACTER VARYING(44),
    mrelatestokycdocumentid CHARACTER VARYING(255),
    mrelatestokyccheckid CHARACTER VARYING(255),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedkycmedia ADD CONSTRAINT mappedkycmedia_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX mappedkycmedia_mid ON mappedkycmedia(mid NULLS FIRST);

CREATE TABLE mappedkyccheck(
    mhow CHARACTER VARYING(32),
    mstaffuserid CHARACTER VARYING(64),
    mcomments CHARACTER VARYING(2000),
    mcustomerid CHARACTER VARYING(44),
    mid CHARACTER VARYING(44),
    mcustomernumber CHARACTER VARYING(50),
    mdate TIMESTAMP,
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    mstaffname CHARACTER VARYING(64),
    msatisfied BOOLEAN,
    mbankid CHARACTER VARYING(44),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    user_c BIGINT
);
ALTER TABLE mappedkyccheck ADD CONSTRAINT mappedkyccheck_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX mappedkyccheck_mid ON mappedkyccheck(mid NULLS FIRST);
CREATE INDEX mappedkyccheck_user_c ON mappedkyccheck(user_c NULLS FIRST);

CREATE TABLE mappedkycdocument(
    mcustomerid CHARACTER VARYING(44),
    mid CHARACTER VARYING(44),
    mcustomernumber CHARACTER VARYING(50),
    mtype CHARACTER VARYING(50),
    mnumber CHARACTER VARYING(50),
    missuedate TIMESTAMP,
    missueplace CHARACTER VARYING(512),
    mexpirydate TIMESTAMP,
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    mbankid CHARACTER VARYING(44),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    user_c BIGINT
);
ALTER TABLE mappedkycdocument ADD CONSTRAINT mappedkycdocument_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX mappedkycdocument_mid ON mappedkycdocument(mid NULLS FIRST);
CREATE INDEX mappedkycdocument_user_c ON mappedkycdocument(user_c NULLS FIRST);

CREATE TABLE mappedsocialmedia(
    bank CHARACTER VARYING(44),
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    mcustomernumber CHARACTER VARYING(64),
    mtype CHARACTER VARYING(16),
    mhandle CHARACTER VARYING(64),
    mdateadded TIMESTAMP,
    mdateactivated TIMESTAMP,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    user_c BIGINT
);
ALTER TABLE mappedsocialmedia ADD CONSTRAINT mappedsocialmedia_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX mappedsocialmedia_mcustomernumber ON mappedsocialmedia(mcustomernumber NULLS FIRST);
CREATE INDEX mappedsocialmedia_user_c ON mappedsocialmedia(user_c NULLS FIRST);
