-- The chat group: rooms, messages, participants, reactions.
--
-- Constraints that carry behaviour rather than just protecting it:
--
--   * REACTION's unique index on (chatmessageid, userid, emoji) is what makes reacting idempotent —
--     a repeated INSERT is rejected instead of stacking duplicate reactions on one message.
--
--   * PARTICIPANT's unique index on (chatroomid, userid) is what makes "one membership per user per
--     room" true; every participant update targets that pair and would otherwise be ambiguous.
--
--   * CHATROOM's unique index on (bankid, name) is what getOrCreateDefaultRoom relies on to stay a
--     get-or-create rather than a create-every-time.
--
-- CHATROOM carries a denormalised copy of the newest message (lastmessageat, lastmessagepreview,
-- lastmessagesenderusername) so a room list does not need a per-room message query. lastmessageat
-- is genuinely NULL until the first message arrives — the room reader maps it to Option — while the
-- two string columns start empty rather than NULL, which is what Mapper's MappedString default
-- wrote.
--
-- PARTICIPANT has no createdat/updatedat: unlike the other three it never mixed in CreatedUpdated.
-- The columns are absent by design, not by omission.
--
-- The three "text" columns (chatroom.description, chatmessage.content, chatmessage.mentioneduserids,
-- participant.permissions) came from MappedText, which H2 rendered as an effectively unbounded
-- VARCHAR. They are nullable and existing rows do contain NULL, so the readers take Option and
-- normalise to "" / Nil rather than assuming a value is present.

CREATE TABLE chatroom(
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    bankid CHARACTER VARYING(255),
    createdbyuserid CHARACTER VARYING(36),
    description TEXT,
    chatroomid CHARACTER VARYING(36),
    joiningkey CHARACTER VARYING(36),
    isopenroom BOOLEAN,
    isarchived BOOLEAN,
    lastmessageat TIMESTAMP,
    lastmessagepreview CHARACTER VARYING(100),
    lastmessagesenderusername CHARACTER VARYING(255),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    name CHARACTER VARYING(255)
);
ALTER TABLE chatroom ADD CONSTRAINT chatroom_pk PRIMARY KEY(id);
CREATE INDEX chatroom_bankid ON chatroom(bankid NULLS FIRST);
CREATE UNIQUE INDEX chatroom_bankid_name ON chatroom(bankid NULLS FIRST, name NULLS FIRST);
CREATE UNIQUE INDEX chatroom_chatroomid ON chatroom(chatroomid NULLS FIRST);

CREATE TABLE chatmessage(
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    chatmessageid CHARACTER VARYING(36),
    chatroomid CHARACTER VARYING(36),
    senderuserid CHARACTER VARYING(36),
    senderconsumerid CHARACTER VARYING(36),
    content TEXT,
    messagetype CHARACTER VARYING(16),
    mentioneduserids TEXT,
    replytomessageid CHARACTER VARYING(36),
    threadid CHARACTER VARYING(36),
    isdeleted BOOLEAN,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE chatmessage ADD CONSTRAINT chatmessage_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX chatmessage_chatmessageid ON chatmessage(chatmessageid NULLS FIRST);
CREATE INDEX chatmessage_chatroomid ON chatmessage(chatroomid NULLS FIRST);
CREATE INDEX chatmessage_senderuserid ON chatmessage(senderuserid NULLS FIRST);
CREATE INDEX chatmessage_threadid ON chatmessage(threadid NULLS FIRST);

CREATE TABLE participant(
    userid CHARACTER VARYING(36),
    consumerid CHARACTER VARYING(36),
    participantid CHARACTER VARYING(36),
    chatroomid CHARACTER VARYING(36),
    webhookurl CHARACTER VARYING(1024),
    joinedat TIMESTAMP,
    lastreadat TIMESTAMP,
    ismuted BOOLEAN,
    permissions TEXT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE participant ADD CONSTRAINT participant_pk PRIMARY KEY(id);
CREATE INDEX participant_chatroomid ON participant(chatroomid NULLS FIRST);
CREATE UNIQUE INDEX participant_chatroomid_userid ON participant(chatroomid NULLS FIRST, userid NULLS FIRST);
CREATE UNIQUE INDEX participant_participantid ON participant(participantid NULLS FIRST);
CREATE INDEX participant_userid ON participant(userid NULLS FIRST);

CREATE TABLE reaction(
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    userid CHARACTER VARYING(36),
    reactionid CHARACTER VARYING(36),
    chatmessageid CHARACTER VARYING(36),
    emoji CHARACTER VARYING(64),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE reaction ADD CONSTRAINT reaction_pk PRIMARY KEY(id);
CREATE INDEX reaction_chatmessageid ON reaction(chatmessageid NULLS FIRST);
CREATE UNIQUE INDEX reaction_chatmessageid_userid_emoji ON reaction(chatmessageid NULLS FIRST, userid NULLS FIRST, emoji NULLS FIRST);
CREATE UNIQUE INDEX reaction_reactionid ON reaction(reactionid NULLS FIRST);
