-- Product collections (and their items), direct debits, and standing orders.
--
--   * MAPPEDPRODUCTCOLLECTION(mcollectioncode, mproductcode) and
--     MAPPEDPRODUCTCOLLECTIONITEM(mcollectioncode, mmemberproductcode) keep a collection from
--     listing the same product twice. getOrCreate* deletes the collection's rows and re-inserts,
--     so the constraint also catches a caller passing the same code twice in one list.
--
--   * DIRECTDEBIT(bankid, accountid, customerid, counterpartyid) is a real guard, not an index for
--     speed: it is what stops a second direct debit being set up for the same customer and
--     counterparty on one account. createDirectDebit wraps the insert in tryo, so the violation
--     surfaces to the caller as a Failure rather than an exception.
--
--   * STANDINGORDER deliberately has no unique index — repeat standing orders between the same
--     parties are legitimate (different amounts, schedules, or start dates), so nothing constrains
--     the tuple.
--
-- datecancelled is written by no code path on either table and so is always NULL; the traits type
-- it as a bare Date, so the readers map the absent value back to null rather than pretending it is
-- present. dateexpires is genuinely optional and behaves the same way.
--
-- standingorder.amountvalue is a BIGINT holding the amount in the currency's smallest unit; the
-- provider converts on the way in and back out. Reading it as a decimal amount without that
-- conversion would be wrong by a factor of 100 for most currencies.

CREATE TABLE mappedproductcollection(
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    mcollectioncode CHARACTER VARYING(50),
    mproductcode CHARACTER VARYING(50),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedproductcollection ADD CONSTRAINT mappedproductcollection_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX mappedproductcollection_mcollectioncode_mproductcode ON mappedproductcollection(mcollectioncode NULLS FIRST, mproductcode NULLS FIRST);

CREATE TABLE mappedproductcollectionitem(
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    mcollectioncode CHARACTER VARYING(50),
    mmemberproductcode CHARACTER VARYING(50),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedproductcollectionitem ADD CONSTRAINT mappedproductcollectionitem_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX mappedproductcollectionitem_mcollectioncode_mmemberproductcode ON mappedproductcollectionitem(mcollectioncode NULLS FIRST, mmemberproductcode NULLS FIRST);

CREATE TABLE directdebit(
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    userid CHARACTER VARYING(44),
    bankid CHARACTER VARYING(44),
    accountid CHARACTER VARYING(44),
    datesigned TIMESTAMP,
    datestarts TIMESTAMP,
    dateexpires TIMESTAMP,
    active BOOLEAN,
    counterpartyid CHARACTER VARYING(44),
    customerid CHARACTER VARYING(44),
    datecancelled TIMESTAMP,
    directdebitid CHARACTER VARYING(44),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE directdebit ADD CONSTRAINT directdebit_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX directdebit_bankid_accountid_customerid_counterpartyid ON directdebit(bankid NULLS FIRST, accountid NULLS FIRST, customerid NULLS FIRST, counterpartyid NULLS FIRST);

CREATE TABLE standingorder(
    standingorderid CHARACTER VARYING(44),
    whendetail CHARACTER VARYING(50),
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    userid CHARACTER VARYING(44),
    bankid CHARACTER VARYING(44),
    accountid CHARACTER VARYING(44),
    couterpartyid CHARACTER VARYING(44),
    amountvalue BIGINT,
    amountcurrency CHARACTER VARYING(3),
    whenfrequency CHARACTER VARYING(50),
    datesigned TIMESTAMP,
    datestarts TIMESTAMP,
    dateexpires TIMESTAMP,
    active BOOLEAN,
    customerid CHARACTER VARYING(44),
    datecancelled TIMESTAMP,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE standingorder ADD CONSTRAINT standingorder_pk PRIMARY KEY(id);
