-- The three webhook registries, consumer scopes, and account applications.
--
-- Each table's unique index is on its own generated id (maccountwebhookid, webhookid, mscopeid,
-- maccountapplicationid) — the public handle callers pass back in. Nothing constrains the
-- combination of fields underneath, which is deliberate on the webhook tables: the same URL may
-- legitimately be registered more than once for different triggers, and re-registering an identical
-- webhook is allowed.
--
-- MAPPEDSCOPE is the exception worth noticing: getScope and deleteScope both look a row up by
-- (mbankid, mconsumerid, mrolename), and addScope inserts without checking, yet no unique index
-- covers that triple. Adding the same scope twice therefore succeeds and leaves two rows, of which
-- lookups see one and a delete removes one. Pre-existing; reproduced rather than corrected here,
-- with the lookups pinned to id ASC so which row wins is at least deterministic.
--
-- MAPPEDACCOUNTAPPLICATION's muserid and mcustomerid come from Option[String] via orNull, so they
-- genuinely hold NULL and are read as Option. The status transition is guarded by a conditional
-- UPDATE elsewhere (DoobieBusinessStatusQueries), which is why the row model carries the numeric
-- id: that guard keys off it.

CREATE TABLE mappedaccountwebhook(
    mcreatedbyuserid CHARACTER VARYING(44),
    maccountid CHARACTER VARYING(64),
    maccountwebhookid CHARACTER VARYING(36),
    mtriggername CHARACTER VARYING(64),
    murl CHARACTER VARYING(1024),
    mhttpmethod CHARACTER VARYING(64),
    mhttpprotocol CHARACTER VARYING(64),
    misactive BOOLEAN,
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    mbankid CHARACTER VARYING(44),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedaccountwebhook ADD CONSTRAINT mappedaccountwebhook_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX mappedaccountwebhook_maccountwebhookid ON mappedaccountwebhook(maccountwebhookid NULLS FIRST);

CREATE TABLE bankaccountnotificationwebhook(
    webhookid CHARACTER VARYING(36),
    triggername CHARACTER VARYING(64),
    url CHARACTER VARYING(1024),
    httpmethod CHARACTER VARYING(64),
    httpprotocol CHARACTER VARYING(64),
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    bankid CHARACTER VARYING(44),
    createdbyuserid CHARACTER VARYING(44),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE bankaccountnotificationwebhook ADD CONSTRAINT bankaccountnotificationwebhook_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX bankaccountnotificationwebhook_webhookid ON bankaccountnotificationwebhook(webhookid NULLS FIRST);

CREATE TABLE systemaccountnotificationwebhook(
    webhookid CHARACTER VARYING(36),
    triggername CHARACTER VARYING(64),
    url CHARACTER VARYING(1024),
    httpmethod CHARACTER VARYING(64),
    httpprotocol CHARACTER VARYING(64),
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    createdbyuserid CHARACTER VARYING(44),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE systemaccountnotificationwebhook ADD CONSTRAINT systemaccountnotificationwebhook_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX systemaccountnotificationwebhook_webhookid ON systemaccountnotificationwebhook(webhookid NULLS FIRST);

CREATE TABLE mappedscope(
    mscopeid CHARACTER VARYING(36),
    mrolename CHARACTER VARYING(255),
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    mbankid CHARACTER VARYING(44),
    mconsumerid CHARACTER VARYING(44),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedscope ADD CONSTRAINT mappedscope_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX mappedscope_mscopeid ON mappedscope(mscopeid NULLS FIRST);

CREATE TABLE mappedaccountapplication(
    mcustomerid CHARACTER VARYING(36),
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    mcode CHARACTER VARYING(50),
    muserid CHARACTER VARYING(36),
    mstatus CHARACTER VARYING(255),
    maccountapplicationid CHARACTER VARYING(36),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedaccountapplication ADD CONSTRAINT mappedaccountapplication_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX mappedaccountapplication_maccountapplicationid ON mappedaccountapplication(maccountapplicationid NULLS FIRST);
