-- Customer addresses and entitlement requests.
--
-- MAPPEDCUSTOMERADDRESS.mcustomerid is NOT the public customer_id: it is a BIGINT holding
-- MAPPEDCUSTOMER's numeric primary key, left over from the Lift foreign key. Everything above the
-- store speaks in the public customer_id, so the queries join through mappedcustomer rather than
-- comparing the two. Reading it as if it were the public id silently matches nothing.
--
-- MAPPEDENTITLEMENTREQUEST has no unique index on (mbankid, muserid, mrolename) even though
-- getEntitlementRequest looks a row up by exactly that triple, so a user can have two outstanding
-- requests for the same role and a lookup sees one of them. Pre-existing; reproduced as-is, with
-- id ASC pinning which one.

CREATE TABLE mappedcustomeraddress(
    mcustomeraddressid CHARACTER VARYING(36),
    mtags CHARACTER VARYING(20),
    mcustomerid BIGINT,
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    mline1 CHARACTER VARYING(255),
    mline2 CHARACTER VARYING(255),
    mline3 CHARACTER VARYING(255),
    mcity CHARACTER VARYING(255),
    mcounty CHARACTER VARYING(255),
    mstate CHARACTER VARYING(255),
    mpostcode CHARACTER VARYING(20),
    mcountrycode CHARACTER VARYING(2),
    mstatus CHARACTER VARYING(20),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedcustomeraddress ADD CONSTRAINT mappedcustomeraddress_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX mappedcustomeraddress_mcustomeraddressid ON mappedcustomeraddress(mcustomeraddressid NULLS FIRST);
CREATE INDEX mappedcustomeraddress_mcustomerid ON mappedcustomeraddress(mcustomerid NULLS FIRST);

CREATE TABLE mappedentitlementrequest(
    mrolename CHARACTER VARYING(255),
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    mbankid CHARACTER VARYING(44),
    muserid CHARACTER VARYING(44),
    mentitlementrequestid CHARACTER VARYING(36),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedentitlementrequest ADD CONSTRAINT mappedentitlementrequest_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX mappedentitlementrequest_mentitlementrequestid ON mappedentitlementrequest(mentitlementrequestid NULLS FIRST);
