-- Customer dependants, counterparty bespokes, and expected challenge answers.
--
-- MAPPEDCUSTOMERDEPENDANT.mcustomer and MAPPEDCOUNTERPARTYBESPOKE.mcounterparty are BIGINTs holding
-- the parent row's numeric primary key, not the public customer_id / counterparty_id. Both
-- providers already take that numeric key as their argument, so the values pass through unchanged —
-- but a reader who assumes these are public ids will match nothing.
--
-- EXPECTEDCHALLENGEANSWER's unique index on challengeid is load-bearing for payment security: the
-- compare-and-set that flips successful false -> true keys off it, and that CAS is what stops one
-- challenge green-lighting a payment twice. successful is stored as SUCCESSFUL_C because SUCCESSFUL
-- collides with a SQL reserved word, which is why the column name does not match the field.
--
-- The optional challenge columns hold '' rather than NULL when absent, because Mapper wrote
-- MappedString's default. That distinction is visible above the store: consentid and basketid are
-- surfaced with a bare Option, so an absent value reads as Some("") rather than None, while the
-- three PSD2 dynamic-linking columns filter empties out and do read as None. Both behaviours are
-- preserved verbatim.

CREATE TABLE mappedcustomerdependant(
    mcustomer BIGINT,
    mdateofbirth TIMESTAMP,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedcustomerdependant ADD CONSTRAINT mappedcustomerdependant_pk PRIMARY KEY(id);
CREATE INDEX mappedcustomerdependant_mcustomer ON mappedcustomerdependant(mcustomer NULLS FIRST);

CREATE TABLE mappedcounterpartybespoke(
    mkey CHARACTER VARYING(255),
    mvaule CHARACTER VARYING(255),
    mcounterparty BIGINT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedcounterpartybespoke ADD CONSTRAINT mappedcounterpartybespoke_pk PRIMARY KEY(id);
CREATE INDEX mappedcounterpartybespoke_mcounterparty ON mappedcounterpartybespoke(mcounterparty NULLS FIRST);

CREATE TABLE expectedchallengeanswer(
    basketid CHARACTER VARYING(100),
    consentid CHARACTER VARYING(100),
    challengeid CHARACTER VARYING(36),
    challengetype CHARACTER VARYING(100),
    expectedanswer CHARACTER VARYING(50),
    expecteduserid CHARACTER VARYING(36),
    salt CHARACTER VARYING(50),
    successful_c BOOLEAN,
    scamethod CHARACTER VARYING(100),
    scastatus CHARACTER VARYING(100),
    attemptcounter INTEGER,
    challengepurpose CHARACTER VARYING(2000),
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    transactionrequestid CHARACTER VARYING(36),
    authenticationmethodid CHARACTER VARYING(100),
    challengecontexthash CHARACTER VARYING(64),
    challengecontextstructure CHARACTER VARYING(500),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE expectedchallengeanswer ADD CONSTRAINT expectedchallengeanswer_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX expectedchallengeanswer_challengeid ON expectedchallengeanswer(challengeid NULLS FIRST);
