-- User attributes and regulated entities.
--
-- USERATTRIBUTE's `type` column is TYPE_C: TYPE collides with a SQL reserved word, so Schemifier
-- appended the suffix. The field is still called Type above the store, which is why the two names
-- do not match.
--
-- Neither table's id column is unique. USERATTRIBUTE.userattributeid carries a plain index despite
-- being the handle every lookup, update and delete keys off, and REGULATEDENTITY.entityid carries
-- no index at all while getRegulatedEntityByEntityId reads by it and deleteRegulatedEntity deletes
-- by it. Both ids are generated UUIDs, so a collision is not the practical worry; the absent
-- constraint just means nothing enforces what the code already assumes. Pre-existing and
-- reproduced as-is, with id ASC pinning which row a lookup sees.

CREATE TABLE userattribute(
    userattributeid CHARACTER VARYING(36),
    value CHARACTER VARYING(255),
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    userid CHARACTER VARYING(36),
    ispersonal BOOLEAN,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    name CHARACTER VARYING(255),
    type_c CHARACTER VARYING(50)
);
ALTER TABLE userattribute ADD CONSTRAINT userattribute_pk PRIMARY KEY(id);
CREATE INDEX userattribute_userattributeid ON userattribute(userattributeid NULLS FIRST);

CREATE TABLE regulatedentity(
    entityname CHARACTER VARYING(256),
    entityid CHARACTER VARYING(36),
    entitycode CHARACTER VARYING(50),
    entitytype CHARACTER VARYING(50),
    entityaddress CHARACTER VARYING(256),
    entitytowncity CHARACTER VARYING(50),
    entitypostcode CHARACTER VARYING(50),
    entitycountry CHARACTER VARYING(50),
    entitywebsite CHARACTER VARYING(256),
    services TEXT,
    certificateauthoritycaownerid CHARACTER VARYING(256),
    entitycertificatepublickey TEXT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE regulatedentity ADD CONSTRAINT regulatedentity_pk PRIMARY KEY(id);
CREATE INDEX regulatedentity_certificateauthoritycaownerid ON regulatedentity(certificateauthoritycaownerid NULLS FIRST);
