-- Routing schemes, per-bank routing-scheme support, and ABAC rules.
--
--   * ROUTINGSCHEME(scheme) is unique, which is what makes `scheme` usable as the handle every
--     read, update and the soft delete key off.
--
--   * BANKSUPPORTEDROUTINGSCHEME(bankid, scheme) is unique, which is what makes
--     putBankSupportedRoutingScheme an upsert rather than an append: it looks the pair up and
--     updates, or inserts when absent.
--
--   * ABACRULE has three plain indexes and no unique one, though abacRuleId is the handle the
--     update and delete key off and getAbacRuleByName reads by rulename. Two rules may therefore
--     share a name. Pre-existing; reproduced with id ASC pinning which one a lookup sees.
--
-- Deleting a routing scheme is a soft delete — status goes to RETIRED and the row stays, so
-- historical addresses can still be resolved. Nothing removes these rows.
--
-- downstreamrails and secondaryaddresspattern hold '' rather than NULL when absent, and the
-- readers turn '' into Nil / None respectively.

CREATE TABLE routingscheme(
    createdbyuserid CHARACTER VARYING(255),
    scheme CHARACTER VARYING(64),
    country CHARACTER VARYING(8),
    addresspattern CHARACTER VARYING(1024),
    exampleaddress CHARACTER VARYING(255),
    description TEXT,
    downstreamrails CHARACTER VARYING(512),
    creationdate TIMESTAMP,
    lastupdate TIMESTAMP,
    status CHARACTER VARYING(16),
    secondaryaddresspattern CHARACTER VARYING(1024),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    category CHARACTER VARYING(16)
);
ALTER TABLE routingscheme ADD CONSTRAINT routingscheme_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX routingscheme_scheme ON routingscheme(scheme NULLS FIRST);

CREATE TABLE banksupportedroutingscheme(
    bankid CHARACTER VARYING(255),
    scheme CHARACTER VARYING(64),
    enabled BOOLEAN,
    banknotes CHARACTER VARYING(1024),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE banksupportedroutingscheme ADD CONSTRAINT banksupportedroutingscheme_pk PRIMARY KEY(id);
CREATE INDEX banksupportedroutingscheme_bankid ON banksupportedroutingscheme(bankid NULLS FIRST);
CREATE UNIQUE INDEX banksupportedroutingscheme_bankid_scheme ON banksupportedroutingscheme(bankid NULLS FIRST, scheme NULLS FIRST);

CREATE TABLE abacrule(
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    createdbyuserid CHARACTER VARYING(255),
    description TEXT,
    updatedbyuserid CHARACTER VARYING(255),
    abacruleid CHARACTER VARYING(255),
    rulename CHARACTER VARYING(255),
    isactive BOOLEAN,
    rulecode TEXT,
    policy TEXT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE abacrule ADD CONSTRAINT abacrule_pk PRIMARY KEY(id);
CREATE INDEX abacrule_abacruleid ON abacrule(abacruleid NULLS FIRST);
CREATE INDEX abacrule_createdbyuserid ON abacrule(createdbyuserid NULLS FIRST);
CREATE INDEX abacrule_rulename ON abacrule(rulename NULLS FIRST);
