-- Endpoint mappings and the dynamic-entity projection registry.
--
-- ENDPOINTMAPPING(operationid) is unique GLOBALLY, not per bank, even though the provider looks
-- rows up by (operationid, bankid). A bank-level mapping and a system-level mapping therefore
-- cannot share an operation id — the second create fails rather than shadowing the first. That is
-- the existing contract and the endpoint tests depend on it; the bankid column narrows a read, it
-- does not widen the key.
--
-- ENDPOINTMAPPING.bankid genuinely holds NULL for system-level mappings, because the provider
-- writes bankId.getOrElse(null) and reads it back through a null/empty check. It is bound as an
-- Option so SQL NULL is preserved rather than throwing at bind time.
--
-- DYNAMICENTITYINDEX is the registry for DE_indexing: one row per declared indexed field, holding
-- the provisioning state machine and the hashed table/column identifiers. The projection *tables*
-- it describes are created by the Doobie provisioner outside any schema tool; this registry is a
-- normal migrated table. Its index on (entityname, bankid, fieldname) is plain, not unique, even
-- though markReady looks a row up by exactly that triple and inserts when absent — so a
-- concurrent double-provision would leave two rows. Pre-existing; reproduced as-is with id ASC
-- pinning which row a lookup sees.

CREATE TABLE endpointmapping(
    endpointmappingid CHARACTER VARYING(36),
    operationid CHARACTER VARYING(255),
    requestmapping TEXT,
    responsemapping TEXT,
    bankid CHARACTER VARYING(255),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE endpointmapping ADD CONSTRAINT endpointmapping_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX endpointmapping_endpointmappingid ON endpointmapping(endpointmappingid NULLS FIRST);
CREATE UNIQUE INDEX endpointmapping_operationid ON endpointmapping(operationid NULLS FIRST);

CREATE TABLE dynamicentityindex(
    fieldname CHARACTER VARYING(255),
    fieldtype CHARACTER VARYING(64),
    indexkind CHARACTER VARYING(32),
    safetablename CHARACTER VARYING(128),
    safecolumnname CHARACTER VARYING(128),
    backfillcheckpoint CHARACTER VARYING(255),
    rowcountexpected BIGINT,
    coercionerrors BIGINT,
    lasterror TEXT,
    provisionerversion INTEGER,
    entityname CHARACTER VARYING(255),
    bankid CHARACTER VARYING(255),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    state CHARACTER VARYING(32)
);
ALTER TABLE dynamicentityindex ADD CONSTRAINT dynamicentityindex_pk PRIMARY KEY(id);
CREATE INDEX dynamicentityindex_entityname_bankid_fieldname ON dynamicentityindex(entityname NULLS FIRST, bankid NULLS FIRST, fieldname NULLS FIRST);
