-- Meetings and their invitees.
--
-- mcustomeruserid and mstaffuserid are BIGINTs holding RESOURCEUSER's numeric primary key, not the
-- public user_id — the `present` accessor resolves them through a join. mstaffuserid is never
-- written (createMeeting has that line commented out), so it is always NULL and the staff user id
-- surfaces as "".
--
-- MAPPEDMEETINGINVITEE.mmappedmeeting is likewise MAPPEDMEETING's numeric key. Invitees were read
-- through a Lift OneToMany that ordered by id ascending; the replacement query keeps that order,
-- which is the order the invitees were supplied in.
--
-- MAPPEDMEETING(mmeetingid) is unique. Nothing constrains (mbankid, mmeetingid) even though
-- getMeeting reads by that pair, but the unique id makes the pair single-valued anyway.

CREATE TABLE mappedmeeting(
    mstaffuserid BIGINT,
    mmeetingid CHARACTER VARYING(36),
    mwhen TIMESTAMP,
    mcustomeruserid BIGINT,
    mproviderid CHARACTER VARYING(64),
    mpurposeid CHARACTER VARYING(64),
    msessionid CHARACTER VARYING(255),
    mcustomertoken CHARACTER VARYING(255),
    mstafftoken CHARACTER VARYING(255),
    mcreatorname CHARACTER VARYING(255),
    mcreatorphone CHARACTER VARYING(32),
    mcreatoremail CHARACTER VARYING(100),
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    mbankid CHARACTER VARYING(44),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedmeeting ADD CONSTRAINT mappedmeeting_pk PRIMARY KEY(id);
CREATE INDEX mappedmeeting_mcustomeruserid ON mappedmeeting(mcustomeruserid NULLS FIRST);
CREATE UNIQUE INDEX mappedmeeting_mmeetingid ON mappedmeeting(mmeetingid NULLS FIRST);
CREATE INDEX mappedmeeting_mstaffuserid ON mappedmeeting(mstaffuserid NULLS FIRST);

CREATE TABLE mappedmeetinginvitee(
    mmappedmeeting BIGINT,
    mphone CHARACTER VARYING(255),
    memail CHARACTER VARYING(100),
    mname CHARACTER VARYING(255),
    mstatus CHARACTER VARYING(255),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedmeetinginvitee ADD CONSTRAINT mappedmeetinginvitee_pk PRIMARY KEY(id);
CREATE INDEX mappedmeetinginvitee_mmappedmeeting ON mappedmeetinginvitee(mmappedmeeting NULLS FIRST);
