-- Customer messages and per-bank transaction-request-type charges.
--
-- MAPPEDCUSTOMERMESSAGE has TWO owner columns and they are not interchangeable. user_c holds
-- RESOURCEUSER's numeric key and is written only by the deprecated addMessage path;
-- `customer` holds MAPPEDCUSTOMER's numeric key and is written only by createCustomerMessage.
-- Each read filters on exactly one of them, so a message created one way is invisible to the other
-- reader. That is the existing behaviour and the reason the deprecation note on `user` exists;
-- reproduced rather than unified here.
--
-- MAPPEDTRANSACTIONREQUESTTYPECHARGE has no index beyond its primary key, though the only read
-- filters on (mbankid, mtransactionrequesttypeid) and expects at most one row. Nothing enforces
-- that. Pre-existing; reproduced with id ASC pinning which row a lookup sees.

CREATE TABLE mappedcustomermessage(
    mmessageid CHARACTER VARYING(36),
    mfromperson CHARACTER VARYING(64),
    mfromdepartment CHARACTER VARYING(64),
    mmessage CHARACTER VARYING(1024),
    mtransport CHARACTER VARYING(64),
    bank CHARACTER VARYING(44),
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    customer BIGINT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    user_c BIGINT
);
ALTER TABLE mappedcustomermessage ADD CONSTRAINT mappedcustomermessage_pk PRIMARY KEY(id);
CREATE INDEX mappedcustomermessage_customer ON mappedcustomermessage(customer NULLS FIRST);
CREATE UNIQUE INDEX mappedcustomermessage_mmessageid ON mappedcustomermessage(mmessageid NULLS FIRST);
CREATE INDEX mappedcustomermessage_user_c ON mappedcustomermessage(user_c NULLS FIRST);

CREATE TABLE mappedtransactionrequesttypecharge(
    mchargecurrency CHARACTER VARYING(3),
    mchargeamount CHARACTER VARYING(32),
    mchargesummary CHARACTER VARYING(255),
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    mbankid CHARACTER VARYING(44),
    mtransactionrequesttypeid CHARACTER VARYING(44),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedtransactionrequesttypecharge ADD CONSTRAINT mappedtransactionrequesttypecharge_pk PRIMARY KEY(id);
