-- Physical cards and their PIN resets.
--
-- MAPPEDPHYSICALCARD.maccount is a BIGINT holding MAPPEDBANKACCOUNT's numeric primary key, not the
-- public account_id. The card's `account` accessor resolves it, and a card whose key does not
-- resolve throws — the trait types account as a bare BankAccount, so there is no absent case.
--
-- The unique index on (mbankid, mbankcardnumber, missuenumber) is the only constraint. Note it does
-- NOT cover mcardid, which is the handle getPhysicalCardForBank, updatePhysicalCard and
-- deletePhysicalCardForBank all key off, nor (mbankid, mserialnumber, mbankcardnumber), which is
-- what createPhysicalCard checks for an existing card before inserting. Both are generated or
-- caller-supplied ids that the code assumes unique without the database enforcing it.
-- Pre-existing; reproduced as-is, with id ASC pinning which row a lookup sees.
--
-- PINRESET.card holds MAPPEDPHYSICALCARD's numeric key. The rows were read through a Lift OneToMany
-- ordered by id ascending; the replacement query keeps that order.
--
-- There is no CARDACTION table. The Lift entity of that name was declared but never registered for
-- schema creation, so it has never existed in any database and nothing reads or writes it. It is
-- dropped rather than migrated — see the code comment.

CREATE TABLE mappedphysicalcard(
    mbankid CHARACTER VARYING(50),
    mreplacementdate TIMESTAMP,
    mreplacementreason CHARACTER VARYING(255),
    mcustomerid CHARACTER VARYING(255),
    mcollected TIMESTAMP,
    maccount BIGINT,
    mposted TIMESTAMP,
    mallows CHARACTER VARYING(255),
    mnetworks CHARACTER VARYING(255),
    mcvv CHARACTER VARYING(255),
    mbrand CHARACTER VARYING(255),
    mtechnology CHARACTER VARYING(255),
    mcancelled BOOLEAN,
    monhotlist BOOLEAN,
    menabled BOOLEAN,
    mexpires TIMESTAMP,
    mvalidfrom TIMESTAMP,
    mserialnumber CHARACTER VARYING(50),
    mnameoncard CHARACTER VARYING(128),
    missuenumber CHARACTER VARYING(10),
    mcardid CHARACTER VARYING(255),
    mcardtype CHARACTER VARYING(255),
    mbankcardnumber CHARACTER VARYING(50),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedphysicalcard ADD CONSTRAINT mappedphysicalcard_pk PRIMARY KEY(id);
CREATE INDEX mappedphysicalcard_maccount ON mappedphysicalcard(maccount NULLS FIRST);
CREATE UNIQUE INDEX mappedphysicalcard_mbankid_mbankcardnumber_missuenumber ON mappedphysicalcard(mbankid NULLS FIRST, mbankcardnumber NULLS FIRST, missuenumber NULLS FIRST);

CREATE TABLE pinreset(
    card BIGINT,
    mreplacementdate TIMESTAMP,
    mreplacementreason CHARACTER VARYING(255),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE pinreset ADD CONSTRAINT pinreset_pk PRIMARY KEY(id);
CREATE INDEX pinreset_card ON pinreset(card NULLS FIRST);
