-- The double-entry book: one row linking the debit and credit legs of a single movement.
--
-- Both unique indexes are load-bearing rather than protective. Each leg — (bank, account,
-- transaction) on the debit side and on the credit side — may appear in the book at most once, so
-- a transaction cannot be booked into two different double-entry pairs. The connector's save wraps
-- the insert in tryo, so a duplicate booking surfaces as a Failure rather than silently creating a
-- second link.
--
-- The transactionrequest* columns hold '' rather than NULL when the movement did not come from a
-- transaction request; the readers turn '' back into None. That is why they are plain Strings here
-- and Options above the store.

CREATE TABLE doubleentrybooktransaction(
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    debittransactionid CHARACTER VARYING(44),
    transactionrequestbankid CHARACTER VARYING(255),
    transactionrequestaccountid CHARACTER VARYING(64),
    transactionrequestid CHARACTER VARYING(44),
    debittransactionbankid CHARACTER VARYING(255),
    debittransactionaccountid CHARACTER VARYING(64),
    credittransactionbankid CHARACTER VARYING(255),
    credittransactionaccountid CHARACTER VARYING(64),
    credittransactionid CHARACTER VARYING(44),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE doubleentrybooktransaction ADD CONSTRAINT doubleentrybooktransaction_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX doubleentrybooktransaction_credittransactionbankid_credittransactionaccountid_credittransactionid ON doubleentrybooktransaction(credittransactionbankid NULLS FIRST, credittransactionaccountid NULLS FIRST, credittransactionid NULLS FIRST);
CREATE UNIQUE INDEX doubleentrybooktransaction_debittransactionbankid_debittransactionaccountid_debittransactionid ON doubleentrybooktransaction(debittransactionbankid NULLS FIRST, debittransactionaccountid NULLS FIRST, debittransactionid NULLS FIRST);
