-- Dynamic endpoints: one row per uploaded OpenAPI document.
--
-- bankid genuinely holds NULL for system-level endpoints — create writes bankId.getOrElse(null) and
-- the reader turns null-or-empty back into None — so it is bound as an Option rather than a bare
-- String.
--
-- Only dynamicendpointid is unique. Every read and the delete accept an optional bank id that
-- merely narrows the match, so a system-level lookup finds a bank-level row with the same id and
-- vice versa is prevented only by the id being generated. Pre-existing; reproduced as-is.

CREATE TABLE dynamicendpoint(
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    dynamicendpointid CHARACTER VARYING(36),
    swaggerstring TEXT,
    userid CHARACTER VARYING(255),
    bankid CHARACTER VARYING(255),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE dynamicendpoint ADD CONSTRAINT dynamicendpoint_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX dynamicendpoint_dynamicendpointid ON dynamicendpoint(dynamicendpointid NULLS FIRST);
