-- Connector metrics: one row per connector method call.
--
-- Writes already went through Doobie (ConnectorMetricBatchWriter batches the inserts); only the
-- reads were still Lift. The table is append-only from the application's side — nothing updates a
-- row once written.
--
-- `date` is stored as DATE_C because DATE collides with a SQL reserved word, which is why the
-- column name does not match the field.
--
-- Five plain indexes, no unique one, and that is correct here: a connector may call the same
-- function with the same correlation id more than once and each call is its own row.

CREATE TABLE mappedconnectormetric(
    correlationid CHARACTER VARYING(36),
    issuccessful BOOLEAN,
    connectorname CHARACTER VARYING(64),
    functionname CHARACTER VARYING(64),
    apiinstanceid CHARACTER VARYING(255),
    requestparams CHARACTER VARYING(1024),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    duration BIGINT,
    date_c TIMESTAMP
);
ALTER TABLE mappedconnectormetric ADD CONSTRAINT mappedconnectormetric_pk PRIMARY KEY(id);
CREATE INDEX mappedconnectormetric_connectorname ON mappedconnectormetric(connectorname NULLS FIRST);
CREATE INDEX mappedconnectormetric_correlationid ON mappedconnectormetric(correlationid NULLS FIRST);
CREATE INDEX mappedconnectormetric_date_c ON mappedconnectormetric(date_c NULLS FIRST);
CREATE INDEX mappedconnectormetric_functionname ON mappedconnectormetric(functionname NULLS FIRST);
CREATE INDEX mappedconnectormetric_issuccessful ON mappedconnectormetric(issuccessful NULLS FIRST);
