-- Entitlements: one row per (bank, user, role) grant.
--
-- The unique index on (mbankid, muserid, mrolename) is load-bearing for authorisation, not an
-- optimisation. addEntitlement relies on it: the insert is wrapped so that a concurrent duplicate
-- grant hits the constraint, and the loser then re-reads and returns the committed row instead of
-- failing or creating a second grant. Without it a role could be held twice and a single revoke
-- would leave one behind.
--
-- Four columns carry an explicit dbColumnName in the entity and so break the m-prefix convention:
-- group_id, process, granted_by_user_id and entitlement_request_id. The migration keeps those exact
-- names — the entity's field names are mGroupId, mProcess, mGrantedByUserId and
-- entitlement_request_id respectively.
--
-- group_id, process and granted_by_user_id default to '' and are read back through an empty check,
-- so absent means empty string. entitlement_request_id is the exception: it defaults to NULL, and
-- its reader additionally rejects the all-zero UUID, because only request-born grants set it.

CREATE TABLE mappedentitlement(
    mrolename CHARACTER VARYING(255),
    mbankid CHARACTER VARYING(44),
    createdat TIMESTAMP,
    muserid CHARACTER VARYING(44),
    updatedat TIMESTAMP,
    mentitlementid CHARACTER VARYING(36),
    mcreatedbyprocess CHARACTER VARYING(255),
    group_id CHARACTER VARYING(255),
    process CHARACTER VARYING(255),
    granted_by_user_id CHARACTER VARYING(44),
    entitlement_request_id CHARACTER VARYING(36),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedentitlement ADD CONSTRAINT mappedentitlement_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX mappedentitlement_mbankid_muserid_mrolename ON mappedentitlement(mbankid NULLS FIRST, muserid NULLS FIRST, mrolename NULLS FIRST);
CREATE UNIQUE INDEX mappedentitlement_mentitlementid ON mappedentitlement(mentitlementid NULLS FIRST);
