-- Rate limiting: one row per (consumer, optional bank, optional api version, optional api name)
-- scope, valid over a date window.
--
-- The three optional scope columns hold SQL NULL, not '', when the scope is broader — the provider
-- writes them through orNull. That distinction is load-bearing: getByConsumerId resolves a limit by
-- trying four increasingly general scopes in order (consumer+version+name, consumer+name,
-- consumer+version, consumer) and each tier matches the columns it is NOT scoping on with
-- `IS NULL`. A row that stored '' instead of NULL would be invisible to every one of those tiers.
--
-- Note the readers are laxer than the queries: apiName/apiVersion/bankId map both NULL and '' to
-- None, while the lookups only accept NULL. Preserved as-is.
--
-- The six call-limit columns are NOT NULL-able in practice but carry no database default. Their
-- defaults come from props (rate_limiting_per_second and friends, -1 when unset) and are resolved
-- in application code at insert time, which is what Lift's field defaults did.
--
-- Only ratelimitingid is unique. Nothing stops two rows sharing a scope and an overlapping date
-- window; findMostRecentRateLimit picks by updatedat descending, so the newest wins.

CREATE TABLE ratelimiting(
    bankid CHARACTER VARYING(44),
    consumerid CHARACTER VARYING(250),
    persecondcalllimit BIGINT,
    perminutecalllimit BIGINT,
    perhourcalllimit BIGINT,
    perdaycalllimit BIGINT,
    perweekcalllimit BIGINT,
    permonthcalllimit BIGINT,
    fromdate TIMESTAMP,
    todate TIMESTAMP,
    apiname CHARACTER VARYING(250),
    apiversion CHARACTER VARYING(250),
    ratelimitingid CHARACTER VARYING(36),
    createdat TIMESTAMP,
    updatedat TIMESTAMP,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE ratelimiting ADD CONSTRAINT ratelimiting_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX ratelimiting_ratelimitingid ON ratelimiting(ratelimitingid NULLS FIRST);
