-- Products: one row per (bank, product code).
--
-- The unique index on (mbankid, mcode) is what makes the code a usable handle — every read, the
-- createOrUpdate decision and the cascade delete key off that pair.
--
-- mparentproductcode models the product hierarchy by value, not by foreign key: getProductTree
-- walks it by repeatedly looking up (bankId, parentProductCode). An empty string terminates the
-- walk, so a product with no parent must store "" and not NULL — which is what Mapper's untouched
-- MappedString default wrote. Storing NULL there would make the walk read a null and the tree
-- would break rather than end.
--
-- No column is nullable in practice for the same reason: every accessor returns a bare String and
-- the sandbox importer omits several fields, relying on the "" default.

CREATE TABLE mappedproduct(
    mbankid CHARACTER VARYING(44),
    mcode CHARACTER VARYING(50),
    mname CHARACTER VARYING(125),
    mlicenseid CHARACTER VARYING(44),
    mlicensename CHARACTER VARYING(255),
    mparentproductcode CHARACTER VARYING(50),
    mcategory CHARACTER VARYING(50),
    mfamily CHARACTER VARYING(50),
    msuperfamily CHARACTER VARYING(50),
    mmoreinfourl CHARACTER VARYING(2000),
    mdetails CHARACTER VARYING(2000),
    mdescription CHARACTER VARYING(2000),
    mtermsandconditionsurl CHARACTER VARYING(2000),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedproduct ADD CONSTRAINT mappedproduct_pk PRIMARY KEY(id);
CREATE INDEX mappedproduct_mbankid ON mappedproduct(mbankid NULLS FIRST);
CREATE UNIQUE INDEX mappedproduct_mbankid_mcode ON mappedproduct(mbankid NULLS FIRST, mcode NULLS FIRST);
