-- Branches: one row per (bank, branch).
--
-- Fifty columns, almost all of them nullable in practice, because the connector writes many of
-- them through orNull — mcounty, mbranchroutingscheme, mbranchroutingaddress, every drive-up
-- opening and closing time, mbranchtype, mmoreinfo and mphonenumber all genuinely hold NULL. The
-- reader surfaces them as null again, which is what Lift's MappedString did; binding them as bare
-- Strings would throw at write time instead.
--
-- The lobby times are the exception: the connector defaults them to "00:00" rather than null, so
-- an absent lobby schedule reads back as a real time rather than a null.
--
-- misaccessible is a tristate stored as text — "Y", "N" or "" for unknown — not a boolean.
--
-- The unique index on (mbankid, mbranchid) is what makes the branch id a usable handle; the plain
-- index on mbankid serves the per-bank listing, which also filters on misdeleted = false. Deletion
-- is soft: nothing removes these rows.

CREATE TABLE mappedbranch(
    mbranchid CHARACTER VARYING(44),
    mname CHARACTER VARYING(255),
    mline1 CHARACTER VARYING(255),
    mline2 CHARACTER VARYING(255),
    mline3 CHARACTER VARYING(255),
    mcity CHARACTER VARYING(255),
    mcounty CHARACTER VARYING(255),
    mstate CHARACTER VARYING(255),
    mpostcode CHARACTER VARYING(20),
    mcountrycode CHARACTER VARYING(2),
    mlocationlatitude DOUBLE PRECISION,
    mlocationlongitude DOUBLE PRECISION,
    mlicenseid CHARACTER VARYING(44),
    mlicensename CHARACTER VARYING(255),
    mlobbyhours CHARACTER VARYING(2000),
    mdriveuphours CHARACTER VARYING(2000),
    misaccessible CHARACTER VARYING(1),
    mbranchtype CHARACTER VARYING(32),
    mmoreinfo CHARACTER VARYING(128),
    mphonenumber CHARACTER VARYING(32),
    misdeleted BOOLEAN,
    mbankid CHARACTER VARYING(44),
    mbranchroutingscheme CHARACTER VARYING(32),
    mbranchroutingaddress CHARACTER VARYING(64),
    mlobbyopeningtimeonmonday CHARACTER VARYING(5),
    mlobbyclosingtimeonmonday CHARACTER VARYING(5),
    mlobbyopeningtimeontuesday CHARACTER VARYING(5),
    mlobbyclosingtimeontuesday CHARACTER VARYING(5),
    mlobbyopeningtimeonwednesday CHARACTER VARYING(5),
    mlobbyclosingtimeonwednesday CHARACTER VARYING(5),
    mlobbyopeningtimeonthursday CHARACTER VARYING(5),
    mlobbyclosingtimeonthursday CHARACTER VARYING(5),
    mlobbyopeningtimeonfriday CHARACTER VARYING(5),
    mlobbyclosingtimeonfriday CHARACTER VARYING(5),
    mlobbyopeningtimeonsaturday CHARACTER VARYING(5),
    mlobbyclosingtimeonsaturday CHARACTER VARYING(5),
    mlobbyopeningtimeonsunday CHARACTER VARYING(5),
    mlobbyclosingtimeonsunday CHARACTER VARYING(5),
    mdriveupopeningtimeonmonday CHARACTER VARYING(5),
    mdriveupclosingtimeonmonday CHARACTER VARYING(5),
    mdriveupopeningtimeontuesday CHARACTER VARYING(5),
    mdriveupclosingtimeontuesday CHARACTER VARYING(5),
    mdriveupopeningtimeonwednesday CHARACTER VARYING(5),
    mdriveupclosingtimeonwednesday CHARACTER VARYING(5),
    mdriveupopeningtimeonthursday CHARACTER VARYING(5),
    mdriveupclosingtimeonthursday CHARACTER VARYING(5),
    mdriveupopeningtimeonfriday CHARACTER VARYING(5),
    mdriveupclosingtimeonfriday CHARACTER VARYING(5),
    mdriveupopeningtimeonsaturday CHARACTER VARYING(5),
    mdriveupclosingtimeonsaturday CHARACTER VARYING(5),
    mdriveupopeningtimeonsunday CHARACTER VARYING(5),
    mdriveupclosingtimeonsunday CHARACTER VARYING(5),
    maccessiblefeatures CHARACTER VARYING(250),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedbranch ADD CONSTRAINT mappedbranch_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX mappedbranch_mbankid_mbranchid ON mappedbranch(mbankid NULLS FIRST, mbranchid NULLS FIRST);
CREATE INDEX mappedbranch_mbankid ON mappedbranch(mbankid NULLS FIRST);
