-- Account holders: the link between a user and a (bank, account).
--
-- NOTE: this table uses a DIFFERENT NAME PREFIX to all the others — MAPPER, not MAPPED.
--
-- The unique index on (user_c, accountbankpermalink, accountpermalink) is load-bearing:
-- getOrCreateAccountHolder is a check-then-insert, and it relies on the database rejecting a
-- concurrent duplicate so the loser can re-read and return the committed row. Without it a user
-- could be recorded twice as holder of one account, and a single revoke would leave one behind.
--
-- user_c holds RESOURCEUSER's numeric primary key, not the public user_id.
--
-- `source` genuinely holds NULL — getOrCreateAccountHolder writes source.getOrElse(null) — and
-- getAccountsHeldByUser distinguishes three cases on it: no filter at all, `IS NULL` for an empty
-- or null source, and an equality match otherwise. A row storing '' rather than NULL would be
-- invisible to the IS NULL branch, so the column must stay nullable.

CREATE TABLE mapperaccountholders(
    accountpermalink CHARACTER VARYING(64),
    accountbankpermalink CHARACTER VARYING(44),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    source CHARACTER VARYING(255),
    user_c BIGINT
);
ALTER TABLE mapperaccountholders ADD CONSTRAINT mapperaccountholders_pk PRIMARY KEY(id);
CREATE INDEX mapperaccountholders_user_c ON mapperaccountholders(user_c NULLS FIRST);
CREATE UNIQUE INDEX mapperaccountholders_user_c_accountbankpermalink_accountpermalink ON mapperaccountholders(user_c NULLS FIRST, accountbankpermalink NULLS FIRST, accountpermalink NULLS FIRST);
