-- Dynamic message docs: one row per connector process definition.
--
-- `process` is unique GLOBALLY, not per bank, even though every read accepts an optional bank id
-- that narrows the match. A bank-level and a system-level doc therefore cannot share a process
-- name — the second create fails rather than shadowing the first. The bankId argument narrows a
-- read; it does not widen the key.
--
-- bankid genuinely holds NULL for system-level docs, because create writes
-- bankId.getOrElse(null). Note the READS are inconsistent with that write: when a bank id is
-- supplied they compare bankid to it, but when it is absent they do not constrain bankid at all,
-- so a system-level lookup also matches bank-level rows. Both behaviours are pre-existing and are
-- reproduced here.

CREATE TABLE dynamicmessagedoc(
    process CHARACTER VARYING(255),
    messageformat CHARACTER VARYING(255),
    outboundtopic CHARACTER VARYING(255),
    inboundtopic CHARACTER VARYING(255),
    outboundavroschema TEXT,
    inboundavroschema TEXT,
    lang CHARACTER VARYING(50),
    methodbody TEXT,
    bankid CHARACTER VARYING(255),
    description CHARACTER VARYING(255),
    adapterimplementation CHARACTER VARYING(255),
    dynamicmessagedocid CHARACTER VARYING(44),
    exampleoutboundmessage TEXT,
    exampleinboundmessage TEXT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE dynamicmessagedoc ADD CONSTRAINT dynamicmessagedoc_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX dynamicmessagedoc_dynamicmessagedocid ON dynamicmessagedoc(dynamicmessagedocid NULLS FIRST);
CREATE UNIQUE INDEX dynamicmessagedoc_process ON dynamicmessagedoc(process NULLS FIRST);
