-- Dynamic resource docs: one row per runtime-defined endpoint.
--
-- `roles` is stored as ROLES_C because ROLES collides with a SQL reserved word, which is why the
-- column name does not match the field.
--
-- The unique index on (requesturl, requestverb) is what makes a dynamic endpoint's route
-- single-valued — it is GLOBAL, not per bank, so a bank-level and a system-level doc cannot claim
-- the same verb and URL. dynamicresourcedocid is separately unique as the public handle.
--
-- bankid, examplerequestbody and successresponsebody all genuinely hold NULL: the provider writes
-- bankId.getOrElse(null) and maps the two optional JSON bodies through orNull. The readers turn a
-- blank body back into None, so an absent body must not become '' either.
--
-- As with dynamicmessagedoc the reads are laxer than the write: a supplied bank id filters on
-- bankid, while an absent one does not constrain it, so a system-level lookup also matches
-- bank-level rows. Pre-existing and reproduced.

CREATE TABLE dynamicresourcedoc(
    requestverb CHARACTER VARYING(255),
    requesturl CHARACTER VARYING(255),
    summary CHARACTER VARYING(255),
    examplerequestbody CHARACTER VARYING(255),
    tags CHARACTER VARYING(255),
    roles_c CHARACTER VARYING(255),
    methodbody TEXT,
    bankid CHARACTER VARYING(255),
    description CHARACTER VARYING(255),
    dynamicresourcedocid CHARACTER VARYING(44),
    partialfunctionname CHARACTER VARYING(255),
    successresponsebody CHARACTER VARYING(255),
    errorresponsebodies CHARACTER VARYING(255),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE dynamicresourcedoc ADD CONSTRAINT dynamicresourcedoc_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX dynamicresourcedoc_dynamicresourcedocid ON dynamicresourcedoc(dynamicresourcedocid NULLS FIRST);
CREATE UNIQUE INDEX dynamicresourcedoc_requesturl_requestverb ON dynamicresourcedoc(requesturl NULLS FIRST, requestverb NULLS FIRST);
