-- Per-row access control for dynamic-entity data: who may read, update, delete or re-grant one
-- DYNAMICDATA row, and who granted them that.
--
-- The unique index on (dynamicdataid, userid) is what makes `grant` an upsert rather than an
-- append — one grant row per user per data row — and what lets `allows` answer a permission
-- question with a single lookup.
--
-- The index on (dynamicdataid, grantedby) serves the revoke walk: revoke follows GrantedBy edges
-- to remove the target user and everyone they granted downstream, so it reads the table by grantor
-- repeatedly.
--
-- bankid genuinely holds NULL for system-level entities, and both scoped queries use `IS NULL`
-- when no bank is supplied — the Lift NullRef, not "no filter". A row storing '' would be
-- invisible to those queries, so the column must stay nullable and the reads must keep the
-- three-way distinction.

CREATE TABLE dynamicdataaccess(
    grantedby CHARACTER VARYING(255),
    canread BOOLEAN,
    canupdate BOOLEAN,
    candelete BOOLEAN,
    cangrant BOOLEAN,
    entityname CHARACTER VARYING(255),
    userid CHARACTER VARYING(255),
    bankid CHARACTER VARYING(255),
    dynamicdataid CHARACTER VARYING(255),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE dynamicdataaccess ADD CONSTRAINT dynamicdataaccess_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX dynamicdataaccess_dynamicdataid_userid ON dynamicdataaccess(dynamicdataid NULLS FIRST, userid NULLS FIRST);
CREATE INDEX dynamicdataaccess_userid_entityname_bankid ON dynamicdataaccess(userid NULLS FIRST, entityname NULLS FIRST, bankid NULLS FIRST);
CREATE INDEX dynamicdataaccess_dynamicdataid_grantedby ON dynamicdataaccess(dynamicdataid NULLS FIRST, grantedby NULLS FIRST);
