-- Dynamic entities: one row per runtime-defined entity type.
--
-- bankid genuinely holds NULL for system-level entities, and — unlike dynamicmessagedoc and
-- dynamicresourcedoc, whose reads leave bankid unconstrained when no bank is supplied — every read
-- here uses `IS NULL` for the system-level case (Lift's NullRef). A system-level lookup therefore
-- does NOT see bank-level entities. The three providers differ on this point and each keeps its own
-- behaviour; a row storing '' rather than NULL would be invisible to this one.
--
-- getDynamicEntities has a third mode: returnBothBankAndSystemLevel ignores the scope entirely and
-- returns every row.
--
-- Only dynamicentityid is unique. Nothing constrains (bankid, entityname) even though
-- getByEntityName treats that pair as a key, so two entities in one scope may share a name.
-- Pre-existing; reproduced with id ASC pinning which one a lookup sees.

CREATE TABLE dynamicentity(
    dynamicentityid CHARACTER VARYING(36),
    updatedat TIMESTAMP,
    entityname CHARACTER VARYING(255),
    metadatajson TEXT,
    userid CHARACTER VARYING(255),
    bankid CHARACTER VARYING(255),
    haspersonalentity BOOLEAN,
    haspublicaccess BOOLEAN,
    hascommunityaccess BOOLEAN,
    userowlevelaccess BOOLEAN,
    createdat TIMESTAMP,
    personalrequiresrole BOOLEAN,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE dynamicentity ADD CONSTRAINT dynamicentity_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX dynamicentity_dynamicentityid ON dynamicentity(dynamicentityid NULLS FIRST);
