-- Dynamic-entity data: one row per record of a runtime-defined entity type. The record itself is
-- JSON in datajson; the columns beside it are only the scoping keys.
--
-- bankid and userid genuinely hold NULL, and the two are read differently:
--   * bankid uses `IS NULL` for the system-level case (Lift's NullRef), so a system-level query
--     does not see bank-level rows;
--   * userid is compared with `= ?` even when the caller passes None, because the provider wrote
--     userId.getOrElse(null). Lift rendered that as `= NULL`, which matches NOTHING — so a
--     personal-entity query with no user id has always returned no rows rather than every row.
--     That is preserved literally: the binding is Option, so the comparison stays `= NULL`.
-- Those two are not interchangeable and the difference is invisible without reading both.
--
-- Only dynamicdataid is unique. It is the caller-supplied id extracted from the request body — the
-- <entityName>_Id field — not a generated one, so the constraint is what stops two records of any
-- entity type sharing an id. Nothing constrains (dynamicentityname, dynamicdataid) as a pair, which
-- means the id space is global across entity types.
--
-- ProjectionStore builds raw SQL against this table for the DE_indexing projections and reads the
-- table and column names from constants on the companion; the names here and there must agree.

CREATE TABLE dynamicdata(
    dynamicentityname CHARACTER VARYING(255),
    ispersonalentity BOOLEAN,
    bankid CHARACTER VARYING(255),
    dynamicdataid CHARACTER VARYING(36),
    datajson TEXT,
    userid CHARACTER VARYING(255),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE dynamicdata ADD CONSTRAINT dynamicdata_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX dynamicdata_dynamicdataid ON dynamicdata(dynamicdataid NULLS FIRST);
