-- View permissions: one row per (view, permission), where the view is identified either by
-- (bank_id, account_id, view_id) for a custom view or by view_id alone for a system view.
--
-- bank_id and account_id are NULL for system views — createSystemViewPermission writes literal
-- nulls — and the system-view reads use `IS NULL` on both (Lift's NullRef), NOT "no filter". A row
-- storing '' would be invisible to every system-view lookup, and a system lookup must not match a
-- custom view's rows. Both halves of that matter.
--
-- The unique index on (bank_id, account_id, view_id, permission) is what makes a permission
-- single-valued per view. resetViewPermissions depends on it: it deletes the view's rows, then
-- inserts each permission inside a Try so that a concurrent reset racing the same insert is
-- absorbed by the constraint rather than duplicating the grant. Note H2 and Postgres treat NULLs in
-- a unique index as distinct, so for SYSTEM views (bank_id and account_id both NULL) the constraint
-- does NOT actually prevent duplicates — the Try swallows nothing there and two concurrent resets
-- can both insert. That gap is pre-existing.
--
-- extradata carries the view-id list for the two special permissions CAN_GRANT_ACCESS_TO_VIEWS and
-- CAN_REVOKE_ACCESS_TO_VIEWS, comma-joined, and is NULL for every other permission.

CREATE TABLE viewpermission(
    bank_id CHARACTER VARYING(255),
    account_id CHARACTER VARYING(255),
    view_id CHARACTER VARYING(44),
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    extradata CHARACTER VARYING(1024),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    permission CHARACTER VARYING(255)
);
ALTER TABLE viewpermission ADD CONSTRAINT viewpermission_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX viewpermission_bank_id_account_id_view_id_permission ON viewpermission(bank_id NULLS FIRST, account_id NULLS FIRST, view_id NULLS FIRST, permission NULLS FIRST);
