-- Account access: the link between a user and a view. A user cannot use a view unless a row here
-- says so, which makes this table part of the authorisation path rather than metadata.
--
-- The unique index on (bank_id, account_id, view_id, user_fk, consumer_id) is load-bearing and all
-- five columns are needed. revokeAccess matches on (bank, account, view, user) and so cannot tell
-- two applications' grants apart; the per-consumer revokes match on (bank, account, view, consumer)
-- and so cannot tell two users apart — on a joint account they would delete whichever row came back
-- first. Undoing exactly one consent's grant needs the full tuple.
--
-- consumer_id defaults to ALL_CONSUMERS, meaning "any consumer may use this grant"; a real consumer
-- id restricts it to that application.
--
-- NOTE: deployed databases also carry a SECOND, quoted-lowercase "consumer_id" column beside this
-- one. It is dead. MigrationOfAccountAccessAddedConsumerId calls Helper.addColumnIfNotExists, which
-- emits ADD COLUMN IF NOT EXISTS "consumer_id" — a quoted identifier, which H2 and Postgres treat as
-- distinct from the unquoted CONSUMER_ID that Schemifier created. The IF NOT EXISTS check therefore
-- never matched, and the script added a duplicate column that nothing reads or writes. This
-- migration builds only the live column; the runtime script still runs and will still add its dead
-- twin, exactly as before.
--
-- view_fk is deprecated (superseded by bank_id/account_id/view_id) and is written by no code path.

CREATE TABLE accountaccess(
    bank_id CHARACTER VARYING(255),
    account_id CHARACTER VARYING(255),
    createdat TIMESTAMP,
    view_id CHARACTER VARYING(44),
    consumer_id CHARACTER VARYING(255),
    user_fk BIGINT,
    view_fk BIGINT,
    updatedat TIMESTAMP,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE accountaccess ADD CONSTRAINT accountaccess_pk PRIMARY KEY(id);
CREATE INDEX accountaccess_user_fk ON accountaccess(user_fk NULLS FIRST);
CREATE INDEX accountaccess_view_fk ON accountaccess(view_fk NULLS FIRST);
CREATE UNIQUE INDEX accountaccess_bank_id_account_id_view_id_user_fk_consumer_id ON accountaccess(bank_id NULLS FIRST, account_id NULLS FIRST, view_id NULLS FIRST, user_fk NULLS FIRST, consumer_id NULLS FIRST);
