-- Mandates and their two child tables.
--
-- A mandate is the legal authority under which someone acts on an account: who may do what, from
-- when until when, under which written terms. MANDATEPROVISION holds the individual clauses of one
-- mandate (each optionally pointing at the view, ABAC rule or challenge type that enforces it), and
-- SIGNATORYPANEL holds the named groups of users a provision can require signatures from.
--
-- Both children reference their parent by MANDATEID, the business id, not by the surrogate ID. The
-- unique index on each business id is what makes that reference resolve to exactly one row, and it
-- is the only uniqueness this schema declares: nothing stops two mandates sharing a
-- MANDATEREFERENCE, and its index exists to make lookups by reference cheap, not to constrain them.
--
-- There is no foreign key and no cascade — deleting a mandate leaves its provisions and panels
-- behind. Preserved as it was; the store never deleted children either.
--
-- LEGALTEXT, DESCRIPTION, CONDITIONS, SIGNATORYREQUIREMENTS, PROVISIONDESCRIPTION and USERIDS are
-- unbounded text because the entity declared them as MappedText: they carry contract prose, a JSON
-- array of signature requirements, and a comma-separated user list respectively.

CREATE TABLE mandate(
    mandateid CHARACTER VARYING(255),
    bankid CHARACTER VARYING(255),
    customerid CHARACTER VARYING(255),
    mandatename CHARACTER VARYING(255),
    mandatereference CHARACTER VARYING(255),
    legaltext CHARACTER VARYING,
    description CHARACTER VARYING,
    validfrom TIMESTAMP,
    validto TIMESTAMP,
    updatedbyuserid CHARACTER VARYING(255),
    createdbyuserid CHARACTER VARYING(255),
    createdat TIMESTAMP,
    status CHARACTER VARYING(50),
    accountid CHARACTER VARYING(255),
    updatedat TIMESTAMP,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mandate ADD CONSTRAINT mandate_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX mandate_mandateid ON mandate(mandateid NULLS FIRST);
CREATE INDEX mandate_bankid_accountid ON mandate(bankid NULLS FIRST, accountid NULLS FIRST);
CREATE INDEX mandate_customerid ON mandate(customerid NULLS FIRST);
CREATE INDEX mandate_mandatereference ON mandate(mandatereference NULLS FIRST);

CREATE TABLE mandateprovision(
    mandateid CHARACTER VARYING(255),
    provisionid CHARACTER VARYING(255),
    provisionname CHARACTER VARYING(255),
    legalreference CHARACTER VARYING(255),
    provisiontype CHARACTER VARYING(50),
    conditions CHARACTER VARYING,
    linkedviewid CHARACTER VARYING(255),
    linkedabacruleid CHARACTER VARYING(255),
    isactive BOOLEAN,
    sortorder INTEGER,
    createdat TIMESTAMP,
    updatedat TIMESTAMP,
    provisiondescription CHARACTER VARYING,
    signatoryrequirements CHARACTER VARYING,
    linkedchallengetype CHARACTER VARYING(255),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mandateprovision ADD CONSTRAINT mandateprovision_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX mandateprovision_provisionid ON mandateprovision(provisionid NULLS FIRST);
CREATE INDEX mandateprovision_mandateid ON mandateprovision(mandateid NULLS FIRST);

CREATE TABLE signatorypanel(
    mandateid CHARACTER VARYING(255),
    description CHARACTER VARYING,
    panelid CHARACTER VARYING(255),
    panelname CHARACTER VARYING(255),
    userids CHARACTER VARYING,
    createdat TIMESTAMP,
    updatedat TIMESTAMP,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE signatorypanel ADD CONSTRAINT signatorypanel_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX signatorypanel_panelid ON signatorypanel(panelid NULLS FIRST);
CREATE INDEX signatorypanel_mandateid ON signatorypanel(mandateid NULLS FIRST);
