-- Berlin Group signing baskets: one basket groups several payments and/or consents so the PSU can
-- authorise them with a single SCA.
--
-- The basket carries nothing but its id and its status (RCVD -> ACTC -> ... -> CANC); the two child
-- tables are pure join tables naming the payments and consents it covers, keyed by BASKETID, the
-- business id, not by the surrogate ID.
--
-- Membership is deliberately unconstrained: the indexes on (BASKETID, PAYMENTID) and
-- (BASKETID, CONSENTID) are not unique, so adding the same payment to a basket twice stores two
-- rows, and BASKETID itself is only indexed rather than unique. Reads resolve a basket by taking
-- the first match, so a duplicate would be invisible rather than an error. Preserved as it was.
--
-- The ids are 36-character UUIDs (MappedUUID), which is why the columns are narrower than the usual
-- 255.

CREATE TABLE signingbasket(
    status CHARACTER VARYING(50),
    basketid CHARACTER VARYING(36),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE signingbasket ADD CONSTRAINT signingbasket_pk PRIMARY KEY(id);
CREATE INDEX signingbasket_basketid ON signingbasket(basketid NULLS FIRST);

CREATE TABLE signingbasketpayment(
    basketid CHARACTER VARYING(36),
    paymentid CHARACTER VARYING(36),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE signingbasketpayment ADD CONSTRAINT signingbasketpayment_pk PRIMARY KEY(id);
CREATE INDEX signingbasketpayment_basketid_paymentid ON signingbasketpayment(basketid NULLS FIRST, paymentid NULLS FIRST);

CREATE TABLE signingbasketconsent(
    basketid CHARACTER VARYING(36),
    consentid CHARACTER VARYING(36),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE signingbasketconsent ADD CONSTRAINT signingbasketconsent_pk PRIMARY KEY(id);
CREATE INDEX signingbasketconsent_basketid_consentid ON signingbasketconsent(basketid NULLS FIRST, consentid NULLS FIRST);
