-- Consent requests: the first step of the consent flow. The client POSTs what it wants to be
-- allowed to do, gets back a consent-request id, and the consent itself is created later from this
-- stored payload.
--
-- PAYLOAD is the whole request body as JSON in one column, unbounded because it carries account
-- routings, a counterparty and a VRP limit set. Nothing indexes into it; it is read back whole.
--
-- CONSUMERID is nullable on purpose - the entity declared its default as null rather than "", and
-- createConsentRequest writes null when the call has no consumer attached. It records which
-- application asked, and is not a foreign key.

CREATE TABLE consentrequest(
    consentrequestid CHARACTER VARYING(36),
    payload CHARACTER VARYING,
    consumerid CHARACTER VARYING(250),
    updatedat TIMESTAMP,
    createdat TIMESTAMP,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE consentrequest ADD CONSTRAINT consentrequest_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX consentrequest_consentrequestid ON consentrequest(consentrequestid NULLS FIRST);
