-- Counterparties and their metadata.
--
-- Two different things share the word "counterparty" here, and only one of them lives in
-- MAPPEDCOUNTERPARTY:
--   * an EXPLICIT counterparty, created through the create-counterparty endpoint, is a row in
--     MAPPEDCOUNTERPARTY;
--   * an IMPLICIT counterparty, derived while reading transactions, is never stored - but a
--     MAPPEDCOUNTERPARTYMETADATA row is created for it so aliases, tags and locations have
--     somewhere to live.
-- That is why the metadata table is keyed by COUNTERPARTYID only and carries no foreign key to
-- MAPPEDCOUNTERPARTY: for most rows there is nothing to point at.
--
-- MAPPEDCOUNTERPARTY has two unique indexes: on the counterparty id, and on
-- (name, this bank, this account, this view) - the same name may not be used twice for the same
-- account and view. Two further unique indexes over the routing columns are commented out in the
-- entity and were never created, which is why a counterparty can be looked up by IBAN but not
-- uniquely: getCounterpartyByIban takes the newest match.
--
-- CORPORATELOCATION and PHYSICALLOCATION hold the id of a MAPPEDCOUNTERPARTYWHERETAG row, or NULL.
-- Schemifier built them as plain indexed BIGINT columns rather than declared foreign keys, so
-- deleting a where-tag leaves the pointer dangling; readers treat a missing tag as no tag.
--
-- USER_C and DATE_C in the where-tag table carry the Schemifier suffix for reserved words: the
-- entity's fields are `user` and `date`.

CREATE TABLE mappedcounterparty(
    createdat TIMESTAMP,
    updatedat TIMESTAMP,
    mdescription CHARACTER VARYING(2000),
    mcounterpartyid CHARACTER VARYING(44),
    mname CHARACTER VARYING(36),
    mthisbankid CHARACTER VARYING(36),
    mthisaccountid CHARACTER VARYING(64),
    mthisviewid CHARACTER VARYING(36),
    mcreatedbyuserid CHARACTER VARYING(36),
    misbeneficiary BOOLEAN,
    mcurrency CHARACTER VARYING(255),
    motherbankroutingscheme CHARACTER VARYING(255),
    motherbankroutingaddress CHARACTER VARYING(255),
    motherbranchroutingscheme CHARACTER VARYING(255),
    motherbranchroutingaddress CHARACTER VARYING(255),
    motheraccountroutingscheme CHARACTER VARYING(255),
    motheraccountroutingaddress CHARACTER VARYING(255),
    motheraccountsecondaryroutingscheme CHARACTER VARYING(255),
    motheraccountsecondaryroutingaddress CHARACTER VARYING(255),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedcounterparty ADD CONSTRAINT mappedcounterparty_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX mappedcounterparty_mcounterpartyid ON mappedcounterparty(mcounterpartyid NULLS FIRST);
CREATE UNIQUE INDEX mappedcounterparty_mname_mthisbankid_mthisaccountid_mthisviewid ON mappedcounterparty(mname NULLS FIRST, mthisbankid NULLS FIRST, mthisaccountid NULLS FIRST, mthisviewid NULLS FIRST);

CREATE TABLE mappedcounterpartymetadata(
    counterpartyid CHARACTER VARYING(44),
    thisbankid CHARACTER VARYING(44),
    thisaccountid CHARACTER VARYING(64),
    moreinfo CHARACTER VARYING(255),
    counterpartyname CHARACTER VARYING(255),
    createdat TIMESTAMP,
    updatedat TIMESTAMP,
    publicalias CHARACTER VARYING(64),
    privatealias CHARACTER VARYING(64),
    corporatelocation BIGINT,
    physicallocation BIGINT,
    imageurl CHARACTER VARYING(2000),
    opencorporatesurl CHARACTER VARYING(2000),
    url CHARACTER VARYING(2000),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedcounterpartymetadata ADD CONSTRAINT mappedcounterpartymetadata_pk PRIMARY KEY(id);
CREATE INDEX mappedcounterpartymetadata_corporatelocation ON mappedcounterpartymetadata(corporatelocation NULLS FIRST);
CREATE INDEX mappedcounterpartymetadata_physicallocation ON mappedcounterpartymetadata(physicallocation NULLS FIRST);
CREATE UNIQUE INDEX mappedcounterpartymetadata_counterpartyid ON mappedcounterpartymetadata(counterpartyid NULLS FIRST);

CREATE TABLE mappedcounterpartywheretag(
    createdat TIMESTAMP,
    updatedat TIMESTAMP,
    geolongitude DOUBLE PRECISION,
    geolatitude DOUBLE PRECISION,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    user_c BIGINT,
    date_c TIMESTAMP
);
ALTER TABLE mappedcounterpartywheretag ADD CONSTRAINT mappedcounterpartywheretag_pk PRIMARY KEY(id);
CREATE INDEX mappedcounterpartywheretag_user_c ON mappedcounterpartywheretag(user_c NULLS FIRST);
