-- Banks.
--
-- PERMALINK is the bank id every URL and every other table refers to, but it is NOT unique: the
-- entity carries a plain index and a comment saying a unique one would be right, held back by tests
-- that create the same bank twice. Reads therefore take the first match rather than assuming one,
-- and this script keeps the index exactly as it is - adding uniqueness here would reject rows that
-- current callers create.
--
-- CREATEDBYUSERID records the user behind POST /my/banks and is indexed because the self-service
-- quota counts a user's banks. It is empty for banks created before the column existed and for
-- paths with no authenticated user, such as the sandbox import, and is never serialized into an API
-- response.

CREATE TABLE mappedbank(
    permalink CHARACTER VARYING(255),
    fullbankname CHARACTER VARYING(255),
    shortbankname CHARACTER VARYING(100),
    logourl CHARACTER VARYING(255),
    websiteurl CHARACTER VARYING(255),
    swiftbic CHARACTER VARYING(255),
    mbankroutingscheme CHARACTER VARYING(255),
    createdbyuserid CHARACTER VARYING(255),
    createdat TIMESTAMP,
    updatedat TIMESTAMP,
    national_identifier CHARACTER VARYING(255),
    mbankroutingaddress CHARACTER VARYING(255),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedbank ADD CONSTRAINT mappedbank_pk PRIMARY KEY(id);
CREATE INDEX mappedbank_permalink ON mappedbank(permalink NULLS FIRST);
CREATE INDEX mappedbank_createdbyuserid ON mappedbank(createdbyuserid NULLS FIRST);
