-- Transactions, as the local (mapped) connector stores them.
--
-- The unique index is on (TRANSACTIONID, BANK, ACCOUNT), not on TRANSACTIONID alone: one transfer
-- is written twice, once from each side, and both rows carry the same transaction id. The second
-- index on (BANK, ACCOUNT) is what an account statement reads.
--
-- AMOUNT and NEWACCOUNTBALANCE are signed integers in the smallest unit of the currency (cents,
-- yen, øre), never decimals. The sign of AMOUNT is the credit/debit indicator.
--
-- TRANSACTIONUUID sits beside TRANSACTIONID for history: v1.1 exposed a UUID before transaction ids
-- became UUIDs themselves. Both are kept.
--
-- The COUNTERPARTY* columns are a snapshot of the other party taken when the transaction was
-- written, not a reference to a counterparty row - a transaction has to keep reading correctly
-- after the counterparty it names has been edited or deleted. COUNTERPARTYACCOUNTNUMBER and
-- COUNTERPARTYIBAN are deprecated in favour of the CPOTHERACCOUNT* routing columns but still
-- written and read.
--
-- EXTRAINFO holds text salvaged from earlier model versions that put things like
-- "BLS 3020201 BLAH BLAH S/C 2014-05-22" in the account-number column. It is kept so the data can
-- be processed by hand later; nothing reads it.

CREATE TABLE mappedtransaction(
    chargepolicy CHARACTER VARYING(32),
    transactionid CHARACTER VARYING(255),
    transactiontype CHARACTER VARYING(100),
    newaccountbalance BIGINT,
    tstartdate TIMESTAMP,
    tfinishdate TIMESTAMP,
    counterpartyiban CHARACTER VARYING(100),
    createdat TIMESTAMP,
    transactionuuid CHARACTER VARYING(36),
    cpcounterpartyid CHARACTER VARYING(44),
    bank CHARACTER VARYING(255),
    updatedat TIMESTAMP,
    counterpartyaccountholder CHARACTER VARYING(255),
    counterpartyaccountnumber CHARACTER VARYING(128),
    counterpartyaccountkind CHARACTER VARYING(40),
    counterpartybankname CHARACTER VARYING(100),
    counterpartynationalid CHARACTER VARYING(40),
    cpotheraccountroutingscheme CHARACTER VARYING(255),
    cpotheraccountroutingaddress CHARACTER VARYING(255),
    cpotherbankroutingscheme CHARACTER VARYING(255),
    cpotherbankroutingaddress CHARACTER VARYING(255),
    cpotheraccountsecondaryroutingscheme CHARACTER VARYING(255),
    cpotheraccountsecondaryroutingaddress CHARACTER VARYING(255),
    cpotheraccountprovider CHARACTER VARYING(36),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    status CHARACTER VARYING(20),
    currency CHARACTER VARYING(10),
    amount BIGINT,
    description CHARACTER VARYING(2000),
    extrainfo CHARACTER VARYING(2000),
    account CHARACTER VARYING(64)
);
ALTER TABLE mappedtransaction ADD CONSTRAINT mappedtransaction_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX mappedtransaction_transactionid_bank_account ON mappedtransaction(transactionid NULLS FIRST, bank NULLS FIRST, account NULLS FIRST);
CREATE INDEX mappedtransaction_bank_account ON mappedtransaction(bank NULLS FIRST, account NULLS FIRST);
