-- Transaction requests: the payment instruction, as opposed to the transaction it eventually
-- produces. One row records what was asked for, what it costs, where it is in the challenge and
-- status flow, and - once it completes - the id of the transaction that settled it.
--
-- MTRANSACTIONIDS holds the settling transaction id (singular, despite the name) and is what
-- bulkDeleteTransactionRequestsByTransactionId matches on.
--
-- MDETAILS is the whole create body as JSON in one unbounded column. toTransactionRequest reads the
-- type-specific half of the request back out of it - IBANs, counterparty ids, agent numbers - so
-- the columns beside it are a partial, denormalised copy rather than the whole story.
--
-- The MPAYMENT* columns carry the Berlin Group periodic-payment schedule and are null for every
-- other kind of request. The MORIGINATOR_* columns carry the FATF Recommendation 16 originator and
-- today are written only by OPEN_CORRIDOR_PROMISE.
--
-- MSTARTDATE, MENDDATE and the two MPAYMENT dates are DATE, not TIMESTAMP: they are calendar dates
-- with no time of day.

CREATE TABLE mappedtransactionrequest(
    mbody_value_amount CHARACTER VARYING(32),
    createdat TIMESTAMP,
    muserid CHARACTER VARYING(100),
    updatedat TIMESTAMP,
    mstatus CHARACTER VARYING(32),
    mconsumerid CHARACTER VARYING(100),
    mapistandard CHARACTER VARYING(50),
    mapiversion CHARACTER VARYING(50),
    mtype CHARACTER VARYING(32),
    mfrom_bankid CHARACTER VARYING(44),
    mto_bankid CHARACTER VARYING(44),
    mdetails CHARACTER VARYING,
    mcharge_currency CHARACTER VARYING(16),
    mcharge_amount CHARACTER VARYING(32),
    mtransactionids CHARACTER VARYING(2000),
    mname CHARACTER VARYING(140),
    mcharge_summary CHARACTER VARYING(64),
    mpaymentstartdate DATE,
    mfrom_accountid CHARACTER VARYING(64),
    mchallenge_id CHARACTER VARYING(64),
    mto_accountid CHARACTER VARYING(128),
    mpaymentfrequency CHARACTER VARYING(64),
    mthisbankid CHARACTER VARYING(44),
    mthisviewid CHARACTER VARYING(44),
    menddate DATE,
    mstartdate DATE,
    mbody_description CHARACTER VARYING(2000),
    mthisaccountid CHARACTER VARYING(64),
    mcharge_policy CHARACTER VARYING(32),
    misbeneficiary BOOLEAN,
    moriginator_name CHARACTER VARYING(140),
    mcounterpartyid CHARACTER VARYING(44),
    mpaymentenddate DATE,
    monbehalfofuserid CHARACTER VARYING(100),
    mbody_value_currency CHARACTER VARYING(16),
    mconsentreferenceid CHARACTER VARYING(64),
    mtransactionrequestid CHARACTER VARYING(44),
    mchallenge_allowedattempts INTEGER,
    mchallenge_challengetype CHARACTER VARYING(100),
    motheraccountroutingscheme CHARACTER VARYING(32),
    motheraccountroutingaddress CHARACTER VARYING(128),
    motherbankroutingscheme CHARACTER VARYING(32),
    motherbankroutingaddress CHARACTER VARYING(64),
    moriginator_address CHARACTER VARYING(2000),
    moriginator_accountroutingscheme CHARACTER VARYING(32),
    moriginator_accountroutingaddress CHARACTER VARYING(128),
    mpaymentexecutionrule CHARACTER VARYING(64),
    mpaymentdayofexecution CHARACTER VARYING(64),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedtransactionrequest ADD CONSTRAINT mappedtransactionrequest_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX mappedtransactionrequest_mtransactionrequestid ON mappedtransactionrequest(mtransactionrequestid NULLS FIRST);
