-- Customers. In OBP a customer and an agent are the same row: MISPENDINGAGENT and
-- MISCONFIRMEDAGENT are what distinguish an agent, and the agent provider reads and writes this
-- same table.
--
-- Two unique indexes: on MCUSTOMERID, the id every API path uses, and on (MBANK, MNUMBER) - a
-- customer number is unique within its bank but not across banks.
--
-- Several child tables (tax residences, addresses, dependants) key off the SURROGATE id rather than
-- MCUSTOMERID, which is why the row has to carry it and why deleting a customer has to look the
-- surrogate up first.
--
-- MCUSTOMERTYPE defaults to INDIVIDUAL and MISPENDINGAGENT to true at the entity level rather than
-- in the DDL; the store writes those defaults explicitly.

CREATE TABLE mappedcustomer(
    mlastokdate TIMESTAMP,
    mbank CHARACTER VARYING(44),
    mnumber CHARACTER VARYING(50),
    mcustomerid CHARACTER VARYING(36),
    mmobilenumber CHARACTER VARYING(50),
    mlegalname CHARACTER VARYING(255),
    memail CHARACTER VARYING(200),
    mdateofbirth TIMESTAMP,
    mdependents INTEGER,
    memploymentstatus CHARACTER VARYING(32),
    mkycstatus BOOLEAN,
    mcreditlimitamount CHARACTER VARYING(100),
    mtitle CHARACTER VARYING(255),
    mnamesuffix CHARACTER VARYING(255),
    mcustomertype CHARACTER VARYING(50),
    mparentcustomerid CHARACTER VARYING(255),
    mispendingagent BOOLEAN,
    misconfirmedagent BOOLEAN,
    mbranchid CHARACTER VARYING(255),
    createdat TIMESTAMP,
    updatedat TIMESTAMP,
    mfaceimagetime TIMESTAMP,
    mfaceimageurl CHARACTER VARYING(2000),
    mcreditrating CHARACTER VARYING(100),
    mcreditsource CHARACTER VARYING(100),
    mrelationshipstatus CHARACTER VARYING(16),
    mhighesteducationattained CHARACTER VARYING(32),
    mcreditlimitcurrency CHARACTER VARYING(100),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedcustomer ADD CONSTRAINT mappedcustomer_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX mappedcustomer_mcustomerid ON mappedcustomer(mcustomerid NULLS FIRST);
CREATE UNIQUE INDEX mappedcustomer_mbank_mnumber ON mappedcustomer(mbank NULLS FIRST, mnumber NULLS FIRST);
