-- API metrics: one row per request served, plus an archive the scheduler moves old rows into.
--
-- The live table is called METRIC, not MAPPEDMETRIC - the entity overrode its table name.
--
-- The two tables have the same shape except that the archive also keeps METRICID, the primary key
-- the row had in METRIC. That is what the archiver de-duplicates on: the two tables have unrelated
-- id sequences, so matching on the archive's own ID would overwrite an unrelated archived row once
-- the archive sequence grew into the live id range.
--
-- CORRELATIONID is NOT NULL and is client-controlled: when the caller sends X-Request-ID (mandatory
-- for Berlin Group) that value is adopted verbatim, which is why it is 256 wide rather than UUID
-- sized. The archive copy must keep the same width or the archiver fails on its longest rows.
--
-- DATE_C carries the Schemifier suffix for a reserved word; the entity field is `date`.
--
-- Later migrations add further indexes to these tables (a user id index on METRIC and a second
-- consent-reference index on each). Those scripts still run and are not repeated here; this file
-- creates the indexes the entity itself declared.

CREATE TABLE metric(
    verb CHARACTER VARYING(16),
    apiinstanceid CHARACTER VARYING(255),
    developeremail CHARACTER VARYING(64),
    appname CHARACTER VARYING(64),
    consent_reference_id CHARACTER VARYING(36),
    httpcode INTEGER,
    certificate_trust CHARACTER VARYING(32),
    sourceip CHARACTER VARYING(64),
    targetip CHARACTER VARYING(64),
    responsebody CHARACTER VARYING,
    userid CHARACTER VARYING(44),
    correlationid CHARACTER VARYING(256) NOT NULL,
    consumerid CHARACTER VARYING(250),
    implementedbypartialfunction CHARACTER VARYING(128),
    implementedinversion CHARACTER VARYING(16),
    certificate_trust_detail CHARACTER VARYING(255),
    url CHARACTER VARYING(2000),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    duration BIGINT,
    username CHARACTER VARYING(64),
    date_c TIMESTAMP
);
ALTER TABLE metric ADD CONSTRAINT metric_pk PRIMARY KEY(id);
CREATE INDEX metric_date_c ON metric(date_c NULLS FIRST);
CREATE INDEX metric_consumerid ON metric(consumerid NULLS FIRST);
CREATE INDEX metric_consent_reference_id ON metric(consent_reference_id NULLS FIRST);

CREATE TABLE metricarchive(
    verb CHARACTER VARYING(16),
    apiinstanceid CHARACTER VARYING(255),
    developeremail CHARACTER VARYING(64),
    appname CHARACTER VARYING(64),
    consent_reference_id CHARACTER VARYING(36),
    httpcode INTEGER,
    certificate_trust CHARACTER VARYING(32),
    sourceip CHARACTER VARYING(64),
    targetip CHARACTER VARYING(64),
    metricid BIGINT,
    responsebody CHARACTER VARYING,
    userid CHARACTER VARYING(44),
    correlationid CHARACTER VARYING(256) NOT NULL,
    consumerid CHARACTER VARYING(250),
    implementedbypartialfunction CHARACTER VARYING(128),
    implementedinversion CHARACTER VARYING(16),
    certificate_trust_detail CHARACTER VARYING(255),
    url CHARACTER VARYING(2000),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    duration BIGINT,
    username CHARACTER VARYING(64),
    date_c TIMESTAMP
);
ALTER TABLE metricarchive ADD CONSTRAINT metricarchive_pk PRIMARY KEY(id);
CREATE INDEX metricarchive_userid ON metricarchive(userid NULLS FIRST);
CREATE INDEX metricarchive_consumerid ON metricarchive(consumerid NULLS FIRST);
CREATE INDEX metricarchive_url ON metricarchive(url NULLS FIRST);
CREATE INDEX metricarchive_date_c ON metricarchive(date_c NULLS FIRST);
CREATE INDEX metricarchive_username ON metricarchive(username NULLS FIRST);
CREATE INDEX metricarchive_appname ON metricarchive(appname NULLS FIRST);
CREATE INDEX metricarchive_developeremail ON metricarchive(developeremail NULLS FIRST);
CREATE INDEX metricarchive_consent_reference_id ON metricarchive(consent_reference_id NULLS FIRST);
