-- Consents: the granted authority a TPP or an application holds over a user's data.
--
-- Two unique ids, both load-bearing: MCONSENTID is the one the API paths use, and
-- CONSENT_REFERENCE_ID is the stable external identifier that consent_item rows point at and that
-- v5.1.0 surfaces in JSON. It replaced a historical derivation from the row's primary key, so both
-- are unique and neither can be dropped.
--
-- MJSONWEBTOKEN holds the consent JWT itself and MJSONWEBTOKENPAYLOAD its decoded payload;
-- JWT_EXPIRES_AT is the exp claim denormalised out of it so expiry can be queried without parsing
-- every token, and the consent_item rows are the same denormalisation for bank, account, view and
-- role.
--
-- MCHALLENGE is the SCA answer hashed with BCrypt using MSALT, never the answer itself.
--
-- The Berlin Group usage limits live here rather than on a view: MFREQUENCYPERDAY with
-- MUSESSOFARTODAYCOUNTER and its update timestamp, MRECURRINGINDICATOR and MVALIDUNTIL. The UK
-- window (MEXPIRATIONDATETIME, MTRANSACTIONFROMDATETIME, MTRANSACTIONTODATETIME) is the same idea
-- for the other standard.
--
-- MVALIDUNTIL and MLASTACTIONDATE are DATE, not TIMESTAMP: calendar dates with no time of day.
--
-- The index on (MUSERID, CREATEDAT) is what the per-user consent listing reads.

CREATE TABLE mappedconsent(
    msecret CHARACTER VARYING(36),
    createdat TIMESTAMP,
    muserid CHARACTER VARYING(36),
    updatedat TIMESTAMP,
    mjsonwebtoken CHARACTER VARYING,
    mconsentid CHARACTER VARYING(36),
    mconsentrequestid CHARACTER VARYING(36),
    msalt CHARACTER VARYING(50),
    mstatus CHARACTER VARYING(40),
    mlastactiondate DATE,
    mconsumerid CHARACTER VARYING(250),
    mchallenge CHARACTER VARYING(50),
    mfrequencyperday INTEGER,
    mapistandard CHARACTER VARYING(50),
    mvaliduntil DATE,
    mapiversion CHARACTER VARYING(50),
    jwt_expires_at TIMESTAMP,
    mnote CHARACTER VARYING,
    mjsonwebtokenpayload CHARACTER VARYING,
    mrecurringindicator BOOLEAN,
    musessofartodaycounter INTEGER,
    musessofartodaycounterupdatedat TIMESTAMP,
    mcombinedserviceindicator BOOLEAN,
    mexpirationdatetime TIMESTAMP,
    mtransactionfromdatetime TIMESTAMP,
    mtransactiontodatetime TIMESTAMP,
    mstatusupdatedatetime TIMESTAMP,
    consent_reference_id CHARACTER VARYING(36),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE mappedconsent ADD CONSTRAINT mappedconsent_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX mappedconsent_mconsentid ON mappedconsent(mconsentid NULLS FIRST);
CREATE UNIQUE INDEX mappedconsent_consent_reference_id ON mappedconsent(consent_reference_id NULLS FIRST);
CREATE INDEX mappedconsent_muserid ON mappedconsent(muserid NULLS FIRST);
CREATE INDEX mappedconsent_muserid_createdat ON mappedconsent(muserid NULLS FIRST, createdat NULLS FIRST);
