-- Bank accounts, as the local (mapped) connector stores them.
--
-- (BANK, THEACCOUNTID) is unique: an account id identifies an account only within its bank.
--
-- ACCOUNTBALANCE is a signed integer in the smallest unit of the currency (cents, yen, øre), never
-- a decimal, and the balance updates go through DoobieBankAccountQueries so they can lock the row.
--
-- The two ACCOUNTRULESCHEMEn/ACCOUNTRULEVALUEn pairs are a fixed-width, denormalised list: exactly
-- two account rules can be stored, and a rule with an empty scheme is skipped when they are read
-- back. Account ROUTINGS are not here at all - they live in bankaccountrouting, one row per routing.
--
-- HOLDER is deprecated: the real account holders are in mapperaccountholders. The column is still
-- written and still read back as `accountHolder`.
--
-- ACCOUNTLASTUPDATE is the last transaction-refresh time and is only maintained by the HBCI path.

CREATE TABLE mappedbankaccount(
    accountcurrency CHARACTER VARYING(10),
    accountlabel CHARACTER VARYING(255),
    accountname CHARACTER VARYING(255),
    accountlastupdate TIMESTAMP,
    accountbalance BIGINT,
    mbranchid CHARACTER VARYING(44),
    createdat TIMESTAMP,
    bank CHARACTER VARYING(44),
    theaccountid CHARACTER VARYING(64),
    accountnumber CHARACTER VARYING(128),
    updatedat TIMESTAMP,
    accountrulescheme1 CHARACTER VARYING(10),
    accountrulevalue1 BIGINT,
    accountrulescheme2 CHARACTER VARYING(10),
    accountrulevalue2 BIGINT,
    kind CHARACTER VARYING(255),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    holder CHARACTER VARYING(100)
);
ALTER TABLE mappedbankaccount ADD CONSTRAINT mappedbankaccount_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX mappedbankaccount_bank_theaccountid ON mappedbankaccount(bank NULLS FIRST, theaccountid NULLS FIRST);
