-- View definitions: what a view is allowed to show and do on an account.
--
-- A SYSTEM view has NULL bank_id and account_id and is scoped by view_id alone; a CUSTOM view
-- belongs to one account and is scoped by all three. That is why the reads use IS NULL rather than
-- an equality test, and why the unique key below is a composed string rather than a column tuple:
-- SQL treats NULLs as distinct, so a unique index over (bank_id, account_id, view_id) would not
-- stop two system views sharing a view id.
--
-- COMPOSITE_UNIQUE_KEY is that composed key - "|<bank>|--|<account>|--|<view>|" - written on every
-- save. The entity marks it deprecated because no API code reads it, but its unique index is the
-- only thing preventing a duplicate view, and ConcurrentViewPermissionRaceTest depends on the
-- database rejecting the loser of a concurrent create. It stays.
--
-- The primary key column is ID_, not ID: the entity declared its own MappedLongIndex.
--
-- CANGRANTACCESSTOVIEWS_ and CANREVOKEACCESSTOVIEWS_ are DEAD columns. Both accessors read the
-- ViewPermission table instead (CAN_GRANT_ACCESS_TO_VIEWS / CAN_REVOKE_ACCESS_TO_VIEWS rows), as
-- do all the other can* accessors since the per-permission boolean columns were retired. The
-- columns are recreated here so an existing database and a fresh one still have the same shape.

CREATE TABLE viewdefinition(
    account_id CHARACTER VARYING(64),
    createdat TIMESTAMP,
    name_ CHARACTER VARYING(125),
    view_id CHARACTER VARYING(44),
    updatedat TIMESTAMP,
    description_ CHARACTER VARYING(255),
    metadataview_ CHARACTER VARYING(44),
    issystem_ BOOLEAN,
    ispublic_ BOOLEAN,
    isfirehose_ BOOLEAN,
    bank_id CHARACTER VARYING(44),
    id_ BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    composite_unique_key CHARACTER VARYING(512),
    useprivatealiasifoneexists_ BOOLEAN,
    usepublicaliasifoneexists_ BOOLEAN,
    hideotheraccountmetadataifalias_ BOOLEAN,
    cangrantaccesstoviews_ CHARACTER VARYING,
    canrevokeaccesstoviews_ CHARACTER VARYING
);
ALTER TABLE viewdefinition ADD CONSTRAINT viewdefinition_pk PRIMARY KEY(id_);
CREATE UNIQUE INDEX viewdefinition_composite_unique_key ON viewdefinition(composite_unique_key NULLS FIRST);
CREATE INDEX viewdefinition_issystem_ ON viewdefinition(issystem_ NULLS FIRST);
CREATE INDEX viewdefinition_ispublic_ ON viewdefinition(ispublic_ NULLS FIRST);
CREATE INDEX viewdefinition_isfirehose_ ON viewdefinition(isfirehose_ NULLS FIRST);
CREATE INDEX viewdefinition_issystem__view_id ON viewdefinition(issystem_ NULLS FIRST, view_id NULLS FIRST);
CREATE INDEX viewdefinition_bank_id_account_id_view_id ON viewdefinition(bank_id NULLS FIRST, account_id NULLS FIRST, view_id NULLS FIRST);
