-- OAuth 1.0a nonces: one row per (consumer key, token key, timestamp, value) a signed request
-- presented, kept so the same nonce cannot be replayed inside its window.
--
-- The consumer and token are stored as their KEYS, not as foreign keys - a nonce outlives neither
-- and needs no join. TIMESTAMP_C carries the Schemifier suffix for a reserved word; the entity
-- field is `timestamp`.
--
-- There are no indexes beyond the primary key. The replay check counts rows on all four columns
-- and the scheduler deletes by timestamp, so both are table scans; this file recreates the table
-- as it is rather than adding an index the previous schema did not have.

CREATE TABLE nonce(
    consumerkey CHARACTER VARYING(250),
    tokenkey CHARACTER VARYING(250),
    value CHARACTER VARYING(250),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    timestamp_c TIMESTAMP
);
ALTER TABLE nonce ADD CONSTRAINT nonce_pk PRIMARY KEY(id);
