-- OAuth 1.0a request and access tokens.
--
-- KEY_C carries the Schemifier suffix for a reserved word; the entity field is `key`.
--
-- CONSUMERID and USERFOREIGNKEY are BIGINT SURROGATE keys, pointing at CONSUMER.ID and
-- RESOURCEUSER.ID. Note that CONSUMER also has its own VARCHAR business id in a column likewise
-- called CONSUMERID - the two are unrelated, and this one is the numeric one.
--
-- Neither key column is unique: the same consumer and user hold a series of tokens over time, and
-- DirectLogin's "only the last issued token counts" rule is a query over expiration dates rather
-- than a constraint.

CREATE TABLE token(
    tokentype CHARACTER VARYING(10),
    expirationdate TIMESTAMP,
    insertdate TIMESTAMP,
    callbackurl CHARACTER VARYING(250),
    userforeignkey BIGINT,
    consumerid BIGINT,
    verifier CHARACTER VARYING(250),
    secret CHARACTER VARYING(250),
    thirdpartyapplicationsecret CHARACTER VARYING(10),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    key_c CHARACTER VARYING(250),
    duration BIGINT
);
ALTER TABLE token ADD CONSTRAINT token_pk PRIMARY KEY(id);
CREATE INDEX token_userforeignkey ON token(userforeignkey NULLS FIRST);
CREATE INDEX token_consumerid ON token(consumerid NULLS FIRST);
