-- Consumers: the registered applications that call the API.
--
-- Two ids again, and they are not interchangeable: ID is the surrogate key that TOKEN points at,
-- while CONSUMERID is the string id the API exposes as consumer_id and that other tables (notably
-- MAPPEDCONSENT.MCONSUMERID) keep copies of. CONSUMERID is 250 wide because it holds more than
-- UUIDs - gateway-login app ids, and the "azp_UUID" composites OAuth2 auto-creates. Do not narrow
-- it without narrowing every table that copies it.
--
-- KEY_C carries the Schemifier suffix for a reserved word; the entity field is `key`.
--
-- AZP and SUB default to a fresh UUID rather than NULL, deliberately: the unique index over
-- (AZP, SUB) is what de-duplicates auto-created OIDC consumers, and databases disagree about
-- whether NULLs collide. A generated value makes every hand-registered consumer distinct under
-- that index without relying on NULL semantics.
--
-- The six PER*CALLLIMIT columns are the rate limits; -1 means no limit, and they default from
-- props rather than from the DDL.

CREATE TABLE consumer(
    clientcertificate CHARACTER VARYING(4000),
    azp CHARACTER VARYING(250),
    jwksuri CHARACTER VARYING(500),
    createdbyuserid CHARACTER VARYING(36),
    consumerid CHARACTER VARYING(250),
    createdat TIMESTAMP,
    company CHARACTER VARYING(100),
    iss CHARACTER VARYING(250),
    aud CHARACTER VARYING,
    logourl CHARACTER VARYING(250),
    updatedat TIMESTAMP,
    secret CHARACTER VARYING(250),
    apptype CHARACTER VARYING(20),
    developeremail CHARACTER VARYING(100),
    redirecturl CHARACTER VARYING(250),
    persecondcalllimit BIGINT,
    perminutecalllimit BIGINT,
    perhourcalllimit BIGINT,
    perdaycalllimit BIGINT,
    perweekcalllimit BIGINT,
    permonthcalllimit BIGINT,
    userauthenticationurl CHARACTER VARYING(250),
    name CHARACTER VARYING(100),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    key_c CHARACTER VARYING(250),
    isactive BOOLEAN,
    sub CHARACTER VARYING(250),
    description CHARACTER VARYING
);
ALTER TABLE consumer ADD CONSTRAINT consumer_pk PRIMARY KEY(id);
CREATE INDEX consumer_name ON consumer(name NULLS FIRST);
CREATE UNIQUE INDEX consumer_key_c ON consumer(key_c NULLS FIRST);
CREATE UNIQUE INDEX consumer_azp_sub ON consumer(azp NULLS FIRST, sub NULLS FIRST);
