-- Resource users: the person (or consent-minted pseudo-person) every account, view, entitlement
-- and consent hangs off.
--
-- Two ids once more: ID is the surrogate key AUTHUSER.USER_C points at, and USERID_ is the UUID the
-- API exposes as user_id. Other tables copy USERID_, never ID.
--
-- PROVIDER_ and NAME_ carry the Schemifier suffix for reserved words; the entity fields are
-- `provider` and `name`. PROVIDERID is the id the identity provider knows the user by - in practice
-- the username - and defaults to NAME_ when a caller does not supply one.
--
-- Two unique indexes, and only the first was declared on the entity: (PROVIDER_, PROVIDERID) came
-- from dbIndexes, while RESOURCEUSER_USERID_UNIQUE was added by MigrationOfResourceUser. Both are
-- recreated here so a fresh database matches a migrated one.
--
-- LASTMARKETINGAGREEMENTSIGNEDDATE is a DATE, not a TIMESTAMP: it records the day an agreement was
-- signed, and the driver hands it back as java.sql.Date.

CREATE TABLE resourceuser(
    email CHARACTER VARYING(100),
    providerid CHARACTER VARYING(100),
    userid_ CHARACTER VARYING(36),
    name_ CHARACTER VARYING(100),
    provider_ CHARACTER VARYING(100),
    company CHARACTER VARYING(50),
    createdbyconsentid CHARACTER VARYING(100),
    isdeleted BOOLEAN,
    lastusedlocale CHARACTER VARYING(10),
    isnaturalperson BOOLEAN,
    principaluserid CHARACTER VARYING(100),
    createdbyuserinvitationid CHARACTER VARYING(100),
    lastmarketingagreementsigneddate DATE,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE resourceuser ADD CONSTRAINT resourceuser_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX resourceuser_provider__providerid ON resourceuser(provider_ NULLS FIRST, providerid NULLS FIRST);
CREATE UNIQUE INDEX resourceuser_userid_unique ON resourceuser(userid_ NULLS FIRST);
