-- Auth users: the login half of a user. AuthUser holds a username, a password and an email; the
-- ResourceUser it points at through USER_C holds everything the API cares about.
--
-- PASSWORD_PW and PASSWORD_SLT are the two halves MappedPassword split a bcrypt hash into, and the
-- split is not decorative: v_oidc_users selects both columns, and OBP-OIDC and the Keycloak user
-- storage provider verify logins straight off that view. PASSWORD_PW holds "b;" + the first 44
-- characters of the 60-character bcrypt string, PASSWORD_SLT the remaining 16; verification puts
-- them back together. Neither column may be renamed, widened past what the view expects, or merged.
--
-- UNIQUEID is the email-validation token: 32 random characters, regenerated once the address is
-- confirmed.
--
-- USER_C is RESOURCEUSER.ID, and is NULL - not 0 - while an AuthUser has no ResourceUser yet.

CREATE TABLE authuser(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    firstname CHARACTER VARYING(100),
    lastname CHARACTER VARYING(100),
    email CHARACTER VARYING(100),
    username CHARACTER VARYING(100),
    password_pw CHARACTER VARYING(48),
    password_slt CHARACTER VARYING(20),
    provider CHARACTER VARYING(100),
    createdat TIMESTAMP,
    uniqueid CHARACTER VARYING(32),
    updatedat TIMESTAMP,
    superuser BOOLEAN,
    timezone CHARACTER VARYING(32),
    passwordshouldbechanged BOOLEAN,
    locale CHARACTER VARYING(16),
    validated BOOLEAN,
    user_c BIGINT
);
ALTER TABLE authuser ADD CONSTRAINT authuser_pk PRIMARY KEY(id);
CREATE INDEX authuser_uniqueid ON authuser(uniqueid NULLS FIRST);
CREATE INDEX authuser_user_c ON authuser(user_c NULLS FIRST);
CREATE UNIQUE INDEX authuser_username_provider ON authuser(username NULLS FIRST, provider NULLS FIRST);
