package code.api.util.flyway

import org.h2.jdbcx.JdbcDataSource
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers

/**
 * Turning Flyway on against a database that already has its tables must not fail.
 *
 * This is the only upgrade path there is. Schemifier no longer creates anything - ToSchemify.models
 * is Nil - so an existing deployment moving to this build has to set flyway.enabled=true, and it
 * does that against a schema Schemifier built, which has no flyway_schema_history table.
 *
 * baselineOnMigrate handles exactly that case, but it stamps the schema at baselineVersion, which
 * defaults to 1. That was right when V001 was the whole initial schema: baselining at 1 said "the
 * existing schema is already there" and only later migrations ran. It stopped being right once the
 * migration became per-table - V001 is now the ATM table alone, and V002..V118 each CREATE TABLE.
 * None of the 147 CREATE TABLE statements says IF NOT EXISTS (they are Schemifier's own exported
 * DDL), so V002 runs `CREATE TABLE MAPPEDNARRATIVE` against a database that already has it and the
 * migration fails. Flyway aborts, and the boot sequence with it.
 *
 * The scenario below is that upgrade in miniature: a schema holding a table an early script
 * creates, no history table, then migrate.
 */
class FlywayBaselineOnExistingSchemaTest extends AnyFlatSpec with Matchers {

  private def dataSourceFor(name: String): JdbcDataSource = {
    val ds = new JdbcDataSource()
    // DB_CLOSE_DELAY=-1 keeps the in-memory database alive for the whole test, and the unique
    // name keeps it clear of the suite's own OBPTest database.
    ds.setURL(s"jdbc:h2:mem:$name;DB_CLOSE_DELAY=-1")
    ds.setUser("sa")
    ds.setPassword("")
    ds
  }

  private def execute(ds: JdbcDataSource, sql: String): Unit = {
    val conn = ds.getConnection
    try {
      val st = conn.createStatement()
      try st.execute(sql) finally st.close()
    } finally conn.close()
  }

  "migrate" should "succeed on a schema Schemifier already built" in {
    val ds = dataSourceFor("flywayBaselineExisting")
    // One table an early script creates, standing in for the hundred-odd Schemifier left behind.
    execute(ds, """CREATE TABLE "PUBLIC"."MAPPEDNARRATIVE"(
                   "CREATEDAT" TIMESTAMP,
                   "TRANSACTION_C" CHARACTER VARYING(44),
                   "BANK" CHARACTER VARYING(44),
                   "UPDATEDAT" TIMESTAMP,
                   "NARRATIVE" CHARACTER VARYING(2000),
                   "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
                   "ACCOUNT" CHARACTER VARYING(44),
                   "USER_C" BIGINT)""")

    scala.util.Try(FlywaySchemaSetup.configure(ds, "h2").migrate()) match {
      case scala.util.Success(_) => // the upgrade path works
      case scala.util.Failure(e) =>
        fail(s"migrating a schema that already has its tables must work - this is the only " +
          s"upgrade path there is: ${e.getClass.getName}: ${e.getMessage}")
    }
  }

  it should "still create the whole schema on an empty database" in {
    // The other half: baselineOnMigrate must not stop a genuinely empty database from being built,
    // which is what a fresh deployment needs.
    val ds = dataSourceFor("flywayBaselineEmpty")
    val result = FlywaySchemaSetup.configure(ds, "h2").migrate()
    result.migrationsExecuted should be > 100

    val conn = ds.getConnection
    try {
      val rs = conn.createStatement().executeQuery(
        "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'PUBLIC'")
      rs.next()
      rs.getInt(1) should be > 100
    } finally conn.close()
  }
}
