FROM eclipse-temurin:25-jre-alpine

# Copy OBP source code
# Copy build artifact (JAR file) from maven build
COPY /obp-api/target/obp-api.jar /app/obp-api.jar
WORKDIR /app
ENTRYPOINT ["java", "-jar", "/app/obp-api.jar"]