// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package code.obp.grpc.metricsstream.api

/** Per-REST-call metric record, mirrors APIMetrics.saveMetric args and
  * MetricJsonV600 (REST v6.0.0). Field names track REST v6.0.0 verbatim.
  *
  * `response_body` is intentionally omitted — can be large and contain PII;
  * fetch via the REST /management/metrics endpoint if needed.
  *
  * @param date
  *   ISO-8601 UTC, seconds precision — matches REST v6.0.0 (yyyy-MM-dd'T'HH:mm:ss'Z').
  * @param apiInstanceId
  *   Identifies which OBP instance (pod) served this request. Sourced from
  *   the `api_instance_id` prop — either a configured value suffixed with a
  *   per-JVM UUID, or a pure UUID if the prop is unset. See
  *   code.api.Constant.ApiInstanceId.
  * @param operationId
  *   OBP operation id, e.g. "OBPv6.0.0-getBanks". Matches MetricJsonV600.operation_id.
  * @param consentReferenceId
  *   Reference id of the consent (if any) that authorised the request.
  *   Mirrors MetricJsonV600.consent_reference_id (REST v6.0.0+).
  */
@SerialVersionUID(0L)
final case class MetricEvent(
    url: _root_.scala.Predef.String = "",
    date: _root_.scala.Predef.String = "",
    duration: _root_.scala.Long = 0L,
    userId: _root_.scala.Predef.String = "",
    username: _root_.scala.Predef.String = "",
    appName: _root_.scala.Predef.String = "",
    developerEmail: _root_.scala.Predef.String = "",
    consumerId: _root_.scala.Predef.String = "",
    implementedByPartialFunction: _root_.scala.Predef.String = "",
    implementedInVersion: _root_.scala.Predef.String = "",
    verb: _root_.scala.Predef.String = "",
    statusCode: _root_.scala.Int = 0,
    correlationId: _root_.scala.Predef.String = "",
    sourceIp: _root_.scala.Predef.String = "",
    targetIp: _root_.scala.Predef.String = "",
    apiInstanceId: _root_.scala.Predef.String = "",
    operationId: _root_.scala.Predef.String = "",
    consentReferenceId: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[MetricEvent] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = url
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = date
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = duration
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(3, __value)
        }
      };
      
      {
        val __value = userId
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
        }
      };
      
      {
        val __value = username
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(5, __value)
        }
      };
      
      {
        val __value = appName
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(6, __value)
        }
      };
      
      {
        val __value = developerEmail
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(7, __value)
        }
      };
      
      {
        val __value = consumerId
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(8, __value)
        }
      };
      
      {
        val __value = implementedByPartialFunction
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(9, __value)
        }
      };
      
      {
        val __value = implementedInVersion
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(10, __value)
        }
      };
      
      {
        val __value = verb
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(11, __value)
        }
      };
      
      {
        val __value = statusCode
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt32Size(12, __value)
        }
      };
      
      {
        val __value = correlationId
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(13, __value)
        }
      };
      
      {
        val __value = sourceIp
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(14, __value)
        }
      };
      
      {
        val __value = targetIp
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(15, __value)
        }
      };
      
      {
        val __value = apiInstanceId
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(16, __value)
        }
      };
      
      {
        val __value = operationId
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(17, __value)
        }
      };
      
      {
        val __value = consentReferenceId
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(18, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = url
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = date
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = duration
        if (__v != 0L) {
          _output__.writeInt64(3, __v)
        }
      };
      {
        val __v = userId
        if (!__v.isEmpty) {
          _output__.writeString(4, __v)
        }
      };
      {
        val __v = username
        if (!__v.isEmpty) {
          _output__.writeString(5, __v)
        }
      };
      {
        val __v = appName
        if (!__v.isEmpty) {
          _output__.writeString(6, __v)
        }
      };
      {
        val __v = developerEmail
        if (!__v.isEmpty) {
          _output__.writeString(7, __v)
        }
      };
      {
        val __v = consumerId
        if (!__v.isEmpty) {
          _output__.writeString(8, __v)
        }
      };
      {
        val __v = implementedByPartialFunction
        if (!__v.isEmpty) {
          _output__.writeString(9, __v)
        }
      };
      {
        val __v = implementedInVersion
        if (!__v.isEmpty) {
          _output__.writeString(10, __v)
        }
      };
      {
        val __v = verb
        if (!__v.isEmpty) {
          _output__.writeString(11, __v)
        }
      };
      {
        val __v = statusCode
        if (__v != 0) {
          _output__.writeInt32(12, __v)
        }
      };
      {
        val __v = correlationId
        if (!__v.isEmpty) {
          _output__.writeString(13, __v)
        }
      };
      {
        val __v = sourceIp
        if (!__v.isEmpty) {
          _output__.writeString(14, __v)
        }
      };
      {
        val __v = targetIp
        if (!__v.isEmpty) {
          _output__.writeString(15, __v)
        }
      };
      {
        val __v = apiInstanceId
        if (!__v.isEmpty) {
          _output__.writeString(16, __v)
        }
      };
      {
        val __v = operationId
        if (!__v.isEmpty) {
          _output__.writeString(17, __v)
        }
      };
      {
        val __v = consentReferenceId
        if (!__v.isEmpty) {
          _output__.writeString(18, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withUrl(__v: _root_.scala.Predef.String): MetricEvent = copy(url = __v)
    def withDate(__v: _root_.scala.Predef.String): MetricEvent = copy(date = __v)
    def withDuration(__v: _root_.scala.Long): MetricEvent = copy(duration = __v)
    def withUserId(__v: _root_.scala.Predef.String): MetricEvent = copy(userId = __v)
    def withUsername(__v: _root_.scala.Predef.String): MetricEvent = copy(username = __v)
    def withAppName(__v: _root_.scala.Predef.String): MetricEvent = copy(appName = __v)
    def withDeveloperEmail(__v: _root_.scala.Predef.String): MetricEvent = copy(developerEmail = __v)
    def withConsumerId(__v: _root_.scala.Predef.String): MetricEvent = copy(consumerId = __v)
    def withImplementedByPartialFunction(__v: _root_.scala.Predef.String): MetricEvent = copy(implementedByPartialFunction = __v)
    def withImplementedInVersion(__v: _root_.scala.Predef.String): MetricEvent = copy(implementedInVersion = __v)
    def withVerb(__v: _root_.scala.Predef.String): MetricEvent = copy(verb = __v)
    def withStatusCode(__v: _root_.scala.Int): MetricEvent = copy(statusCode = __v)
    def withCorrelationId(__v: _root_.scala.Predef.String): MetricEvent = copy(correlationId = __v)
    def withSourceIp(__v: _root_.scala.Predef.String): MetricEvent = copy(sourceIp = __v)
    def withTargetIp(__v: _root_.scala.Predef.String): MetricEvent = copy(targetIp = __v)
    def withApiInstanceId(__v: _root_.scala.Predef.String): MetricEvent = copy(apiInstanceId = __v)
    def withOperationId(__v: _root_.scala.Predef.String): MetricEvent = copy(operationId = __v)
    def withConsentReferenceId(__v: _root_.scala.Predef.String): MetricEvent = copy(consentReferenceId = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = url
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = date
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = duration
          if (__t != 0L) __t else null
        }
        case 4 => {
          val __t = userId
          if (__t != "") __t else null
        }
        case 5 => {
          val __t = username
          if (__t != "") __t else null
        }
        case 6 => {
          val __t = appName
          if (__t != "") __t else null
        }
        case 7 => {
          val __t = developerEmail
          if (__t != "") __t else null
        }
        case 8 => {
          val __t = consumerId
          if (__t != "") __t else null
        }
        case 9 => {
          val __t = implementedByPartialFunction
          if (__t != "") __t else null
        }
        case 10 => {
          val __t = implementedInVersion
          if (__t != "") __t else null
        }
        case 11 => {
          val __t = verb
          if (__t != "") __t else null
        }
        case 12 => {
          val __t = statusCode
          if (__t != 0) __t else null
        }
        case 13 => {
          val __t = correlationId
          if (__t != "") __t else null
        }
        case 14 => {
          val __t = sourceIp
          if (__t != "") __t else null
        }
        case 15 => {
          val __t = targetIp
          if (__t != "") __t else null
        }
        case 16 => {
          val __t = apiInstanceId
          if (__t != "") __t else null
        }
        case 17 => {
          val __t = operationId
          if (__t != "") __t else null
        }
        case 18 => {
          val __t = consentReferenceId
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(url)
        case 2 => _root_.scalapb.descriptors.PString(date)
        case 3 => _root_.scalapb.descriptors.PLong(duration)
        case 4 => _root_.scalapb.descriptors.PString(userId)
        case 5 => _root_.scalapb.descriptors.PString(username)
        case 6 => _root_.scalapb.descriptors.PString(appName)
        case 7 => _root_.scalapb.descriptors.PString(developerEmail)
        case 8 => _root_.scalapb.descriptors.PString(consumerId)
        case 9 => _root_.scalapb.descriptors.PString(implementedByPartialFunction)
        case 10 => _root_.scalapb.descriptors.PString(implementedInVersion)
        case 11 => _root_.scalapb.descriptors.PString(verb)
        case 12 => _root_.scalapb.descriptors.PInt(statusCode)
        case 13 => _root_.scalapb.descriptors.PString(correlationId)
        case 14 => _root_.scalapb.descriptors.PString(sourceIp)
        case 15 => _root_.scalapb.descriptors.PString(targetIp)
        case 16 => _root_.scalapb.descriptors.PString(apiInstanceId)
        case 17 => _root_.scalapb.descriptors.PString(operationId)
        case 18 => _root_.scalapb.descriptors.PString(consentReferenceId)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: code.obp.grpc.metricsstream.api.MetricEvent.type = code.obp.grpc.metricsstream.api.MetricEvent
    // @@protoc_insertion_point(GeneratedMessage[code.obp.grpc.metricsstream.g1.MetricEvent])
}

object MetricEvent extends scalapb.GeneratedMessageCompanion[code.obp.grpc.metricsstream.api.MetricEvent] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[code.obp.grpc.metricsstream.api.MetricEvent] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): code.obp.grpc.metricsstream.api.MetricEvent = {
    var __url: _root_.scala.Predef.String = ""
    var __date: _root_.scala.Predef.String = ""
    var __duration: _root_.scala.Long = 0L
    var __userId: _root_.scala.Predef.String = ""
    var __username: _root_.scala.Predef.String = ""
    var __appName: _root_.scala.Predef.String = ""
    var __developerEmail: _root_.scala.Predef.String = ""
    var __consumerId: _root_.scala.Predef.String = ""
    var __implementedByPartialFunction: _root_.scala.Predef.String = ""
    var __implementedInVersion: _root_.scala.Predef.String = ""
    var __verb: _root_.scala.Predef.String = ""
    var __statusCode: _root_.scala.Int = 0
    var __correlationId: _root_.scala.Predef.String = ""
    var __sourceIp: _root_.scala.Predef.String = ""
    var __targetIp: _root_.scala.Predef.String = ""
    var __apiInstanceId: _root_.scala.Predef.String = ""
    var __operationId: _root_.scala.Predef.String = ""
    var __consentReferenceId: _root_.scala.Predef.String = ""
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __url = _input__.readStringRequireUtf8()
        case 18 =>
          __date = _input__.readStringRequireUtf8()
        case 24 =>
          __duration = _input__.readInt64()
        case 34 =>
          __userId = _input__.readStringRequireUtf8()
        case 42 =>
          __username = _input__.readStringRequireUtf8()
        case 50 =>
          __appName = _input__.readStringRequireUtf8()
        case 58 =>
          __developerEmail = _input__.readStringRequireUtf8()
        case 66 =>
          __consumerId = _input__.readStringRequireUtf8()
        case 74 =>
          __implementedByPartialFunction = _input__.readStringRequireUtf8()
        case 82 =>
          __implementedInVersion = _input__.readStringRequireUtf8()
        case 90 =>
          __verb = _input__.readStringRequireUtf8()
        case 96 =>
          __statusCode = _input__.readInt32()
        case 106 =>
          __correlationId = _input__.readStringRequireUtf8()
        case 114 =>
          __sourceIp = _input__.readStringRequireUtf8()
        case 122 =>
          __targetIp = _input__.readStringRequireUtf8()
        case 130 =>
          __apiInstanceId = _input__.readStringRequireUtf8()
        case 138 =>
          __operationId = _input__.readStringRequireUtf8()
        case 146 =>
          __consentReferenceId = _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    code.obp.grpc.metricsstream.api.MetricEvent(
        url = __url,
        date = __date,
        duration = __duration,
        userId = __userId,
        username = __username,
        appName = __appName,
        developerEmail = __developerEmail,
        consumerId = __consumerId,
        implementedByPartialFunction = __implementedByPartialFunction,
        implementedInVersion = __implementedInVersion,
        verb = __verb,
        statusCode = __statusCode,
        correlationId = __correlationId,
        sourceIp = __sourceIp,
        targetIp = __targetIp,
        apiInstanceId = __apiInstanceId,
        operationId = __operationId,
        consentReferenceId = __consentReferenceId,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[code.obp.grpc.metricsstream.api.MetricEvent] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      code.obp.grpc.metricsstream.api.MetricEvent(
        url = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        date = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        duration = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
        userId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        username = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        appName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        developerEmail = __fieldsMap.get(scalaDescriptor.findFieldByNumber(7).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        consumerId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(8).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        implementedByPartialFunction = __fieldsMap.get(scalaDescriptor.findFieldByNumber(9).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        implementedInVersion = __fieldsMap.get(scalaDescriptor.findFieldByNumber(10).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        verb = __fieldsMap.get(scalaDescriptor.findFieldByNumber(11).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        statusCode = __fieldsMap.get(scalaDescriptor.findFieldByNumber(12).get).map(_.as[_root_.scala.Int]).getOrElse(0),
        correlationId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(13).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        sourceIp = __fieldsMap.get(scalaDescriptor.findFieldByNumber(14).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        targetIp = __fieldsMap.get(scalaDescriptor.findFieldByNumber(15).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        apiInstanceId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(16).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        operationId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(17).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        consentReferenceId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(18).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = MetricsStreamProto.javaDescriptor.getMessageTypes().get(1)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = MetricsStreamProto.scalaDescriptor.messages(1)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = code.obp.grpc.metricsstream.api.MetricEvent(
    url = "",
    date = "",
    duration = 0L,
    userId = "",
    username = "",
    appName = "",
    developerEmail = "",
    consumerId = "",
    implementedByPartialFunction = "",
    implementedInVersion = "",
    verb = "",
    statusCode = 0,
    correlationId = "",
    sourceIp = "",
    targetIp = "",
    apiInstanceId = "",
    operationId = "",
    consentReferenceId = ""
  )
  implicit class MetricEventLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, code.obp.grpc.metricsstream.api.MetricEvent]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, code.obp.grpc.metricsstream.api.MetricEvent](_l) {
    def url: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.url)((c_, f_) => c_.copy(url = f_))
    def date: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.date)((c_, f_) => c_.copy(date = f_))
    def duration: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.duration)((c_, f_) => c_.copy(duration = f_))
    def userId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.userId)((c_, f_) => c_.copy(userId = f_))
    def username: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.username)((c_, f_) => c_.copy(username = f_))
    def appName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.appName)((c_, f_) => c_.copy(appName = f_))
    def developerEmail: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.developerEmail)((c_, f_) => c_.copy(developerEmail = f_))
    def consumerId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.consumerId)((c_, f_) => c_.copy(consumerId = f_))
    def implementedByPartialFunction: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.implementedByPartialFunction)((c_, f_) => c_.copy(implementedByPartialFunction = f_))
    def implementedInVersion: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.implementedInVersion)((c_, f_) => c_.copy(implementedInVersion = f_))
    def verb: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.verb)((c_, f_) => c_.copy(verb = f_))
    def statusCode: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] = field(_.statusCode)((c_, f_) => c_.copy(statusCode = f_))
    def correlationId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.correlationId)((c_, f_) => c_.copy(correlationId = f_))
    def sourceIp: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.sourceIp)((c_, f_) => c_.copy(sourceIp = f_))
    def targetIp: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.targetIp)((c_, f_) => c_.copy(targetIp = f_))
    def apiInstanceId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.apiInstanceId)((c_, f_) => c_.copy(apiInstanceId = f_))
    def operationId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.operationId)((c_, f_) => c_.copy(operationId = f_))
    def consentReferenceId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.consentReferenceId)((c_, f_) => c_.copy(consentReferenceId = f_))
  }
  final val URL_FIELD_NUMBER = 1
  final val DATE_FIELD_NUMBER = 2
  final val DURATION_FIELD_NUMBER = 3
  final val USER_ID_FIELD_NUMBER = 4
  final val USERNAME_FIELD_NUMBER = 5
  final val APP_NAME_FIELD_NUMBER = 6
  final val DEVELOPER_EMAIL_FIELD_NUMBER = 7
  final val CONSUMER_ID_FIELD_NUMBER = 8
  final val IMPLEMENTED_BY_PARTIAL_FUNCTION_FIELD_NUMBER = 9
  final val IMPLEMENTED_IN_VERSION_FIELD_NUMBER = 10
  final val VERB_FIELD_NUMBER = 11
  final val STATUS_CODE_FIELD_NUMBER = 12
  final val CORRELATION_ID_FIELD_NUMBER = 13
  final val SOURCE_IP_FIELD_NUMBER = 14
  final val TARGET_IP_FIELD_NUMBER = 15
  final val API_INSTANCE_ID_FIELD_NUMBER = 16
  final val OPERATION_ID_FIELD_NUMBER = 17
  final val CONSENT_REFERENCE_ID_FIELD_NUMBER = 18
  def of(
    url: _root_.scala.Predef.String,
    date: _root_.scala.Predef.String,
    duration: _root_.scala.Long,
    userId: _root_.scala.Predef.String,
    username: _root_.scala.Predef.String,
    appName: _root_.scala.Predef.String,
    developerEmail: _root_.scala.Predef.String,
    consumerId: _root_.scala.Predef.String,
    implementedByPartialFunction: _root_.scala.Predef.String,
    implementedInVersion: _root_.scala.Predef.String,
    verb: _root_.scala.Predef.String,
    statusCode: _root_.scala.Int,
    correlationId: _root_.scala.Predef.String,
    sourceIp: _root_.scala.Predef.String,
    targetIp: _root_.scala.Predef.String,
    apiInstanceId: _root_.scala.Predef.String,
    operationId: _root_.scala.Predef.String,
    consentReferenceId: _root_.scala.Predef.String
  ): _root_.code.obp.grpc.metricsstream.api.MetricEvent = _root_.code.obp.grpc.metricsstream.api.MetricEvent(
    url,
    date,
    duration,
    userId,
    username,
    appName,
    developerEmail,
    consumerId,
    implementedByPartialFunction,
    implementedInVersion,
    verb,
    statusCode,
    correlationId,
    sourceIp,
    targetIp,
    apiInstanceId,
    operationId,
    consentReferenceId
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[code.obp.grpc.metricsstream.g1.MetricEvent])
}
