// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package code.obp.grpc.metricsstream.api

/** Server-side filters. Empty string = no filter on that field.
  * Filters AND together: passing consumer_id + verb = events matching BOTH.
  * url_substring matches if the event's url contains the given substring.
  */
@SerialVersionUID(0L)
final case class StreamMetricsRequest(
    consumerId: _root_.scala.Predef.String = "",
    userId: _root_.scala.Predef.String = "",
    verb: _root_.scala.Predef.String = "",
    urlSubstring: _root_.scala.Predef.String = "",
    implementedByPartialFunction: _root_.scala.Predef.String = "",
    appName: _root_.scala.Predef.String = "",
    consentReferenceId: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[StreamMetricsRequest] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = consumerId
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = userId
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = verb
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      
      {
        val __value = urlSubstring
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
        }
      };
      
      {
        val __value = implementedByPartialFunction
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(5, __value)
        }
      };
      
      {
        val __value = appName
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(6, __value)
        }
      };
      
      {
        val __value = consentReferenceId
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(7, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = consumerId
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = userId
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = verb
        if (!__v.isEmpty) {
          _output__.writeString(3, __v)
        }
      };
      {
        val __v = urlSubstring
        if (!__v.isEmpty) {
          _output__.writeString(4, __v)
        }
      };
      {
        val __v = implementedByPartialFunction
        if (!__v.isEmpty) {
          _output__.writeString(5, __v)
        }
      };
      {
        val __v = appName
        if (!__v.isEmpty) {
          _output__.writeString(6, __v)
        }
      };
      {
        val __v = consentReferenceId
        if (!__v.isEmpty) {
          _output__.writeString(7, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withConsumerId(__v: _root_.scala.Predef.String): StreamMetricsRequest = copy(consumerId = __v)
    def withUserId(__v: _root_.scala.Predef.String): StreamMetricsRequest = copy(userId = __v)
    def withVerb(__v: _root_.scala.Predef.String): StreamMetricsRequest = copy(verb = __v)
    def withUrlSubstring(__v: _root_.scala.Predef.String): StreamMetricsRequest = copy(urlSubstring = __v)
    def withImplementedByPartialFunction(__v: _root_.scala.Predef.String): StreamMetricsRequest = copy(implementedByPartialFunction = __v)
    def withAppName(__v: _root_.scala.Predef.String): StreamMetricsRequest = copy(appName = __v)
    def withConsentReferenceId(__v: _root_.scala.Predef.String): StreamMetricsRequest = copy(consentReferenceId = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = consumerId
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = userId
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = verb
          if (__t != "") __t else null
        }
        case 4 => {
          val __t = urlSubstring
          if (__t != "") __t else null
        }
        case 5 => {
          val __t = implementedByPartialFunction
          if (__t != "") __t else null
        }
        case 6 => {
          val __t = appName
          if (__t != "") __t else null
        }
        case 7 => {
          val __t = consentReferenceId
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(consumerId)
        case 2 => _root_.scalapb.descriptors.PString(userId)
        case 3 => _root_.scalapb.descriptors.PString(verb)
        case 4 => _root_.scalapb.descriptors.PString(urlSubstring)
        case 5 => _root_.scalapb.descriptors.PString(implementedByPartialFunction)
        case 6 => _root_.scalapb.descriptors.PString(appName)
        case 7 => _root_.scalapb.descriptors.PString(consentReferenceId)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: code.obp.grpc.metricsstream.api.StreamMetricsRequest.type = code.obp.grpc.metricsstream.api.StreamMetricsRequest
    // @@protoc_insertion_point(GeneratedMessage[code.obp.grpc.metricsstream.g1.StreamMetricsRequest])
}

object StreamMetricsRequest extends scalapb.GeneratedMessageCompanion[code.obp.grpc.metricsstream.api.StreamMetricsRequest] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[code.obp.grpc.metricsstream.api.StreamMetricsRequest] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): code.obp.grpc.metricsstream.api.StreamMetricsRequest = {
    var __consumerId: _root_.scala.Predef.String = ""
    var __userId: _root_.scala.Predef.String = ""
    var __verb: _root_.scala.Predef.String = ""
    var __urlSubstring: _root_.scala.Predef.String = ""
    var __implementedByPartialFunction: _root_.scala.Predef.String = ""
    var __appName: _root_.scala.Predef.String = ""
    var __consentReferenceId: _root_.scala.Predef.String = ""
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __consumerId = _input__.readStringRequireUtf8()
        case 18 =>
          __userId = _input__.readStringRequireUtf8()
        case 26 =>
          __verb = _input__.readStringRequireUtf8()
        case 34 =>
          __urlSubstring = _input__.readStringRequireUtf8()
        case 42 =>
          __implementedByPartialFunction = _input__.readStringRequireUtf8()
        case 50 =>
          __appName = _input__.readStringRequireUtf8()
        case 58 =>
          __consentReferenceId = _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    code.obp.grpc.metricsstream.api.StreamMetricsRequest(
        consumerId = __consumerId,
        userId = __userId,
        verb = __verb,
        urlSubstring = __urlSubstring,
        implementedByPartialFunction = __implementedByPartialFunction,
        appName = __appName,
        consentReferenceId = __consentReferenceId,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[code.obp.grpc.metricsstream.api.StreamMetricsRequest] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      code.obp.grpc.metricsstream.api.StreamMetricsRequest(
        consumerId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        userId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        verb = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        urlSubstring = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        implementedByPartialFunction = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        appName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        consentReferenceId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(7).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = MetricsStreamProto.javaDescriptor.getMessageTypes().get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = MetricsStreamProto.scalaDescriptor.messages(0)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = code.obp.grpc.metricsstream.api.StreamMetricsRequest(
    consumerId = "",
    userId = "",
    verb = "",
    urlSubstring = "",
    implementedByPartialFunction = "",
    appName = "",
    consentReferenceId = ""
  )
  implicit class StreamMetricsRequestLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, code.obp.grpc.metricsstream.api.StreamMetricsRequest]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, code.obp.grpc.metricsstream.api.StreamMetricsRequest](_l) {
    def consumerId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.consumerId)((c_, f_) => c_.copy(consumerId = f_))
    def userId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.userId)((c_, f_) => c_.copy(userId = f_))
    def verb: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.verb)((c_, f_) => c_.copy(verb = f_))
    def urlSubstring: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.urlSubstring)((c_, f_) => c_.copy(urlSubstring = f_))
    def implementedByPartialFunction: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.implementedByPartialFunction)((c_, f_) => c_.copy(implementedByPartialFunction = f_))
    def appName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.appName)((c_, f_) => c_.copy(appName = f_))
    def consentReferenceId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.consentReferenceId)((c_, f_) => c_.copy(consentReferenceId = f_))
  }
  final val CONSUMER_ID_FIELD_NUMBER = 1
  final val USER_ID_FIELD_NUMBER = 2
  final val VERB_FIELD_NUMBER = 3
  final val URL_SUBSTRING_FIELD_NUMBER = 4
  final val IMPLEMENTED_BY_PARTIAL_FUNCTION_FIELD_NUMBER = 5
  final val APP_NAME_FIELD_NUMBER = 6
  final val CONSENT_REFERENCE_ID_FIELD_NUMBER = 7
  def of(
    consumerId: _root_.scala.Predef.String,
    userId: _root_.scala.Predef.String,
    verb: _root_.scala.Predef.String,
    urlSubstring: _root_.scala.Predef.String,
    implementedByPartialFunction: _root_.scala.Predef.String,
    appName: _root_.scala.Predef.String,
    consentReferenceId: _root_.scala.Predef.String
  ): _root_.code.obp.grpc.metricsstream.api.StreamMetricsRequest = _root_.code.obp.grpc.metricsstream.api.StreamMetricsRequest(
    consumerId,
    userId,
    verb,
    urlSubstring,
    implementedByPartialFunction,
    appName,
    consentReferenceId
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[code.obp.grpc.metricsstream.g1.StreamMetricsRequest])
}
