name: $(Rev:r)

trigger:
  - main
  - master

variables:
- group: common

resources:
  repositories:
    - repository: templates
      type: git
      name: DevOps/azure-templates

stages:

# Build
# -----
  - stage: BuildStage
    displayName: Build (Docker)
    dependsOn:
    jobs:
    - template: ci/jobs/build-docker-with-args.yml@templates
      parameters:
        imageName: maib-obp-api
        buildDir: $(Build.SourcesDirectory)/Dockerfile
        buildArgs: --build-arg NEXUS_USER=$(NEXUS_USER) --build-arg NEXUS_PASS=$(NEXUS_PASS)