package code.api.util.http4s

import java.lang.management.ManagementFactory

import cats.effect.IO
import code.api.cache.Redis
import code.api.util.{APIUtil, DoobieUtil}
import code.util.Helper.MdcLoggable
import doobie._
import doobie.implicits._
import org.http4s._
import org.http4s.dsl.io._
import org.http4s.headers.{Accept, `Content-Type`}
import org.http4s.Charset

object StatusPage extends MdcLoggable {

  private lazy val gitProps: java.util.Properties = {
    val props = new java.util.Properties()
    val is = getClass.getResourceAsStream("/git.properties")
    if (is != null) {
      try props.load(is) finally is.close()
    }
    props
  }

  private def gitProp(key: String): String =
    Option(gitProps.getProperty(key)).map(_.trim).filter(_.nonEmpty).getOrElse("unknown")

  private def gitCommit: String = gitProp("git.commit.id")

  /**
   * The branch and the moment the running artifact was built. Both come from the same stamp as the
   * commit, and both were unusable until the stamp stopped being generated by
   * git-commit-id-maven-plugin: in a git worktree it named the main checkout's branch, and it
   * refused to rewrite the file when only the build time had changed. Absent from older stamps, so
   * they degrade to "unknown" rather than failing.
   */
  private def gitBranch: String = gitProp("git.branch")

  private def gitBuildTime: String = gitProp("git.build.time")

  /**
   * True when the build had uncommitted changes. Reported alongside the commit because the stamp
   * names the last commit, not what was compiled: a build from a modified working tree names a
   * revision whose source never produced this artifact, and checking that id out would not
   * reproduce it. Absent from older stamps, so it defaults to false rather than failing.
   */
  private def gitDirty: Boolean =
    Option(gitProps.getProperty("git.dirty")).exists(_.trim.equalsIgnoreCase("true"))

  private def apiInstanceId: String = code.api.Constant.ApiInstanceId

  private def uptimeSeconds: Long =
    ManagementFactory.getRuntimeMXBean.getUptime / 1000L

  private def prefersJson(req: Request[IO]): Boolean =
    req.headers.get[Accept].exists { accept =>
      accept.values.toList.exists { mediaRange =>
        mediaRange.mediaRange == MediaType.application.json
      }
    }

  private case class EmailChecks(
    config: String,        // "ok" / "warn"
    configDetail: String,  // human-readable reason when "warn", empty otherwise
    smtp: String,          // "ok" / "fail"
    smtpDetail: String     // host:port that was probed, plus error message on fail
  )

  private case class Checks(database: String, redis: String, email: EmailChecks) {
    // Email is a soft dependency — config/smtp warnings do NOT flip overall to 503.
    def allOk: Boolean = database == "ok" && redis == "ok"
  }

  // SMTP probe is the only expensive bit. Cache it for 60s so frequent /status
  // pollers (Prometheus blackbox, k8s probes) don't hammer the mail server with
  // a TCP connect on every request. Config checks are essentially free so we
  // recompute them each time.
  private val SmtpCacheTtlMillis = 60000L
  private val smtpCache: java.util.concurrent.atomic.AtomicReference[(Long, String, String)] =
    new java.util.concurrent.atomic.AtomicReference((0L, "", ""))

  private def probeSmtp(): (String, String) = {
    val host = APIUtil.getPropsValue("mail.smtp.host", "localhost")
    val port = APIUtil.getPropsAsIntValue("mail.smtp.port", 25)
    val target = s"$host:$port"
    try {
      val socket = new java.net.Socket()
      try {
        socket.connect(new java.net.InetSocketAddress(host, port), 2000)
        socket.setSoTimeout(2000)
        val in = new java.io.BufferedReader(new java.io.InputStreamReader(socket.getInputStream))
        val banner = Option(in.readLine()).getOrElse("")
        if (banner.startsWith("220")) "ok" -> s"$target (banner: ${banner.take(80)})"
        else "fail" -> s"$target — unexpected greeting: ${banner.take(80)}"
      } finally socket.close()
    } catch {
      case e: Throwable =>
        logger.warn(s"StatusPage says: smtp check to $target failed: ${e.getMessage}")
        "fail" -> s"$target — ${e.getClass.getSimpleName}: ${e.getMessage}"
    }
  }

  private def cachedSmtpCheck(): (String, String) = {
    val now = System.currentTimeMillis()
    val cached = smtpCache.get()
    if (now - cached._1 < SmtpCacheTtlMillis && cached._2.nonEmpty) {
      (cached._2, cached._3)
    } else {
      val (status, detail) = probeSmtp()
      smtpCache.set((now, status, detail))
      (status, detail)
    }
  }

  private def runEmailChecks: EmailChecks = {
    val portalUrl = APIUtil.getPortalUrl
    val sender = APIUtil.getPropsValue("mail.users.userinfo.sender.address", "noreply@example.com")
    val portalMissing = portalUrl.isEmpty
    val senderIsDefault = sender == "noreply@example.com"
    val (configStatus, configDetail) =
      if (portalMissing && senderIsDefault)
        "warn" -> "public_obp_portal_url (or legacy portal_external_url) not set; mail.users.userinfo.sender.address is default 'noreply@example.com'"
      else if (portalMissing)
        "warn" -> "public_obp_portal_url (or legacy portal_external_url) not set — validation/reset emails will be silently skipped"
      else if (senderIsDefault)
        "warn" -> "mail.users.userinfo.sender.address is default 'noreply@example.com' — most SMTP servers will reject it"
      else
        "ok" -> ""

    val (smtpStatus, smtpDetail) = cachedSmtpCheck()
    EmailChecks(configStatus, configDetail, smtpStatus, smtpDetail)
  }

  private def runChecks: IO[Checks] = IO {
    val db = try {
      DoobieUtil.runQuery(sql"SELECT 1".query[Int].unique)
      "ok"
    } catch {
      case e: Throwable =>
        logger.warn(s"StatusPage says: database check failed: ${e.getMessage}")
        "fail"
    }
    val redis = try {
      if (Redis.isRedisReady) "ok" else "fail"
    } catch {
      case e: Throwable =>
        logger.warn(s"StatusPage says: redis check failed: ${e.getMessage}")
        "fail"
    }
    val email = try runEmailChecks catch {
      case e: Throwable =>
        logger.warn(s"StatusPage says: email checks errored: ${e.getMessage}")
        EmailChecks("warn", s"email check error: ${e.getMessage}", "fail", "")
    }
    Checks(db, redis, email)
  }

  val routes: HttpRoutes[IO] = HttpRoutes.of[IO] {
    case req @ GET -> Root / "status" =>
      runChecks.flatMap { checks =>
        val response = if (prefersJson(req)) jsonResponse(checks) else htmlResponse(checks)
        if (checks.allOk) response
        else response.map(_.withStatus(Status.ServiceUnavailable))
      }

    // Liveness probe: the process is running and can respond to HTTP.
    // Does not touch DB or Redis — those belong in /status (readiness).
    case GET -> Root / "health" =>
      Ok("""{"status":"ok"}""").map(_.withContentType(`Content-Type`(MediaType.application.json, Charset.`UTF-8`)))
  }

  private def jsonEscape(s: String): String =
    s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")

  private def jsonResponse(checks: Checks): IO[Response[IO]] = {
    val status = if (checks.allOk) "ok" else "degraded"
    val json =
      s"""{
         |  "status": "$status",
         |  "api_instance_id": "$apiInstanceId",
         |  "git_commit": "$gitCommit",
         |  "git_branch": "${jsonEscape(gitBranch)}",
         |  "git_dirty": $gitDirty,
         |  "git_build_time": "${jsonEscape(gitBuildTime)}",
         |  "uptime_seconds": $uptimeSeconds,
         |  "checks": {
         |    "database": "${checks.database}",
         |    "redis": "${checks.redis}",
         |    "email": {
         |      "config": "${checks.email.config}",
         |      "config_detail": "${jsonEscape(checks.email.configDetail)}",
         |      "smtp": "${checks.email.smtp}",
         |      "smtp_detail": "${jsonEscape(checks.email.smtpDetail)}"
         |    }
         |  }
         |}""".stripMargin
    Ok(json).map(_.withContentType(`Content-Type`(MediaType.application.json, Charset.`UTF-8`)))
  }

  private def htmlEscape(s: String): String =
    s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;")

  private def htmlResponse(checks: Checks): IO[Response[IO]] = {
    val overall = if (checks.allOk) "ok" else "degraded"
    val overallColor = if (checks.allOk) "#2e7d32" else "#c62828"
    def badge(v: String): String = {
      val color = v match {
        case "ok"   => "#2e7d32"
        case "warn" => "#ef6c00"
        case _      => "#c62828"
      }
      s"""<span style="color: $color; font-weight: bold;">$v</span>"""
    }
    def detailCell(detail: String): String =
      if (detail.isEmpty) "" else s"""<div style="color: #666; font-size: 0.85em; margin-top: 4px;">${htmlEscape(detail)}</div>"""

    val html =
      s"""<!DOCTYPE html>
         |<html>
         |<head>
         |  <title>OBP API - Status</title>
         |  <style>
         |    body { font-family: sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; }
         |    h1 { color: #333; }
         |    h2 { color: #555; margin-top: 30px; }
         |    table { border-collapse: collapse; width: 100%; }
         |    th, td { padding: 6px 12px; text-align: left; border-bottom: 1px solid #eee; vertical-align: top; }
         |    th { width: 180px; }
         |  </style>
         |</head>
         |<body>
         |  <h1>OBP API Status: <span style="color: $overallColor;">$overall</span></h1>
         |
         |  <h2>Instance</h2>
         |  <table>
         |    <tr><th>api_instance_id</th><td>$apiInstanceId</td></tr>
         |    <tr><th>git_commit</th><td>$gitCommit${
              if (gitDirty)
                """ <span style="color: #ef6c00; font-weight: bold;">dirty</span>""" +
                """<div style="color: #666; font-size: 0.85em; margin-top: 4px;">""" +
                "built from a working tree with uncommitted changes &mdash; this names the last " +
                "commit, not necessarily what is running</div>"
              else ""
            }</td></tr>
         |    <tr><th>git_branch</th><td>${htmlEscape(gitBranch)}</td></tr>
         |    <tr><th>git_build_time</th><td>${htmlEscape(gitBuildTime)}</td></tr>
         |    <tr><th>uptime_seconds</th><td>$uptimeSeconds</td></tr>
         |  </table>
         |
         |  <h2>Checks</h2>
         |  <table>
         |    <tr><th>database</th><td>${badge(checks.database)}</td></tr>
         |    <tr><th>redis</th><td>${badge(checks.redis)}</td></tr>
         |  </table>
         |
         |  <h2>Email (soft dependency — does not affect overall status)</h2>
         |  <table>
         |    <tr><th>config</th><td>${badge(checks.email.config)}${detailCell(checks.email.configDetail)}</td></tr>
         |    <tr><th>smtp</th><td>${badge(checks.email.smtp)}${detailCell(checks.email.smtpDetail)}</td></tr>
         |  </table>
         |</body>
         |</html>""".stripMargin

    Ok(html).map(_.withContentType(`Content-Type`(MediaType.text.html, Charset.`UTF-8`)))
  }
}
