package code.api.util.flyway

import java.io.{File, PrintWriter}

import bootstrap.liftweb.ToSchemify
import net.liftweb.common.Empty
import net.liftweb.db.{DB, StandardDBVendor}
import net.liftweb.util.ConnectionIdentifier

/**
 * One-shot tool that exports the DDL Lift's Schemifier would execute against an
 * empty database, as a Flyway baseline migration (V001__initial_schema.sql).
 *
 * Schemifier remains the boot-time schema authority during the Mapper -> Doobie
 * migration; this export freezes its output so Flyway can take over as the schema
 * authority once the last Mapper entity is gone. This tool is deleted together
 * with Schemifier in the final teardown phase.
 *
 * Usage (H2 baseline, used by the test suite):
 *   mvn exec:java -pl obp-api -Dexec.mainClass=code.api.util.flyway.FlywayBaselineExport
 *
 * Usage (vendor-specific baseline, e.g. an EMPTY local PostgreSQL database):
 *   mvn exec:java -pl obp-api -Dexec.mainClass=code.api.util.flyway.FlywayBaselineExport \
 *     -Dexport.db.driver=org.postgresql.Driver \
 *     -Dexport.db.url=jdbc:postgresql://localhost:5432/obp_baseline_export \
 *     -Dexport.db.user=obp -Dexport.db.password=secret \
 *     -Dexport.vendor=postgresql
 *
 * The target database MUST be empty: Schemifier emits CREATE statements only for
 * objects that do not exist yet, so a non-empty database yields a partial baseline.
 */
object FlywayBaselineExport {

  private case object ExportConnectionIdentifier extends ConnectionIdentifier {
    val jndiName = "flyway_baseline_export"
  }

  def main(args: Array[String]): Unit = {
    val driver   = sys.props.getOrElse("export.db.driver", "org.h2.Driver")
    // NON_KEYWORDS=VALUE: OBP entities use `value` as a column name; without lifting it from
    // H2's reserved-word list, Schemifier's unquoted DDL fails (matches the runtime H2 URL in
    // code.api.constant.Constant.h2DatabaseDefaultUrlValue).
    val url      = sys.props.getOrElse("export.db.url", "jdbc:h2:mem:flyway_baseline_export;NON_KEYWORDS=VALUE;DB_CLOSE_DELAY=-1")
    val user     = sys.props.get("export.db.user")
    val password = sys.props.get("export.db.password")
    val vendorId = sys.props.getOrElse("export.vendor", "h2")

    val dbVendor = new StandardDBVendor(
      driver,
      url,
      user.map(net.liftweb.common.Full(_)).getOrElse(Empty),
      password.map(net.liftweb.common.Full(_)).getOrElse(Empty)
    )
    DB.defineConnectionManager(ExportConnectionIdentifier, dbVendor)

    // Build the schema into the (empty, throwaway) export database with performWrite = true,
    // then read the COMPLETE DDL back. Schemifier's own return value omits the index
    // statements it runs, so relying on it loses every unique/plain index — which the
    // concurrency contracts depend on. For H2 we therefore dump via the engine's SCRIPT
    // command (tables + primary keys + unique indexes + plain indexes). Non-H2 vendors fall
    // back to the Schemifier statement list (run this tool against a real empty instance of
    // that vendor, then hand-verify indexes).
    val isH2 = driver.toLowerCase.contains("h2")
    val ddl: List[String] =
      if (isH2) {
        net.liftweb.mapper.Schemifier.schemify(
          true, net.liftweb.mapper.Schemifier.infoF _, ExportConnectionIdentifier, ToSchemify.models: _*)
        dumpH2Schema(dbVendor)
      } else {
        net.liftweb.mapper.Schemifier.schemify(
          true, net.liftweb.mapper.Schemifier.infoF _, ExportConnectionIdentifier, ToSchemify.models: _*)
          .map(normalizeStatement)
      }

    val outDir = new File(s"obp-api/src/main/resources/db/migration/$vendorId")
    outDir.mkdirs()
    val outFile = new File(outDir, "V001__initial_schema.sql")
    val writer = new PrintWriter(outFile, "UTF-8")
    try {
      writer.println("-- Flyway baseline: schema as created by Lift Schemifier against an empty database.")
      writer.println(s"-- Generated by code.api.util.flyway.FlywayBaselineExport (vendor: $vendorId).")
      writer.println("-- Do not edit by hand while Schemifier is still active; regenerate instead.")
      writer.println()
      ddl.foreach { statement =>
        writer.println(statement + ";")
      }
    } finally {
      writer.close()
      dbVendor.closeAllConnections_!()
    }

    println(s"Wrote ${ddl.size} DDL statements to ${outFile.getPath}")
    // HikariCP / Lift keep non-daemon threads alive; exit explicitly so the build tool returns.
    sys.exit(0)
  }

  /**
   * Dump the full schema of the H2 export database via the engine's SCRIPT command.
   * Each result-set row is one complete, semicolon-terminated statement. We keep only
   * the schema-defining ones (tables, indexes, constraints, identity sequences) and drop
   * H2 housekeeping (SET, CREATE USER, GRANT, ...).
   */
  private def dumpH2Schema(dbVendor: StandardDBVendor): List[String] = {
    val conn = dbVendor.newConnection(ExportConnectionIdentifier)
      .openOrThrowException("FlywayBaselineExport: could not obtain export connection for SCRIPT dump")
    val stmt = conn.createStatement()
    try {
      val rs = stmt.executeQuery("SCRIPT NODATA NOSETTINGS")
      val buf = scala.collection.mutable.ListBuffer[String]()
      while (rs.next()) buf += rs.getString(1)
      rs.close()
      buf.toList
        .map(normalizeStatement)
        .map(canonicalizeTableKeyword)
        .filter(_.nonEmpty)
        .filter { s =>
          val u = s.toUpperCase
          u.startsWith("CREATE TABLE") || u.startsWith("CREATE INDEX") ||
          u.startsWith("CREATE UNIQUE INDEX") || u.startsWith("CREATE SEQUENCE") ||
          u.startsWith("ALTER TABLE")
        }
    } finally {
      stmt.close()
      conn.close()
    }
  }

  /** Trim a statement and strip a single trailing semicolon (re-added uniformly on write). */
  private def normalizeStatement(s: String): String = {
    val t = s.trim
    if (t.endsWith(";")) t.dropRight(1).trim else t
  }

  /** H2's SCRIPT emits CREATE MEMORY/CACHED TABLE; normalise to portable CREATE TABLE. */
  private def canonicalizeTableKeyword(s: String): String = {
    val u = s.toUpperCase
    if (u.startsWith("CREATE MEMORY TABLE")) "CREATE TABLE" + s.substring("CREATE MEMORY TABLE".length)
    else if (u.startsWith("CREATE CACHED TABLE")) "CREATE TABLE" + s.substring("CREATE CACHED TABLE".length)
    else s
  }
}
