package code.mandate

import java.text.SimpleDateFormat

import code.setup.ServerSetup

/**
 * Characterization test for the mandate store (mandate, provision, signatory panel).
 *
 * The three tables had no direct coverage and the v6.0.0 endpoints above them have none either,
 * so a storage swap could have changed behaviour with nothing to notice. Written against the Lift
 * Mapper implementation first and confirmed green there, so it pins existing behaviour rather than
 * describing the Doobie rewrite.
 *
 * What it pins:
 *   - the ids are GENERATED by the store, not supplied by the caller, and each is unique;
 *   - listings are ordered: mandates by most recently updated first, provisions by sortOrder
 *     ascending, panels by name ascending — the API returns these lists verbatim, so the order is
 *     part of the contract;
 *   - updateMandate stamps the row as updated, which is what moves it to the head of the listing;
 *   - lookups are scoped and do not leak across accounts or across parent mandates;
 *   - a miss is Empty rather than an exception or a Full(false).
 *
 * Uses only the provider interface, which both implementations share.
 */
class MandateProviderTest extends ServerSetup {

  private val provider = MappedMandateProvider

  private val fmt = new SimpleDateFormat("yyyy-MM-dd")
  private val validFrom = fmt.parse("2026-01-01")
  private val validTo = fmt.parse("2027-01-01")

  private def createMandate(bankId: String, accountId: String, name: String,
                            status: String = "ACTIVE"): MandateTrait =
    provider.createMandate(bankId, accountId, "customer-1", name, s"ref-$name",
      "legal text", "description", status, validFrom, validTo, "creator-user")
      .openOrThrowException(s"expected the mandate $name just created")

  private def createProvision(mandateId: String, name: String, sortOrder: Int,
                              isActive: Boolean = true): MandateProvisionTrait =
    provider.createMandateProvision(mandateId, name, "provision description", "legal ref",
      "SIGNATURE", "conditions", "requirements", "owner", "abac-rule-1", "SMS", isActive, sortOrder)
      .openOrThrowException(s"expected the provision $name just created")

  Feature("mandate storage") {

    Scenario("a created mandate round-trips under a generated id") {
      val created = createMandate("bank-roundtrip", "account-roundtrip", "Roundtrip")

      withClue("the mandate id is generated by the store, not supplied: ") {
        created.mandateId.nonEmpty should equal(true)
      }
      created.bankId should equal("bank-roundtrip")
      created.accountId should equal("account-roundtrip")
      created.customerId should equal("customer-1")
      created.mandateName should equal("Roundtrip")
      created.mandateReference should equal("ref-Roundtrip")
      created.legalText should equal("legal text")
      created.description should equal("description")
      created.status should equal("ACTIVE")
      created.validFrom.getTime should equal(validFrom.getTime)
      created.validTo.getTime should equal(validTo.getTime)
      created.createdByUserId should equal("creator-user")
      withClue("the creator is recorded as the last updater too: ") {
        created.updatedByUserId should equal("creator-user")
      }

      val fetched = provider.getMandateById(created.mandateId)
        .openOrThrowException("expected to read back the mandate just created")
      fetched.mandateName should equal("Roundtrip")
      withClue("a date read back from the store compares by instant, not by class — the store " +
        "returns a java.sql.Timestamp where the caller passed a java.util.Date: ") {
        fetched.validFrom.getTime should equal(validFrom.getTime)
      }
    }

    Scenario("generated mandate ids are unique") {
      val one = createMandate("bank-unique", "account-unique", "One")
      val two = createMandate("bank-unique", "account-unique", "Two")
      one.mandateId should not equal two.mandateId
    }

    Scenario("listing is scoped to one account and ordered most recently updated first") {
      val first = createMandate("bank-list", "account-list", "First")
      Thread.sleep(5)
      val second = createMandate("bank-list", "account-list", "Second")
      createMandate("bank-list", "account-other", "Other account")
      createMandate("bank-other", "account-list", "Other bank")

      val listed = provider.getMandatesByBankAndAccount("bank-list", "account-list")
        .openOrThrowException("expected the mandates of that account")

      listed.map(_.mandateName) should equal(List("Second", "First"))

      When("the older mandate is updated it moves to the head of the listing")
      Thread.sleep(5)
      provider.updateMandate(first.mandateId, "First updated", "ref-First", "legal text",
        "description", "ACTIVE", validFrom, validTo, "updater-user")
        .openOrThrowException("expected the update to succeed")

      provider.getMandatesByBankAndAccount("bank-list", "account-list")
        .openOrThrowException("expected the mandates of that account")
        .map(_.mandateName) should equal(List("First updated", "Second"))

      And("the second mandate is untouched")
      provider.getMandateById(second.mandateId)
        .openOrThrowException("expected the second mandate").mandateName should equal("Second")
    }

    Scenario("the active listing filters on status") {
      createMandate("bank-active", "account-active", "Live", status = "ACTIVE")
      createMandate("bank-active", "account-active", "Cancelled", status = "CANCELLED")

      provider.getActiveMandatesByBankAndAccount("bank-active", "account-active")
        .openOrThrowException("expected the active mandates")
        .map(_.mandateName) should equal(List("Live"))

      And("the unfiltered listing still shows both")
      provider.getMandatesByBankAndAccount("bank-active", "account-active")
        .openOrThrowException("expected every mandate").size should equal(2)
    }

    Scenario("an update rewrites the mutable fields and records who made it") {
      val created = createMandate("bank-update", "account-update", "Before")
      val newValidTo = fmt.parse("2030-06-30")

      val updated = provider.updateMandate(created.mandateId, "After", "ref-After", "new legal",
        "new description", "SUSPENDED", validFrom, newValidTo, "updater-user")
        .openOrThrowException("expected the update to succeed")

      updated.mandateId should equal(created.mandateId)
      updated.mandateName should equal("After")
      updated.mandateReference should equal("ref-After")
      updated.legalText should equal("new legal")
      updated.description should equal("new description")
      updated.status should equal("SUSPENDED")
      updated.validTo.getTime should equal(newValidTo.getTime)
      updated.updatedByUserId should equal("updater-user")
      withClue("the original creator is not overwritten by an update: ") {
        updated.createdByUserId should equal("creator-user")
      }
      withClue("the bank and account of a mandate are not touched by an update: ") {
        updated.bankId should equal("bank-update")
        updated.accountId should equal("account-update")
      }

      And("the change is visible to a fresh read")
      provider.getMandateById(created.mandateId)
        .openOrThrowException("expected the updated mandate").status should equal("SUSPENDED")
    }

    Scenario("a deleted mandate is gone, and a miss is Empty rather than a failure") {
      val created = createMandate("bank-delete", "account-delete", "Doomed")

      provider.deleteMandate(created.mandateId)
        .openOrThrowException("expected the delete to succeed") should equal(true)
      provider.getMandateById(created.mandateId).isDefined should equal(false)

      And("every operation on an id that does not exist is Empty")
      provider.getMandateById("no-such-mandate").isDefined should equal(false)
      provider.deleteMandate("no-such-mandate").isDefined should equal(false)
      provider.updateMandate("no-such-mandate", "n", "r", "l", "d", "ACTIVE", validFrom, validTo, "u")
        .isDefined should equal(false)

      And("the listing of an account that has none is empty rather than absent")
      provider.getMandatesByBankAndAccount("bank-delete", "account-delete")
        .openOrThrowException("expected an empty list") should equal(Nil)
    }
  }

  Feature("mandate provision storage") {

    Scenario("a created provision round-trips under a generated id") {
      val mandate = createMandate("bank-prov", "account-prov", "With provisions")
      val created = createProvision(mandate.mandateId, "Single signature", 1)

      created.provisionId.nonEmpty should equal(true)
      created.mandateId should equal(mandate.mandateId)
      created.provisionName should equal("Single signature")
      created.provisionDescription should equal("provision description")
      created.legalReference should equal("legal ref")
      created.provisionType should equal("SIGNATURE")
      created.conditions should equal("conditions")
      created.signatoryRequirements should equal("requirements")
      created.linkedViewId should equal("owner")
      created.linkedAbacRuleId should equal("abac-rule-1")
      created.linkedChallengeType should equal("SMS")
      created.isActive should equal(true)
      created.sortOrder should equal(1)

      provider.getMandateProvisionById(created.provisionId)
        .openOrThrowException("expected to read the provision back")
        .provisionName should equal("Single signature")
    }

    Scenario("provisions are scoped to their mandate and ordered by sortOrder ascending") {
      val mandate = createMandate("bank-prov-order", "account-prov-order", "Ordered")
      val other = createMandate("bank-prov-order", "account-prov-order", "Other")
      createProvision(mandate.mandateId, "Third", 30)
      createProvision(mandate.mandateId, "First", 10)
      createProvision(mandate.mandateId, "Second", 20)
      createProvision(other.mandateId, "Belongs elsewhere", 1)

      provider.getMandateProvisionsByMandateId(mandate.mandateId)
        .openOrThrowException("expected the provisions of that mandate")
        .map(_.provisionName) should equal(List("First", "Second", "Third"))
    }

    Scenario("an inactive provision is still stored and still listed") {
      val mandate = createMandate("bank-prov-inactive", "account-prov-inactive", "Has inactive")
      createProvision(mandate.mandateId, "Retired", 1, isActive = false)

      val listed = provider.getMandateProvisionsByMandateId(mandate.mandateId)
        .openOrThrowException("expected the provisions of that mandate")
      listed.size should equal(1)
      withClue("listing does not filter on isActive — the caller decides: ") {
        listed.head.isActive should equal(false)
      }
    }

    Scenario("an update rewrites the provision, and a miss is Empty") {
      val mandate = createMandate("bank-prov-update", "account-prov-update", "To update")
      val created = createProvision(mandate.mandateId, "Before", 1)

      val updated = provider.updateMandateProvision(created.provisionId, "After", "new description",
        "new ref", "PANEL", "new conditions", "new requirements", "accountant", "abac-rule-2",
        "EMAIL", isActive = false, sortOrder = 5)
        .openOrThrowException("expected the update to succeed")

      updated.provisionId should equal(created.provisionId)
      updated.provisionName should equal("After")
      updated.provisionType should equal("PANEL")
      updated.linkedChallengeType should equal("EMAIL")
      updated.isActive should equal(false)
      updated.sortOrder should equal(5)
      withClue("the parent mandate of a provision is not touched by an update: ") {
        updated.mandateId should equal(mandate.mandateId)
      }

      And("deleting it removes it, and every operation on an unknown id is Empty")
      provider.deleteMandateProvision(created.provisionId)
        .openOrThrowException("expected the delete to succeed") should equal(true)
      provider.getMandateProvisionById(created.provisionId).isDefined should equal(false)
      provider.deleteMandateProvision("no-such-provision").isDefined should equal(false)
      provider.updateMandateProvision("no-such-provision", "n", "d", "r", "T", "c", "s", "v", "a",
        "SMS", isActive = true, sortOrder = 0).isDefined should equal(false)
    }
  }

  Feature("signatory panel storage") {

    Scenario("a created panel round-trips under a generated id") {
      val mandate = createMandate("bank-panel", "account-panel", "With panel")
      val created = provider.createSignatoryPanel(mandate.mandateId, "Board", "The board",
        "user-1,user-2").openOrThrowException("expected the panel just created")

      created.panelId.nonEmpty should equal(true)
      created.mandateId should equal(mandate.mandateId)
      created.panelName should equal("Board")
      created.description should equal("The board")
      withClue("the member list is stored as the caller passed it, comma separated: ") {
        created.userIds should equal("user-1,user-2")
      }

      provider.getSignatoryPanelById(created.panelId)
        .openOrThrowException("expected to read the panel back").panelName should equal("Board")
    }

    Scenario("panels are scoped to their mandate and ordered by name ascending") {
      val mandate = createMandate("bank-panel-order", "account-panel-order", "Ordered panels")
      val other = createMandate("bank-panel-order", "account-panel-order", "Other")
      provider.createSignatoryPanel(mandate.mandateId, "Treasury", "", "user-1")
      provider.createSignatoryPanel(mandate.mandateId, "Auditors", "", "user-2")
      provider.createSignatoryPanel(other.mandateId, "Belongs elsewhere", "", "user-3")

      provider.getSignatoryPanelsByMandateId(mandate.mandateId)
        .openOrThrowException("expected the panels of that mandate")
        .map(_.panelName) should equal(List("Auditors", "Treasury"))
    }

    Scenario("an update rewrites the panel, and a miss is Empty") {
      val mandate = createMandate("bank-panel-update", "account-panel-update", "To update")
      val created = provider.createSignatoryPanel(mandate.mandateId, "Before", "old", "user-1")
        .openOrThrowException("expected the panel just created")

      val updated = provider.updateSignatoryPanel(created.panelId, "After", "new", "user-2,user-3")
        .openOrThrowException("expected the update to succeed")

      updated.panelId should equal(created.panelId)
      updated.panelName should equal("After")
      updated.description should equal("new")
      updated.userIds should equal("user-2,user-3")
      withClue("the parent mandate of a panel is not touched by an update: ") {
        updated.mandateId should equal(mandate.mandateId)
      }

      And("deleting it removes it, and every operation on an unknown id is Empty")
      provider.deleteSignatoryPanel(created.panelId)
        .openOrThrowException("expected the delete to succeed") should equal(true)
      provider.getSignatoryPanelById(created.panelId).isDefined should equal(false)
      provider.deleteSignatoryPanel("no-such-panel").isDefined should equal(false)
      provider.updateSignatoryPanel("no-such-panel", "n", "d", "u").isDefined should equal(false)
    }
  }
}
