// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package code.obp.grpc.chat.api

@SerialVersionUID(0L)
final case class ChatMessageEvent(
    eventType: _root_.scala.Predef.String = "",
    chatMessageId: _root_.scala.Predef.String = "",
    chatRoomId: _root_.scala.Predef.String = "",
    senderUserId: _root_.scala.Predef.String = "",
    senderConsumerId: _root_.scala.Predef.String = "",
    senderUsername: _root_.scala.Predef.String = "",
    senderProvider: _root_.scala.Predef.String = "",
    senderConsumerName: _root_.scala.Predef.String = "",
    content: _root_.scala.Predef.String = "",
    messageType: _root_.scala.Predef.String = "",
    mentionedUserIds: _root_.scala.Seq[_root_.scala.Predef.String] = _root_.scala.Seq.empty,
    replyToMessageId: _root_.scala.Predef.String = "",
    threadId: _root_.scala.Predef.String = "",
    isDeleted: _root_.scala.Boolean = false,
    createdAt: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp] = _root_.scala.None,
    updatedAt: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp] = _root_.scala.None
    ) extends scalapb.GeneratedMessage with scalapb.Message[ChatMessageEvent] with scalapb.lenses.Updatable[ChatMessageEvent] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      if (eventType != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, eventType) }
      if (chatMessageId != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, chatMessageId) }
      if (chatRoomId != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, chatRoomId) }
      if (senderUserId != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, senderUserId) }
      if (senderConsumerId != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(5, senderConsumerId) }
      if (senderUsername != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(6, senderUsername) }
      if (senderProvider != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(7, senderProvider) }
      if (senderConsumerName != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(8, senderConsumerName) }
      if (content != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(9, content) }
      if (messageType != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(10, messageType) }
      mentionedUserIds.foreach { __item =>
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(11, __item)
      }
      if (replyToMessageId != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(12, replyToMessageId) }
      if (threadId != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(13, threadId) }
      if (isDeleted != false) { __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(14, isDeleted) }
      if (createdAt.isDefined) {
        val __v = createdAt.get
        val __s = __v.serializedSize
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__s) + __s
      }
      if (updatedAt.isDefined) {
        val __v = updatedAt.get
        val __s = __v.serializedSize
        __size += 2 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__s) + __s
      }
      __size
    }
    final override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = eventType
        if (__v != "") {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = chatMessageId
        if (__v != "") {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = chatRoomId
        if (__v != "") {
          _output__.writeString(3, __v)
        }
      };
      {
        val __v = senderUserId
        if (__v != "") {
          _output__.writeString(4, __v)
        }
      };
      {
        val __v = senderConsumerId
        if (__v != "") {
          _output__.writeString(5, __v)
        }
      };
      {
        val __v = senderUsername
        if (__v != "") {
          _output__.writeString(6, __v)
        }
      };
      {
        val __v = senderProvider
        if (__v != "") {
          _output__.writeString(7, __v)
        }
      };
      {
        val __v = senderConsumerName
        if (__v != "") {
          _output__.writeString(8, __v)
        }
      };
      {
        val __v = content
        if (__v != "") {
          _output__.writeString(9, __v)
        }
      };
      {
        val __v = messageType
        if (__v != "") {
          _output__.writeString(10, __v)
        }
      };
      mentionedUserIds.foreach { __v =>
        _output__.writeString(11, __v)
      };
      {
        val __v = replyToMessageId
        if (__v != "") {
          _output__.writeString(12, __v)
        }
      };
      {
        val __v = threadId
        if (__v != "") {
          _output__.writeString(13, __v)
        }
      };
      {
        val __v = isDeleted
        if (__v != false) {
          _output__.writeBool(14, __v)
        }
      };
      createdAt.foreach { __v =>
        _output__.writeTag(15, 2)
        _output__.writeUInt32NoTag(__v.serializedSize)
        __v.writeTo(_output__)
      };
      updatedAt.foreach { __v =>
        _output__.writeTag(16, 2)
        _output__.writeUInt32NoTag(__v.serializedSize)
        __v.writeTo(_output__)
      };
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): code.obp.grpc.chat.api.ChatMessageEvent = {
      var __eventType = this.eventType
      var __chatMessageId = this.chatMessageId
      var __chatRoomId = this.chatRoomId
      var __senderUserId = this.senderUserId
      var __senderConsumerId = this.senderConsumerId
      var __senderUsername = this.senderUsername
      var __senderProvider = this.senderProvider
      var __senderConsumerName = this.senderConsumerName
      var __content = this.content
      var __messageType = this.messageType
      val __mentionedUserIds = (_root_.scala.collection.immutable.Vector.newBuilder[_root_.scala.Predef.String] ++= this.mentionedUserIds)
      var __replyToMessageId = this.replyToMessageId
      var __threadId = this.threadId
      var __isDeleted = this.isDeleted
      var __createdAt = this.createdAt
      var __updatedAt = this.updatedAt
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __eventType = _input__.readString()
          case 18 =>
            __chatMessageId = _input__.readString()
          case 26 =>
            __chatRoomId = _input__.readString()
          case 34 =>
            __senderUserId = _input__.readString()
          case 42 =>
            __senderConsumerId = _input__.readString()
          case 50 =>
            __senderUsername = _input__.readString()
          case 58 =>
            __senderProvider = _input__.readString()
          case 66 =>
            __senderConsumerName = _input__.readString()
          case 74 =>
            __content = _input__.readString()
          case 82 =>
            __messageType = _input__.readString()
          case 90 =>
            __mentionedUserIds += _input__.readString()
          case 98 =>
            __replyToMessageId = _input__.readString()
          case 106 =>
            __threadId = _input__.readString()
          case 112 =>
            __isDeleted = _input__.readBool()
          case 122 =>
            __createdAt = _root_.scala.Option(_root_.scalapb.LiteParser.readMessage(_input__, __createdAt.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)))
          case 130 =>
            __updatedAt = _root_.scala.Option(_root_.scalapb.LiteParser.readMessage(_input__, __updatedAt.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)))
          case tag => _input__.skipField(tag)
        }
      }
      code.obp.grpc.chat.api.ChatMessageEvent(
          eventType = __eventType,
          chatMessageId = __chatMessageId,
          chatRoomId = __chatRoomId,
          senderUserId = __senderUserId,
          senderConsumerId = __senderConsumerId,
          senderUsername = __senderUsername,
          senderProvider = __senderProvider,
          senderConsumerName = __senderConsumerName,
          content = __content,
          messageType = __messageType,
          mentionedUserIds = __mentionedUserIds.result(),
          replyToMessageId = __replyToMessageId,
          threadId = __threadId,
          isDeleted = __isDeleted,
          createdAt = __createdAt,
          updatedAt = __updatedAt
      )
    }
    def getCreatedAt: com.google.protobuf.timestamp.Timestamp = createdAt.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)
    def getUpdatedAt: com.google.protobuf.timestamp.Timestamp = updatedAt.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)
    def withEventType(__v: _root_.scala.Predef.String): ChatMessageEvent = copy(eventType = __v)
    def withChatMessageId(__v: _root_.scala.Predef.String): ChatMessageEvent = copy(chatMessageId = __v)
    def withChatRoomId(__v: _root_.scala.Predef.String): ChatMessageEvent = copy(chatRoomId = __v)
    def withSenderUserId(__v: _root_.scala.Predef.String): ChatMessageEvent = copy(senderUserId = __v)
    def withSenderConsumerId(__v: _root_.scala.Predef.String): ChatMessageEvent = copy(senderConsumerId = __v)
    def withSenderUsername(__v: _root_.scala.Predef.String): ChatMessageEvent = copy(senderUsername = __v)
    def withSenderProvider(__v: _root_.scala.Predef.String): ChatMessageEvent = copy(senderProvider = __v)
    def withSenderConsumerName(__v: _root_.scala.Predef.String): ChatMessageEvent = copy(senderConsumerName = __v)
    def withContent(__v: _root_.scala.Predef.String): ChatMessageEvent = copy(content = __v)
    def withMessageType(__v: _root_.scala.Predef.String): ChatMessageEvent = copy(messageType = __v)
    def withMentionedUserIds(__v: _root_.scala.Seq[_root_.scala.Predef.String]): ChatMessageEvent = copy(mentionedUserIds = __v)
    def addMentionedUserIds(__vs: _root_.scala.Predef.String*): ChatMessageEvent = addAllMentionedUserIds(__vs)
    def addAllMentionedUserIds(__vs: _root_.scala.Iterable[_root_.scala.Predef.String]): ChatMessageEvent = copy(mentionedUserIds = mentionedUserIds ++ __vs)
    def withReplyToMessageId(__v: _root_.scala.Predef.String): ChatMessageEvent = copy(replyToMessageId = __v)
    def withThreadId(__v: _root_.scala.Predef.String): ChatMessageEvent = copy(threadId = __v)
    def withIsDeleted(__v: _root_.scala.Boolean): ChatMessageEvent = copy(isDeleted = __v)
    def clearCreatedAt: ChatMessageEvent = copy(createdAt = _root_.scala.None)
    def withCreatedAt(__v: com.google.protobuf.timestamp.Timestamp): ChatMessageEvent = copy(createdAt = _root_.scala.Option(__v))
    def clearUpdatedAt: ChatMessageEvent = copy(updatedAt = _root_.scala.None)
    def withUpdatedAt(__v: com.google.protobuf.timestamp.Timestamp): ChatMessageEvent = copy(updatedAt = _root_.scala.Option(__v))
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = eventType
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = chatMessageId
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = chatRoomId
          if (__t != "") __t else null
        }
        case 4 => {
          val __t = senderUserId
          if (__t != "") __t else null
        }
        case 5 => {
          val __t = senderConsumerId
          if (__t != "") __t else null
        }
        case 6 => {
          val __t = senderUsername
          if (__t != "") __t else null
        }
        case 7 => {
          val __t = senderProvider
          if (__t != "") __t else null
        }
        case 8 => {
          val __t = senderConsumerName
          if (__t != "") __t else null
        }
        case 9 => {
          val __t = content
          if (__t != "") __t else null
        }
        case 10 => {
          val __t = messageType
          if (__t != "") __t else null
        }
        case 11 => mentionedUserIds
        case 12 => {
          val __t = replyToMessageId
          if (__t != "") __t else null
        }
        case 13 => {
          val __t = threadId
          if (__t != "") __t else null
        }
        case 14 => {
          val __t = isDeleted
          if (__t != false) __t else null
        }
        case 15 => createdAt.orNull
        case 16 => updatedAt.orNull
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(eventType)
        case 2 => _root_.scalapb.descriptors.PString(chatMessageId)
        case 3 => _root_.scalapb.descriptors.PString(chatRoomId)
        case 4 => _root_.scalapb.descriptors.PString(senderUserId)
        case 5 => _root_.scalapb.descriptors.PString(senderConsumerId)
        case 6 => _root_.scalapb.descriptors.PString(senderUsername)
        case 7 => _root_.scalapb.descriptors.PString(senderProvider)
        case 8 => _root_.scalapb.descriptors.PString(senderConsumerName)
        case 9 => _root_.scalapb.descriptors.PString(content)
        case 10 => _root_.scalapb.descriptors.PString(messageType)
        case 11 => _root_.scalapb.descriptors.PRepeated(mentionedUserIds.iterator.map(_root_.scalapb.descriptors.PString).toVector)
        case 12 => _root_.scalapb.descriptors.PString(replyToMessageId)
        case 13 => _root_.scalapb.descriptors.PString(threadId)
        case 14 => _root_.scalapb.descriptors.PBoolean(isDeleted)
        case 15 => createdAt.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 16 => updatedAt.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = code.obp.grpc.chat.api.ChatMessageEvent
}

object ChatMessageEvent extends scalapb.GeneratedMessageCompanion[code.obp.grpc.chat.api.ChatMessageEvent] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[code.obp.grpc.chat.api.ChatMessageEvent] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): code.obp.grpc.chat.api.ChatMessageEvent = {
    require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
    val __fields = javaDescriptor.getFields
    code.obp.grpc.chat.api.ChatMessageEvent(
      __fieldsMap.getOrElse(__fields.get(0), "").asInstanceOf[_root_.scala.Predef.String],
      __fieldsMap.getOrElse(__fields.get(1), "").asInstanceOf[_root_.scala.Predef.String],
      __fieldsMap.getOrElse(__fields.get(2), "").asInstanceOf[_root_.scala.Predef.String],
      __fieldsMap.getOrElse(__fields.get(3), "").asInstanceOf[_root_.scala.Predef.String],
      __fieldsMap.getOrElse(__fields.get(4), "").asInstanceOf[_root_.scala.Predef.String],
      __fieldsMap.getOrElse(__fields.get(5), "").asInstanceOf[_root_.scala.Predef.String],
      __fieldsMap.getOrElse(__fields.get(6), "").asInstanceOf[_root_.scala.Predef.String],
      __fieldsMap.getOrElse(__fields.get(7), "").asInstanceOf[_root_.scala.Predef.String],
      __fieldsMap.getOrElse(__fields.get(8), "").asInstanceOf[_root_.scala.Predef.String],
      __fieldsMap.getOrElse(__fields.get(9), "").asInstanceOf[_root_.scala.Predef.String],
      __fieldsMap.getOrElse(__fields.get(10), Nil).asInstanceOf[_root_.scala.Seq[_root_.scala.Predef.String]],
      __fieldsMap.getOrElse(__fields.get(11), "").asInstanceOf[_root_.scala.Predef.String],
      __fieldsMap.getOrElse(__fields.get(12), "").asInstanceOf[_root_.scala.Predef.String],
      __fieldsMap.getOrElse(__fields.get(13), false).asInstanceOf[_root_.scala.Boolean],
      __fieldsMap.get(__fields.get(14)).asInstanceOf[_root_.scala.Option[com.google.protobuf.timestamp.Timestamp]],
      __fieldsMap.get(__fields.get(15)).asInstanceOf[_root_.scala.Option[com.google.protobuf.timestamp.Timestamp]]
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[code.obp.grpc.chat.api.ChatMessageEvent] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      code.obp.grpc.chat.api.ChatMessageEvent(
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(7).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(8).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(9).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(10).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(11).get).map(_.as[_root_.scala.Seq[_root_.scala.Predef.String]]).getOrElse(_root_.scala.Seq.empty),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(12).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(13).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(14).get).map(_.as[_root_.scala.Boolean]).getOrElse(false),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(15).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.timestamp.Timestamp]]),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(16).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.timestamp.Timestamp]])
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = ChatProto.javaDescriptor.getMessageTypes.get(1)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = throw new UnsupportedOperationException("scalaDescriptor not available")
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    (__number: @_root_.scala.unchecked) match {
      case 15 => com.google.protobuf.timestamp.Timestamp
      case 16 => com.google.protobuf.timestamp.Timestamp
    }
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = code.obp.grpc.chat.api.ChatMessageEvent(
  )
  implicit class ChatMessageEventLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, code.obp.grpc.chat.api.ChatMessageEvent]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, code.obp.grpc.chat.api.ChatMessageEvent](_l) {
    def eventType: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.eventType)((c_, f_) => c_.copy(eventType = f_))
    def chatMessageId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.chatMessageId)((c_, f_) => c_.copy(chatMessageId = f_))
    def chatRoomId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.chatRoomId)((c_, f_) => c_.copy(chatRoomId = f_))
    def senderUserId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.senderUserId)((c_, f_) => c_.copy(senderUserId = f_))
    def senderConsumerId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.senderConsumerId)((c_, f_) => c_.copy(senderConsumerId = f_))
    def senderUsername: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.senderUsername)((c_, f_) => c_.copy(senderUsername = f_))
    def senderProvider: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.senderProvider)((c_, f_) => c_.copy(senderProvider = f_))
    def senderConsumerName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.senderConsumerName)((c_, f_) => c_.copy(senderConsumerName = f_))
    def content: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.content)((c_, f_) => c_.copy(content = f_))
    def messageType: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.messageType)((c_, f_) => c_.copy(messageType = f_))
    def mentionedUserIds: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[_root_.scala.Predef.String]] = field(_.mentionedUserIds)((c_, f_) => c_.copy(mentionedUserIds = f_))
    def replyToMessageId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.replyToMessageId)((c_, f_) => c_.copy(replyToMessageId = f_))
    def threadId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.threadId)((c_, f_) => c_.copy(threadId = f_))
    def isDeleted: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.isDeleted)((c_, f_) => c_.copy(isDeleted = f_))
    def createdAt: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.timestamp.Timestamp] = field(_.getCreatedAt)((c_, f_) => c_.copy(createdAt = _root_.scala.Option(f_)))
    def optionalCreatedAt: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.google.protobuf.timestamp.Timestamp]] = field(_.createdAt)((c_, f_) => c_.copy(createdAt = f_))
    def updatedAt: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.timestamp.Timestamp] = field(_.getUpdatedAt)((c_, f_) => c_.copy(updatedAt = _root_.scala.Option(f_)))
    def optionalUpdatedAt: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.google.protobuf.timestamp.Timestamp]] = field(_.updatedAt)((c_, f_) => c_.copy(updatedAt = f_))
  }
  final val EVENTTYPE_FIELD_NUMBER = 1
  final val CHATMESSAGEID_FIELD_NUMBER = 2
  final val CHATROOMID_FIELD_NUMBER = 3
  final val SENDERUSERID_FIELD_NUMBER = 4
  final val SENDERCONSUMERID_FIELD_NUMBER = 5
  final val SENDERUSERNAME_FIELD_NUMBER = 6
  final val SENDERPROVIDER_FIELD_NUMBER = 7
  final val SENDERCONSUMERNAME_FIELD_NUMBER = 8
  final val CONTENT_FIELD_NUMBER = 9
  final val MESSAGETYPE_FIELD_NUMBER = 10
  final val MENTIONEDUSERIDS_FIELD_NUMBER = 11
  final val REPLYTOMESSAGEID_FIELD_NUMBER = 12
  final val THREADID_FIELD_NUMBER = 13
  final val ISDELETED_FIELD_NUMBER = 14
  final val CREATEDAT_FIELD_NUMBER = 15
  final val UPDATEDAT_FIELD_NUMBER = 16
}
