// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package code.obp.grpc.chat.api

@SerialVersionUID(0L)
final case class TypingIndicator(
    chatRoomId: _root_.scala.Predef.String = "",
    userId: _root_.scala.Predef.String = "",
    username: _root_.scala.Predef.String = "",
    provider: _root_.scala.Predef.String = "",
    isTyping: _root_.scala.Boolean = false
    ) extends scalapb.GeneratedMessage with scalapb.Message[TypingIndicator] with scalapb.lenses.Updatable[TypingIndicator] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      if (chatRoomId != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, chatRoomId) }
      if (userId != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, userId) }
      if (username != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, username) }
      if (provider != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, provider) }
      if (isTyping != false) { __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(5, isTyping) }
      __size
    }
    final override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = chatRoomId
        if (__v != "") {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = userId
        if (__v != "") {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = username
        if (__v != "") {
          _output__.writeString(3, __v)
        }
      };
      {
        val __v = provider
        if (__v != "") {
          _output__.writeString(4, __v)
        }
      };
      {
        val __v = isTyping
        if (__v != false) {
          _output__.writeBool(5, __v)
        }
      };
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): code.obp.grpc.chat.api.TypingIndicator = {
      var __chatRoomId = this.chatRoomId
      var __userId = this.userId
      var __username = this.username
      var __provider = this.provider
      var __isTyping = this.isTyping
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __chatRoomId = _input__.readString()
          case 18 =>
            __userId = _input__.readString()
          case 26 =>
            __username = _input__.readString()
          case 34 =>
            __provider = _input__.readString()
          case 40 =>
            __isTyping = _input__.readBool()
          case tag => _input__.skipField(tag)
        }
      }
      code.obp.grpc.chat.api.TypingIndicator(
          chatRoomId = __chatRoomId,
          userId = __userId,
          username = __username,
          provider = __provider,
          isTyping = __isTyping
      )
    }
    def withChatRoomId(__v: _root_.scala.Predef.String): TypingIndicator = copy(chatRoomId = __v)
    def withUserId(__v: _root_.scala.Predef.String): TypingIndicator = copy(userId = __v)
    def withUsername(__v: _root_.scala.Predef.String): TypingIndicator = copy(username = __v)
    def withProvider(__v: _root_.scala.Predef.String): TypingIndicator = copy(provider = __v)
    def withIsTyping(__v: _root_.scala.Boolean): TypingIndicator = copy(isTyping = __v)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = chatRoomId
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = userId
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = username
          if (__t != "") __t else null
        }
        case 4 => {
          val __t = provider
          if (__t != "") __t else null
        }
        case 5 => {
          val __t = isTyping
          if (__t != false) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(chatRoomId)
        case 2 => _root_.scalapb.descriptors.PString(userId)
        case 3 => _root_.scalapb.descriptors.PString(username)
        case 4 => _root_.scalapb.descriptors.PString(provider)
        case 5 => _root_.scalapb.descriptors.PBoolean(isTyping)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = code.obp.grpc.chat.api.TypingIndicator
}

object TypingIndicator extends scalapb.GeneratedMessageCompanion[code.obp.grpc.chat.api.TypingIndicator] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[code.obp.grpc.chat.api.TypingIndicator] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): code.obp.grpc.chat.api.TypingIndicator = {
    require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
    val __fields = javaDescriptor.getFields
    code.obp.grpc.chat.api.TypingIndicator(
      __fieldsMap.getOrElse(__fields.get(0), "").asInstanceOf[_root_.scala.Predef.String],
      __fieldsMap.getOrElse(__fields.get(1), "").asInstanceOf[_root_.scala.Predef.String],
      __fieldsMap.getOrElse(__fields.get(2), "").asInstanceOf[_root_.scala.Predef.String],
      __fieldsMap.getOrElse(__fields.get(3), "").asInstanceOf[_root_.scala.Predef.String],
      __fieldsMap.getOrElse(__fields.get(4), false).asInstanceOf[_root_.scala.Boolean]
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[code.obp.grpc.chat.api.TypingIndicator] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      code.obp.grpc.chat.api.TypingIndicator(
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scala.Boolean]).getOrElse(false)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = ChatProto.javaDescriptor.getMessageTypes.get(3)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = throw new UnsupportedOperationException("scalaDescriptor not available")
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = code.obp.grpc.chat.api.TypingIndicator(
  )
  implicit class TypingIndicatorLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, code.obp.grpc.chat.api.TypingIndicator]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, code.obp.grpc.chat.api.TypingIndicator](_l) {
    def chatRoomId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.chatRoomId)((c_, f_) => c_.copy(chatRoomId = f_))
    def userId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.userId)((c_, f_) => c_.copy(userId = f_))
    def username: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.username)((c_, f_) => c_.copy(username = f_))
    def provider: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.provider)((c_, f_) => c_.copy(provider = f_))
    def isTyping: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.isTyping)((c_, f_) => c_.copy(isTyping = f_))
  }
  final val CHATROOMID_FIELD_NUMBER = 1
  final val USERID_FIELD_NUMBER = 2
  final val USERNAME_FIELD_NUMBER = 3
  final val PROVIDER_FIELD_NUMBER = 4
  final val ISTYPING_FIELD_NUMBER = 5
}
