// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package code.obp.grpc.chat.api

@SerialVersionUID(0L)
final case class TypingEvent(
    chatRoomId: _root_.scala.Predef.String = "",
    isTyping: _root_.scala.Boolean = false,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[TypingEvent] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = chatRoomId
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = isTyping
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(2, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = chatRoomId
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = isTyping
        if (__v != false) {
          _output__.writeBool(2, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withChatRoomId(__v: _root_.scala.Predef.String): TypingEvent = copy(chatRoomId = __v)
    def withIsTyping(__v: _root_.scala.Boolean): TypingEvent = copy(isTyping = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = chatRoomId
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = isTyping
          if (__t != false) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(chatRoomId)
        case 2 => _root_.scalapb.descriptors.PBoolean(isTyping)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: code.obp.grpc.chat.api.TypingEvent.type = code.obp.grpc.chat.api.TypingEvent
    // @@protoc_insertion_point(GeneratedMessage[code.obp.grpc.chat.g1.TypingEvent])
}

object TypingEvent extends scalapb.GeneratedMessageCompanion[code.obp.grpc.chat.api.TypingEvent] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[code.obp.grpc.chat.api.TypingEvent] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): code.obp.grpc.chat.api.TypingEvent = {
    var __chatRoomId: _root_.scala.Predef.String = ""
    var __isTyping: _root_.scala.Boolean = false
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __chatRoomId = _input__.readStringRequireUtf8()
        case 16 =>
          __isTyping = _input__.readBool()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    code.obp.grpc.chat.api.TypingEvent(
        chatRoomId = __chatRoomId,
        isTyping = __isTyping,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[code.obp.grpc.chat.api.TypingEvent] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      code.obp.grpc.chat.api.TypingEvent(
        chatRoomId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        isTyping = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Boolean]).getOrElse(false)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = ChatProto.javaDescriptor.getMessageTypes().get(2)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ChatProto.scalaDescriptor.messages(2)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = code.obp.grpc.chat.api.TypingEvent(
    chatRoomId = "",
    isTyping = false
  )
  implicit class TypingEventLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, code.obp.grpc.chat.api.TypingEvent]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, code.obp.grpc.chat.api.TypingEvent](_l) {
    def chatRoomId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.chatRoomId)((c_, f_) => c_.copy(chatRoomId = f_))
    def isTyping: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.isTyping)((c_, f_) => c_.copy(isTyping = f_))
  }
  final val CHAT_ROOM_ID_FIELD_NUMBER = 1
  final val IS_TYPING_FIELD_NUMBER = 2
  def of(
    chatRoomId: _root_.scala.Predef.String,
    isTyping: _root_.scala.Boolean
  ): _root_.code.obp.grpc.chat.api.TypingEvent = _root_.code.obp.grpc.chat.api.TypingEvent(
    chatRoomId,
    isTyping
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[code.obp.grpc.chat.g1.TypingEvent])
}
