-- Narrative table, second table off Lift Mapper.
-- DDL captured from FlywayBaselineExport (Schemifier's own output for the entity as it
-- stood when it was deleted), narrowed to this table. Note TRANSACTION_C: Lift escapes
-- the SQL reserved word TRANSACTION with a _c suffix.

CREATE TABLE "PUBLIC"."MAPPEDNARRATIVE"(
    "CREATEDAT" TIMESTAMP,
    "TRANSACTION_C" CHARACTER VARYING(44),
    "BANK" CHARACTER VARYING(44),
    "UPDATEDAT" TIMESTAMP,
    "NARRATIVE" CHARACTER VARYING(2000),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "ACCOUNT" CHARACTER VARYING(64)
);
ALTER TABLE "PUBLIC"."MAPPEDNARRATIVE" ADD CONSTRAINT "PUBLIC"."MAPPEDNARRATIVE_PK" PRIMARY KEY("ID");
