-- Product tag table, seventh table off Lift Mapper.
-- Table and plain index are Schemifier's own output (FlywayBaselineExport), narrowed here.
--
-- The UNIQUE index is added by hand because the export does not carry it: the entity
-- declared UniqueIndex(BankId, ProductCode, Tag) via dbIndexes, and only the plain
-- Index(BankId, ProductCode) survived the dump. It is not decoration - ProductTagsProvider
-- diffs desired against stored tags instead of truncating, and that is only race-free at
-- row level if the database refuses a duplicate (bank, product, tag).

CREATE TABLE "PUBLIC"."PRODUCTTAG"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "TAG" CHARACTER VARYING(100),
    "PRODUCTCODE" CHARACTER VARYING(50),
    "BANKID" CHARACTER VARYING(44)
);
ALTER TABLE "PUBLIC"."PRODUCTTAG" ADD CONSTRAINT "PUBLIC"."PRODUCTTAG_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."PRODUCTTAG_BANKID_PRODUCTCODE" ON "PUBLIC"."PRODUCTTAG"("BANKID" NULLS FIRST, "PRODUCTCODE" NULLS FIRST);
CREATE UNIQUE INDEX "PUBLIC"."PRODUCTTAG_BANKID_PRODUCTCODE_TAG" ON "PUBLIC"."PRODUCTTAG"("BANKID" NULLS FIRST, "PRODUCTCODE" NULLS FIRST, "TAG" NULLS FIRST);
