-- Consent item table, ninth table off Lift Mapper.
-- The entity had no provider and no call sites at all: every access to this table is raw
-- SQL (DoobieConsentQueries, MappedConsent, the v5.1.0 endpoints, the reference-id
-- migration). It existed only so Schemifier would create the table, which is now Flyway's
-- job. Table and column names are snake_case via dbTableName/dbColumnName overrides.

CREATE TABLE "PUBLIC"."CONSENT_ITEM"(
    "CONSENT_ITEM_ID" CHARACTER VARYING(36),
    "ACCOUNT_ID" CHARACTER VARYING(255),
    "BANK_ID" CHARACTER VARYING(255),
    "CONSENT_REFERENCE_ID" CHARACTER VARYING(36),
    "ROLE_NAME" CHARACTER VARYING(255),
    "VIEW_ID" CHARACTER VARYING(255),
    "ITEM_TYPE" CHARACTER VARYING(64),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."CONSENT_ITEM" ADD CONSTRAINT "PUBLIC"."CONSENT_ITEM_PK" PRIMARY KEY("ID");
