-- JSON schema validation table, tenth table off Lift Mapper.
-- DDL from FlywayBaselineExport (Schemifier's own output), narrowed to this table.
--
-- The UNIQUE index is added by hand: the entity declared UniqueIndex(OperationId) through
-- dbIndexes and the export does not carry dbIndexes-declared unique indexes (same gap as
-- producttag). It is load-bearing - getByOperationId and update both assume one row per
-- operation id, and update's find-then-write would otherwise race into duplicates.

CREATE TABLE "PUBLIC"."JSONSCHEMAVALIDATION"(
    "JSONSCHEMA" CHARACTER VARYING,
    "OPERATIONID" CHARACTER VARYING(200),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."JSONSCHEMAVALIDATION" ADD CONSTRAINT "PUBLIC"."JSONSCHEMAVALIDATION_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."JSONSCHEMAVALIDATION_OPERATIONID" ON "PUBLIC"."JSONSCHEMAVALIDATION"("OPERATIONID" NULLS FIRST);
