-- ETag table, thirteenth table off Lift Mapper.
-- Table name is ETag, not MappedETag: the entity overrode dbTableName.
-- Columns from FlywayBaselineExport (Schemifier's own output), narrowed to this table.
--
-- The unique index is added by hand and is not optional. FlywayBaselineExport does not emit
-- dbIndexes-declared unique indexes; the database has this one, confirmed by reading
-- information_schema.indexes on a normally booted instance:
--   ETAG / ETAG_ETAGRESOURCE / UNIQUE INDEX
-- Dropping it would let checkIfModifiedSinceHeader accumulate several rows per cache key,
-- since it looks the key up and inserts when absent, with no other guard.

CREATE TABLE "PUBLIC"."ETAG"(
    "ETAGRESOURCE" CHARACTER VARYING(1000),
    "ETAGVALUE" CHARACTER VARYING(256),
    "LASTUPDATEDMSSINCEEPOCH" BIGINT,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."ETAG" ADD CONSTRAINT "PUBLIC"."ETAG_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."ETAG_ETAGRESOURCE" ON "PUBLIC"."ETAG"("ETAGRESOURCE" NULLS FIRST);
