-- User locks table, fifteenth table off Lift Mapper.
-- Columns match Schemifier's own output; UserId is a MappedUUID, hence VARCHAR(36).
--
-- The unique index is added by hand and is required. FlywayBaselineExport does not emit
-- dbIndexes-declared unique indexes even though Schemifier creates them; read from a booted
-- instance, information_schema.indexes reports:
--   USERLOCKS / USERLOCKS_USERID / UNIQUE INDEX
-- lockUser looks the user up and inserts when absent, so one row per user is the whole
-- contract: a duplicate would make isLocked and unlockUser disagree about which row counts.

CREATE TABLE "PUBLIC"."USERLOCKS"(
    "USERID" CHARACTER VARYING(36),
    "LASTLOCKDATE" TIMESTAMP,
    "TYPEOFLOCK" CHARACTER VARYING(100),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."USERLOCKS" ADD CONSTRAINT "PUBLIC"."USERLOCKS_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."USERLOCKS_USERID" ON "PUBLIC"."USERLOCKS"("USERID" NULLS FIRST);
