-- User auth context table, twentieth table off Lift Mapper. Table name stays
-- mappeduserauthcontext (the entity did not override dbTableName).
--
-- mKey/mValue are 4000 chars: that width itself was a historical migration
-- (MigrationOfUserAuthContextFieldLength), already applied everywhere; Flyway creates it at
-- that width directly, so there is nothing left for that migration to widen on a fresh instance.
--
-- The unique index is added by hand and does exist. FlywayBaselineExport does not emit
-- dbIndexes-declared unique indexes even though Schemifier creates them; read from a booted
-- instance, information_schema.indexes reports:
--   MAPPEDUSERAUTHCONTEXT / MAPPEDUSERAUTHCONTEXT_MUSERID_MKEY_CREATEDAT / UNIQUE INDEX
-- Same shape as consent_auth_context: createdAt is part of the key, so two writes for the same
-- (userId, key) inside one millisecond collide, and everything else about "duplicates" is
-- intentional - see createUserAuthContext's callers.

CREATE TABLE "PUBLIC"."MAPPEDUSERAUTHCONTEXT"(
    "MUSERID" CHARACTER VARYING(44),
    "MCONSUMERID" CHARACTER VARYING(255),
    "MVALUE" CHARACTER VARYING(4000),
    "UPDATEDAT" TIMESTAMP,
    "CREATEDAT" TIMESTAMP,
    "MUSERAUTHCONTEXTID" CHARACTER VARYING(36),
    "MKEY" CHARACTER VARYING(4000),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."MAPPEDUSERAUTHCONTEXT" ADD CONSTRAINT "PUBLIC"."MAPPEDUSERAUTHCONTEXT_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."MAPPEDUSERAUTHCONTEXT_MUSERID_MKEY_CREATEDAT" ON "PUBLIC"."MAPPEDUSERAUTHCONTEXT"("MUSERID" NULLS FIRST, "MKEY" NULLS FIRST, "CREATEDAT" NULLS FIRST);
