-- User init action table, twenty-first table off Lift Mapper.
-- UserId is a MappedUUID, hence VARCHAR(36).
--
-- The unique index is added by hand and is required. FlywayBaselineExport does not emit
-- dbIndexes-declared unique indexes even though Schemifier creates them; read from a booted
-- instance, information_schema.indexes reports:
--   USERINITACTION / USERINITACTION_USERID_ACTIONNAME_ACTIONVALUE / UNIQUE INDEX
-- createOrUpdateInitAction relies on it: it finds by the full (userId, actionName, actionValue)
-- triple and updates in place, so a second write for the same triple must not add a row.

CREATE TABLE "PUBLIC"."USERINITACTION"(
    "ACTIONNAME" CHARACTER VARYING(100),
    "ACTIONVALUE" CHARACTER VARYING(100),
    "UPDATEDAT" TIMESTAMP,
    "CREATEDAT" TIMESTAMP,
    "USERID" CHARACTER VARYING(36),
    "SUCCESS" BOOLEAN,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."USERINITACTION" ADD CONSTRAINT "PUBLIC"."USERINITACTION_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."USERINITACTION_USERID_ACTIONNAME_ACTIONVALUE" ON "PUBLIC"."USERINITACTION"("USERID" NULLS FIRST, "ACTIONNAME" NULLS FIRST, "ACTIONVALUE" NULLS FIRST);
