-- Account id mapping table, twenty-second table off Lift Mapper.
-- mAccountId is a MappedUUID, hence VARCHAR(36).
--
-- Both unique indexes are added by hand and are required. FlywayBaselineExport does not emit
-- dbIndexes-declared unique indexes even though Schemifier creates them; read from a booted
-- instance, information_schema.indexes reports:
--   ACCOUNTIDMAPPING / ACCOUNTIDMAPPING_MACCOUNTID / UNIQUE INDEX
--   ACCOUNTIDMAPPING / ACCOUNTIDMAPPING_MACCOUNTID_MACCOUNTPLAINTEXTREFERENCE / UNIQUE INDEX
-- getOrCreateAccountId's comment describes a concurrent-insert retry for a duplicate
-- accountPlainTextReference, but neither index actually constrains that column alone -
-- mAccountId is what is unique here, and every fresh insert gets a new random UUID for it, so
-- two concurrent creates for the SAME accountPlainTextReference do not collide at the database
-- level and both succeed. That gap is reproduced as-is: it is a genuine schema question (should
-- accountPlainTextReference be unique on its own?) rather than something a table migration
-- should decide unilaterally, and this table's rows already exist under today's schema. The
-- retry branch is kept in the provider as dead-but-harmless code, matching what it actually is
-- today.

CREATE TABLE "PUBLIC"."ACCOUNTIDMAPPING"(
    "MACCOUNTID" CHARACTER VARYING(36),
    "UPDATEDAT" TIMESTAMP,
    "CREATEDAT" TIMESTAMP,
    "MACCOUNTPLAINTEXTREFERENCE" CHARACTER VARYING(255),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."ACCOUNTIDMAPPING" ADD CONSTRAINT "PUBLIC"."ACCOUNTIDMAPPING_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."ACCOUNTIDMAPPING_MACCOUNTID" ON "PUBLIC"."ACCOUNTIDMAPPING"("MACCOUNTID" NULLS FIRST);
CREATE UNIQUE INDEX "PUBLIC"."ACCOUNTIDMAPPING_MACCOUNTID_MACCOUNTPLAINTEXTREFERENCE" ON "PUBLIC"."ACCOUNTIDMAPPING"("MACCOUNTID" NULLS FIRST, "MACCOUNTPLAINTEXTREFERENCE" NULLS FIRST);
