-- Transaction id mapping table, twenty-third table off Lift Mapper. Sibling of
-- accountidmapping. TransactionId is a MappedUUID, hence VARCHAR(36).
--
-- Both unique indexes are added by hand and are required. FlywayBaselineExport does not emit
-- dbIndexes-declared unique indexes even though Schemifier creates them; read from a booted
-- instance, information_schema.indexes reports:
--   TRANSACTIONIDMAPPING / TRANSACTIONIDMAPPING_TRANSACTIONID / UNIQUE INDEX
--   TRANSACTIONIDMAPPING / TRANSACTIONIDMAPPING_TRANSACTIONID_TRANSACTIONPLAINTEXTREFERENCE / UNIQUE INDEX
-- As with accountidmapping, neither index constrains transactionPlainTextReference on its own -
-- only TransactionId is unique, and every insert gets a fresh random UUID for it - so two
-- concurrent creates for the same reference do not collide at the database level. Reproduced
-- as-is; see the sibling table's migration note and the follow-up investigation it triggered.

CREATE TABLE "PUBLIC"."TRANSACTIONIDMAPPING"(
    "TRANSACTIONID" CHARACTER VARYING(36),
    "UPDATEDAT" TIMESTAMP,
    "CREATEDAT" TIMESTAMP,
    "TRANSACTIONPLAINTEXTREFERENCE" CHARACTER VARYING(255),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."TRANSACTIONIDMAPPING" ADD CONSTRAINT "PUBLIC"."TRANSACTIONIDMAPPING_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."TRANSACTIONIDMAPPING_TRANSACTIONID" ON "PUBLIC"."TRANSACTIONIDMAPPING"("TRANSACTIONID" NULLS FIRST);
CREATE UNIQUE INDEX "PUBLIC"."TRANSACTIONIDMAPPING_TRANSACTIONID_TRANSACTIONPLAINTEXTREFERENCE" ON "PUBLIC"."TRANSACTIONIDMAPPING"("TRANSACTIONID" NULLS FIRST, "TRANSACTIONPLAINTEXTREFERENCE" NULLS FIRST);
