-- Customer id mapping table, twenty-fourth table off Lift Mapper. Third of the id-mapping
-- triplet (accountidmapping, transactionidmapping, this one). mCustomerId is a MappedUUID,
-- hence VARCHAR(36). mBankId/mCustomerNumber are deprecated since 2019-08-23 ("We used
-- customerPlainTextReference instead") and nothing writes or reads them anymore, but the
-- columns are kept - dropping them is a separate decision from moving the table off Mapper.
--
-- Both unique indexes are added by hand and are required. FlywayBaselineExport does not emit
-- dbIndexes-declared unique indexes even though Schemifier creates them; read from a booted
-- instance, information_schema.indexes reports:
--   MAPPEDCUSTOMERIDMAPPING / MAPPEDCUSTOMERIDMAPPING_MCUSTOMERID / UNIQUE INDEX
--   MAPPEDCUSTOMERIDMAPPING / MAPPEDCUSTOMERIDMAPPING_MCUSTOMERID_MCUSTOMERPLAINTEXTREFERENCE / UNIQUE INDEX
-- As with the other two id-mapping tables, neither index constrains mCustomerPlainTextReference
-- on its own - only mCustomerId is unique, and every insert gets a fresh random UUID for it - so
-- two concurrent creates for the same reference do not collide at the database level. Reproduced
-- as-is; see accountidmapping's migration note and the follow-up investigation it triggered.

CREATE TABLE "PUBLIC"."MAPPEDCUSTOMERIDMAPPING"(
    "UPDATEDAT" TIMESTAMP,
    "CREATEDAT" TIMESTAMP,
    "MBANKID" CHARACTER VARYING(50),
    "MCUSTOMERID" CHARACTER VARYING(36),
    "MCUSTOMERNUMBER" CHARACTER VARYING(50),
    "MCUSTOMERPLAINTEXTREFERENCE" CHARACTER VARYING(255),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."MAPPEDCUSTOMERIDMAPPING" ADD CONSTRAINT "PUBLIC"."MAPPEDCUSTOMERIDMAPPING_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."MAPPEDCUSTOMERIDMAPPING_MCUSTOMERID" ON "PUBLIC"."MAPPEDCUSTOMERIDMAPPING"("MCUSTOMERID" NULLS FIRST);
CREATE UNIQUE INDEX "PUBLIC"."MAPPEDCUSTOMERIDMAPPING_MCUSTOMERID_MCUSTOMERPLAINTEXTREFERENCE" ON "PUBLIC"."MAPPEDCUSTOMERIDMAPPING"("MCUSTOMERID" NULLS FIRST, "MCUSTOMERPLAINTEXTREFERENCE" NULLS FIRST);
