-- Bank account data table, twenty-fifth table off Lift Mapper.
-- Nothing creates or reads this table anywhere in the current codebase - only
-- DeleteAccountCascade deletes from it, to clear out any rows an account may have picked up
-- while this entity was in active use. Kept so that cascade delete still has a real table to
-- target; not a candidate for dropping outright without checking production data first.
--
-- The unique index is added by hand and does exist. FlywayBaselineExport does not emit
-- dbIndexes-declared unique indexes even though Schemifier creates them; read from a booted
-- instance, information_schema.indexes reports:
--   MAPPEDBANKACCOUNTDATA / MAPPEDBANKACCOUNTDATA_BANKID_ACCOUNTID / UNIQUE INDEX

CREATE TABLE "PUBLIC"."MAPPEDBANKACCOUNTDATA"(
    "UPDATEDAT" TIMESTAMP,
    "CREATEDAT" TIMESTAMP,
    "ACCOUNTLABEL" CHARACTER VARYING(255),
    "BANKID" CHARACTER VARYING(255),
    "ACCOUNTID" CHARACTER VARYING(255),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."MAPPEDBANKACCOUNTDATA" ADD CONSTRAINT "PUBLIC"."MAPPEDBANKACCOUNTDATA_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."MAPPEDBANKACCOUNTDATA_BANKID_ACCOUNTID" ON "PUBLIC"."MAPPEDBANKACCOUNTDATA"("BANKID" NULLS FIRST, "ACCOUNTID" NULLS FIRST);
