-- Bad login attempt table, twenty-seventh table off Lift Mapper.
--
-- The unique index is added by hand and does exist. FlywayBaselineExport does not emit
-- dbIndexes-declared unique indexes even though Schemifier creates them; read from a booted
-- instance, information_schema.indexes reports:
--   MAPPEDBADLOGINATTEMPT / MAPPEDBADLOGINATTEMPT_PROVIDER_MUSERNAME / UNIQUE INDEX
-- This is not the index MigrationOfMappedBadLoginAttemptDropIndex removes - that one-time
-- runtime migration (still tracked in migration_script_log, not Flyway) drops a differently
-- named legacy index, mappedbadloginattempt_musername, which constrained mUsername alone and
-- would have rejected the same username logging in under two different providers.
--
-- Concurrent bad-login increments are handled by an atomic UPDATE ... SET counter = counter + 1
-- (see DoobieBadLoginAttemptQueries), not by this index; the index only stops two rows existing
-- for the same (provider, username) pair.

CREATE TABLE "PUBLIC"."MAPPEDBADLOGINATTEMPT"(
    "MUSERNAME" CHARACTER VARYING(100) NOT NULL,
    "MLASTFAILUREDATE" TIMESTAMP,
    "MBADATTEMPTSSINCELASTSUCCESSORRESET" INTEGER,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "PROVIDER" CHARACTER VARYING(100)
);
ALTER TABLE "PUBLIC"."MAPPEDBADLOGINATTEMPT" ADD CONSTRAINT "PUBLIC"."MAPPEDBADLOGINATTEMPT_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."MAPPEDBADLOGINATTEMPT_PROVIDER_MUSERNAME" ON "PUBLIC"."MAPPEDBADLOGINATTEMPT"("PROVIDER" NULLS FIRST, "MUSERNAME" NULLS FIRST);
