-- Bank account routing table, twenty-eighth table off Lift Mapper. Stores IBAN and other
-- account-routing addresses (schemes: IBAN, OBP, sort-code-account-number, ...). BankId is a
-- UUIDString (44 chars); AccountId is the wider AccountIdString (64 chars) - not the usual
-- MappedUUID shape seen on most other tables.
--
-- Both unique indexes are added by hand and are required. FlywayBaselineExport does not emit
-- dbIndexes-declared unique indexes even though Schemifier creates them; read from a booted
-- instance, information_schema.indexes reports:
--   BANKACCOUNTROUTING / BANKACCOUNTROUTING_BANKID_ACCOUNTID_ACCOUNTROUTINGSCHEME / UNIQUE INDEX
--   BANKACCOUNTROUTING / BANKACCOUNTROUTING_BANKID_ACCOUNTROUTINGSCHEME_ACCOUNTROUTINGADDRESS / UNIQUE INDEX
-- The first is "one address per (account, scheme)"; the second is "one account per
-- (bank, scheme, address)" - an address like an IBAN can't be claimed by two different accounts
-- at the same bank under the same scheme. Both are read directly by
-- LocalMappedConnector.getBankAccountByRoutingLegacy and getAccountRouting, which rely on the
-- database, not application code, to keep either from being violated.

CREATE TABLE "PUBLIC"."BANKACCOUNTROUTING"(
    "UPDATEDAT" TIMESTAMP,
    "CREATEDAT" TIMESTAMP,
    "BANKID" CHARACTER VARYING(44),
    "ACCOUNTID" CHARACTER VARYING(64),
    "ACCOUNTROUTINGSCHEME" CHARACTER VARYING(32),
    "ACCOUNTROUTINGADDRESS" CHARACTER VARYING(128),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."BANKACCOUNTROUTING" ADD CONSTRAINT "PUBLIC"."BANKACCOUNTROUTING_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."BANKACCOUNTROUTING_BANKID_ACCOUNTID_ACCOUNTROUTINGSCHEME" ON "PUBLIC"."BANKACCOUNTROUTING"("BANKID" NULLS FIRST, "ACCOUNTID" NULLS FIRST, "ACCOUNTROUTINGSCHEME" NULLS FIRST);
CREATE UNIQUE INDEX "PUBLIC"."BANKACCOUNTROUTING_BANKID_ACCOUNTROUTINGSCHEME_ACCOUNTROUTINGADDRESS" ON "PUBLIC"."BANKACCOUNTROUTING"("BANKID" NULLS FIRST, "ACCOUNTROUTINGSCHEME" NULLS FIRST, "ACCOUNTROUTINGADDRESS" NULLS FIRST);
