-- FX rate table, twenty-ninth table off Lift Mapper. BankId is a UUIDString (44 chars);
-- currency codes are ISO 3-letter.
--
-- No unique index: only plain indexes on the two currency-code columns, matching Schemifier's
-- actual output. The entity declared a foreign key on both currency columns pointing at
-- MappedCurrency, but that table has always had zero rows and the FK was never enforced in
-- practice - confirmed by inserting a row for a currency pair with nothing in MappedCurrency,
-- which succeeded. MappedCurrency is deleted as dead code in the same change (see
-- MappedCurrency.scala's removal), so there is no FK target to declare here even if one were
-- wanted.
--
-- createOrUpdateFXRate is find-then-write on (bankId, fromCurrencyCode, toCurrencyCode); with no
-- unique index, a genuinely concurrent pair of calls for the same triple can both miss the find
-- and both insert, same as the id-mapping tables' documented gap.

CREATE TABLE "PUBLIC"."MAPPEDFXRATE"(
    "MBANKID" CHARACTER VARYING(44),
    "MFROMCURRENCYCODE" CHARACTER VARYING(3),
    "MTOCURRENCYCODE" CHARACTER VARYING(3),
    "MCONVERSIONVALUE" DOUBLE PRECISION,
    "MEFFECTIVEDATE" TIMESTAMP,
    "MINVERSECONVERSIONVALUE" DOUBLE PRECISION,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."MAPPEDFXRATE" ADD CONSTRAINT "PUBLIC"."MAPPEDFXRATE_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."MAPPEDFXRATE_MFROMCURRENCYCODE" ON "PUBLIC"."MAPPEDFXRATE"("MFROMCURRENCYCODE" NULLS FIRST);
CREATE INDEX "PUBLIC"."MAPPEDFXRATE_MTOCURRENCYCODE" ON "PUBLIC"."MAPPEDFXRATE"("MTOCURRENCYCODE" NULLS FIRST);
