-- Migration script log table, thirty-first table off Lift Mapper. This is migration bookkeeping
-- itself - the table every historical migration script writes to via Migration.saveLog, and the
-- one resetDatabaseForTestClass (ServerSetup.scala) deliberately excludes from its per-test-class
-- wipe: clearing it makes isExecuted always false, so a fresh test JVM would re-run every
-- historical migration against a database that already has their effects (e.g. migration-created
-- views), and a migration that retypes a view-projected column then fails outright. That
-- exclusion continues to apply after this table moves to Flyway - it is simply never in the
-- automatic per-table reset list any migrated table gets added to.
--
-- The unique index is added by hand and does exist. FlywayBaselineExport does not emit
-- dbIndexes-declared unique indexes even though Schemifier creates them; read from a booted
-- instance, information_schema.indexes reports:
--   MIGRATIONSCRIPTLOG / MIGRATIONSCRIPTLOG_NAME_ISSUCCESSFUL / UNIQUE INDEX
-- saveLog's find-then-update-or-create keys on exactly (name, isSuccessful).

CREATE TABLE "PUBLIC"."MIGRATIONSCRIPTLOG"(
    "ISSUCCESSFUL" BOOLEAN,
    "COMMITID" CHARACTER VARYING(100),
    "STARTDATE" BIGINT,
    "ENDDATE" BIGINT,
    "UPDATEDAT" TIMESTAMP,
    "CREATEDAT" TIMESTAMP,
    "REMARK" CHARACTER VARYING(1024),
    "MIGRATIONSCRIPTLOGID" CHARACTER VARYING(36),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "NAME" CHARACTER VARYING(100)
);
ALTER TABLE "PUBLIC"."MIGRATIONSCRIPTLOG" ADD CONSTRAINT "PUBLIC"."MIGRATIONSCRIPTLOG_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."MIGRATIONSCRIPTLOG_NAME_ISSUCCESSFUL" ON "PUBLIC"."MIGRATIONSCRIPTLOG"("NAME" NULLS FIRST, "ISSUCCESSFUL" NULLS FIRST);
