-- Transaction request reasons table, thirty-second table off Lift Mapper. A write-only audit
-- record: nothing in the codebase reads it back - it is populated alongside a transaction
-- request's creation and never queried again here. TransactionRequestReasonId defaults via
-- APIUtil.generateUUID(), hence VARCHAR(44) like other UUID-valued columns.
--
-- No unique index - only the primary key. Schemifier's own output for this table, confirmed by
-- reading information_schema.indexes on a booted instance; multiple reasons naturally attach to
-- one transactionrequestid, so nothing here was ever expected to be unique.

CREATE TABLE "PUBLIC"."TRANSACTIONREQUESTREASONS"(
    "AMOUNT" CHARACTER VARYING(32),
    "CURRENCY" CHARACTER VARYING(3),
    "DOCUMENTNUMBER" CHARACTER VARYING(100),
    "DESCRIPTION" CHARACTER VARYING(2048),
    "UPDATEDAT" TIMESTAMP,
    "CREATEDAT" TIMESTAMP,
    "TRANSACTIONREQUESTID" CHARACTER VARYING(44),
    "TRANSACTIONREQUESTREASONID" CHARACTER VARYING(44),
    "CODE" CHARACTER VARYING(8),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."TRANSACTIONREQUESTREASONS" ADD CONSTRAINT "PUBLIC"."TRANSACTIONREQUESTREASONS_PK" PRIMARY KEY("ID");
