-- Api product attribute table, thirty-third table off Lift Mapper. ApiProductAttributeId is a
-- MappedUUID (36 chars); BankId is a UUIDString (44 chars). Type is a reserved word in H2, hence
-- the TYPE_C column.
--
-- The unique index is added by hand and is required. FlywayBaselineExport does not emit
-- dbIndexes-declared unique indexes even though Schemifier creates them; read from a booted
-- instance, information_schema.indexes reports:
--   APIPRODUCTATTRIBUTE / APIPRODUCTATTRIBUTE_APIPRODUCTATTRIBUTEID / UNIQUE INDEX
-- createOrUpdateApiProductAttribute looks up by this id, not by (bankId, apiProductCode), so a
-- bank/product pair can carry more than one attribute with the same name at once - lookup by id
-- is the only thing that has to be unique.

CREATE TABLE "PUBLIC"."APIPRODUCTATTRIBUTE"(
    "ISACTIVE" BOOLEAN,
    "APIPRODUCTCODE" CHARACTER VARYING(50),
    "VALUE" CHARACTER VARYING(2000),
    "UPDATEDAT" TIMESTAMP,
    "CREATEDAT" TIMESTAMP,
    "BANKID" CHARACTER VARYING(44),
    "APIPRODUCTATTRIBUTEID" CHARACTER VARYING(36),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "NAME" CHARACTER VARYING(256),
    "TYPE_C" CHARACTER VARYING(50)
);
ALTER TABLE "PUBLIC"."APIPRODUCTATTRIBUTE" ADD CONSTRAINT "PUBLIC"."APIPRODUCTATTRIBUTE_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."APIPRODUCTATTRIBUTE_BANKID" ON "PUBLIC"."APIPRODUCTATTRIBUTE"("BANKID" NULLS FIRST);
CREATE UNIQUE INDEX "PUBLIC"."APIPRODUCTATTRIBUTE_APIPRODUCTATTRIBUTEID" ON "PUBLIC"."APIPRODUCTATTRIBUTE"("APIPRODUCTATTRIBUTEID" NULLS FIRST);
