-- Card attribute table, thirty-fifth table off Lift Mapper. mCardAttributeId is a MappedUUID
-- (36 chars); mBankId/mCardId are UUIDString (44 chars).
--
-- No unique index - only two plain indexes on mCardId and mCardAttributeId, matching
-- Schemifier's real output (the entity's own dbIndexes declares only Index, never UniqueIndex).
-- createOrUpdateCardAttribute finds by mCardAttributeId to decide update vs create, but nothing
-- in the schema enforces that lookup key being unique.

CREATE TABLE "PUBLIC"."MAPPEDCARDATTRIBUTE"(
    "MCARDID" CHARACTER VARYING(44),
    "MCARDATTRIBUTEID" CHARACTER VARYING(36),
    "MBANKID" CHARACTER VARYING(44),
    "MNAME" CHARACTER VARYING(50),
    "MTYPE" CHARACTER VARYING(50),
    "MVALUE" CHARACTER VARYING(255),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."MAPPEDCARDATTRIBUTE" ADD CONSTRAINT "PUBLIC"."MAPPEDCARDATTRIBUTE_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."MAPPEDCARDATTRIBUTE_MCARDID" ON "PUBLIC"."MAPPEDCARDATTRIBUTE"("MCARDID" NULLS FIRST);
CREATE INDEX "PUBLIC"."MAPPEDCARDATTRIBUTE_MCARDATTRIBUTEID" ON "PUBLIC"."MAPPEDCARDATTRIBUTE"("MCARDATTRIBUTEID" NULLS FIRST);
