-- ATM attribute table, thirty-sixth table off Lift Mapper. AtmAttributeId is a MappedUUID
-- (36 chars); BankId_/AtmId_ are UUIDString (44 chars). The Type column is stored as TYPE_C -
-- Lift Mapper suffixes reserved SQL words, and TYPE collides with H2's reserved TYPE keyword.
--
-- No unique index - only a plain composite index on (BankId, AtmId), matching the entity's own
-- dbIndexes (Index(BankId_, AtmId_)), confirmed against a booted instance's
-- information_schema.indexes.
--
-- IsActive defaults to true at the application layer (isActive.getOrElse(true) on create), not
-- via a column DEFAULT - matching the Mapper field's defaultValue, which only fired through the
-- Mapper API, never as a schema-level default.

CREATE TABLE "PUBLIC"."ATMATTRIBUTE"(
    "ATMID" CHARACTER VARYING(44),
    "ATMATTRIBUTEID" CHARACTER VARYING(36),
    "BANKID" CHARACTER VARYING(44),
    "ISACTIVE" BOOLEAN,
    "VALUE" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(50),
    "TYPE_C" CHARACTER VARYING(50),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."ATMATTRIBUTE" ADD CONSTRAINT "PUBLIC"."ATMATTRIBUTE_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."ATMATTRIBUTE_BANKID_ATMID" ON "PUBLIC"."ATMATTRIBUTE"("BANKID" NULLS FIRST, "ATMID" NULLS FIRST);
