-- Bank attribute table, thirty-seventh table off Lift Mapper. BankAttributeId is a MappedUUID
-- (36 chars); BankId_ is a UUIDString (44 chars). The BankId_ Mapper field has no dbColumnName
-- override, so the DB column keeps the trailing underscore (BANKID_) - unlike AtmAttribute's
-- BankId_/AtmId_, which did override it. The Type column is stored as TYPE_C for the same
-- reserved-word reason as AtmAttribute (see V034).
--
-- No unique index - only a plain index on BankId_, matching the entity's own dbIndexes
-- (Index(BankId_)), confirmed against a booted instance's information_schema.indexes.
--
-- IsActive defaults to true at the application layer (isActive.getOrElse(true) on create), not
-- via a column DEFAULT - matching the Mapper field's defaultValue, which only fired through the
-- Mapper API.

CREATE TABLE "PUBLIC"."BANKATTRIBUTE"(
    "BANKID_" CHARACTER VARYING(44),
    "BANKATTRIBUTEID" CHARACTER VARYING(36),
    "ISACTIVE" BOOLEAN,
    "VALUE" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(50),
    "TYPE_C" CHARACTER VARYING(50),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."BANKATTRIBUTE" ADD CONSTRAINT "PUBLIC"."BANKATTRIBUTE_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."BANKATTRIBUTE_BANKID_" ON "PUBLIC"."BANKATTRIBUTE"("BANKID_" NULLS FIRST);
