-- Regulated-entity attribute table, thirty-ninth table off Lift Mapper. RegulatedEntityAttributeId
-- is a MappedUUID (36 chars); RegulatedEntityId_ is a UUIDString (44 chars) with an explicit
-- dbColumnName override ("RegulatedEntityId"), so the column is clean - no trailing underscore.
-- The Type column is stored as TYPE_C for the same reserved-word reason as AtmAttribute/
-- BankAttribute/CounterpartyAttribute.
--
-- No unique index - only a plain index on regulatedentityid, matching the entity's own dbIndexes
-- (Index(RegulatedEntityId_)), confirmed against a booted instance's information_schema.indexes.
--
-- IsActive defaults to true at the application layer (isActive.getOrElse(true) on create), not
-- via a column DEFAULT - matching the Mapper field's defaultValue, which only fired through the
-- Mapper API.

CREATE TABLE "PUBLIC"."REGULATEDENTITYATTRIBUTE"(
    "REGULATEDENTITYID" CHARACTER VARYING(44),
    "ISACTIVE" BOOLEAN,
    "VALUE" CHARACTER VARYING(255),
    "REGULATEDENTITYATTRIBUTEID" CHARACTER VARYING(36),
    "NAME" CHARACTER VARYING(50),
    "TYPE_C" CHARACTER VARYING(50),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."REGULATEDENTITYATTRIBUTE" ADD CONSTRAINT "PUBLIC"."REGULATEDENTITYATTRIBUTE_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."REGULATEDENTITYATTRIBUTE_REGULATEDENTITYID" ON "PUBLIC"."REGULATEDENTITYATTRIBUTE"("REGULATEDENTITYID" NULLS FIRST);
