-- Product attribute table, fortieth table off Lift Mapper. mProductAttributeId is a MappedUUID
-- (36 chars); mBankId is a UUIDString (44 chars). No reserved-word column renames here - mType
-- (unlike the bare Type column on AtmAttribute/BankAttribute/CounterpartyAttribute/
-- RegulatedEntityAttribute) does not collide with H2's reserved TYPE keyword.
--
-- No unique index - only plain indexes on mBankId and mProductAttributeId, matching the entity's
-- own dbIndexes (Index(mBankId) :: Index(mProductAttributeId)), confirmed against a booted
-- instance's information_schema.indexes.
--
-- IsActive defaults to true at the application layer (isActive.getOrElse(true) on create), not
-- via a column DEFAULT - matching the Mapper field's defaultValue, which only fired through the
-- Mapper API.

CREATE TABLE "PUBLIC"."MAPPEDPRODUCTATTRIBUTE"(
    "MBANKID" CHARACTER VARYING(44),
    "MCODE" CHARACTER VARYING(50),
    "MNAME" CHARACTER VARYING(50),
    "MTYPE" CHARACTER VARYING(50),
    "ISACTIVE" BOOLEAN,
    "MVALUE" CHARACTER VARYING(255),
    "MPRODUCTATTRIBUTEID" CHARACTER VARYING(36),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."MAPPEDPRODUCTATTRIBUTE" ADD CONSTRAINT "PUBLIC"."MAPPEDPRODUCTATTRIBUTE_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."MAPPEDPRODUCTATTRIBUTE_MBANKID" ON "PUBLIC"."MAPPEDPRODUCTATTRIBUTE"("MBANKID" NULLS FIRST);
CREATE INDEX "PUBLIC"."MAPPEDPRODUCTATTRIBUTE_MPRODUCTATTRIBUTEID" ON "PUBLIC"."MAPPEDPRODUCTATTRIBUTE"("MPRODUCTATTRIBUTEID" NULLS FIRST);
