-- Customer attribute table, forty-first table off Lift Mapper. mCustomerAttributeId is a
-- MappedUUID (36 chars); mBankId/mCustomerId are UUIDString (44 chars). mBankId has an explicit
-- dbColumnName override ("mbankidid") - a historical typo baked into the schema, preserved
-- verbatim (see the entity's own comment: "the column name is typo that left over from history").
-- mValue is 2000 chars, wider than the 255 used by the other *Attribute tables.
--
-- No unique index - only plain indexes on mCustomerId and mCustomerAttributeId, matching the
-- entity's own dbIndexes (Index(mCustomerId) :: Index(mCustomerAttributeId)), confirmed against a
-- booted instance's information_schema.indexes.

CREATE TABLE "PUBLIC"."MAPPEDCUSTOMERATTRIBUTE"(
    "MVALUE" CHARACTER VARYING(2000),
    "MBANKIDID" CHARACTER VARYING(44),
    "MNAME" CHARACTER VARYING(50),
    "MCUSTOMERID" CHARACTER VARYING(44),
    "MTYPE" CHARACTER VARYING(50),
    "MCUSTOMERATTRIBUTEID" CHARACTER VARYING(36),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."MAPPEDCUSTOMERATTRIBUTE" ADD CONSTRAINT "PUBLIC"."MAPPEDCUSTOMERATTRIBUTE_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."MAPPEDCUSTOMERATTRIBUTE_MCUSTOMERID" ON "PUBLIC"."MAPPEDCUSTOMERATTRIBUTE"("MCUSTOMERID" NULLS FIRST);
CREATE INDEX "PUBLIC"."MAPPEDCUSTOMERATTRIBUTE_MCUSTOMERATTRIBUTEID" ON "PUBLIC"."MAPPEDCUSTOMERATTRIBUTE"("MCUSTOMERATTRIBUTEID" NULLS FIRST);
