-- Transaction-request attribute table, forty-fourth table off Lift Mapper.
-- TransactionRequestAttributeId is a MappedUUID (36 chars); BankId/TransactionRequestId are
-- UUIDString (44 chars). The Type column is stored as TYPE_C for the same reserved-word reason
-- as AtmAttribute/BankAttribute/CounterpartyAttribute/RegulatedEntityAttribute. Value is a
-- MappedText, so CHARACTER VARYING with no bound (same pattern as V015's MethodBody) - Open
-- Corridor promise evidence stores the full A1.1 preimage JSON here, which exceeds any fixed
-- varchar bound.
--
-- No unique index - only plain indexes on transactionrequestid and
-- transactionrequestattributeid, matching the entity's own dbIndexes
-- (Index(TransactionRequestId) :: Index(TransactionRequestAttributeId)), confirmed against a
-- booted instance's information_schema.indexes.

CREATE TABLE "PUBLIC"."TRANSACTIONREQUESTATTRIBUTE"(
    "VALUE" CHARACTER VARYING,
    "BANKID" CHARACTER VARYING(44),
    "ISPERSONAL" BOOLEAN,
    "TRANSACTIONREQUESTID" CHARACTER VARYING(44),
    "TRANSACTIONREQUESTATTRIBUTEID" CHARACTER VARYING(36),
    "NAME" CHARACTER VARYING(50),
    "TYPE_C" CHARACTER VARYING(50),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."TRANSACTIONREQUESTATTRIBUTE" ADD CONSTRAINT "PUBLIC"."TRANSACTIONREQUESTATTRIBUTE_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."TRANSACTIONREQUESTATTRIBUTE_TRANSACTIONREQUESTID" ON "PUBLIC"."TRANSACTIONREQUESTATTRIBUTE"("TRANSACTIONREQUESTID" NULLS FIRST);
CREATE INDEX "PUBLIC"."TRANSACTIONREQUESTATTRIBUTE_TRANSACTIONREQUESTATTRIBUTEID" ON "PUBLIC"."TRANSACTIONREQUESTATTRIBUTE"("TRANSACTIONREQUESTATTRIBUTEID" NULLS FIRST);
