-- Customer link table (bank-to-bank customer relationships, e.g. spouse/parent at another
-- bank), forty-sixth table off Lift Mapper. CustomerLinkId is a MappedUUID (36 chars);
-- CustomerId/OtherCustomerId are UUIDString (44 chars); BankId/OtherBankId/RelationshipTo are
-- plain MappedString(255). createdat/updatedat come from the CreatedUpdated mixin. dbTableName is
-- explicitly overridden to "CustomerLink" (mixed case in the entity source; H2 stores/reports it
-- lowercase either way).
--
-- Unique index on customerlinkid, matching UniqueIndex(CustomerLinkId); plain indexes on
-- customerid and othercustomerid, matching Index(CustomerId)/Index(OtherCustomerId) - confirmed
-- against a booted instance's information_schema.indexes.

CREATE TABLE "PUBLIC"."CUSTOMERLINK"(
    "UPDATEDAT" TIMESTAMP,
    "CREATEDAT" TIMESTAMP,
    "BANKID" CHARACTER VARYING(255),
    "CUSTOMERLINKID" CHARACTER VARYING(36),
    "RELATIONSHIPTO" CHARACTER VARYING(255),
    "CUSTOMERID" CHARACTER VARYING(44),
    "OTHERBANKID" CHARACTER VARYING(255),
    "OTHERCUSTOMERID" CHARACTER VARYING(44),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."CUSTOMERLINK" ADD CONSTRAINT "PUBLIC"."CUSTOMERLINK_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."CUSTOMERLINK_CUSTOMERLINKID" ON "PUBLIC"."CUSTOMERLINK"("CUSTOMERLINKID" NULLS FIRST);
CREATE INDEX "PUBLIC"."CUSTOMERLINK_CUSTOMERID" ON "PUBLIC"."CUSTOMERLINK"("CUSTOMERID" NULLS FIRST);
CREATE INDEX "PUBLIC"."CUSTOMERLINK_OTHERCUSTOMERID" ON "PUBLIC"."CUSTOMERLINK"("OTHERCUSTOMERID" NULLS FIRST);
