-- Counterparty limit table, forty-seventh table off Lift Mapper. CounterpartyLimitId is a
-- MappedUUID (36 chars); BankId/AccountId/ViewId/CounterpartyId/Currency are MappedString(255),
-- with BankId/AccountId/ViewId/CounterpartyId declared dbNotNull_?=true. The four amount fields
-- are MappedDecimal(MathContext.DECIMAL64, 10) -> NUMERIC(16,10); the three transaction-count
-- fields are MappedInt -> INTEGER. createdat/updatedat come from the CreatedUpdated mixin.
--
-- Two unique indexes: one on counterpartylimitid, one on the composite
-- (bankid, accountid, viewid, counterpartyid) - at most one limit per (bank, account, view,
-- counterparty) tuple. Matches the entity's own dbIndexes
-- (UniqueIndex(CounterpartyLimitId) :: UniqueIndex(BankId, AccountId, ViewId, CounterpartyId)),
-- confirmed against a booted instance's information_schema.indexes.

CREATE TABLE "PUBLIC"."COUNTERPARTYLIMIT"(
    "MAXSINGLEAMOUNT" NUMERIC(16, 10),
    "MAXMONTHLYAMOUNT" NUMERIC(16, 10),
    "MAXYEARLYAMOUNT" NUMERIC(16, 10),
    "MAXTOTALAMOUNT" NUMERIC(16, 10),
    "UPDATEDAT" TIMESTAMP,
    "CREATEDAT" TIMESTAMP,
    "BANKID" CHARACTER VARYING(255) NOT NULL,
    "ACCOUNTID" CHARACTER VARYING(255) NOT NULL,
    "CURRENCY" CHARACTER VARYING(255),
    "VIEWID" CHARACTER VARYING(255) NOT NULL,
    "COUNTERPARTYID" CHARACTER VARYING(255) NOT NULL,
    "COUNTERPARTYLIMITID" CHARACTER VARYING(36),
    "MAXNUMBEROFMONTHLYTRANSACTIONS" INTEGER,
    "MAXNUMBEROFYEARLYTRANSACTIONS" INTEGER,
    "MAXNUMBEROFTRANSACTIONS" INTEGER,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."COUNTERPARTYLIMIT" ADD CONSTRAINT "PUBLIC"."COUNTERPARTYLIMIT_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."COUNTERPARTYLIMIT_COUNTERPARTYLIMITID" ON "PUBLIC"."COUNTERPARTYLIMIT"("COUNTERPARTYLIMITID" NULLS FIRST);
CREATE UNIQUE INDEX "PUBLIC"."COUNTERPARTYLIMIT_BANKID_ACCOUNTID_VIEWID_COUNTERPARTYID" ON "PUBLIC"."COUNTERPARTYLIMIT"("BANKID" NULLS FIRST, "ACCOUNTID" NULLS FIRST, "VIEWID" NULLS FIRST, "COUNTERPARTYID" NULLS FIRST);
