-- Customer account link table (which customer(s) can act as agent/owner on which account),
-- forty-eighth table off Lift Mapper. CustomerAccountLinkId is a MappedUUID (36 chars);
-- CustomerId/AccountId are UUIDString (44 chars); BankId/RelationshipType are
-- MappedString(255). createdat/updatedat come from the CreatedUpdated mixin.
--
-- Two unique indexes: one on customeraccountlinkid, one on the composite (accountid, customerid)
-- - a customer has at most one link per account. Matches the entity's own dbIndexes
-- (UniqueIndex(CustomerAccountLinkId) :: UniqueIndex(AccountId, CustomerId)), confirmed against a
-- booted instance's information_schema.indexes.

CREATE TABLE "PUBLIC"."CUSTOMERACCOUNTLINK"(
    "CUSTOMERID" CHARACTER VARYING(44),
    "RELATIONSHIPTYPE" CHARACTER VARYING(255),
    "UPDATEDAT" TIMESTAMP,
    "CREATEDAT" TIMESTAMP,
    "BANKID" CHARACTER VARYING(255),
    "ACCOUNTID" CHARACTER VARYING(44),
    "CUSTOMERACCOUNTLINKID" CHARACTER VARYING(36),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."CUSTOMERACCOUNTLINK" ADD CONSTRAINT "PUBLIC"."CUSTOMERACCOUNTLINK_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."CUSTOMERACCOUNTLINK_CUSTOMERACCOUNTLINKID" ON "PUBLIC"."CUSTOMERACCOUNTLINK"("CUSTOMERACCOUNTLINKID" NULLS FIRST);
CREATE UNIQUE INDEX "PUBLIC"."CUSTOMERACCOUNTLINK_ACCOUNTID_CUSTOMERID" ON "PUBLIC"."CUSTOMERACCOUNTLINK"("ACCOUNTID" NULLS FIRST, "CUSTOMERID" NULLS FIRST);
