-- User-customer link table, forty-ninth table off Lift Mapper. mUserCustomerLinkId is a
-- MappedUUID (36 chars); mUserId/mCustomerId are UUIDString (44 chars); mDateInserted is a
-- separate MappedDateTime column distinct from the createdat/updatedat pair the CreatedUpdated
-- mixin also adds (the trait's dateInserted getter reads mdateinserted, not createdat).
--
-- Two unique indexes: one on musercustomerlinkid, one on the composite (muserid, mcustomerid) -
-- a user has at most one link per customer. Matches the entity's own dbIndexes
-- (UniqueIndex(mUserCustomerLinkId) :: UniqueIndex(mUserId, mCustomerId)), confirmed against a
-- booted instance's information_schema.indexes.
--
-- ConcurrentDuplicateCreationTest scenario L relies on this unique index: getOCreateUserCustomerLink
-- does find-then-insert with no surrounding transaction, and depends on the second concurrent
-- insert failing the constraint so it can retry the find - dropping this index would let two
-- threads both insert a row for the same (userId, customerId) pair.

CREATE TABLE "PUBLIC"."MAPPEDUSERCUSTOMERLINK"(
    "MISACTIVE" BOOLEAN,
    "UPDATEDAT" TIMESTAMP,
    "CREATEDAT" TIMESTAMP,
    "MUSERID" CHARACTER VARYING(44),
    "MCUSTOMERID" CHARACTER VARYING(44),
    "MDATEINSERTED" TIMESTAMP,
    "MUSERCUSTOMERLINKID" CHARACTER VARYING(36),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."MAPPEDUSERCUSTOMERLINK" ADD CONSTRAINT "PUBLIC"."MAPPEDUSERCUSTOMERLINK_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."MAPPEDUSERCUSTOMERLINK_MUSERCUSTOMERLINKID" ON "PUBLIC"."MAPPEDUSERCUSTOMERLINK"("MUSERCUSTOMERLINKID" NULLS FIRST);
CREATE UNIQUE INDEX "PUBLIC"."MAPPEDUSERCUSTOMERLINK_MUSERID_MCUSTOMERID" ON "PUBLIC"."MAPPEDUSERCUSTOMERLINK"("MUSERID" NULLS FIRST, "MCUSTOMERID" NULLS FIRST);
