-- CRM event table, fiftieth table off Lift Mapper. mCrmEventId is a MappedUUID (36 chars);
-- mBankId is a UUIDString (44 chars); mUserId is a MappedLongForeignKey(this, ResourceUser) -
-- it stores ResourceUser's internal BIGINT primary key, not the user's UUID userId.
-- createdat/updatedat come from the CreatedUpdated mixin (unused by the entity's own fields,
-- which use separate mScheduledDate/mActualDate columns).
--
-- Three indexes: a UNIQUE INDEX on mcrmeventid and a plain index on mbankid, both matching the
-- entity's own dbIndexes (UniqueIndex(mCrmEventId) :: Index(mBankId)); plus a plain index on
-- muserid that the entity does NOT declare explicitly - Lift Mapper auto-indexes
-- MappedLongForeignKey columns, confirmed against a booted instance's information_schema.indexes.

CREATE TABLE "PUBLIC"."MAPPEDCRMEVENT"(
    "MCRMEVENTID" CHARACTER VARYING(36),
    "MDETAIL" CHARACTER VARYING(1024),
    "MCHANNEL" CHARACTER VARYING(32),
    "MSCHEDULEDDATE" TIMESTAMP,
    "MACTUALDATE" TIMESTAMP,
    "MRESULT" CHARACTER VARYING(32),
    "MCUSTOMERNAME" CHARACTER VARYING(64),
    "UPDATEDAT" TIMESTAMP,
    "CREATEDAT" TIMESTAMP,
    "MBANKID" CHARACTER VARYING(44),
    "MCATEGORY" CHARACTER VARYING(32),
    "MUSERID" BIGINT,
    "MCUSTOMERNUMBER" CHARACTER VARYING(64),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."MAPPEDCRMEVENT" ADD CONSTRAINT "PUBLIC"."MAPPEDCRMEVENT_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."MAPPEDCRMEVENT_MUSERID" ON "PUBLIC"."MAPPEDCRMEVENT"("MUSERID" NULLS FIRST);
CREATE UNIQUE INDEX "PUBLIC"."MAPPEDCRMEVENT_MCRMEVENTID" ON "PUBLIC"."MAPPEDCRMEVENT"("MCRMEVENTID" NULLS FIRST);
CREATE INDEX "PUBLIC"."MAPPEDCRMEVENT_MBANKID" ON "PUBLIC"."MAPPEDCRMEVENT"("MBANKID" NULLS FIRST);
