-- User-refresh tracking table (controls the refresh_user.interval login flow), fifty-first
-- table off Lift Mapper. mUserId is a UUIDString (44 chars). createdat/updatedat come from the
-- CreatedUpdated mixin - updatedat is the field this table actually cares about
-- (createOrUpdateRefreshUser bumps it on every login to mark "last refreshed").
--
-- One unique index on muserid - one row per user - matching the entity's own dbIndexes
-- (UniqueIndex(mUserId)), confirmed against a booted instance's information_schema.indexes.

CREATE TABLE "PUBLIC"."MAPPEDUSERREFRESHES"(
    "MUSERID" CHARACTER VARYING(44),
    "UPDATEDAT" TIMESTAMP,
    "CREATEDAT" TIMESTAMP,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."MAPPEDUSERREFRESHES" ADD CONSTRAINT "PUBLIC"."MAPPEDUSERREFRESHES_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."MAPPEDUSERREFRESHES_MUSERID" ON "PUBLIC"."MAPPEDUSERREFRESHES"("MUSERID" NULLS FIRST);
