-- Payee lookup cache table (fifty-second table off Lift Mapper). Backs the mobile-wallet
-- payee-lookup flow: createPayeeLookup writes a short-lived row keyed by a random lookupId,
-- getActivePayeeLookup reads it back by lookupId and filters expired rows in Scala (expired
-- rows are not auto-deleted). One unique index on lookupid (Schemifier's UniqueIndex(LookupId))
-- and one plain index on expiresat (Index(ExpiresAt)), confirmed against a booted instance's
-- information_schema.indexes.

CREATE TABLE "PUBLIC"."PAYEELOOKUP"(
    "LOOKUPID" CHARACTER VARYING(64),
    "IDENTIFIERTYPE" CHARACTER VARYING(64),
    "IDENTIFIER" CHARACTER VARYING(255),
    "FSPID" CHARACTER VARYING(32),
    "NETWORKPROVIDER" CHARACTER VARYING(64),
    "FULLNAME" CHARACTER VARYING(255),
    "ACCOUNTCATEGORY" CHARACTER VARYING(32),
    "ACCOUNTTYPE" CHARACTER VARYING(32),
    "IDENTITYTYPE" CHARACTER VARYING(32),
    "IDENTITYVALUE" CHARACTER VARYING(64),
    "FROMBANKID" CHARACTER VARYING(255),
    "FROMACCOUNTID" CHARACTER VARYING(255),
    "CREATEDBYUSERID" CHARACTER VARYING(255),
    "CREATIONDATE" TIMESTAMP,
    "EXPIRESAT" TIMESTAMP,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."PAYEELOOKUP" ADD CONSTRAINT "PUBLIC"."PAYEELOOKUP_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."PAYEELOOKUP_LOOKUPID" ON "PUBLIC"."PAYEELOOKUP"("LOOKUPID" NULLS FIRST);
CREATE INDEX "PUBLIC"."PAYEELOOKUP_EXPIRESAT" ON "PUBLIC"."PAYEELOOKUP"("EXPIRESAT" NULLS FIRST);
