-- Append-only audit log of MetricsArchiveScheduler runs (fifty-fourth table off Lift Mapper).
-- One row per completed run: how many rows were moved metric -> metricarchive, how many
-- outdated archive rows were deleted, wall-clock duration, and whether the run succeeded.
-- Self-capped by MetricsArchiveRun.recordRun via pruneToMostRecent - the table stays small.
--
-- One unique index on runid (Schemifier's UniqueIndex(RunId)) and one plain index on
-- startedat (Index(StartedAt)), confirmed against a booted instance's information_schema.

CREATE TABLE "PUBLIC"."METRICSARCHIVERUN"(
    "SUCCESS" BOOLEAN,
    "RUNID" CHARACTER VARYING(36),
    "STARTEDAT" TIMESTAMP,
    "APIINSTANCEID" CHARACTER VARYING(100),
    "ENDEDAT" TIMESTAMP,
    "DURATIONMS" BIGINT,
    "ROWSMOVEDTOARCHIVE" INTEGER,
    "REMARK" CHARACTER VARYING(1000000000),
    "ROWSDELETEDFROMARCHIVE" INTEGER,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."METRICSARCHIVERUN" ADD CONSTRAINT "PUBLIC"."METRICSARCHIVERUN_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."METRICSARCHIVERUN_RUNID" ON "PUBLIC"."METRICSARCHIVERUN"("RUNID" NULLS FIRST);
CREATE INDEX "PUBLIC"."METRICSARCHIVERUN_STARTEDAT" ON "PUBLIC"."METRICSARCHIVERUN"("STARTEDAT" NULLS FIRST);
