-- Open Corridor platform fee accrual ledger (fifty-fifth table off Lift Mapper).
-- One row per covered promise: OpenCorridorSettlement.accrue writes it in the settle
-- transaction, OpenCorridorFees.sweep sums a bank's unswept rows per currency and stamps
-- them with a fee_settlement_id once swept. NULL/empty fee_settlement_id means still open.
--
-- Unique index on transaction_request_id (accrual is idempotent per covered promise),
-- plain indexes on debtor_bank_id and fee_settlement_id, confirmed against a booted
-- instance's information_schema.

CREATE TABLE "PUBLIC"."OPEN_CORRIDOR_FEE_ACCRUAL"(
    "CURRENCY" CHARACTER VARYING(8),
    "AMOUNT" CHARACTER VARYING(32),
    "DEBTOR_BANK_ID" CHARACTER VARYING(255),
    "FEE_SETTLEMENT_ID" CHARACTER VARYING(64),
    "ACCRUED_AT" TIMESTAMP,
    "TRANSACTION_REQUEST_ID" CHARACTER VARYING(64),
    "COVERED_BY_SETTLEMENT_ID" CHARACTER VARYING(64),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."OPEN_CORRIDOR_FEE_ACCRUAL" ADD CONSTRAINT "PUBLIC"."OPEN_CORRIDOR_FEE_ACCRUAL_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."OPEN_CORRIDOR_FEE_ACCRUAL_TRANSACTION_REQUEST_ID" ON "PUBLIC"."OPEN_CORRIDOR_FEE_ACCRUAL"("TRANSACTION_REQUEST_ID" NULLS FIRST);
CREATE INDEX "PUBLIC"."OPEN_CORRIDOR_FEE_ACCRUAL_DEBTOR_BANK_ID" ON "PUBLIC"."OPEN_CORRIDOR_FEE_ACCRUAL"("DEBTOR_BANK_ID" NULLS FIRST);
CREATE INDEX "PUBLIC"."OPEN_CORRIDOR_FEE_ACCRUAL_FEE_SETTLEMENT_ID" ON "PUBLIC"."OPEN_CORRIDOR_FEE_ACCRUAL"("FEE_SETTLEMENT_ID" NULLS FIRST);
