-- Web UI properties table (fifty-seventh table off Lift Mapper). Props whose name starts
-- with "webui_" can be overridden here at runtime via CRUD endpoints instead of the static
-- props file; MappedWebUiPropsProvider.getWebUiPropsValue layers brand/language variants
-- over the requested name before falling back to APIUtil.getPropsValue.
--
-- Two unique indexes (webuipropsid, name), confirmed against a booted instance's
-- information_schema.

CREATE TABLE "PUBLIC"."WEBUIPROPS"(
    "VALUE" CHARACTER VARYING(1000000000),
    "WEBUIPROPSID" CHARACTER VARYING(36),
    "NAME" CHARACTER VARYING(255),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."WEBUIPROPS" ADD CONSTRAINT "PUBLIC"."WEBUIPROPS_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."WEBUIPROPS_WEBUIPROPSID" ON "PUBLIC"."WEBUIPROPS"("WEBUIPROPSID" NULLS FIRST);
CREATE UNIQUE INDEX "PUBLIC"."WEBUIPROPS_NAME" ON "PUBLIC"."WEBUIPROPS"("NAME" NULLS FIRST);
