-- Groups-of-roles table (fifty-ninth table off Lift Mapper, dbTableName override
-- "GroupOfRoles"). Backs the v6.0.0 management/groups CRUD endpoints - a named bundle
-- of roles (list_of_roles, comma-separated) that can be granted to a user's entitlement
-- in one shot, scoped to a bank or system-wide (empty bank_id).
--
-- Two plain indexes (groupid, bankid) - the entity declares Index, not UniqueIndex, for
-- both - confirmed against a booted instance's information_schema.

CREATE TABLE "PUBLIC"."GROUPOFROLES"(
    "UPDATEDAT" TIMESTAMP,
    "CREATEDAT" TIMESTAMP,
    "BANKID" CHARACTER VARYING(255),
    "GROUPID" CHARACTER VARYING(36),
    "GROUPNAME" CHARACTER VARYING(255),
    "GROUPDESCRIPTION" CHARACTER VARYING(1000000000),
    "LISTOFROLES" CHARACTER VARYING(1000000000),
    "ISENABLED" BOOLEAN,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."GROUPOFROLES" ADD CONSTRAINT "PUBLIC"."GROUPOFROLES_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."GROUPOFROLES_GROUPID" ON "PUBLIC"."GROUPOFROLES"("GROUPID" NULLS FIRST);
CREATE INDEX "PUBLIC"."GROUPOFROLES_BANKID" ON "PUBLIC"."GROUPOFROLES"("BANKID" NULLS FIRST);
