-- Attribute definitions (sixty-first table off Lift Mapper). Declares the attributes that may
-- be attached to each entity category (Account / Transaction / Customer / Product / Card /
-- TransactionRequest ...): name, value type, description, alias, which views the attribute may
-- be seen on, and whether it is active. The per-entity attribute tables carry the values; this
-- table is the schema for them.
--
-- One unique index on (bankid, name, category), confirmed against a booted instance's
-- information_schema - the natural key the provider's find-then-update keys off.

CREATE TABLE "PUBLIC"."ATTRIBUTEDEFINITION"(
    "UPDATEDAT" TIMESTAMP,
    "CREATEDAT" TIMESTAMP,
    "BANKID" CHARACTER VARYING(50),
    "ISACTIVE" BOOLEAN,
    "DESCRIPTION" CHARACTER VARYING(256),
    "TYPEOFVALUE" CHARACTER VARYING(50),
    "ALIAS" CHARACTER VARYING(50),
    "CANBESEENONVIEWS" CHARACTER VARYING(256),
    "ATTRIBUTEDEFINITIONID" CHARACTER VARYING(36),
    "NAME" CHARACTER VARYING(50),
    "CATEGORY" CHARACTER VARYING(50),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."ATTRIBUTEDEFINITION" ADD CONSTRAINT "PUBLIC"."ATTRIBUTEDEFINITION_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."ATTRIBUTEDEFINITION_BANKID_NAME_CATEGORY"
    ON "PUBLIC"."ATTRIBUTEDEFINITION"("BANKID" NULLS FIRST, "NAME" NULLS FIRST, "CATEGORY" NULLS FIRST);
