-- Scheduler lock table (sixty-second table off Lift Mapper).
--
-- This is a LOCK table, not a job-history log: a row exists only while a job holds the lock and
-- is deleted when the job finishes. In healthy operation it is empty; rows present are either
-- currently-running jobs or stale locks left by a JVM that died before its finally block ran.
-- Contrast metricsarchiverun, which is the durable audit log of completed runs.
--
-- One unique index on jobid, confirmed against a booted instance's information_schema.

CREATE TABLE "PUBLIC"."JOBSCHEDULER"(
    "JOBID" CHARACTER VARYING(36),
    "APIINSTANCEID" CHARACTER VARYING(100),
    "UPDATEDAT" TIMESTAMP,
    "CREATEDAT" TIMESTAMP,
    "NAME" CHARACTER VARYING(100),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."JOBSCHEDULER" ADD CONSTRAINT "PUBLIC"."JOBSCHEDULER_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."JOBSCHEDULER_JOBID" ON "PUBLIC"."JOBSCHEDULER"("JOBID" NULLS FIRST);
