-- Endpoint tags (sixty-fourth table off Lift Mapper). User-defined tags attached to an endpoint
-- by operationId, either system-level (bankid null/empty) or scoped to one bank. Surfaced on
-- resource docs alongside the built-in tags.
--
-- One unique index on endpointtagid, confirmed against a booted instance's information_schema.
-- Note there is NO uniqueness on (operationid, tagname) or (bankid, operationid, tagname), so the
-- same tag can be created repeatedly for one endpoint.

CREATE TABLE "PUBLIC"."ENDPOINTTAG"(
    "UPDATEDAT" TIMESTAMP,
    "CREATEDAT" TIMESTAMP,
    "BANKID" CHARACTER VARYING(255),
    "OPERATIONID" CHARACTER VARYING(255),
    "TAGNAME" CHARACTER VARYING(255),
    "ENDPOINTTAGID" CHARACTER VARYING(36),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."ENDPOINTTAG" ADD CONSTRAINT "PUBLIC"."ENDPOINTTAG_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."ENDPOINTTAG_ENDPOINTTAGID" ON "PUBLIC"."ENDPOINTTAG"("ENDPOINTTAGID" NULLS FIRST);
