-- Per-bank AMQP broker coordinates (sixty-sixth table off Lift Mapper). Where OBP-API publishes
-- messages destined for a bank's own infrastructure: each onboarded bank's Bank Node consumes on
-- its OWN vhost with its own credentials, so permission isolation is enforced at the broker level
-- and publishing is keyed by bank_id through this registry.
--
-- password is write-only by contract: accepted on registration, never echoed by any endpoint
-- (AmqpBankBrokerJsonV700 deliberately has no password field).
--
-- One unique index on bank_id - one broker per bank, which is what makes upsert well-defined.
-- Confirmed against a booted instance.

CREATE TABLE "PUBLIC"."AMQP_BANK_BROKER"(
    "BANK_ID" CHARACTER VARYING(255),
    "HOST" CHARACTER VARYING(255),
    "PORT" INTEGER,
    "VIRTUAL_HOST" CHARACTER VARYING(255),
    "USERNAME" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255),
    "USE_SSL" BOOLEAN,
    "CREATED_AT" TIMESTAMP,
    "UPDATED_AT" TIMESTAMP,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."AMQP_BANK_BROKER" ADD CONSTRAINT "PUBLIC"."AMQP_BANK_BROKER_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."AMQP_BANK_BROKER_BANK_ID" ON "PUBLIC"."AMQP_BANK_BROKER"("BANK_ID" NULLS FIRST);
