-- Product fees (sixty-seventh table off Lift Mapper). Fees attached to a bank's product:
-- name, amount+currency, frequency and type, with an active flag.
--
-- The `type` field is stored as TYPE_C, not TYPE: Lift's Schemifier appends "_c" to column names
-- that collide with SQL reserved words. Reproduced exactly - naming it TYPE here would create a
-- column the code never reads.
--
-- amount is DECIMAL(34,2) - MappedDecimal with MathContext.DECIMAL128 and scale 2.
--
-- Two PLAIN indexes (bankid, productfeeid) - the entity declares Index, not UniqueIndex, for
-- both, so productfeeid is NOT unique at the database level even though the provider treats it
-- as an identifier. Confirmed against a booted instance; reproduced as-is.

CREATE TABLE "PUBLIC"."PRODUCTFEE"(
    "MOREINFO" CHARACTER VARYING(255),
    "BANKID" CHARACTER VARYING(44),
    "CURRENCY" CHARACTER VARYING(50),
    "AMOUNT" NUMERIC(34, 2),
    "PRODUCTCODE" CHARACTER VARYING(50),
    "PRODUCTFEEID" CHARACTER VARYING(44),
    "ISACTIVE" BOOLEAN,
    "FREQUENCY" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(100),
    "TYPE_C" CHARACTER VARYING(255),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."PRODUCTFEE" ADD CONSTRAINT "PUBLIC"."PRODUCTFEE_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."PRODUCTFEE_BANKID" ON "PUBLIC"."PRODUCTFEE"("BANKID" NULLS FIRST);
CREATE INDEX "PUBLIC"."PRODUCTFEE_PRODUCTFEEID" ON "PUBLIC"."PRODUCTFEE"("PRODUCTFEEID" NULLS FIRST);
