-- Transactional outbox (sixty-eighth table off Lift Mapper).
--
-- The business event (e.g. an Open Corridor settle) commits in one DB transaction; its outbound
-- messages must survive a crash between that commit and the publish. So they are written here in
-- the SAME transaction and a relay publishes them afterwards with at-least-once redelivery.
-- Publishing to a broker cannot join the DB transaction - this table is what closes that gap.
--
-- Row lifecycle: PENDING (relay keeps publishing with backoff) -> DELIVERED (receiver replied
-- success) or STICKY (receiver replied with an error retrying cannot fix; needs operator
-- reconciliation via GET /management/message-outbox and its /retry).
--
-- updated_at is not decoration: the relay's exponential backoff is computed from it, so every
-- write must stamp it. Three plain indexes (status, subject_id, outbox_type) - none unique -
-- confirmed against a booted instance.

CREATE TABLE "PUBLIC"."MESSAGE_OUTBOX"(
    "ATTEMPTS" INTEGER,
    "LAST_ERROR" CHARACTER VARYING(2000),
    "LAST_REPLY_JSON" CHARACTER VARYING(1000000000),
    "SUBJECT_ID" CHARACTER VARYING(64),
    "OUTBOX_TYPE" CHARACTER VARYING(32),
    "SUBJECT_ID_TYPE" CHARACTER VARYING(32),
    "OPERATION_NAME" CHARACTER VARYING(64),
    "TARGET_ID" CHARACTER VARYING(255),
    "PAYLOAD_JSON" CHARACTER VARYING(1000000000),
    "CREATED_AT" TIMESTAMP,
    "UPDATED_AT" TIMESTAMP,
    "METADATA_JSON" CHARACTER VARYING(1000000000),
    "STATUS" CHARACTER VARYING(16),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."MESSAGE_OUTBOX" ADD CONSTRAINT "PUBLIC"."MESSAGE_OUTBOX_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."MESSAGE_OUTBOX_STATUS" ON "PUBLIC"."MESSAGE_OUTBOX"("STATUS" NULLS FIRST);
CREATE INDEX "PUBLIC"."MESSAGE_OUTBOX_SUBJECT_ID" ON "PUBLIC"."MESSAGE_OUTBOX"("SUBJECT_ID" NULLS FIRST);
CREATE INDEX "PUBLIC"."MESSAGE_OUTBOX_OUTBOX_TYPE" ON "PUBLIC"."MESSAGE_OUTBOX"("OUTBOX_TYPE" NULLS FIRST);
