-- OpenID Connect tokens (sixty-ninth table off Lift Mapper). The OIDC token set obtained for an
-- AuthUser at login, keyed to that user by authuserprimarykey (AuthUser's internal id, not a
-- user_id UUID).
--
-- NO index on authuserprimarykey even though every read filters on it: the entity overrode
-- dbIndexes with nothing but super.dbIndexes, so Schemifier created only the primary key.
-- Confirmed against a booted instance - reproduced as-is rather than "improved", since adding an
-- index is a schema decision beyond a storage swap.
--
-- Rows accumulate: createToken always inserts, and the read takes the newest by createdat rather
-- than updating in place, so a user's token history is retained.

CREATE TABLE "PUBLIC"."OPENIDCONNECTTOKEN"(
    "SCOPE" CHARACTER VARYING(250),
    "ACCESSTOKEN" CHARACTER VARYING(1000000000),
    "IDTOKEN" CHARACTER VARYING(1000000000),
    "REFRESHTOKEN" CHARACTER VARYING(1000000000),
    "TOKENTYPE" CHARACTER VARYING(250),
    "EXPIRESIN" BIGINT,
    "AUTHUSERPRIMARYKEY" BIGINT,
    "UPDATEDAT" TIMESTAMP,
    "CREATEDAT" TIMESTAMP,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."OPENIDCONNECTTOKEN" ADD CONSTRAINT "PUBLIC"."OPENIDCONNECTTOKEN_PK" PRIMARY KEY("ID");
