-- User agreements (seventieth table off Lift Mapper). One row per agreement a user accepted,
-- retained as a history: createUserAgreement always inserts, and reads take the most recent by
-- date per (userId, agreementType) rather than updating in place.
--
-- The `date` field is stored as DATE_C, not DATE: Schemifier appends "_c" to column names that
-- collide with SQL reserved words - the same treatment ProductFee's `type` gets. Reproduced
-- exactly; naming it DATE would create a column the code never reads.
--
-- agreementhash is a SHA-256 of agreementtext, recomputed on every write by the entity's
-- beforeSave hook. It is derived data, so it must be written by whatever inserts the row rather
-- than trusted from the caller.
--
-- One unique index on useragreementid. Confirmed against a booted instance.

CREATE TABLE "PUBLIC"."USERAGREEMENT"(
    "UPDATEDAT" TIMESTAMP,
    "CREATEDAT" TIMESTAMP,
    "USERID" CHARACTER VARYING(255),
    "USERAGREEMENTID" CHARACTER VARYING(44),
    "AGREEMENTHASH" CHARACTER VARYING(64),
    "AGREEMENTTYPE" CHARACTER VARYING(64),
    "AGREEMENTTEXT" CHARACTER VARYING(1000000000),
    "DATE_C" DATE,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."USERAGREEMENT" ADD CONSTRAINT "PUBLIC"."USERAGREEMENT_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."USERAGREEMENT_USERAGREEMENTID" ON "PUBLIC"."USERAGREEMENT"("USERAGREEMENTID" NULLS FIRST);
