-- User invitations (seventy-first table off Lift Mapper). An invitation a bank issues to a
-- prospective user; the invitee follows a link carrying `secretkey` to claim it.
--
-- secretkey is a CSPRNG-generated Long (SecureRandomUtil), and it is the ONLY credential on the
-- invitation link - getUserInvitationBySecretLink looks up by it alone, with no bank scoping. It
-- is therefore security-relevant rather than an ordinary column, which is why the Doobie insert
-- generates it the same way rather than letting a caller pass one in.
--
-- Note there is NO index on secretkey despite every claim lookup filtering on it, and no
-- uniqueness constraint on it either. Confirmed against a booted instance; reproduced as-is,
-- since adding either is a schema decision beyond a storage swap.
--
-- One unique index on userinvitationid.

CREATE TABLE "PUBLIC"."USERINVITATION"(
    "USERINVITATIONID" CHARACTER VARYING(44),
    "FIRSTNAME" CHARACTER VARYING(50),
    "LASTNAME" CHARACTER VARYING(50),
    "PURPOSE" CHARACTER VARYING(50),
    "SECRETKEY" BIGINT,
    "UPDATEDAT" TIMESTAMP,
    "CREATEDAT" TIMESTAMP,
    "BANKID" CHARACTER VARYING(255),
    "COMPANY" CHARACTER VARYING(50),
    "STATUS" CHARACTER VARYING(50),
    "COUNTRY" CHARACTER VARYING(50),
    "EMAIL" CHARACTER VARYING(50),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."USERINVITATION" ADD CONSTRAINT "PUBLIC"."USERINVITATION_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."USERINVITATION_USERINVITATIONID" ON "PUBLIC"."USERINVITATION"("USERINVITATIONID" NULLS FIRST);
