-- Account access requests (seventy-third table off Lift Mapper). A maker/checker workflow: a
-- requestor asks for a user to be granted a view on an account, and a checker approves or
-- declines it exactly once.
--
-- "Exactly once" is enforced in SQL, not in Scala: updateStatus goes through
-- DoobieBusinessStatusQueries.conditionalAccountAccessRequestStatus, an
-- UPDATE ... WHERE id = ? AND status = 'INITIATED'. The loser of a concurrent approve/decline
-- gets 0 rows back and a Failure, rather than silently overwriting the other decision. That
-- guard predates this migration (see ConcurrentBusinessStatusRaceTest scenario M2) and the
-- migration leaves it exactly as it is - it is the whole reason the table is safe.
--
-- Four PLAIN indexes, none unique - including on accountaccessrequestid, which the provider
-- treats as an identifier. Confirmed against a booted instance; reproduced as-is.

CREATE TABLE "PUBLIC"."ACCOUNTACCESSREQUEST"(
    "VIEWID" CHARACTER VARYING(255),
    "ISSYSTEMVIEW" BOOLEAN,
    "REQUESTORUSERID" CHARACTER VARYING(44),
    "TARGETUSERID" CHARACTER VARYING(44),
    "CHECKERUSERID" CHARACTER VARYING(255),
    "CHECKERCOMMENT" CHARACTER VARYING(1000000000),
    "UPDATEDAT" TIMESTAMP,
    "CREATEDAT" TIMESTAMP,
    "BANKID" CHARACTER VARYING(44),
    "ACCOUNTID" CHARACTER VARYING(44),
    "STATUS" CHARACTER VARYING(64),
    "ACCOUNTACCESSREQUESTID" CHARACTER VARYING(36),
    "BUSINESSJUSTIFICATION" CHARACTER VARYING(1000000000),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."ACCOUNTACCESSREQUEST" ADD CONSTRAINT "PUBLIC"."ACCOUNTACCESSREQUEST_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."ACCOUNTACCESSREQUEST_ACCOUNTACCESSREQUESTID" ON "PUBLIC"."ACCOUNTACCESSREQUEST"("ACCOUNTACCESSREQUESTID" NULLS FIRST);
CREATE INDEX "PUBLIC"."ACCOUNTACCESSREQUEST_BANKID_ACCOUNTID" ON "PUBLIC"."ACCOUNTACCESSREQUEST"("BANKID" NULLS FIRST, "ACCOUNTID" NULLS FIRST);
CREATE INDEX "PUBLIC"."ACCOUNTACCESSREQUEST_REQUESTORUSERID" ON "PUBLIC"."ACCOUNTACCESSREQUEST"("REQUESTORUSERID" NULLS FIRST);
CREATE INDEX "PUBLIC"."ACCOUNTACCESSREQUEST_STATUS" ON "PUBLIC"."ACCOUNTACCESSREQUEST"("STATUS" NULLS FIRST);
