-- Bulk payments (seventy-fourth and seventy-fifth tables off Lift Mapper — two tables, one
-- entity file).
--
-- BULKPAYMENT: one row per item in a bulk transaction request. The unique index on
-- (transactionrequestid, itemindex) is what stops the same item being recorded twice for a
-- request.
--
-- BULKBATCHREFERENCE: one row per claimed batch_reference, scoped to a source account. Its unique
-- index on (frombankid, fromaccountid, batchreference) is the IDEMPOTENCY GUARD for bulk
-- submission: claimBatchReference relies on the database rejecting a duplicate claim, with tryo
-- turning that rejection into a Failure. Without the constraint, two concurrent submissions of
-- the same batch reference would both be accepted and the batch would execute twice. Not
-- decoration.
--
-- Every column is nullable, including those the code treats as required — Schemifier only marks
-- NOT NULL where dbNotNull_? says so, and this entity does not. failurereason and transactionid
-- are explicitly nullable and genuinely carry NULL (written from Option via orNull, read back
-- through Option), so their bindings must be Option-typed on the Doobie side.

CREATE TABLE "PUBLIC"."BULKPAYMENT"(
    "ROUTINGSCHEME" CHARACTER VARYING(64),
    "ITEMINDEX" INTEGER,
    "ENDTOENDID" CHARACTER VARYING(64),
    "FAILUREREASON" CHARACTER VARYING(1000),
    "CURRENCY" CHARACTER VARYING(8),
    "ADDRESS" CHARACTER VARYING(128),
    "DESCRIPTION" CHARACTER VARYING(2000),
    "TRANSACTIONID" CHARACTER VARYING(64),
    "STATUS" CHARACTER VARYING(16),
    "AMOUNT" CHARACTER VARYING(32),
    "TRANSACTIONREQUESTID" CHARACTER VARYING(64),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."BULKPAYMENT" ADD CONSTRAINT "PUBLIC"."BULKPAYMENT_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."BULKPAYMENT_TRANSACTIONREQUESTID" ON "PUBLIC"."BULKPAYMENT"("TRANSACTIONREQUESTID" NULLS FIRST);
CREATE UNIQUE INDEX "PUBLIC"."BULKPAYMENT_TRANSACTIONREQUESTID_ITEMINDEX" ON "PUBLIC"."BULKPAYMENT"("TRANSACTIONREQUESTID" NULLS FIRST, "ITEMINDEX" NULLS FIRST);

CREATE TABLE "PUBLIC"."BULKBATCHREFERENCE"(
    "FROMBANKID" CHARACTER VARYING(255),
    "FROMACCOUNTID" CHARACTER VARYING(255),
    "BATCHREFERENCE" CHARACTER VARYING(64),
    "TRANSACTIONREQUESTID" CHARACTER VARYING(64),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."BULKBATCHREFERENCE" ADD CONSTRAINT "PUBLIC"."BULKBATCHREFERENCE_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."BULKBATCHREFERENCE_FROMBANKID_FROMACCOUNTID_BATCHREFERENCE" ON "PUBLIC"."BULKBATCHREFERENCE"("FROMBANKID" NULLS FIRST, "FROMACCOUNTID" NULLS FIRST, "BATCHREFERENCE" NULLS FIRST);
