-- Endpoint mappings and the dynamic-entity projection registry.
--
-- ENDPOINTMAPPING(operationid) is unique GLOBALLY, not per bank, even though the provider looks
-- rows up by (operationid, bankid). A bank-level mapping and a system-level mapping therefore
-- cannot share an operation id — the second create fails rather than shadowing the first. That is
-- the existing contract and the endpoint tests depend on it; the bankid column narrows a read, it
-- does not widen the key.
--
-- ENDPOINTMAPPING.bankid genuinely holds NULL for system-level mappings, because the provider
-- writes bankId.getOrElse(null) and reads it back through a null/empty check. It is bound as an
-- Option so SQL NULL is preserved rather than throwing at bind time.
--
-- DYNAMICENTITYINDEX is the registry for DE_indexing: one row per declared indexed field, holding
-- the provisioning state machine and the hashed table/column identifiers. The projection *tables*
-- it describes are created by the Doobie provisioner outside any schema tool; this registry is a
-- normal migrated table. Its index on (entityname, bankid, fieldname) is plain, not unique, even
-- though markReady looks a row up by exactly that triple and inserts when absent — so a
-- concurrent double-provision would leave two rows. Pre-existing; reproduced as-is with id ASC
-- pinning which row a lookup sees.

CREATE TABLE "PUBLIC"."ENDPOINTMAPPING"(
    "ENDPOINTMAPPINGID" CHARACTER VARYING(36),
    "OPERATIONID" CHARACTER VARYING(255),
    "REQUESTMAPPING" CHARACTER VARYING(1000000000),
    "RESPONSEMAPPING" CHARACTER VARYING(1000000000),
    "BANKID" CHARACTER VARYING(255),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."ENDPOINTMAPPING" ADD CONSTRAINT "PUBLIC"."ENDPOINTMAPPING_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."ENDPOINTMAPPING_ENDPOINTMAPPINGID" ON "PUBLIC"."ENDPOINTMAPPING"("ENDPOINTMAPPINGID" NULLS FIRST);
CREATE UNIQUE INDEX "PUBLIC"."ENDPOINTMAPPING_OPERATIONID" ON "PUBLIC"."ENDPOINTMAPPING"("OPERATIONID" NULLS FIRST);

CREATE TABLE "PUBLIC"."DYNAMICENTITYINDEX"(
    "FIELDNAME" CHARACTER VARYING(255),
    "FIELDTYPE" CHARACTER VARYING(64),
    "INDEXKIND" CHARACTER VARYING(32),
    "SAFETABLENAME" CHARACTER VARYING(128),
    "SAFECOLUMNNAME" CHARACTER VARYING(128),
    "BACKFILLCHECKPOINT" CHARACTER VARYING(255),
    "ROWCOUNTEXPECTED" BIGINT,
    "COERCIONERRORS" BIGINT,
    "LASTERROR" CHARACTER VARYING(1000000000),
    "PROVISIONERVERSION" INTEGER,
    "ENTITYNAME" CHARACTER VARYING(255),
    "BANKID" CHARACTER VARYING(255),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "STATE" CHARACTER VARYING(32)
);
ALTER TABLE "PUBLIC"."DYNAMICENTITYINDEX" ADD CONSTRAINT "PUBLIC"."DYNAMICENTITYINDEX_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."DYNAMICENTITYINDEX_ENTITYNAME_BANKID_FIELDNAME" ON "PUBLIC"."DYNAMICENTITYINDEX"("ENTITYNAME" NULLS FIRST, "BANKID" NULLS FIRST, "FIELDNAME" NULLS FIRST);
