-- Physical cards and their PIN resets.
--
-- MAPPEDPHYSICALCARD.maccount is a BIGINT holding MAPPEDBANKACCOUNT's numeric primary key, not the
-- public account_id. The card's `account` accessor resolves it, and a card whose key does not
-- resolve throws — the trait types account as a bare BankAccount, so there is no absent case.
--
-- The unique index on (mbankid, mbankcardnumber, missuenumber) is the only constraint. Note it does
-- NOT cover mcardid, which is the handle getPhysicalCardForBank, updatePhysicalCard and
-- deletePhysicalCardForBank all key off, nor (mbankid, mserialnumber, mbankcardnumber), which is
-- what createPhysicalCard checks for an existing card before inserting. Both are generated or
-- caller-supplied ids that the code assumes unique without the database enforcing it.
-- Pre-existing; reproduced as-is, with id ASC pinning which row a lookup sees.
--
-- PINRESET.card holds MAPPEDPHYSICALCARD's numeric key. The rows were read through a Lift OneToMany
-- ordered by id ascending; the replacement query keeps that order.
--
-- There is no CARDACTION table. The Lift entity of that name was declared but never registered for
-- schema creation, so it has never existed in any database and nothing reads or writes it. It is
-- dropped rather than migrated — see the code comment.

CREATE TABLE "PUBLIC"."MAPPEDPHYSICALCARD"(
    "MBANKID" CHARACTER VARYING(50),
    "MREPLACEMENTDATE" TIMESTAMP,
    "MREPLACEMENTREASON" CHARACTER VARYING(255),
    "MCUSTOMERID" CHARACTER VARYING(255),
    "MCOLLECTED" TIMESTAMP,
    "MACCOUNT" BIGINT,
    "MPOSTED" TIMESTAMP,
    "MALLOWS" CHARACTER VARYING(255),
    "MNETWORKS" CHARACTER VARYING(255),
    "MCVV" CHARACTER VARYING(255),
    "MBRAND" CHARACTER VARYING(255),
    "MTECHNOLOGY" CHARACTER VARYING(255),
    "MCANCELLED" BOOLEAN,
    "MONHOTLIST" BOOLEAN,
    "MENABLED" BOOLEAN,
    "MEXPIRES" TIMESTAMP,
    "MVALIDFROM" TIMESTAMP,
    "MSERIALNUMBER" CHARACTER VARYING(50),
    "MNAMEONCARD" CHARACTER VARYING(128),
    "MISSUENUMBER" CHARACTER VARYING(10),
    "MCARDID" CHARACTER VARYING(255),
    "MCARDTYPE" CHARACTER VARYING(255),
    "MBANKCARDNUMBER" CHARACTER VARYING(50),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."MAPPEDPHYSICALCARD" ADD CONSTRAINT "PUBLIC"."MAPPEDPHYSICALCARD_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."MAPPEDPHYSICALCARD_MACCOUNT" ON "PUBLIC"."MAPPEDPHYSICALCARD"("MACCOUNT" NULLS FIRST);
CREATE UNIQUE INDEX "PUBLIC"."MAPPEDPHYSICALCARD_MBANKID_MBANKCARDNUMBER_MISSUENUMBER" ON "PUBLIC"."MAPPEDPHYSICALCARD"("MBANKID" NULLS FIRST, "MBANKCARDNUMBER" NULLS FIRST, "MISSUENUMBER" NULLS FIRST);

CREATE TABLE "PUBLIC"."PINRESET"(
    "CARD" BIGINT,
    "MREPLACEMENTDATE" TIMESTAMP,
    "MREPLACEMENTREASON" CHARACTER VARYING(255),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."PINRESET" ADD CONSTRAINT "PUBLIC"."PINRESET_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."PINRESET_CARD" ON "PUBLIC"."PINRESET"("CARD" NULLS FIRST);
