-- Entitlements: one row per (bank, user, role) grant.
--
-- The unique index on (mbankid, muserid, mrolename) is load-bearing for authorisation, not an
-- optimisation. addEntitlement relies on it: the insert is wrapped so that a concurrent duplicate
-- grant hits the constraint, and the loser then re-reads and returns the committed row instead of
-- failing or creating a second grant. Without it a role could be held twice and a single revoke
-- would leave one behind.
--
-- Four columns carry an explicit dbColumnName in the entity and so break the m-prefix convention:
-- group_id, process, granted_by_user_id and entitlement_request_id. The migration keeps those exact
-- names — the entity's field names are mGroupId, mProcess, mGrantedByUserId and
-- entitlement_request_id respectively.
--
-- group_id, process and granted_by_user_id default to '' and are read back through an empty check,
-- so absent means empty string. entitlement_request_id is the exception: it defaults to NULL, and
-- its reader additionally rejects the all-zero UUID, because only request-born grants set it.

CREATE TABLE "PUBLIC"."MAPPEDENTITLEMENT"(
    "MROLENAME" CHARACTER VARYING(255),
    "MBANKID" CHARACTER VARYING(44),
    "CREATEDAT" TIMESTAMP,
    "MUSERID" CHARACTER VARYING(44),
    "UPDATEDAT" TIMESTAMP,
    "MENTITLEMENTID" CHARACTER VARYING(36),
    "MCREATEDBYPROCESS" CHARACTER VARYING(255),
    "GROUP_ID" CHARACTER VARYING(255),
    "PROCESS" CHARACTER VARYING(255),
    "GRANTED_BY_USER_ID" CHARACTER VARYING(44),
    "ENTITLEMENT_REQUEST_ID" CHARACTER VARYING(36),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."MAPPEDENTITLEMENT" ADD CONSTRAINT "PUBLIC"."MAPPEDENTITLEMENT_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."MAPPEDENTITLEMENT_MBANKID_MUSERID_MROLENAME" ON "PUBLIC"."MAPPEDENTITLEMENT"("MBANKID" NULLS FIRST, "MUSERID" NULLS FIRST, "MROLENAME" NULLS FIRST);
CREATE UNIQUE INDEX "PUBLIC"."MAPPEDENTITLEMENT_MENTITLEMENTID" ON "PUBLIC"."MAPPEDENTITLEMENT"("MENTITLEMENTID" NULLS FIRST);
