-- Rate limiting: one row per (consumer, optional bank, optional api version, optional api name)
-- scope, valid over a date window.
--
-- The three optional scope columns hold SQL NULL, not '', when the scope is broader — the provider
-- writes them through orNull. That distinction is load-bearing: getByConsumerId resolves a limit by
-- trying four increasingly general scopes in order (consumer+version+name, consumer+name,
-- consumer+version, consumer) and each tier matches the columns it is NOT scoping on with
-- `IS NULL`. A row that stored '' instead of NULL would be invisible to every one of those tiers.
--
-- Note the readers are laxer than the queries: apiName/apiVersion/bankId map both NULL and '' to
-- None, while the lookups only accept NULL. Preserved as-is.
--
-- The six call-limit columns are NOT NULL-able in practice but carry no database default. Their
-- defaults come from props (rate_limiting_per_second and friends, -1 when unset) and are resolved
-- in application code at insert time, which is what Lift's field defaults did.
--
-- Only ratelimitingid is unique. Nothing stops two rows sharing a scope and an overlapping date
-- window; findMostRecentRateLimit picks by updatedat descending, so the newest wins.

CREATE TABLE "PUBLIC"."RATELIMITING"(
    "BANKID" CHARACTER VARYING(44),
    "CONSUMERID" CHARACTER VARYING(250),
    "PERSECONDCALLLIMIT" BIGINT,
    "PERMINUTECALLLIMIT" BIGINT,
    "PERHOURCALLLIMIT" BIGINT,
    "PERDAYCALLLIMIT" BIGINT,
    "PERWEEKCALLLIMIT" BIGINT,
    "PERMONTHCALLLIMIT" BIGINT,
    "FROMDATE" TIMESTAMP,
    "TODATE" TIMESTAMP,
    "APINAME" CHARACTER VARYING(250),
    "APIVERSION" CHARACTER VARYING(250),
    "RATELIMITINGID" CHARACTER VARYING(36),
    "CREATEDAT" TIMESTAMP,
    "UPDATEDAT" TIMESTAMP,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."RATELIMITING" ADD CONSTRAINT "PUBLIC"."RATELIMITING_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."RATELIMITING_RATELIMITINGID" ON "PUBLIC"."RATELIMITING"("RATELIMITINGID" NULLS FIRST);
