-- Products: one row per (bank, product code).
--
-- The unique index on (mbankid, mcode) is what makes the code a usable handle — every read, the
-- createOrUpdate decision and the cascade delete key off that pair.
--
-- mparentproductcode models the product hierarchy by value, not by foreign key: getProductTree
-- walks it by repeatedly looking up (bankId, parentProductCode). An empty string terminates the
-- walk, so a product with no parent must store "" and not NULL — which is what Mapper's untouched
-- MappedString default wrote. Storing NULL there would make the walk read a null and the tree
-- would break rather than end.
--
-- No column is nullable in practice for the same reason: every accessor returns a bare String and
-- the sandbox importer omits several fields, relying on the "" default.

CREATE TABLE "PUBLIC"."MAPPEDPRODUCT"(
    "MBANKID" CHARACTER VARYING(44),
    "MCODE" CHARACTER VARYING(50),
    "MNAME" CHARACTER VARYING(125),
    "MLICENSEID" CHARACTER VARYING(44),
    "MLICENSENAME" CHARACTER VARYING(255),
    "MPARENTPRODUCTCODE" CHARACTER VARYING(50),
    "MCATEGORY" CHARACTER VARYING(50),
    "MFAMILY" CHARACTER VARYING(50),
    "MSUPERFAMILY" CHARACTER VARYING(50),
    "MMOREINFOURL" CHARACTER VARYING(2000),
    "MDETAILS" CHARACTER VARYING(2000),
    "MDESCRIPTION" CHARACTER VARYING(2000),
    "MTERMSANDCONDITIONSURL" CHARACTER VARYING(2000),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."MAPPEDPRODUCT" ADD CONSTRAINT "PUBLIC"."MAPPEDPRODUCT_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."MAPPEDPRODUCT_MBANKID" ON "PUBLIC"."MAPPEDPRODUCT"("MBANKID" NULLS FIRST);
CREATE UNIQUE INDEX "PUBLIC"."MAPPEDPRODUCT_MBANKID_MCODE" ON "PUBLIC"."MAPPEDPRODUCT"("MBANKID" NULLS FIRST, "MCODE" NULLS FIRST);
