-- Dynamic message docs: one row per connector process definition.
--
-- `process` is unique GLOBALLY, not per bank, even though every read accepts an optional bank id
-- that narrows the match. A bank-level and a system-level doc therefore cannot share a process
-- name — the second create fails rather than shadowing the first. The bankId argument narrows a
-- read; it does not widen the key.
--
-- bankid genuinely holds NULL for system-level docs, because create writes
-- bankId.getOrElse(null). Note the READS are inconsistent with that write: when a bank id is
-- supplied they compare bankid to it, but when it is absent they do not constrain bankid at all,
-- so a system-level lookup also matches bank-level rows. Both behaviours are pre-existing and are
-- reproduced here.

CREATE TABLE "PUBLIC"."DYNAMICMESSAGEDOC"(
    "PROCESS" CHARACTER VARYING(255),
    "MESSAGEFORMAT" CHARACTER VARYING(255),
    "OUTBOUNDTOPIC" CHARACTER VARYING(255),
    "INBOUNDTOPIC" CHARACTER VARYING(255),
    "OUTBOUNDAVROSCHEMA" CHARACTER VARYING(1000000000),
    "INBOUNDAVROSCHEMA" CHARACTER VARYING(1000000000),
    "LANG" CHARACTER VARYING(50),
    "METHODBODY" CHARACTER VARYING(1000000000),
    "BANKID" CHARACTER VARYING(255),
    "DESCRIPTION" CHARACTER VARYING(255),
    "ADAPTERIMPLEMENTATION" CHARACTER VARYING(255),
    "DYNAMICMESSAGEDOCID" CHARACTER VARYING(44),
    "EXAMPLEOUTBOUNDMESSAGE" CHARACTER VARYING(1000000000),
    "EXAMPLEINBOUNDMESSAGE" CHARACTER VARYING(1000000000),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."DYNAMICMESSAGEDOC" ADD CONSTRAINT "PUBLIC"."DYNAMICMESSAGEDOC_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."DYNAMICMESSAGEDOC_DYNAMICMESSAGEDOCID" ON "PUBLIC"."DYNAMICMESSAGEDOC"("DYNAMICMESSAGEDOCID" NULLS FIRST);
CREATE UNIQUE INDEX "PUBLIC"."DYNAMICMESSAGEDOC_PROCESS" ON "PUBLIC"."DYNAMICMESSAGEDOC"("PROCESS" NULLS FIRST);
