-- Dynamic resource docs: one row per runtime-defined endpoint.
--
-- `roles` is stored as ROLES_C because ROLES collides with a SQL reserved word, which is why the
-- column name does not match the field.
--
-- The unique index on (requesturl, requestverb) is what makes a dynamic endpoint's route
-- single-valued — it is GLOBAL, not per bank, so a bank-level and a system-level doc cannot claim
-- the same verb and URL. dynamicresourcedocid is separately unique as the public handle.
--
-- bankid, examplerequestbody and successresponsebody all genuinely hold NULL: the provider writes
-- bankId.getOrElse(null) and maps the two optional JSON bodies through orNull. The readers turn a
-- blank body back into None, so an absent body must not become '' either.
--
-- As with dynamicmessagedoc the reads are laxer than the write: a supplied bank id filters on
-- bankid, while an absent one does not constrain it, so a system-level lookup also matches
-- bank-level rows. Pre-existing and reproduced.

CREATE TABLE "PUBLIC"."DYNAMICRESOURCEDOC"(
    "REQUESTVERB" CHARACTER VARYING(255),
    "REQUESTURL" CHARACTER VARYING(255),
    "SUMMARY" CHARACTER VARYING(255),
    "EXAMPLEREQUESTBODY" CHARACTER VARYING(255),
    "TAGS" CHARACTER VARYING(255),
    "ROLES_C" CHARACTER VARYING(255),
    "METHODBODY" CHARACTER VARYING(1000000000),
    "BANKID" CHARACTER VARYING(255),
    "DESCRIPTION" CHARACTER VARYING(255),
    "DYNAMICRESOURCEDOCID" CHARACTER VARYING(44),
    "PARTIALFUNCTIONNAME" CHARACTER VARYING(255),
    "SUCCESSRESPONSEBODY" CHARACTER VARYING(255),
    "ERRORRESPONSEBODIES" CHARACTER VARYING(255),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."DYNAMICRESOURCEDOC" ADD CONSTRAINT "PUBLIC"."DYNAMICRESOURCEDOC_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."DYNAMICRESOURCEDOC_DYNAMICRESOURCEDOCID" ON "PUBLIC"."DYNAMICRESOURCEDOC"("DYNAMICRESOURCEDOCID" NULLS FIRST);
CREATE UNIQUE INDEX "PUBLIC"."DYNAMICRESOURCEDOC_REQUESTURL_REQUESTVERB" ON "PUBLIC"."DYNAMICRESOURCEDOC"("REQUESTURL" NULLS FIRST, "REQUESTVERB" NULLS FIRST);
