-- Per-row access control for dynamic-entity data: who may read, update, delete or re-grant one
-- DYNAMICDATA row, and who granted them that.
--
-- The unique index on (dynamicdataid, userid) is what makes `grant` an upsert rather than an
-- append — one grant row per user per data row — and what lets `allows` answer a permission
-- question with a single lookup.
--
-- The index on (dynamicdataid, grantedby) serves the revoke walk: revoke follows GrantedBy edges
-- to remove the target user and everyone they granted downstream, so it reads the table by grantor
-- repeatedly.
--
-- bankid genuinely holds NULL for system-level entities, and both scoped queries use `IS NULL`
-- when no bank is supplied — the Lift NullRef, not "no filter". A row storing '' would be
-- invisible to those queries, so the column must stay nullable and the reads must keep the
-- three-way distinction.

CREATE TABLE "PUBLIC"."DYNAMICDATAACCESS"(
    "GRANTEDBY" CHARACTER VARYING(255),
    "CANREAD" BOOLEAN,
    "CANUPDATE" BOOLEAN,
    "CANDELETE" BOOLEAN,
    "CANGRANT" BOOLEAN,
    "ENTITYNAME" CHARACTER VARYING(255),
    "USERID" CHARACTER VARYING(255),
    "BANKID" CHARACTER VARYING(255),
    "DYNAMICDATAID" CHARACTER VARYING(255),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."DYNAMICDATAACCESS" ADD CONSTRAINT "PUBLIC"."DYNAMICDATAACCESS_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."DYNAMICDATAACCESS_DYNAMICDATAID_USERID" ON "PUBLIC"."DYNAMICDATAACCESS"("DYNAMICDATAID" NULLS FIRST, "USERID" NULLS FIRST);
CREATE INDEX "PUBLIC"."DYNAMICDATAACCESS_USERID_ENTITYNAME_BANKID" ON "PUBLIC"."DYNAMICDATAACCESS"("USERID" NULLS FIRST, "ENTITYNAME" NULLS FIRST, "BANKID" NULLS FIRST);
CREATE INDEX "PUBLIC"."DYNAMICDATAACCESS_DYNAMICDATAID_GRANTEDBY" ON "PUBLIC"."DYNAMICDATAACCESS"("DYNAMICDATAID" NULLS FIRST, "GRANTEDBY" NULLS FIRST);
