-- Dynamic entities: one row per runtime-defined entity type.
--
-- bankid genuinely holds NULL for system-level entities, and — unlike dynamicmessagedoc and
-- dynamicresourcedoc, whose reads leave bankid unconstrained when no bank is supplied — every read
-- here uses `IS NULL` for the system-level case (Lift's NullRef). A system-level lookup therefore
-- does NOT see bank-level entities. The three providers differ on this point and each keeps its own
-- behaviour; a row storing '' rather than NULL would be invisible to this one.
--
-- getDynamicEntities has a third mode: returnBothBankAndSystemLevel ignores the scope entirely and
-- returns every row.
--
-- Only dynamicentityid is unique. Nothing constrains (bankid, entityname) even though
-- getByEntityName treats that pair as a key, so two entities in one scope may share a name.
-- Pre-existing; reproduced with id ASC pinning which one a lookup sees.

CREATE TABLE "PUBLIC"."DYNAMICENTITY"(
    "DYNAMICENTITYID" CHARACTER VARYING(36),
    "UPDATEDAT" TIMESTAMP,
    "ENTITYNAME" CHARACTER VARYING(255),
    "METADATAJSON" CHARACTER VARYING(1000000000),
    "USERID" CHARACTER VARYING(255),
    "BANKID" CHARACTER VARYING(255),
    "HASPERSONALENTITY" BOOLEAN,
    "HASPUBLICACCESS" BOOLEAN,
    "HASCOMMUNITYACCESS" BOOLEAN,
    "USEROWLEVELACCESS" BOOLEAN,
    "CREATEDAT" TIMESTAMP,
    "PERSONALREQUIRESROLE" BOOLEAN,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."DYNAMICENTITY" ADD CONSTRAINT "PUBLIC"."DYNAMICENTITY_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."DYNAMICENTITY_DYNAMICENTITYID" ON "PUBLIC"."DYNAMICENTITY"("DYNAMICENTITYID" NULLS FIRST);
