-- Account access: the link between a user and a view. A user cannot use a view unless a row here
-- says so, which makes this table part of the authorisation path rather than metadata.
--
-- The unique index on (bank_id, account_id, view_id, user_fk, consumer_id) is load-bearing and all
-- five columns are needed. revokeAccess matches on (bank, account, view, user) and so cannot tell
-- two applications' grants apart; the per-consumer revokes match on (bank, account, view, consumer)
-- and so cannot tell two users apart — on a joint account they would delete whichever row came back
-- first. Undoing exactly one consent's grant needs the full tuple.
--
-- consumer_id defaults to ALL_CONSUMERS, meaning "any consumer may use this grant"; a real consumer
-- id restricts it to that application.
--
-- NOTE: deployed databases also carry a SECOND, quoted-lowercase "consumer_id" column beside this
-- one. It is dead. MigrationOfAccountAccessAddedConsumerId calls Helper.addColumnIfNotExists, which
-- emits ADD COLUMN IF NOT EXISTS "consumer_id" — a quoted identifier, which H2 and Postgres treat as
-- distinct from the unquoted CONSUMER_ID that Schemifier created. The IF NOT EXISTS check therefore
-- never matched, and the script added a duplicate column that nothing reads or writes. This
-- migration builds only the live column; the runtime script still runs and will still add its dead
-- twin, exactly as before.
--
-- view_fk is deprecated (superseded by bank_id/account_id/view_id) and is written by no code path.

CREATE TABLE "PUBLIC"."ACCOUNTACCESS"(
    "BANK_ID" CHARACTER VARYING(255),
    "ACCOUNT_ID" CHARACTER VARYING(255),
    "CREATEDAT" TIMESTAMP,
    "VIEW_ID" CHARACTER VARYING(44),
    "CONSUMER_ID" CHARACTER VARYING(255),
    "USER_FK" BIGINT,
    "VIEW_FK" BIGINT,
    "UPDATEDAT" TIMESTAMP,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."ACCOUNTACCESS" ADD CONSTRAINT "PUBLIC"."ACCOUNTACCESS_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."ACCOUNTACCESS_USER_FK" ON "PUBLIC"."ACCOUNTACCESS"("USER_FK" NULLS FIRST);
CREATE INDEX "PUBLIC"."ACCOUNTACCESS_VIEW_FK" ON "PUBLIC"."ACCOUNTACCESS"("VIEW_FK" NULLS FIRST);
CREATE UNIQUE INDEX "PUBLIC"."ACCOUNTACCESS_BANK_ID_ACCOUNT_ID_VIEW_ID_USER_FK_CONSUMER_ID" ON "PUBLIC"."ACCOUNTACCESS"("BANK_ID" NULLS FIRST, "ACCOUNT_ID" NULLS FIRST, "VIEW_ID" NULLS FIRST, "USER_FK" NULLS FIRST, "CONSUMER_ID" NULLS FIRST);
