-- Berlin Group signing baskets: one basket groups several payments and/or consents so the PSU can
-- authorise them with a single SCA.
--
-- The basket carries nothing but its id and its status (RCVD -> ACTC -> ... -> CANC); the two child
-- tables are pure join tables naming the payments and consents it covers, keyed by BASKETID, the
-- business id, not by the surrogate ID.
--
-- Membership is deliberately unconstrained: the indexes on (BASKETID, PAYMENTID) and
-- (BASKETID, CONSENTID) are not unique, so adding the same payment to a basket twice stores two
-- rows, and BASKETID itself is only indexed rather than unique. Reads resolve a basket by taking
-- the first match, so a duplicate would be invisible rather than an error. Preserved as it was.
--
-- The ids are 36-character UUIDs (MappedUUID), which is why the columns are narrower than the usual
-- 255.

CREATE TABLE "PUBLIC"."SIGNINGBASKET"(
    "STATUS" CHARACTER VARYING(50),
    "BASKETID" CHARACTER VARYING(36),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."SIGNINGBASKET" ADD CONSTRAINT "PUBLIC"."SIGNINGBASKET_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."SIGNINGBASKET_BASKETID" ON "PUBLIC"."SIGNINGBASKET"("BASKETID" NULLS FIRST);

CREATE TABLE "PUBLIC"."SIGNINGBASKETPAYMENT"(
    "BASKETID" CHARACTER VARYING(36),
    "PAYMENTID" CHARACTER VARYING(36),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."SIGNINGBASKETPAYMENT" ADD CONSTRAINT "PUBLIC"."SIGNINGBASKETPAYMENT_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."SIGNINGBASKETPAYMENT_BASKETID_PAYMENTID" ON "PUBLIC"."SIGNINGBASKETPAYMENT"("BASKETID" NULLS FIRST, "PAYMENTID" NULLS FIRST);

CREATE TABLE "PUBLIC"."SIGNINGBASKETCONSENT"(
    "BASKETID" CHARACTER VARYING(36),
    "CONSENTID" CHARACTER VARYING(36),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."SIGNINGBASKETCONSENT" ADD CONSTRAINT "PUBLIC"."SIGNINGBASKETCONSENT_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."SIGNINGBASKETCONSENT_BASKETID_CONSENTID" ON "PUBLIC"."SIGNINGBASKETCONSENT"("BASKETID" NULLS FIRST, "CONSENTID" NULLS FIRST);
