-- Consent requests: the first step of the consent flow. The client POSTs what it wants to be
-- allowed to do, gets back a consent-request id, and the consent itself is created later from this
-- stored payload.
--
-- PAYLOAD is the whole request body as JSON in one column, unbounded because it carries account
-- routings, a counterparty and a VRP limit set. Nothing indexes into it; it is read back whole.
--
-- CONSUMERID is nullable on purpose - the entity declared its default as null rather than "", and
-- createConsentRequest writes null when the call has no consumer attached. It records which
-- application asked, and is not a foreign key.

CREATE TABLE "PUBLIC"."CONSENTREQUEST"(
    "CONSENTREQUESTID" CHARACTER VARYING(36),
    "PAYLOAD" CHARACTER VARYING,
    "CONSUMERID" CHARACTER VARYING(250),
    "UPDATEDAT" TIMESTAMP,
    "CREATEDAT" TIMESTAMP,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."CONSENTREQUEST" ADD CONSTRAINT "PUBLIC"."CONSENTREQUEST_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."CONSENTREQUEST_CONSENTREQUESTID" ON "PUBLIC"."CONSENTREQUEST"("CONSENTREQUESTID" NULLS FIRST);
