-- Banks.
--
-- PERMALINK is the bank id every URL and every other table refers to, but it is NOT unique: the
-- entity carries a plain index and a comment saying a unique one would be right, held back by tests
-- that create the same bank twice. Reads therefore take the first match rather than assuming one,
-- and this script keeps the index exactly as it is - adding uniqueness here would reject rows that
-- current callers create.
--
-- CREATEDBYUSERID records the user behind POST /my/banks and is indexed because the self-service
-- quota counts a user's banks. It is empty for banks created before the column existed and for
-- paths with no authenticated user, such as the sandbox import, and is never serialized into an API
-- response.

CREATE TABLE "PUBLIC"."MAPPEDBANK"(
    "PERMALINK" CHARACTER VARYING(255),
    "FULLBANKNAME" CHARACTER VARYING(255),
    "SHORTBANKNAME" CHARACTER VARYING(100),
    "LOGOURL" CHARACTER VARYING(255),
    "WEBSITEURL" CHARACTER VARYING(255),
    "SWIFTBIC" CHARACTER VARYING(255),
    "MBANKROUTINGSCHEME" CHARACTER VARYING(255),
    "CREATEDBYUSERID" CHARACTER VARYING(255),
    "CREATEDAT" TIMESTAMP,
    "UPDATEDAT" TIMESTAMP,
    "NATIONAL_IDENTIFIER" CHARACTER VARYING(255),
    "MBANKROUTINGADDRESS" CHARACTER VARYING(255),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."MAPPEDBANK" ADD CONSTRAINT "PUBLIC"."MAPPEDBANK_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."MAPPEDBANK_PERMALINK" ON "PUBLIC"."MAPPEDBANK"("PERMALINK" NULLS FIRST);
CREATE INDEX "PUBLIC"."MAPPEDBANK_CREATEDBYUSERID" ON "PUBLIC"."MAPPEDBANK"("CREATEDBYUSERID" NULLS FIRST);
