-- Bank accounts, as the local (mapped) connector stores them.
--
-- (BANK, THEACCOUNTID) is unique: an account id identifies an account only within its bank.
--
-- ACCOUNTBALANCE is a signed integer in the smallest unit of the currency (cents, yen, øre), never
-- a decimal, and the balance updates go through DoobieBankAccountQueries so they can lock the row.
--
-- The two ACCOUNTRULESCHEMEn/ACCOUNTRULEVALUEn pairs are a fixed-width, denormalised list: exactly
-- two account rules can be stored, and a rule with an empty scheme is skipped when they are read
-- back. Account ROUTINGS are not here at all - they live in bankaccountrouting, one row per routing.
--
-- HOLDER is deprecated: the real account holders are in mapperaccountholders. The column is still
-- written and still read back as `accountHolder`.
--
-- ACCOUNTLASTUPDATE is the last transaction-refresh time and is only maintained by the HBCI path.

CREATE TABLE "PUBLIC"."MAPPEDBANKACCOUNT"(
    "ACCOUNTCURRENCY" CHARACTER VARYING(10),
    "ACCOUNTLABEL" CHARACTER VARYING(255),
    "ACCOUNTNAME" CHARACTER VARYING(255),
    "ACCOUNTLASTUPDATE" TIMESTAMP,
    "ACCOUNTBALANCE" BIGINT,
    "MBRANCHID" CHARACTER VARYING(44),
    "CREATEDAT" TIMESTAMP,
    "BANK" CHARACTER VARYING(44),
    "THEACCOUNTID" CHARACTER VARYING(64),
    "ACCOUNTNUMBER" CHARACTER VARYING(128),
    "UPDATEDAT" TIMESTAMP,
    "ACCOUNTRULESCHEME1" CHARACTER VARYING(10),
    "ACCOUNTRULEVALUE1" BIGINT,
    "ACCOUNTRULESCHEME2" CHARACTER VARYING(10),
    "ACCOUNTRULEVALUE2" BIGINT,
    "KIND" CHARACTER VARYING(255),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "HOLDER" CHARACTER VARYING(100)
);
ALTER TABLE "PUBLIC"."MAPPEDBANKACCOUNT" ADD CONSTRAINT "PUBLIC"."MAPPEDBANKACCOUNT_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."MAPPEDBANKACCOUNT_BANK_THEACCOUNTID" ON "PUBLIC"."MAPPEDBANKACCOUNT"("BANK" NULLS FIRST, "THEACCOUNTID" NULLS FIRST);
