-- View definitions: what a view is allowed to show and do on an account.
--
-- A SYSTEM view has NULL bank_id and account_id and is scoped by view_id alone; a CUSTOM view
-- belongs to one account and is scoped by all three. That is why the reads use IS NULL rather than
-- an equality test, and why the unique key below is a composed string rather than a column tuple:
-- SQL treats NULLs as distinct, so a unique index over (bank_id, account_id, view_id) would not
-- stop two system views sharing a view id.
--
-- COMPOSITE_UNIQUE_KEY is that composed key - "|<bank>|--|<account>|--|<view>|" - written on every
-- save. The entity marks it deprecated because no API code reads it, but its unique index is the
-- only thing preventing a duplicate view, and ConcurrentViewPermissionRaceTest depends on the
-- database rejecting the loser of a concurrent create. It stays.
--
-- The primary key column is ID_, not ID: the entity declared its own MappedLongIndex.
--
-- CANGRANTACCESSTOVIEWS_ and CANREVOKEACCESSTOVIEWS_ are DEAD columns. Both accessors read the
-- ViewPermission table instead (CAN_GRANT_ACCESS_TO_VIEWS / CAN_REVOKE_ACCESS_TO_VIEWS rows), as
-- do all the other can* accessors since the per-permission boolean columns were retired. The
-- columns are recreated here so an existing database and a fresh one still have the same shape.

CREATE TABLE "PUBLIC"."VIEWDEFINITION"(
    "ACCOUNT_ID" CHARACTER VARYING(64),
    "CREATEDAT" TIMESTAMP,
    "NAME_" CHARACTER VARYING(125),
    "VIEW_ID" CHARACTER VARYING(44),
    "UPDATEDAT" TIMESTAMP,
    "DESCRIPTION_" CHARACTER VARYING(255),
    "METADATAVIEW_" CHARACTER VARYING(44),
    "ISSYSTEM_" BOOLEAN,
    "ISPUBLIC_" BOOLEAN,
    "ISFIREHOSE_" BOOLEAN,
    "BANK_ID" CHARACTER VARYING(44),
    "ID_" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "COMPOSITE_UNIQUE_KEY" CHARACTER VARYING(512),
    "USEPRIVATEALIASIFONEEXISTS_" BOOLEAN,
    "USEPUBLICALIASIFONEEXISTS_" BOOLEAN,
    "HIDEOTHERACCOUNTMETADATAIFALIAS_" BOOLEAN,
    "CANGRANTACCESSTOVIEWS_" CHARACTER VARYING,
    "CANREVOKEACCESSTOVIEWS_" CHARACTER VARYING
);
ALTER TABLE "PUBLIC"."VIEWDEFINITION" ADD CONSTRAINT "PUBLIC"."VIEWDEFINITION_PK" PRIMARY KEY("ID_");
CREATE UNIQUE INDEX "PUBLIC"."VIEWDEFINITION_COMPOSITE_UNIQUE_KEY" ON "PUBLIC"."VIEWDEFINITION"("COMPOSITE_UNIQUE_KEY" NULLS FIRST);
CREATE INDEX "PUBLIC"."VIEWDEFINITION_ISSYSTEM_" ON "PUBLIC"."VIEWDEFINITION"("ISSYSTEM_" NULLS FIRST);
CREATE INDEX "PUBLIC"."VIEWDEFINITION_ISPUBLIC_" ON "PUBLIC"."VIEWDEFINITION"("ISPUBLIC_" NULLS FIRST);
CREATE INDEX "PUBLIC"."VIEWDEFINITION_ISFIREHOSE_" ON "PUBLIC"."VIEWDEFINITION"("ISFIREHOSE_" NULLS FIRST);
CREATE INDEX "PUBLIC"."VIEWDEFINITION_ISSYSTEM__VIEW_ID" ON "PUBLIC"."VIEWDEFINITION"("ISSYSTEM_" NULLS FIRST, "VIEW_ID" NULLS FIRST);
CREATE INDEX "PUBLIC"."VIEWDEFINITION_BANK_ID_ACCOUNT_ID_VIEW_ID" ON "PUBLIC"."VIEWDEFINITION"("BANK_ID" NULLS FIRST, "ACCOUNT_ID" NULLS FIRST, "VIEW_ID" NULLS FIRST);
