-- OAuth 1.0a request and access tokens.
--
-- KEY_C carries the Schemifier suffix for a reserved word; the entity field is `key`.
--
-- CONSUMERID and USERFOREIGNKEY are BIGINT SURROGATE keys, pointing at CONSUMER.ID and
-- RESOURCEUSER.ID. Note that CONSUMER also has its own VARCHAR business id in a column likewise
-- called CONSUMERID - the two are unrelated, and this one is the numeric one.
--
-- Neither key column is unique: the same consumer and user hold a series of tokens over time, and
-- DirectLogin's "only the last issued token counts" rule is a query over expiration dates rather
-- than a constraint.

CREATE TABLE "PUBLIC"."TOKEN"(
    "TOKENTYPE" CHARACTER VARYING(10),
    "EXPIRATIONDATE" TIMESTAMP,
    "INSERTDATE" TIMESTAMP,
    "CALLBACKURL" CHARACTER VARYING(250),
    "USERFOREIGNKEY" BIGINT,
    "CONSUMERID" BIGINT,
    "VERIFIER" CHARACTER VARYING(250),
    "SECRET" CHARACTER VARYING(250),
    "THIRDPARTYAPPLICATIONSECRET" CHARACTER VARYING(10),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "KEY_C" CHARACTER VARYING(250),
    "DURATION" BIGINT
);
ALTER TABLE "PUBLIC"."TOKEN" ADD CONSTRAINT "PUBLIC"."TOKEN_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."TOKEN_USERFOREIGNKEY" ON "PUBLIC"."TOKEN"("USERFOREIGNKEY" NULLS FIRST);
CREATE INDEX "PUBLIC"."TOKEN_CONSUMERID" ON "PUBLIC"."TOKEN"("CONSUMERID" NULLS FIRST);
