-- Consumers: the registered applications that call the API.
--
-- Two ids again, and they are not interchangeable: ID is the surrogate key that TOKEN points at,
-- while CONSUMERID is the string id the API exposes as consumer_id and that other tables (notably
-- MAPPEDCONSENT.MCONSUMERID) keep copies of. CONSUMERID is 250 wide because it holds more than
-- UUIDs - gateway-login app ids, and the "azp_UUID" composites OAuth2 auto-creates. Do not narrow
-- it without narrowing every table that copies it.
--
-- KEY_C carries the Schemifier suffix for a reserved word; the entity field is `key`.
--
-- AZP and SUB default to a fresh UUID rather than NULL, deliberately: the unique index over
-- (AZP, SUB) is what de-duplicates auto-created OIDC consumers, and databases disagree about
-- whether NULLs collide. A generated value makes every hand-registered consumer distinct under
-- that index without relying on NULL semantics.
--
-- The six PER*CALLLIMIT columns are the rate limits; -1 means no limit, and they default from
-- props rather than from the DDL.

CREATE TABLE "PUBLIC"."CONSUMER"(
    "CLIENTCERTIFICATE" CHARACTER VARYING(4000),
    "AZP" CHARACTER VARYING(250),
    "JWKSURI" CHARACTER VARYING(500),
    "CREATEDBYUSERID" CHARACTER VARYING(36),
    "CONSUMERID" CHARACTER VARYING(250),
    "CREATEDAT" TIMESTAMP,
    "COMPANY" CHARACTER VARYING(100),
    "ISS" CHARACTER VARYING(250),
    "AUD" CHARACTER VARYING,
    "LOGOURL" CHARACTER VARYING(250),
    "UPDATEDAT" TIMESTAMP,
    "SECRET" CHARACTER VARYING(250),
    "APPTYPE" CHARACTER VARYING(20),
    "DEVELOPEREMAIL" CHARACTER VARYING(100),
    "REDIRECTURL" CHARACTER VARYING(250),
    "PERSECONDCALLLIMIT" BIGINT,
    "PERMINUTECALLLIMIT" BIGINT,
    "PERHOURCALLLIMIT" BIGINT,
    "PERDAYCALLLIMIT" BIGINT,
    "PERWEEKCALLLIMIT" BIGINT,
    "PERMONTHCALLLIMIT" BIGINT,
    "USERAUTHENTICATIONURL" CHARACTER VARYING(250),
    "NAME" CHARACTER VARYING(100),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "KEY_C" CHARACTER VARYING(250),
    "ISACTIVE" BOOLEAN,
    "SUB" CHARACTER VARYING(250),
    "DESCRIPTION" CHARACTER VARYING
);
ALTER TABLE "PUBLIC"."CONSUMER" ADD CONSTRAINT "PUBLIC"."CONSUMER_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."CONSUMER_NAME" ON "PUBLIC"."CONSUMER"("NAME" NULLS FIRST);
CREATE UNIQUE INDEX "PUBLIC"."CONSUMER_KEY_C" ON "PUBLIC"."CONSUMER"("KEY_C" NULLS FIRST);
CREATE UNIQUE INDEX "PUBLIC"."CONSUMER_AZP_SUB" ON "PUBLIC"."CONSUMER"("AZP" NULLS FIRST, "SUB" NULLS FIRST);
