-- Resource users: the person (or consent-minted pseudo-person) every account, view, entitlement
-- and consent hangs off.
--
-- Two ids once more: ID is the surrogate key AUTHUSER.USER_C points at, and USERID_ is the UUID the
-- API exposes as user_id. Other tables copy USERID_, never ID.
--
-- PROVIDER_ and NAME_ carry the Schemifier suffix for reserved words; the entity fields are
-- `provider` and `name`. PROVIDERID is the id the identity provider knows the user by - in practice
-- the username - and defaults to NAME_ when a caller does not supply one.
--
-- Two unique indexes, and only the first was declared on the entity: (PROVIDER_, PROVIDERID) came
-- from dbIndexes, while RESOURCEUSER_USERID_UNIQUE was added by MigrationOfResourceUser. Both are
-- recreated here so a fresh database matches a migrated one.
--
-- LASTMARKETINGAGREEMENTSIGNEDDATE is a DATE, not a TIMESTAMP: it records the day an agreement was
-- signed, and the driver hands it back as java.sql.Date.

CREATE TABLE "PUBLIC"."RESOURCEUSER"(
    "EMAIL" CHARACTER VARYING(100),
    "PROVIDERID" CHARACTER VARYING(100),
    "USERID_" CHARACTER VARYING(36),
    "NAME_" CHARACTER VARYING(100),
    "PROVIDER_" CHARACTER VARYING(100),
    "COMPANY" CHARACTER VARYING(50),
    "CREATEDBYCONSENTID" CHARACTER VARYING(100),
    "ISDELETED" BOOLEAN,
    "LASTUSEDLOCALE" CHARACTER VARYING(10),
    "ISNATURALPERSON" BOOLEAN,
    "PRINCIPALUSERID" CHARACTER VARYING(100),
    "CREATEDBYUSERINVITATIONID" CHARACTER VARYING(100),
    "LASTMARKETINGAGREEMENTSIGNEDDATE" DATE,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);
ALTER TABLE "PUBLIC"."RESOURCEUSER" ADD CONSTRAINT "PUBLIC"."RESOURCEUSER_PK" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "PUBLIC"."RESOURCEUSER_PROVIDER__PROVIDERID" ON "PUBLIC"."RESOURCEUSER"("PROVIDER_" NULLS FIRST, "PROVIDERID" NULLS FIRST);
CREATE UNIQUE INDEX "PUBLIC"."RESOURCEUSER_USERID_UNIQUE" ON "PUBLIC"."RESOURCEUSER"("USERID_" NULLS FIRST);
