-- Auth users: the login half of a user. AuthUser holds a username, a password and an email; the
-- ResourceUser it points at through USER_C holds everything the API cares about.
--
-- PASSWORD_PW and PASSWORD_SLT are the two halves MappedPassword split a bcrypt hash into, and the
-- split is not decorative: v_oidc_users selects both columns, and OBP-OIDC and the Keycloak user
-- storage provider verify logins straight off that view. PASSWORD_PW holds "b;" + the first 44
-- characters of the 60-character bcrypt string, PASSWORD_SLT the remaining 16; verification puts
-- them back together. Neither column may be renamed, widened past what the view expects, or merged.
--
-- UNIQUEID is the email-validation token: 32 random characters, regenerated once the address is
-- confirmed.
--
-- USER_C is RESOURCEUSER.ID, and is NULL - not 0 - while an AuthUser has no ResourceUser yet.

CREATE TABLE "PUBLIC"."AUTHUSER"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "FIRSTNAME" CHARACTER VARYING(100),
    "LASTNAME" CHARACTER VARYING(100),
    "EMAIL" CHARACTER VARYING(100),
    "USERNAME" CHARACTER VARYING(100),
    "PASSWORD_PW" CHARACTER VARYING(48),
    "PASSWORD_SLT" CHARACTER VARYING(20),
    "PROVIDER" CHARACTER VARYING(100),
    "CREATEDAT" TIMESTAMP,
    "UNIQUEID" CHARACTER VARYING(32),
    "UPDATEDAT" TIMESTAMP,
    "SUPERUSER" BOOLEAN,
    "TIMEZONE" CHARACTER VARYING(32),
    "PASSWORDSHOULDBECHANGED" BOOLEAN,
    "LOCALE" CHARACTER VARYING(16),
    "VALIDATED" BOOLEAN,
    "USER_C" BIGINT
);
ALTER TABLE "PUBLIC"."AUTHUSER" ADD CONSTRAINT "PUBLIC"."AUTHUSER_PK" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."AUTHUSER_UNIQUEID" ON "PUBLIC"."AUTHUSER"("UNIQUEID" NULLS FIRST);
CREATE INDEX "PUBLIC"."AUTHUSER_USER_C" ON "PUBLIC"."AUTHUSER"("USER_C" NULLS FIRST);
CREATE UNIQUE INDEX "PUBLIC"."AUTHUSER_USERNAME_PROVIDER" ON "PUBLIC"."AUTHUSER"("USERNAME" NULLS FIRST, "PROVIDER" NULLS FIRST);
