// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package code.obp.grpc.logcache.api

/** @param apiInstanceId
  *   Identifies which OBP instance (pod) emitted this entry. Sourced from
  *   the `api_instance_id` prop — either a configured value suffixed with a
  *   per-JVM UUID, or a pure UUID if the prop is unset. See
  *   code.api.constant.Constant.ApiInstanceId.
  */
@SerialVersionUID(0L)
final case class LogCacheEntry(
    level: code.obp.grpc.logcache.api.LogLevel = code.obp.grpc.logcache.api.LogLevel.LOG_LEVEL_UNSPECIFIED,
    message: _root_.scala.Predef.String = "",
    timestamp: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp] = _root_.scala.None,
    apiInstanceId: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[LogCacheEntry] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = level.value
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(1, __value)
        }
      };
      
      {
        val __value = message
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      if (timestamp.isDefined) {
        val __value = timestamp.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      
      {
        val __value = apiInstanceId
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = level.value
        if (__v != 0) {
          _output__.writeEnum(1, __v)
        }
      };
      {
        val __v = message
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      timestamp.foreach { __v =>
        val __m = __v
        _output__.writeTag(3, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = apiInstanceId
        if (!__v.isEmpty) {
          _output__.writeString(4, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withLevel(__v: code.obp.grpc.logcache.api.LogLevel): LogCacheEntry = copy(level = __v)
    def withMessage(__v: _root_.scala.Predef.String): LogCacheEntry = copy(message = __v)
    def getTimestamp: com.google.protobuf.timestamp.Timestamp = timestamp.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)
    def clearTimestamp: LogCacheEntry = copy(timestamp = _root_.scala.None)
    def withTimestamp(__v: com.google.protobuf.timestamp.Timestamp): LogCacheEntry = copy(timestamp = Option(__v))
    def withApiInstanceId(__v: _root_.scala.Predef.String): LogCacheEntry = copy(apiInstanceId = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = level.javaValueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
        case 2 => {
          val __t = message
          if (__t != "") __t else null
        }
        case 3 => timestamp.orNull
        case 4 => {
          val __t = apiInstanceId
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PEnum(level.scalaValueDescriptor)
        case 2 => _root_.scalapb.descriptors.PString(message)
        case 3 => timestamp.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 4 => _root_.scalapb.descriptors.PString(apiInstanceId)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: code.obp.grpc.logcache.api.LogCacheEntry.type = code.obp.grpc.logcache.api.LogCacheEntry
    // @@protoc_insertion_point(GeneratedMessage[code.obp.grpc.logcache.g1.LogCacheEntry])
}

object LogCacheEntry extends scalapb.GeneratedMessageCompanion[code.obp.grpc.logcache.api.LogCacheEntry] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[code.obp.grpc.logcache.api.LogCacheEntry] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): code.obp.grpc.logcache.api.LogCacheEntry = {
    var __level: code.obp.grpc.logcache.api.LogLevel = code.obp.grpc.logcache.api.LogLevel.LOG_LEVEL_UNSPECIFIED
    var __message: _root_.scala.Predef.String = ""
    var __timestamp: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp] = _root_.scala.None
    var __apiInstanceId: _root_.scala.Predef.String = ""
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 8 =>
          __level = code.obp.grpc.logcache.api.LogLevel.fromValue(_input__.readEnum())
        case 18 =>
          __message = _input__.readStringRequireUtf8()
        case 26 =>
          __timestamp = _root_.scala.Option(__timestamp.fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.timestamp.Timestamp](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 34 =>
          __apiInstanceId = _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    code.obp.grpc.logcache.api.LogCacheEntry(
        level = __level,
        message = __message,
        timestamp = __timestamp,
        apiInstanceId = __apiInstanceId,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[code.obp.grpc.logcache.api.LogCacheEntry] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      code.obp.grpc.logcache.api.LogCacheEntry(
        level = code.obp.grpc.logcache.api.LogLevel.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(code.obp.grpc.logcache.api.LogLevel.LOG_LEVEL_UNSPECIFIED.scalaValueDescriptor).number),
        message = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        timestamp = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.timestamp.Timestamp]]),
        apiInstanceId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = LogCacheProto.javaDescriptor.getMessageTypes().get(1)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = LogCacheProto.scalaDescriptor.messages(1)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 3 => __out = com.google.protobuf.timestamp.Timestamp
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = {
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 1 => code.obp.grpc.logcache.api.LogLevel
    }
  }
  lazy val defaultInstance = code.obp.grpc.logcache.api.LogCacheEntry(
    level = code.obp.grpc.logcache.api.LogLevel.LOG_LEVEL_UNSPECIFIED,
    message = "",
    timestamp = _root_.scala.None,
    apiInstanceId = ""
  )
  implicit class LogCacheEntryLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, code.obp.grpc.logcache.api.LogCacheEntry]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, code.obp.grpc.logcache.api.LogCacheEntry](_l) {
    def level: _root_.scalapb.lenses.Lens[UpperPB, code.obp.grpc.logcache.api.LogLevel] = field(_.level)((c_, f_) => c_.copy(level = f_))
    def message: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.message)((c_, f_) => c_.copy(message = f_))
    def timestamp: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.timestamp.Timestamp] = field(_.getTimestamp)((c_, f_) => c_.copy(timestamp = _root_.scala.Option(f_)))
    def optionalTimestamp: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.google.protobuf.timestamp.Timestamp]] = field(_.timestamp)((c_, f_) => c_.copy(timestamp = f_))
    def apiInstanceId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.apiInstanceId)((c_, f_) => c_.copy(apiInstanceId = f_))
  }
  final val LEVEL_FIELD_NUMBER = 1
  final val MESSAGE_FIELD_NUMBER = 2
  final val TIMESTAMP_FIELD_NUMBER = 3
  final val API_INSTANCE_ID_FIELD_NUMBER = 4
  def of(
    level: code.obp.grpc.logcache.api.LogLevel,
    message: _root_.scala.Predef.String,
    timestamp: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp],
    apiInstanceId: _root_.scala.Predef.String
  ): _root_.code.obp.grpc.logcache.api.LogCacheEntry = _root_.code.obp.grpc.logcache.api.LogCacheEntry(
    level,
    message,
    timestamp,
    apiInstanceId
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[code.obp.grpc.logcache.g1.LogCacheEntry])
}
