package code.metadata.counterparties

import code.api.cache.Caching
import code.api.util.{APIUtil, DoobieUtil}
import code.users.Users
import code.util.Helper.MdcLoggable
import com.openbankproject.commons.model._
import doobie._
import doobie.implicits._
import doobie.implicits.javasql._
import net.liftweb.common.{Box, Empty, Failure, Full}
import net.liftweb.util.Helpers.tryo
import net.liftweb.util.StringHelpers

import java.util.{Date, UUID}
import scala.concurrent.duration._

// For now, there are two Counterparties: one is used for CreateCounterParty.Counterparty, the other is for getTransactions.Counterparty.
// 1st is created by app explicitly, when use `CreateCounterParty` endpoint. This will be stored in database .
// 2nd is generated by obp implicitly, when use `getTransactions` endpoint. This will not be stored in database, but we create the CounterpartyMetadata for it. And the CounterpartyMetadata is in database.
// They are relevant somehow, but they are different data for now. Both data can be get by the following `MapperCounterparties` object.
object MapperCounterparties extends Counterparties with MdcLoggable {

  // TODO Rewrite caching function
  val MetadataTTL = 0 // getSecondsCache("getOrCreateMetadata")

  override def getOrCreateMetadata(bankId: BankId, accountId: AccountId, counterpartyId: String, counterpartyName:String): Box[CounterpartyMetadata] = {
    val cacheKey = ("code.metadata.counterparties.MapperCounterparties", "getOrCreateMetadata", List(bankId, accountId, counterpartyId, counterpartyName).mkString("_"))
    Caching.memoizeSyncWithProvider(Some(cacheKey.toString()))(MetadataTTL.second) {

      /**
        * Generates a new alias name that is guaranteed not to collide with any existing public alias names
        * for the account in question
        */
      def newPublicAliasName(): String = {
        val firstAliasAttempt = "ALIAS_" + UUID.randomUUID.toString.toUpperCase.take(6)

        // NOTE: this maps to the addPublicAlias FUNCTION, not to the alias value, so the list holds
        // functions and isDuplicate below can never match. The collision check has therefore never
        // fired; the alias is whatever the first attempt produced. Preserved verbatim - correcting
        // it would change which alias existing sandboxes generate, and belongs in its own change.
        val counterpartyMetadatasPublicAlias = MappedCounterpartyMetadata
          .findAllByBankAndAccount(bankId.value, accountId.value)
          .map(_.addPublicAlias)

        def isDuplicate(publicAlias: String) = counterpartyMetadatasPublicAlias.contains(publicAlias)

        /**
          * Appends things to @publicAlias until it a unique public alias name within @account
          */
        def appendUntilUnique(publicAlias: String): String = {
          val newAlias = publicAlias + UUID.randomUUID.toString.toUpperCase.take(1)
          // Recursive call.
          if (isDuplicate(newAlias)) appendUntilUnique(newAlias)
          else newAlias
        }

        if (isDuplicate(firstAliasAttempt)) appendUntilUnique(firstAliasAttempt)
        else firstAliasAttempt
      }

      def findMappedCounterpartyMetadataById(counterpartyId: String) =
        MappedCounterpartyMetadata.findByCounterpartyId(counterpartyId)

      findMappedCounterpartyMetadataById(counterpartyId) match {
        case Full(e) =>
          logger.debug(s"getOrCreateMetadata--Get MappedCounterpartyMetadata counterpartyId($counterpartyId)")
          Full(e)
        // Create it!
        case _ => {
          logger.debug(s"getOrCreateMetadata--Create MappedCounterpartyMetadata counterpartyId($counterpartyId)")
          tryo {
            MappedCounterpartyMetadata.insert(
              counterpartyId = counterpartyId,
              thisBankId = bankId.value,
              thisAccountId = accountId.value,
              counterpartyName = counterpartyName,
              publicAlias = newPublicAliasName())
          } match {
            case Full(created) => Full(created)
            // Two concurrent callers can both miss the read above; the unique index on
            // counterpartyId rejects the loser's insert, and it reads the winner's row instead.
            case Failure(_, _, _) =>
              findMappedCounterpartyMetadataById(counterpartyId)
            case other => other
          }
        }
      }
    }
  }

  // Get all counterparty metadata for a single OBP account
  override def getMetadatas(originalPartyBankId: BankId, originalPartyAccountId: AccountId): List[CounterpartyMetadata] =
    MappedCounterpartyMetadata.findAllByBankAndAccount(originalPartyBankId.value, originalPartyAccountId.value)

  override def getMetadata(originalPartyBankId: BankId, originalPartyAccountId: AccountId, counterpartyMetadataId: String): Box[CounterpartyMetadata] =
    /**
     * This particular implementation requires the metadata id to be the same as the otherParty (OtherBankAccount) id
     */
    MappedCounterpartyMetadata.findByBankAccountAndCounterpartyId(
      originalPartyBankId.value, originalPartyAccountId.value, counterpartyMetadataId)

  override def deleteMetadata(originalPartyBankId: BankId, originalPartyAccountId: AccountId, counterpartyMetadataId: String): Box[Boolean] =
    MappedCounterpartyMetadata.findByBankAccountAndCounterpartyId(
      originalPartyBankId.value, originalPartyAccountId.value, counterpartyMetadataId)
      .map(metadata => MappedCounterpartyMetadata.deleteById(metadata.metadataPrimaryKey))

  def addMetadata(bankId: BankId, accountId : AccountId): Box[CounterpartyMetadata] =
    // Deliberately has no counterparty id: this creates the metadata row for an account before any
    // counterparty is known.
    Full(MappedCounterpartyMetadata.insertForAccount(bankId.value, accountId.value))


  override def getCounterparty(counterpartyId : String): Box[CounterpartyTrait] =
    MappedCounterparty.findByCounterpartyId(counterpartyId)

  override def deleteCounterparty(counterpartyId : String): Box[Boolean] =
    MappedCounterparty.findByCounterpartyId(counterpartyId)
      .map(counterparty => MappedCounterparty.deleteById(counterparty.counterpartyPrimaryKey))

  //TODO, here has a problem, MappedCounterparty has no unique constrain on IBan. But we get Counterparty By Iban. For now, we do not support update Counterpary endpoint. Here we only return the latest record.
  override def getCounterpartyByIban(iban : String): Box[MappedCounterparty] =
    MappedCounterparty.findNewestBySecondaryRoutingAddress(iban)

  def getCounterpartyByIbanAndBankAccountId(iban : String, bankId: BankId, accountId: AccountId): Box[MappedCounterparty] =
    MappedCounterparty.findBySecondaryRoutingAddressAndAccount(iban, bankId.value, accountId.value)

  override def getCounterpartyByRoutings(
    otherBankRoutingScheme: String,
    otherBankRoutingAddress: String,
    otherBranchRoutingScheme: String,
    otherBranchRoutingAddress: String,
    otherAccountRoutingScheme: String,
    otherAccountRoutingAddress: String
  ): Box[CounterpartyTrait] =
    MappedCounterparty.findByRoutings(
      otherBankRoutingScheme, otherBankRoutingAddress,
      otherBranchRoutingScheme, otherBranchRoutingAddress,
      otherAccountRoutingScheme, otherAccountRoutingAddress)

  override def getCounterpartyBySecondaryRouting(
    otherAccountSecondaryRoutingScheme: String,
    otherAccountSecondaryRoutingAddress: String
  ): Box[CounterpartyTrait] =
    MappedCounterparty.findBySecondaryRouting(
      otherAccountSecondaryRoutingScheme, otherAccountSecondaryRoutingAddress)



  override def getCounterparties(thisBankId: BankId, thisAccountId: AccountId, viewId: ViewId): Box[List[CounterpartyTrait]] =
    Full(MappedCounterparty.findAllByAccountAndView(thisBankId.value, thisAccountId.value, viewId.value))

  override def createCounterparty(
                                  createdByUserId: String,
                                  thisBankId: String,
                                  thisAccountId : String,
                                  thisViewId : String,
                                  name: String,
                                  otherAccountRoutingScheme : String,
                                  otherAccountRoutingAddress : String,
                                  otherBankRoutingScheme : String,
                                  otherBankRoutingAddress : String,
                                  otherBranchRoutingScheme: String,
                                  otherBranchRoutingAddress: String,
                                  isBeneficiary: Boolean,
                                  otherAccountSecondaryRoutingScheme: String,
                                  otherAccountSecondaryRoutingAddress: String,
                                  description: String,
                                  currency: String,
                                  bespoke: List[CounterpartyBespoke]
                                 ): Box[CounterpartyTrait] = {
    tryo{
      val mappedCounterparty = MappedCounterparty.insert(
        counterpartyId = APIUtil.createExplicitCounterpartyId(), //We create the Counterparty_Id here, it means, it will be created in each connector.
        name = name,
        createdByUserId = createdByUserId,
        thisBankId = thisBankId,
        thisAccountId = thisAccountId,
        thisViewId = thisViewId,
        // The schemes are normalised on write, the addresses are not.
        otherAccountRoutingScheme = StringHelpers.snakify(otherAccountRoutingScheme).toUpperCase,
        otherAccountRoutingAddress = otherAccountRoutingAddress,
        otherBankRoutingScheme = StringHelpers.snakify(otherBankRoutingScheme).toUpperCase,
        otherBankRoutingAddress = otherBankRoutingAddress,
        otherBranchRoutingScheme = StringHelpers.snakify(otherBranchRoutingScheme).toUpperCase,
        otherBranchRoutingAddress = otherBranchRoutingAddress,
        isBeneficiary = isBeneficiary,
        description = description,
        currency = currency,
        otherAccountSecondaryRoutingScheme = otherAccountSecondaryRoutingScheme,
        otherAccountSecondaryRoutingAddress = otherAccountSecondaryRoutingAddress)

      // The bespoke rows are written by the provider and read back through it (see `bespoke`
      // below), so they are stored here directly. The former `mBespoke += ...` fed a Lift
      // OneToMany collection on an already-saved parent that was never saved again and never
      // read from, so it persisted nothing.
      CounterpartyBespokes.counterpartyBespokers.vend
        .createCounterpartyBespokes(mappedCounterparty.counterpartyPrimaryKey, bespoke)

      mappedCounterparty
    }
  }

 override def checkCounterpartyExists(
                               name: String,
                               thisBankId: String,
                               thisAccountId: String,
                               thisViewId: String
                             ): Box[CounterpartyTrait] =
   MappedCounterparty.findByNameAndAccountAndView(name, thisBankId, thisAccountId, thisViewId)


  private def getCounterpartyMetadata(counterpartyId : String) : Box[MappedCounterpartyMetadata] =
    MappedCounterpartyMetadata.findByCounterpartyId(counterpartyId)

  override def getPublicAlias(counterpartyId : String): Box[String] =
    getCounterpartyMetadata(counterpartyId).map(_.getPublicAlias)

  override def getPrivateAlias(counterpartyId : String): Box[String] =
    getCounterpartyMetadata(counterpartyId).map(_.getPrivateAlias)

  override def getPhysicalLocation(counterpartyId : String): Box[GeoTag] =
    getCounterpartyMetadata(counterpartyId).flatMap(m => Box(m.getPhysicalLocation))

  override def getOpenCorporatesURL(counterpartyId : String): Box[String] =
    getCounterpartyMetadata(counterpartyId).map(_.getOpenCorporatesURL)

  override def getImageURL(counterpartyId : String): Box[String] =
    getCounterpartyMetadata(counterpartyId).map(_.getImageURL)

  override def getUrl(counterpartyId : String): Box[String] =
    getCounterpartyMetadata(counterpartyId).map(_.getUrl)

  override def getMoreInfo(counterpartyId : String): Box[String] =
    getCounterpartyMetadata(counterpartyId).map(_.getMoreInfo)

  override def getCorporateLocation(counterpartyId : String): Box[GeoTag] =
    getCounterpartyMetadata(counterpartyId).flatMap(m => Box(m.getCorporateLocation))

  override def addPublicAlias(counterpartyId : String, alias: String): Box[Boolean] =
    getCounterpartyMetadata(counterpartyId).map(_.addPublicAlias(alias))

  override def addPrivateAlias(counterpartyId : String, alias: String): Box[Boolean] =
    getCounterpartyMetadata(counterpartyId).map(_.addPrivateAlias(alias))

  override def addURL(counterpartyId : String, url: String): Box[Boolean] =
    getCounterpartyMetadata(counterpartyId).map(_.addURL(url))

  override def addImageURL(counterpartyId : String, url: String): Box[Boolean] =
    getCounterpartyMetadata(counterpartyId).map(_.addImageURL(url))

  override def addOpenCorporatesURL(counterpartyId : String, url: String): Box[Boolean] =
    getCounterpartyMetadata(counterpartyId).map(_.addOpenCorporatesURL(url))

  override def addMoreInfo(counterpartyId : String, moreInfo: String): Box[Boolean] =
    getCounterpartyMetadata(counterpartyId).map(_.addMoreInfo(moreInfo))

  override def addPhysicalLocation(counterpartyId : String, userId: UserPrimaryKey, datePosted : Date, longitude : Double, latitude : Double): Box[Boolean] =
    getCounterpartyMetadata(counterpartyId).map(_.addPhysicalLocation(userId, datePosted, longitude, latitude))

  override def addCorporateLocation(counterpartyId : String, userId: UserPrimaryKey, datePosted : Date, longitude : Double, latitude : Double): Box[Boolean] =
    getCounterpartyMetadata(counterpartyId).map(_.addCorporateLocation(userId, datePosted, longitude, latitude))

  override def deletePhysicalLocation(counterpartyId : String): Box[Boolean] =
    getCounterpartyMetadata(counterpartyId).map(_.deletePhysicalLocation())

  override def deleteCorporateLocation(counterpartyId : String): Box[Boolean] =
    getCounterpartyMetadata(counterpartyId).map(_.deleteCorporateLocation())

  override def bulkDeleteAllCounterparties(): Box[Boolean] = {
    MappedCounterparty.deleteAll()
    Full(true)
  }
}


// for now, there are two Counterparties: one is used for CreateCounterParty.Counterparty, the other is for getTransactions.Counterparty.
// 1st is created by app explicitly, when use `CreateCounterParty` endpoint. This will be stored in database .
// 2nd is generated by obp implicitly, when use `getTransactions` endpoint. This will not be stored in database, but we create the CounterpartyMetadata for it. And the CounterpartyMetadata is in database.
// They are relevant somehow, but they are different data for now.

/**
 * Everything an account's owner has attached to one counterparty: the aliases shown instead of the
 * real name, free-text notes, and two map pins.
 *
 * A row exists for every counterparty an account has seen, including the implicit ones that are
 * never stored as counterparties themselves — which is why it is keyed by counterparty id and
 * carries the bank and account it belongs to rather than a foreign key.
 *
 * The mutator members are `val`s of function type because the trait declares them that way.
 * Each writes straight through to the row identified by `metadataPrimaryKey` and returns whether
 * the write succeeded, so a value read from an instance held across a write is stale — as it was
 * with Mapper.
 */
case class MappedCounterpartyMetadata(
  metadataPrimaryKey: Long,
  counterpartyId: String,
  counterpartyName: String,
  thisBankId: String,
  thisAccountId: String,
  publicAlias: String,
  privateAlias: String,
  moreInfo: String,
  url: String,
  imageUrl: String,
  openCorporatesUrl: String,
  corporateLocationId: Option[Long],
  physicalLocationId: Option[Long]
) extends CounterpartyMetadata {

  override def getCounterpartyId: String = counterpartyId
  override def getCounterpartyName: String = counterpartyName
  override def getPublicAlias: String = publicAlias
  override def getPrivateAlias: String = privateAlias
  override def getMoreInfo: String = moreInfo
  override def getUrl: String = url
  override def getImageURL: String = imageUrl
  override def getOpenCorporatesURL: String = openCorporatesUrl

  override def getCorporateLocation: Option[GeoTag] =
    corporateLocationId.flatMap(MappedCounterpartyWhereTag.findById)
  override def getPhysicalLocation: Option[GeoTag] =
    physicalLocationId.flatMap(MappedCounterpartyWhereTag.findById)

  override val addPrivateAlias: String => Boolean =
    x => MappedCounterpartyMetadata.setText(metadataPrimaryKey, fr"privatealias", x)
  override val addURL: String => Boolean =
    x => MappedCounterpartyMetadata.setText(metadataPrimaryKey, fr"url", x)
  override val addMoreInfo: String => Boolean =
    x => MappedCounterpartyMetadata.setText(metadataPrimaryKey, fr"moreinfo", x)
  override val addPublicAlias: String => Boolean =
    x => MappedCounterpartyMetadata.setText(metadataPrimaryKey, fr"publicalias", x)
  override val addOpenCorporatesURL: String => Boolean =
    x => MappedCounterpartyMetadata.setText(metadataPrimaryKey, fr"opencorporatesurl", x)
  override val addImageURL: String => Boolean =
    x => MappedCounterpartyMetadata.setText(metadataPrimaryKey, fr"imageurl", x)

  override val addCorporateLocation: (UserPrimaryKey, Date, Double, Double) => Boolean =
    (userId, datePosted, longitude, latitude) =>
      MappedCounterpartyMetadata.setLocation(metadataPrimaryKey, fr"corporatelocation",
        corporateLocationId, userId, datePosted, longitude, latitude)
  override val addPhysicalLocation: (UserPrimaryKey, Date, Double, Double) => Boolean =
    (userId, datePosted, longitude, latitude) =>
      MappedCounterpartyMetadata.setLocation(metadataPrimaryKey, fr"physicallocation",
        physicalLocationId, userId, datePosted, longitude, latitude)

  // Deletes the where-tag row and leaves the pointer to it behind, exactly as Mapper's
  // `location.obj.map(_.delete_!)` did. A dangling pointer reads back as no location, so the
  // observable result is the same and no second write is needed.
  override val deleteCorporateLocation: () => Boolean =
    () => corporateLocationId.exists(MappedCounterpartyWhereTag.deleteById)
  override val deletePhysicalLocation: () => Boolean =
    () => physicalLocationId.exists(MappedCounterpartyWhereTag.deleteById)
}

object MappedCounterpartyMetadata {

  private val selectColumns =
    fr"""SELECT id, counterpartyid, counterpartyname, thisbankid, thisaccountid, publicalias,
                privatealias, moreinfo, url, imageurl, opencorporatesurl, corporatelocation,
                physicallocation
         FROM mappedcounterpartymetadata"""

  private type Row = (Long, Option[String], Option[String], Option[String], Option[String],
    Option[String], Option[String], Option[String], Option[String], Option[String], Option[String],
    Option[Long], Option[Long])

  private def fromRow(row: Row): MappedCounterpartyMetadata = row match {
    case (id, counterpartyId, counterpartyName, thisBankId, thisAccountId, publicAlias,
          privateAlias, moreInfo, url, imageUrl, openCorporatesUrl, corporateLocation,
          physicalLocation) =>
      MappedCounterpartyMetadata(id, counterpartyId.orNull, counterpartyName.orNull,
        thisBankId.orNull, thisAccountId.orNull, publicAlias.orNull, privateAlias.orNull,
        moreInfo.orNull, url.orNull, imageUrl.orNull, openCorporatesUrl.orNull,
        corporateLocation, physicalLocation)
  }

  private def query(condition: Fragment): List[MappedCounterpartyMetadata] =
    DoobieUtil.runQuery((selectColumns ++ condition).query[Row].to[List]).map(fromRow)

  private def opt(value: String): Option[String] = Option(value)

  private def one(condition: Fragment): Box[MappedCounterpartyMetadata] =
    query(condition ++ fr"ORDER BY id ASC LIMIT 1").headOption match {
      case Some(row) => Full(row)
      case None => Empty
    }

  def findByCounterpartyId(counterpartyId: String): Box[MappedCounterpartyMetadata] =
    one(fr"WHERE counterpartyid = ${opt(counterpartyId)}")

  def findAllByBankAndAccount(thisBankId: String, thisAccountId: String): List[MappedCounterpartyMetadata] =
    query(fr"WHERE thisbankid = ${opt(thisBankId)} AND thisaccountid = ${opt(thisAccountId)}")

  def findByBankAccountAndCounterpartyId(thisBankId: String, thisAccountId: String,
                                         counterpartyId: String): Box[MappedCounterpartyMetadata] =
    one(fr"""WHERE thisbankid = ${opt(thisBankId)} AND thisaccountid = ${opt(thisAccountId)}
               AND counterpartyid = ${opt(counterpartyId)}""")

  def countByCounterpartyId(counterpartyId: String): Long =
    DoobieUtil.runQuery(
      (fr"SELECT COUNT(*) FROM mappedcounterpartymetadata WHERE counterpartyid = ${opt(counterpartyId)}")
        .query[Long].unique)

  def insert(counterpartyId: String, thisBankId: String, thisAccountId: String,
             counterpartyName: String, publicAlias: String): MappedCounterpartyMetadata = {
    val now = new java.sql.Timestamp(System.currentTimeMillis())
    val id = DoobieUtil.runUpdate(
      sql"""INSERT INTO mappedcounterpartymetadata
            (counterpartyid, thisbankid, thisaccountid, counterpartyname, publicalias,
             privatealias, moreinfo, url, imageurl, opencorporatesurl, createdat, updatedat)
            VALUES (${opt(counterpartyId)}, ${opt(thisBankId)}, ${opt(thisAccountId)},
             ${opt(counterpartyName)}, ${opt(publicAlias)}, '', '', '', '', '', $now, $now)"""
        .update.withUniqueGeneratedKeys[Long]("id"))
    MappedCounterpartyMetadata(id, counterpartyId, counterpartyName, thisBankId, thisAccountId,
      publicAlias, "", "", "", "", "", None, None)
  }

  /** The metadata row an account gets before any counterparty is known: no id, no alias. */
  def insertForAccount(thisBankId: String, thisAccountId: String): MappedCounterpartyMetadata =
    insert(counterpartyId = "", thisBankId = thisBankId, thisAccountId = thisAccountId,
      counterpartyName = "", publicAlias = "")

  private[counterparties] def setText(metadataPrimaryKey: Long, column: Fragment,
                                      value: String): Boolean =
    tryo {
      DoobieUtil.runUpdate(
        (fr"UPDATE mappedcounterpartymetadata SET" ++ column ++ fr" = ${opt(value)}," ++
          fr"updatedat = ${new java.sql.Timestamp(System.currentTimeMillis())}" ++
          fr"WHERE id = $metadataPrimaryKey").update.run)
      true
    }.getOrElse(false)

  /**
   * Moves a map pin: updates the where-tag the metadata already points at, or creates one and
   * points at it. Mapper reused the existing row the same way, so a location that several readers
   * hold is updated in place rather than replaced.
   */
  private[counterparties] def setLocation(metadataPrimaryKey: Long, column: Fragment,
                                          existingTagId: Option[Long], userId: UserPrimaryKey,
                                          datePosted: Date, longitude: Double,
                                          latitude: Double): Boolean =
    tryo {
      val tagId = existingTagId match {
        case Some(id) =>
          MappedCounterpartyWhereTag.update(id, userId.value, datePosted, longitude, latitude)
          id
        case None =>
          MappedCounterpartyWhereTag.insert(userId.value, datePosted, longitude, latitude)
      }
      DoobieUtil.runUpdate(
        (fr"UPDATE mappedcounterpartymetadata SET" ++ column ++ fr" = $tagId," ++
          fr"updatedat = ${new java.sql.Timestamp(System.currentTimeMillis())}" ++
          fr"WHERE id = $metadataPrimaryKey").update.run)
      true
    }.getOrElse(false)

  def deleteById(metadataPrimaryKey: Long): Boolean =
    DoobieUtil.runUpdate(
      sql"DELETE FROM mappedcounterpartymetadata WHERE id = $metadataPrimaryKey".update.run) > 0

  def deleteAll(): Unit = {
    DoobieUtil.runUpdate(sql"DELETE FROM mappedcounterpartymetadata".update.run)
    ()
  }
}

/** One map pin: where a counterparty is, according to the user who posted it. */
case class MappedCounterpartyWhereTag(
  whereTagPrimaryKey: Long,
  userPrimaryKey: Long,
  date: Date,
  geoLatitude: Double,
  geoLongitude: Double
) extends GeoTag {
  override def postedBy: Box[User] = Users.users.vend.getUserByResourceUserId(userPrimaryKey)
  override def datePosted: Date = date
  override def latitude: Double = geoLatitude
  override def longitude: Double = geoLongitude
}

object MappedCounterpartyWhereTag {

  // user and date carry the Schemifier suffix for reserved words.
  private val selectColumns =
    fr"SELECT id, user_c, date_c, geolatitude, geolongitude FROM mappedcounterpartywheretag"

  private type Row = (Long, Option[Long], Option[java.sql.Timestamp], Option[Double], Option[Double])

  private def fromRow(row: Row): MappedCounterpartyWhereTag = row match {
    case (id, userPrimaryKey, date, geoLatitude, geoLongitude) =>
      MappedCounterpartyWhereTag(id, userPrimaryKey.getOrElse(0L),
        date.map(ts => ts: Date).orNull, geoLatitude.getOrElse(0d), geoLongitude.getOrElse(0d))
  }

  def findById(whereTagPrimaryKey: Long): Option[MappedCounterpartyWhereTag] =
    DoobieUtil.runQuery(
      (selectColumns ++ fr"WHERE id = $whereTagPrimaryKey").query[Row].to[List])
      .map(fromRow).headOption

  def insert(userPrimaryKey: Long, datePosted: Date, longitude: Double, latitude: Double): Long = {
    val now = new java.sql.Timestamp(System.currentTimeMillis())
    DoobieUtil.runUpdate(
      sql"""INSERT INTO mappedcounterpartywheretag
            (user_c, date_c, geolatitude, geolongitude, createdat, updatedat)
            VALUES ($userPrimaryKey, ${Option(datePosted).map(d => new java.sql.Timestamp(d.getTime))},
             $latitude, $longitude, $now, $now)"""
        .update.withUniqueGeneratedKeys[Long]("id"))
  }

  def update(whereTagPrimaryKey: Long, userPrimaryKey: Long, datePosted: Date, longitude: Double,
             latitude: Double): Unit = {
    val now = new java.sql.Timestamp(System.currentTimeMillis())
    DoobieUtil.runUpdate(
      sql"""UPDATE mappedcounterpartywheretag
            SET user_c = $userPrimaryKey,
                date_c = ${Option(datePosted).map(d => new java.sql.Timestamp(d.getTime))},
                geolatitude = $latitude, geolongitude = $longitude, updatedat = $now
            WHERE id = $whereTagPrimaryKey"""
        .update.run)
    ()
  }

  def deleteById(whereTagPrimaryKey: Long): Boolean =
    DoobieUtil.runUpdate(
      sql"DELETE FROM mappedcounterpartywheretag WHERE id = $whereTagPrimaryKey".update.run) > 0

  def deleteAll(): Unit = {
    DoobieUtil.runUpdate(sql"DELETE FROM mappedcounterpartywheretag".update.run)
    ()
  }
}

/**
 * An explicit counterparty: one the account holder created through the API, as opposed to the
 * implicit ones derived from transactions, which are never stored here.
 *
 * `counterpartyPrimaryKey` is the surrogate key and would normally stay inside the store, but the
 * bespoke key/value rows are keyed by it rather than by the counterparty id, so it has to be
 * carried on the row for `bespoke` to resolve.
 */
case class MappedCounterparty(
  counterpartyPrimaryKey: Long,
  counterpartyId: String,
  name: String,
  createdByUserId: String,
  thisBankId: String,
  thisAccountId: String,
  thisViewId: String,
  otherBankRoutingScheme: String,
  otherBankRoutingAddress: String,
  otherBranchRoutingScheme: String,
  otherBranchRoutingAddress: String,
  otherAccountRoutingScheme: String,
  otherAccountRoutingAddress: String,
  otherAccountSecondaryRoutingScheme: String,
  otherAccountSecondaryRoutingAddress: String,
  isBeneficiary: Boolean,
  description: String,
  currency: String
) extends CounterpartyTrait {

  override def bespoke: List[CounterpartyBespoke] =
    CounterpartyBespokes.counterpartyBespokers.vend
      .getCounterpartyBespokesByCounterpartyId(counterpartyPrimaryKey)
      .map(
        mappedBespoke=>CounterpartyBespoke(mappedBespoke.key,mappedBespoke.value)
      )
}

object MappedCounterparty {

  /**
   * The limit the create/update endpoints quote in their error message when a description is too
   * long. It is the column width, and the endpoints read it from here rather than hard-coding it.
   */
  val descriptionMaxLength: Int = 2000

  private val selectColumns =
    fr"""SELECT id, mcounterpartyid, mname, mcreatedbyuserid, mthisbankid, mthisaccountid,
                mthisviewid, motherbankroutingscheme, motherbankroutingaddress,
                motherbranchroutingscheme, motherbranchroutingaddress,
                motheraccountroutingscheme, motheraccountroutingaddress,
                motheraccountsecondaryroutingscheme, motheraccountsecondaryroutingaddress,
                misbeneficiary, mdescription, mcurrency
         FROM mappedcounterparty"""

  private type Row = (Long, Option[String], Option[String], Option[String], Option[String],
    Option[String], Option[String], Option[String], Option[String], Option[String], Option[String],
    Option[String], Option[String], Option[String], Option[String], Option[Boolean], Option[String],
    Option[String])

  private def fromRow(row: Row): MappedCounterparty = row match {
    case (id, counterpartyId, name, createdByUserId, thisBankId, thisAccountId, thisViewId,
          otherBankRoutingScheme, otherBankRoutingAddress, otherBranchRoutingScheme,
          otherBranchRoutingAddress, otherAccountRoutingScheme, otherAccountRoutingAddress,
          otherAccountSecondaryRoutingScheme, otherAccountSecondaryRoutingAddress, isBeneficiary,
          description, currency) =>
      MappedCounterparty(id, counterpartyId.orNull, name.orNull, createdByUserId.orNull,
        thisBankId.orNull, thisAccountId.orNull, thisViewId.orNull,
        otherBankRoutingScheme.orNull, otherBankRoutingAddress.orNull,
        otherBranchRoutingScheme.orNull, otherBranchRoutingAddress.orNull,
        otherAccountRoutingScheme.orNull, otherAccountRoutingAddress.orNull,
        otherAccountSecondaryRoutingScheme.orNull, otherAccountSecondaryRoutingAddress.orNull,
        isBeneficiary.getOrElse(false), description.orNull,
        // currency alone reads back "" rather than null for a NULL column: the entity exposed it
        // through the field's toString, which renders a null value as the empty string, and
        // callers compare it against a currency code.
        currency.getOrElse(""))
  }

  private def query(condition: Fragment): List[MappedCounterparty] =
    DoobieUtil.runQuery((selectColumns ++ condition).query[Row].to[List]).map(fromRow)

  private def opt(value: String): Option[String] = Option(value)

  private def one(condition: Fragment): Box[MappedCounterparty] =
    query(condition ++ fr"ORDER BY id ASC LIMIT 1").headOption match {
      case Some(row) => Full(row)
      case None => Empty
    }

  def findByCounterpartyId(counterpartyId: String): Box[MappedCounterparty] =
    one(fr"WHERE mcounterpartyid = ${opt(counterpartyId)}")

  /** Nothing makes the IBAN unique, so the newest row wins. */
  def findNewestBySecondaryRoutingAddress(iban: String): Box[MappedCounterparty] =
    query(fr"WHERE motheraccountsecondaryroutingaddress = ${opt(iban)} ORDER BY id DESC LIMIT 1")
      .headOption match {
        case Some(row) => Full(row)
        case None => Empty
      }

  def findBySecondaryRoutingAddressAndAccount(iban: String, thisBankId: String,
                                              thisAccountId: String): Box[MappedCounterparty] =
    one(fr"""WHERE motheraccountsecondaryroutingaddress = ${opt(iban)}
               AND mthisbankid = ${opt(thisBankId)} AND mthisaccountid = ${opt(thisAccountId)}""")

  def findByRoutings(otherBankRoutingScheme: String, otherBankRoutingAddress: String,
                     otherBranchRoutingScheme: String, otherBranchRoutingAddress: String,
                     otherAccountRoutingScheme: String,
                     otherAccountRoutingAddress: String): Box[MappedCounterparty] =
    one(fr"""WHERE motherbankroutingscheme = ${opt(otherBankRoutingScheme)}
               AND motherbankroutingaddress = ${opt(otherBankRoutingAddress)}
               AND motherbranchroutingscheme = ${opt(otherBranchRoutingScheme)}
               AND motherbranchroutingaddress = ${opt(otherBranchRoutingAddress)}
               AND motheraccountroutingscheme = ${opt(otherAccountRoutingScheme)}
               AND motheraccountroutingaddress = ${opt(otherAccountRoutingAddress)}""")

  def findBySecondaryRouting(otherAccountSecondaryRoutingScheme: String,
                             otherAccountSecondaryRoutingAddress: String): Box[MappedCounterparty] =
    one(fr"""WHERE motheraccountsecondaryroutingscheme = ${opt(otherAccountSecondaryRoutingScheme)}
               AND motheraccountsecondaryroutingaddress = ${opt(otherAccountSecondaryRoutingAddress)}""")

  def findAllByAccountAndView(thisBankId: String, thisAccountId: String,
                              thisViewId: String): List[MappedCounterparty] =
    query(fr"""WHERE mthisaccountid = ${opt(thisAccountId)} AND mthisbankid = ${opt(thisBankId)}
                 AND mthisviewid = ${opt(thisViewId)}""")

  def findByNameAndAccountAndView(name: String, thisBankId: String, thisAccountId: String,
                                  thisViewId: String): Box[MappedCounterparty] =
    one(fr"""WHERE mname = ${opt(name)} AND mthisbankid = ${opt(thisBankId)}
               AND mthisaccountid = ${opt(thisAccountId)} AND mthisviewid = ${opt(thisViewId)}""")

  def insert(counterpartyId: String, name: String, createdByUserId: String, thisBankId: String,
             thisAccountId: String, thisViewId: String, otherAccountRoutingScheme: String,
             otherAccountRoutingAddress: String, otherBankRoutingScheme: String,
             otherBankRoutingAddress: String, otherBranchRoutingScheme: String,
             otherBranchRoutingAddress: String, isBeneficiary: Boolean, description: String,
             currency: String, otherAccountSecondaryRoutingScheme: String,
             otherAccountSecondaryRoutingAddress: String): MappedCounterparty = {
    val now = new java.sql.Timestamp(System.currentTimeMillis())
    val id = DoobieUtil.runUpdate(
      sql"""INSERT INTO mappedcounterparty
            (mcounterpartyid, mname, mcreatedbyuserid, mthisbankid, mthisaccountid, mthisviewid,
             motherbankroutingscheme, motherbankroutingaddress, motherbranchroutingscheme,
             motherbranchroutingaddress, motheraccountroutingscheme, motheraccountroutingaddress,
             motheraccountsecondaryroutingscheme, motheraccountsecondaryroutingaddress,
             misbeneficiary, mdescription, mcurrency, createdat, updatedat)
            VALUES (${opt(counterpartyId)}, ${opt(name)}, ${opt(createdByUserId)},
             ${opt(thisBankId)}, ${opt(thisAccountId)}, ${opt(thisViewId)},
             ${opt(otherBankRoutingScheme)}, ${opt(otherBankRoutingAddress)},
             ${opt(otherBranchRoutingScheme)}, ${opt(otherBranchRoutingAddress)},
             ${opt(otherAccountRoutingScheme)}, ${opt(otherAccountRoutingAddress)},
             ${opt(otherAccountSecondaryRoutingScheme)},
             ${opt(otherAccountSecondaryRoutingAddress)},
             $isBeneficiary, ${opt(description)}, ${opt(currency)}, $now, $now)"""
        .update.withUniqueGeneratedKeys[Long]("id"))
    MappedCounterparty(id, counterpartyId, name, createdByUserId, thisBankId, thisAccountId,
      thisViewId, otherBankRoutingScheme, otherBankRoutingAddress, otherBranchRoutingScheme,
      otherBranchRoutingAddress, otherAccountRoutingScheme, otherAccountRoutingAddress,
      otherAccountSecondaryRoutingScheme, otherAccountSecondaryRoutingAddress, isBeneficiary,
      description, currency)
  }

  def deleteById(counterpartyPrimaryKey: Long): Boolean =
    DoobieUtil.runUpdate(
      sql"DELETE FROM mappedcounterparty WHERE id = $counterpartyPrimaryKey".update.run) > 0

  def deleteAll(): Unit = {
    DoobieUtil.runUpdate(sql"DELETE FROM mappedcounterparty".update.run)
    ()
  }
}
