name: Build on Pull Request

on:
  pull_request:
    branches:
      - '**'
env:
  ## Sets environment variable
  DOCKER_HUB_ORGANIZATION: ${{ vars.DOCKER_HUB_ORGANIZATION }}


jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        ports:
          # Opens tcp port 6379 on the host and service container
          - 6379:6379
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: |
          pwd
          ls obp-api
          mkdir obp-api/target/
          touch obp-api/target/obp-api-1.10.1.war
      - name: Save user name and .war artifact
        run: |
          mkdir -p ./pr
          echo ${{ github.event.pull_request.user.login }} > ./pr/UN
          cp obp-api/target/obp-api-1.10.1.war ./pr/obp-api-1.10.1.war
      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/



